import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: { translation: {
    nav: { home:'Home', features:'Features', pricing:'Pricing', login:'Login', signup:'Start Free Trial', dashboard:'Dashboard' },
    hero: { title:'Build Your Online Platform', subtitle:'Create a stunning store in minutes. Sell across all 58 wilayas with powerful tools, AI features, and zero coding.', cta:'Start Free — 14 Days Trial', cta2:'See How It Works' },
    features: { title:'Everything You Need to Sell Online', subtitle:'Powerful tools built for Algerian e-commerce' },
    pricing: { title:'Simple, Transparent Pricing', start:'Start Free Trial' },
    auth: { login:'Login', register:'Create Account', loginSubtitle:'Sign in to your store owner account', registerSubtitle:'Create your store owner account', registerHeroTitle:'Start your business today', registerHeroSubtitle:'14-day free trial. No credit card needed.', email:'Email', password:'Password', name:'Full Name', phone:'Phone Number', emailOrPhone:'Email or Phone Number', emailOrPhonePlaceholder:'you@email.com or phone number', namePlaceholder:'Your full name', phonePlaceholder:'Your phone number', addressPlaceholder:'Your address', address:'Address', city:'City', wilaya:'Wilaya', allFieldsRequired:'Name, email, phone and password are required', forgotPassword:'Forgot password?', noAccount:"Don't have an account?", hasAccount:'Already have an account?' },
    dashboard: { welcome:'Welcome back', storeVisits:'Store Visits', totalSales:'Total Sales', totalOrders:'Total Orders', avgOrderValue:'Avg Order Value', products:'Products', recentOrders:'Recent Orders', salesOverview:'Sales Overview', orderStatus:'Order Status', viewDetails:'View Details', addProduct:'Add Product', viewOrders:'View Orders', customers:'Customers', settings:'Settings', createStore:'Create Store', createStoreDesc:'Start selling in minutes with a beautiful design.', noStores:'Create Your First Store' },
    sidebar: { dashboard:'Dashboard', orders:'Orders', abandonedOrders:'Abandoned Orders', preparing:'Preparing', products:'Products', customers:'Customers', analytics:'Analytics', settings:'Settings', apps:'Apps & Integrations', staff:'Staff', stockManager:'Stock Manager',analytics:'Analytics',costs:'Costs',billing:'Billing & Plans',domains:'Domains' },
    orders: { title:'Orders', all:'All', pending:'Pending', confirmed:'Confirmed', preparing:'Preparing', shipped:'Shipped', delivered:'Delivered', cancelled:'Cancelled', returned:'Returned', orderNumber:'Order #', customer:'Customer', total:'Total', status:'Status', date:'Date', actions:'Actions', noOrders:'No orders yet', paymentMethod:'Payment Method', shippingAddress:'Shipping Address', senderInfo:'Customer Information', phone:'Phone', email:'Email', city:'City', wilaya:'Wilaya', notes:'Notes', items:'Order Items', subtotal:'Subtotal', shipping:'Shipping', discount:'Discount', trackingNumber:'Tracking Number' },
    products: { title:'Products', addProduct:'Add Product', editProduct:'Edit Product', name:'Product Name', price:'Price', stock:'Stock', category:'Category', description:'Description', comparePrice:'Compare Price', sku:'SKU', images:'Product Images', uploadImages:'Click to upload or drag & drop', uploadHint:'PNG, JPG, WEBP up to 10MB each', featured:'Featured Product', active:'Active', inactive:'Inactive', noProducts:'No products yet', save:'Save', cancel:'Cancel', deleteConfirm:'Delete this product?', inStock:'in stock', outOfStock:'Out of stock' },
    store: { search:'Search products...', allCategories:'ALL CATEGORIES', new:'NEW', addToCart:'Add to Cart', buyNow:'Buy Now', cart:'Cart', checkout:'Checkout', continueShopping:'Continue Shopping', orderNow:'ORDER NOW', paymentMethod:'Payment Method', cod:'Cash on Delivery', codDesc:'Pay in cash upon delivery of your order', ccp:'CCP Direct Transfer', ccpDesc:'Manual transfer to our CCP account', baridimob:'BaridiMob QR Payment', baridimobDesc:'Quick scan & pay via BaridiMob app', bankTransfer:'Bank Transfer', bankTransferDesc:'Pay via Bank Transfer', shippingInfo:'Shipping Information', orderSummary:'Order Summary', subtotal:'Subtotal', shipping:'Shipping', discount:'Discount', total:'TOTAL TO PAY', placeOrder:'Place Order', orderSuccess:'Order Placed Successfully!', productPrice:'PRODUCT PRICE', shippingCost:'SHIPPING+', securePayment:'SECURE PAYMENT', sslSecured:'SSL SECURED', codAvailable:'CASH ON DELIVERY AVAILABLE IN ALL 58 WILAYAS', saveInfo:'SAVE INFORMATION FOR NEXT TIME' },
    common: { save:'Save', cancel:'Cancel', delete:'Delete', edit:'Edit', search:'Search', loading:'Loading...', noData:'No data found', confirm:'Confirm', back:'Back', next:'Next', submit:'Submit', viewAll:'View All', close:'Close', install:'Install', uninstall:'Uninstall', comingSoon:'Coming soon', active:'Active', actions:'Actions' },
    apps: { title:'Apps & Integrations', subtitle:'Supercharge your store with powerful apps and integrations.' },
    recovery: { title:'Cart Recovery', subtitle:'Manage and automate abandoned order conversion.', totalCarts:'Total Carts', recovered:'Recovered', recoveredRevenue:'Recovered Revenue', lostRevenue:'Lost Revenue', syncData:'Sync Data', automationSettings:'Automation Settings' },
    staff: { title:'Staff Management', addStaff:'Add Staff Member', role:'Role', admin:'Admin', preparer:'Preparer', confirmer:'Confirmer', accountant:'Accountant', viewer:'Viewer' },
    settings: { general:'General', design:'Design & Appearance', payment:'Payment Methods', shipping:'Shipping', ai:'AI Features', storeName:'Store Name', storeUrl:'Store URL', description:'Description', logo:'Store Logo', uploadLogo:'Upload logo from device', contactPhone:'Contact Phone / WhatsApp', contactEmail:'Contact Email', currency:'Currency', isLive:'Store is Live (Published)', heroTitle:'Hero Title', heroSubtitle:'Hero Subtitle', metaTitle:'Meta Title (SEO)', metaDescription:'Meta Description (SEO)', primaryColor:'Primary Color', secondaryColor:'Secondary Color', accentColor:'Accent Color', bgColor:'Background Color', aiChatbot:'AI Chatbot', botName:'Bot Name', botGreeting:'Greeting Message', fakeDetection:'AI Fake Order Detection', cartRecovery:'AI Cart Recovery', defaultShipping:'Default shipping cost: 400 DZD' },
    shipping: { title:'Shipping Wilayas', desk:'Desk Delivery', home:'Home Delivery', days:'Days', partners:'Shipping Partners', trackShipment:'Track Shipment' },
    chatbot: { greeting:'How may I assist you?', placeholder:'Enter command...', suggestedActions:'SUGGESTED ACTIONS', operational:'Operational' },
  }},
  fr: { translation: {
    nav: { home:'Accueil', features:'Fonctionnalités', pricing:'Tarifs', login:'Connexion', signup:'Essai Gratuit', dashboard:'Tableau de bord' },
    hero: { title:'Créez Votre Plateforme en Ligne', subtitle:"Créez une boutique en quelques minutes. Vendez dans les 58 wilayas avec des outils puissants, l'IA et sans code.", cta:'Essai Gratuit — 14 Jours', cta2:'Voir Comment Ça Marche' },
    features: { title:'Tout ce dont vous avez besoin pour vendre en ligne', subtitle:'Des outils puissants pour le e-commerce algérien' },
    pricing: { title:'Tarifs Simples et Transparents', start:'Essai Gratuit' },
    auth: { login:'Connexion', register:'Créer un Compte', loginSubtitle:'Connectez-vous à votre compte', registerSubtitle:'Créez votre compte propriétaire', registerHeroTitle:"Lancez votre business aujourd'hui", registerHeroSubtitle:'Essai gratuit de 14 jours. Sans carte bancaire.', email:'Email', password:'Mot de passe', name:'Nom Complet', phone:'Téléphone', emailOrPhone:'Email ou Téléphone', emailOrPhonePlaceholder:'email@exemple.com ou téléphone', namePlaceholder:'Votre nom complet', phonePlaceholder:'Votre numéro de téléphone', addressPlaceholder:'Votre adresse', address:'Adresse', city:'Ville', wilaya:'Wilaya', allFieldsRequired:'Nom, email, téléphone et mot de passe sont obligatoires', forgotPassword:'Mot de passe oublié ?', noAccount:'Pas de compte ?', hasAccount:'Déjà un compte ?' },
    dashboard: { welcome:'Bon retour', storeVisits:'Visites', totalSales:'Ventes Totales', totalOrders:'Commandes', avgOrderValue:'Valeur Moyenne', products:'Produits', recentOrders:'Commandes Récentes', salesOverview:'Aperçu des Ventes', orderStatus:'Statut des Commandes', viewDetails:'Voir Détails', addProduct:'Ajouter Produit', viewOrders:'Voir Commandes', customers:'Clients', settings:'Paramètres', createStore:'Créer une Boutique', createStoreDesc:'Commencez à vendre en quelques minutes.', noStores:'Créez Votre Première Boutique' },
    sidebar: { dashboard:'Tableau de bord', orders:'Commandes', abandonedOrders:'Paniers Abandonnés', preparing:'En Préparation', products:'Produits', customers:'Clients', analytics:'Analytiques', settings:'Paramètres', apps:'Applications & Intégrations', staff:'Personnel', stockManager:'Gestionnaire de Stock',analytics:'Analytiques',costs:'Coûts',billing:'Facturation & Plans',domains:'Domaines' },
    orders: { title:'Commandes', all:'Tout', pending:'En attente', confirmed:'Confirmée', preparing:'En préparation', shipped:'Expédiée', delivered:'Livrée', cancelled:'Annulée', returned:'Retournée', orderNumber:'N° Commande', customer:'Client', total:'Total', status:'Statut', date:'Date', actions:'Actions', noOrders:'Aucune commande', paymentMethod:'Mode de paiement', shippingAddress:'Adresse de livraison', senderInfo:'Informations du Client', phone:'Téléphone', email:'Email', city:'Ville', wilaya:'Wilaya', notes:'Notes', items:'Articles', subtotal:'Sous-total', shipping:'Livraison', discount:'Remise', trackingNumber:'Numéro de suivi' },
    products: { title:'Produits', addProduct:'Ajouter Produit', editProduct:'Modifier Produit', name:'Nom du Produit', price:'Prix', stock:'Stock', category:'Catégorie', description:'Description', comparePrice:'Prix comparé', sku:'SKU', images:'Images du Produit', uploadImages:'Cliquez pour uploader ou glisser-déposer', uploadHint:'PNG, JPG, WEBP jusqu\'à 10MB', featured:'Produit en Vedette', active:'Actif', inactive:'Inactif', noProducts:'Aucun produit', save:'Enregistrer', cancel:'Annuler', deleteConfirm:'Supprimer ce produit ?', inStock:'en stock', outOfStock:'Rupture de stock' },
    store: { search:'Rechercher des produits...', allCategories:'TOUTES CATÉGORIES', new:'NOUVEAU', addToCart:'Ajouter au Panier', buyNow:'Acheter', cart:'Panier', checkout:'Commander', continueShopping:'Continuer les Achats', orderNow:'COMMANDER', paymentMethod:'Mode de Paiement', cod:'Paiement à la Livraison', codDesc:'Payez en espèces à la livraison', ccp:'Virement CCP', ccpDesc:'Virement manuel vers notre compte CCP', baridimob:'Paiement BaridiMob QR', baridimobDesc:'Scannez et payez via BaridiMob', bankTransfer:'Virement Bancaire', bankTransferDesc:'Payez par virement bancaire', shippingInfo:'Informations de Livraison', orderSummary:'Résumé de la Commande', subtotal:'Sous-total', shipping:'Livraison', discount:'Remise', total:'TOTAL À PAYER', placeOrder:'Passer la Commande', orderSuccess:'Commande Passée avec Succès !', productPrice:'PRIX DU PRODUIT', shippingCost:'LIVRAISON+', securePayment:'PAIEMENT SÉCURISÉ', sslSecured:'SSL SÉCURISÉ', codAvailable:'PAIEMENT À LA LIVRAISON DISPONIBLE DANS LES 58 WILAYAS', saveInfo:'SAUVEGARDER MES INFORMATIONS' },
    common: { save:'Enregistrer', cancel:'Annuler', delete:'Supprimer', edit:'Modifier', search:'Rechercher', loading:'Chargement...', noData:'Aucune donnée', confirm:'Confirmer', back:'Retour', next:'Suivant', submit:'Soumettre', viewAll:'Voir Tout', close:'Fermer', install:'Installer', uninstall:'Désinstaller', comingSoon:'Bientôt disponible', active:'Actif', actions:'Actions' },
    apps: { title:'Applications & Intégrations', subtitle:'Boostez votre boutique avec des applications puissantes.' },
    recovery: { title:'Récupération de Paniers', subtitle:'Gérez la conversion des commandes abandonnées.', totalCarts:'Total Paniers', recovered:'Récupérés', recoveredRevenue:'Revenus Récupérés', lostRevenue:'Revenus Perdus', syncData:'Synchroniser', automationSettings:'Paramètres Automatisation' },
    staff: { title:'Gestion du Personnel', addStaff:'Ajouter un Membre', role:'Rôle', admin:'Administrateur', preparer:'Préparateur', confirmer:'Confirmateur', accountant:'Comptable', viewer:'Observateur' },
    settings: { general:'Général', design:'Design & Apparence', payment:'Méthodes de Paiement', shipping:'Livraison', ai:'Fonctionnalités IA', storeName:'Nom de la Boutique', storeUrl:'URL de la Boutique', description:'Description', logo:'Logo de la Boutique', uploadLogo:'Uploader un logo depuis votre appareil', contactPhone:'Téléphone / WhatsApp', contactEmail:'Email de Contact', currency:'Devise', isLive:'Boutique Publiée', heroTitle:'Titre Principal', heroSubtitle:'Sous-titre Principal', metaTitle:'Titre Meta (SEO)', metaDescription:'Description Meta (SEO)', primaryColor:'Couleur Principale', secondaryColor:'Couleur Secondaire', accentColor:'Couleur d\'Accent', bgColor:'Couleur de Fond', aiChatbot:'Chatbot IA', botName:'Nom du Bot', botGreeting:'Message d\'Accueil', fakeDetection:'Détection de Fausses Commandes', cartRecovery:'Récupération de Paniers IA', defaultShipping:'Livraison par défaut : 400 DZD' },
    shipping: { title:'Wilayas de Livraison', desk:'Livraison Bureau', home:'Livraison Domicile', days:'Jours', partners:'Partenaires de Livraison', trackShipment:'Suivre l\'Expédition' },
    chatbot: { greeting:'Comment puis-je vous aider ?', placeholder:'Entrez une commande...', suggestedActions:'ACTIONS SUGGÉRÉES', operational:'Opérationnel' },
  }},
  ar: { translation: {
    nav: { home:'الرئيسية', features:'المميزات', pricing:'الأسعار', login:'تسجيل الدخول', signup:'ابدأ مجاناً', dashboard:'لوحة التحكم' },
    hero: { title:'أنشئ منصتك الرقمية', subtitle:'أنشئ متجرك الإلكتروني في دقائق. بع في كل 58 ولاية بأدوات قوية وذكاء اصطناعي بدون برمجة.', cta:'ابدأ مجاناً — 14 يوم', cta2:'شاهد كيف يعمل' },
    features: { title:'كل ما تحتاجه للبيع عبر الإنترنت', subtitle:'أدوات قوية للتجارة الإلكترونية الجزائرية' },
    pricing: { title:'أسعار بسيطة وشفافة', start:'ابدأ مجاناً' },
    auth: { login:'تسجيل الدخول', register:'إنشاء حساب', loginSubtitle:'سجّل الدخول إلى حسابك', registerSubtitle:'أنشئ حساب صاحب متجر', registerHeroTitle:'ابدأ عملك اليوم', registerHeroSubtitle:'تجربة مجانية 14 يوماً. بدون بطاقة ائتمان.', email:'البريد الإلكتروني', password:'كلمة المرور', name:'الاسم الكامل', phone:'رقم الهاتف', emailOrPhone:'البريد الإلكتروني أو رقم الهاتف', emailOrPhonePlaceholder:'بريدك أو رقم هاتفك', namePlaceholder:'اسمك الكامل', phonePlaceholder:'رقم هاتفك', addressPlaceholder:'عنوانك', address:'العنوان', city:'المدينة', wilaya:'الولاية', allFieldsRequired:'الاسم والبريد ورقم الهاتف وكلمة المرور مطلوبة', noAccount:'ليس لديك حساب؟', hasAccount:'لديك حساب بالفعل؟' },
    dashboard: { welcome:'مرحباً بعودتك', storeVisits:'زيارات المتجر', totalSales:'إجمالي المبيعات', totalOrders:'إجمالي الطلبات', avgOrderValue:'متوسط قيمة الطلب', products:'المنتجات', recentOrders:'الطلبات الأخيرة', salesOverview:'نظرة عامة على المبيعات', orderStatus:'حالة الطلبات', viewDetails:'عرض التفاصيل', addProduct:'إضافة منتج', viewOrders:'عرض الطلبات', customers:'العملاء', settings:'الإعدادات', createStore:'إنشاء متجر', createStoreDesc:'ابدأ البيع في دقائق.', noStores:'أنشئ متجرك الأول' },
    sidebar: { dashboard:'لوحة التحكم', orders:'الطلبات', abandonedOrders:'السلات المتروكة', preparing:'قيد التحضير', products:'المنتجات', customers:'العملاء', analytics:'التحليلات', settings:'الإعدادات', apps:'التطبيقات والتكاملات', staff:'الموظفين', stockManager:'إدارة المخزون',analytics:'التحليلات',costs:'التكاليف',billing:'الفواتير والخطط',domains:'النطاقات' },
    orders: { title:'الطلبات', all:'الكل', pending:'قيد الانتظار', confirmed:'مؤكد', preparing:'قيد التحضير', shipped:'تم الشحن', delivered:'تم التوصيل', cancelled:'ملغى', returned:'مرتجع', orderNumber:'رقم الطلب', customer:'العميل', total:'المجموع', status:'الحالة', date:'التاريخ', actions:'الإجراءات', noOrders:'لا توجد طلبات', paymentMethod:'طريقة الدفع', shippingAddress:'عنوان الشحن', senderInfo:'معلومات العميل', phone:'الهاتف', email:'البريد', city:'المدينة', wilaya:'الولاية', notes:'ملاحظات', items:'عناصر الطلب', subtotal:'المجموع الفرعي', shipping:'الشحن', discount:'الخصم', trackingNumber:'رقم التتبع' },
    products: { title:'المنتجات', addProduct:'إضافة منتج', editProduct:'تعديل منتج', name:'اسم المنتج', price:'السعر', stock:'المخزون', category:'الفئة', description:'الوصف', comparePrice:'سعر المقارنة', sku:'رمز المنتج', images:'صور المنتج', uploadImages:'انقر للرفع أو اسحب وأفلت', uploadHint:'PNG, JPG, WEBP حتى 10 ميغابايت', featured:'منتج مميز', active:'نشط', inactive:'غير نشط', noProducts:'لا توجد منتجات', save:'حفظ', cancel:'إلغاء', deleteConfirm:'حذف هذا المنتج؟', inStock:'متوفر', outOfStock:'غير متوفر' },
    store: { search:'ابحث عن منتجات...', allCategories:'كل الفئات', new:'جديد', addToCart:'أضف إلى السلة', buyNow:'اشتري الآن', cart:'السلة', checkout:'إتمام الشراء', continueShopping:'متابعة التسوق', orderNow:'اطلب الآن', paymentMethod:'طريقة الدفع', cod:'الدفع عند الاستلام', codDesc:'ادفع نقداً عند استلام طلبك', ccp:'تحويل CCP', ccpDesc:'تحويل يدوي إلى حسابنا CCP', baridimob:'دفع BaridiMob', baridimobDesc:'امسح وادفع عبر تطبيق BaridiMob', bankTransfer:'تحويل بنكي', bankTransferDesc:'ادفع عبر التحويل البنكي', shippingInfo:'معلومات الشحن', orderSummary:'ملخص الطلب', subtotal:'المجموع الفرعي', shipping:'الشحن', discount:'الخصم', total:'المبلغ الإجمالي', placeOrder:'تأكيد الطلب', orderSuccess:'تم تقديم الطلب بنجاح!', productPrice:'سعر المنتج', shippingCost:'تكلفة الشحن', securePayment:'دفع آمن', sslSecured:'محمي بـ SSL', codAvailable:'الدفع عند الاستلام متاح في كل 58 ولاية', saveInfo:'حفظ المعلومات للمرة القادمة' },
    common: { save:'حفظ', cancel:'إلغاء', delete:'حذف', edit:'تعديل', search:'بحث', loading:'جاري التحميل...', noData:'لا توجد بيانات', confirm:'تأكيد', back:'رجوع', next:'التالي', submit:'إرسال', viewAll:'عرض الكل', close:'إغلاق', install:'تثبيت', uninstall:'إزالة', comingSoon:'قريباً', active:'نشط', actions:'إجراءات' },
    apps: { title:'التطبيقات والتكاملات', subtitle:'عزز متجرك بتطبيقات وتكاملات قوية.' },
    recovery: { title:'استرداد السلات', subtitle:'إدارة تحويل الطلبات المتروكة.', totalCarts:'إجمالي السلات', recovered:'المستردة', recoveredRevenue:'الإيرادات المستردة', lostRevenue:'الإيرادات المفقودة', syncData:'مزامنة', automationSettings:'إعدادات الأتمتة' },
    staff: { title:'إدارة الموظفين', addStaff:'إضافة موظف', role:'الدور', admin:'مدير', preparer:'محضّر', confirmer:'مؤكّد', accountant:'محاسب', viewer:'مشاهد' },
    settings: { general:'عام', design:'التصميم والمظهر', payment:'طرق الدفع', shipping:'الشحن', ai:'ميزات الذكاء الاصطناعي', storeName:'اسم المتجر', storeUrl:'رابط المتجر', description:'الوصف', logo:'شعار المتجر', uploadLogo:'ارفع شعاراً من جهازك', contactPhone:'الهاتف / واتساب', contactEmail:'البريد الإلكتروني', currency:'العملة', isLive:'المتجر منشور', heroTitle:'العنوان الرئيسي', heroSubtitle:'العنوان الفرعي', metaTitle:'عنوان Meta', metaDescription:'وصف Meta', primaryColor:'اللون الرئيسي', secondaryColor:'اللون الثانوي', accentColor:'لون التمييز', bgColor:'لون الخلفية', aiChatbot:'روبوت الدردشة', botName:'اسم الروبوت', botGreeting:'رسالة الترحيب', fakeDetection:'كشف الطلبات المزيفة', cartRecovery:'استرداد السلات', defaultShipping:'تكلفة الشحن الافتراضية: 400 د.ج' },
    shipping: { title:'ولايات الشحن', desk:'توصيل مكتب', home:'توصيل منزل', days:'أيام', partners:'شركاء الشحن', trackShipment:'تتبع الشحنة' },
    chatbot: { greeting:'كيف يمكنني مساعدتك؟', placeholder:'أدخل أمراً...', suggestedActions:'إجراءات مقترحة', operational:'يعمل' },
  }},
};

i18n.use(initReactI18next).init({
  resources, lng: localStorage.getItem('lang') || 'en', fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

export default i18n;
