import React,{useState,useEffect} from'react';
import DashboardLayout from'../../components/shared/DashboardLayout';
import{useStoreManagement}from'../../hooks/useStore';
import{ownerApi}from'../../utils/api';
import toast from'react-hot-toast';
import{Plus,X,Save,Trash2,ChevronUp,ChevronDown,Eye,EyeOff,Type,Image,Layout,Package,Copy,Monitor,Smartphone,Star,Sparkles,Zap,Layers}from'lucide-react';

const FONTS=['Inter','Arial','Georgia','Playfair Display','Poppins','Roboto','Montserrat','Lora','Raleway','Cairo','Tajawal','DM Sans','Space Grotesk'];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);

const SECTION_TYPES=[
  {type:'hero',label:'Hero Banner',icon:Layout,desc:'Large banner with title and subtitle'},
  {type:'products',label:'Products Grid',icon:Package,desc:'Display products in a grid'},
  {type:'text',label:'Text Block',icon:Type,desc:'Custom text content'},
  {type:'image',label:'Image',icon:Image,desc:'Full-width or contained image'},
  {type:'banner',label:'Promo Banner',icon:Sparkles,desc:'Promotional banner with CTA'},
  {type:'spacer',label:'Spacer',icon:ChevronDown,desc:'Empty space between sections'},
  {type:'features',label:'Features/Trust',icon:Star,desc:'Feature icons with text'},
  {type:'testimonials',label:'Testimonials',icon:Star,desc:'Customer reviews showcase'},
  {type:'custom_html',label:'Custom HTML',icon:Zap,desc:'Raw HTML content'},
];

// Templates inspired by Canva's ecommerce website library — distinct niches,
// editorial hero layouts, refined palettes, single-purpose section rhythm.
// Animation presets — each template gets its own signature motion that gets
// stamped onto every section when the template is applied. The Storefront
// BuilderSections reads `section.animation` and plays the matching preset
// via framer-motion whileInView (see Storefront.jsx).
const ANIMATIONS=['editorial','luxe','warm','bouncy','calm','slam','tech','glow','rise','noble'];

const TEMPLATES=[
  {name:'White Minimalist Fashion',animation:'editorial',desc:'Canva-style clean editorial. All-white canvas, oversized Playfair display type. Apparel & lookbooks.',colors:['#ffffff','#111111','#f2f2f2'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#ffffff',textColor:'#111111',padding:'120',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1400'},content:{title:'Wardrobe, elevated.',subtitle:'The spring edit — 42 new pieces, curated in Algiers.',btnText:'Shop the edit',btnLink:'#products',titleSize:'92',subtitleSize:'18',btnColor:'#111111',bgImage:'',overlay:'0',align:'center',height:'640'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#111111',textColor:'#ffffff',padding:'16',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1400'},content:{text:'FREE SHIPPING OVER 8 000 DZD   ·   14-DAY RETURNS   ·   NEW ARRIVALS EVERY WEEK',btnText:'',btnLink:'',fontSize:'11',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#111111',padding:'90',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1320'},content:{title:'THE EDIT',titleSize:'14',columns:'4',mobileColumns:'2',cardStyle:'minimal',showPrice:true,showName:true,showBtn:false,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#f2f2f2',textColor:'#111111',padding:'100',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'900'},content:{text:'"Style is knowing who you are, what you want to say, and not giving a damn."',fontSize:'34',lineHeight:'1.5',align:'center',maxWidth:'720'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#111111',padding:'90',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1320'},content:{title:'BESTSELLERS',titleSize:'14',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'3',featured:true}},
      {id:uid(),type:'features',visible:true,style:{bg:'#111111',textColor:'#ffffff',padding:'64',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1200'},content:{items:[{icon:'◼',title:'CURATED',desc:'Hand-selected every week'},{icon:'◼',title:'SUSTAINABLE',desc:'Small-batch production'},{icon:'◼',title:'WORLDWIDE',desc:'Ships to 50+ countries'}],columns:'3'}},
  ]},
  {name:'Brown Beauty Launch',animation:'luxe',desc:'Canva beauty single-page launch. Warm taupe & mocha, serif display, product-focused.',colors:['#f3ece2','#6b3e26','#e9dcc9'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#f3ece2',textColor:'#3d2414',padding:'110',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{title:'Glow, bottled.',subtitle:'The new serum everyone\'s reaching for — 97% natural, dermatologist-tested.',btnText:'Shop the launch',btnLink:'#products',titleSize:'74',subtitleSize:'18',btnColor:'#6b3e26',bgImage:'',overlay:'0',align:'center',height:'580'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#e9dcc9',textColor:'#3d2414',padding:'64',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'✦',title:'97% Natural',desc:'Cold-pressed botanicals'},{icon:'◈',title:'Dermatologist-tested',desc:'Safe for sensitive skin'},{icon:'◉',title:'Refillable',desc:'Glass, not plastic'}],columns:'3'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#3d2414',padding:'90',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{title:'The Collection',titleSize:'42',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'6',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#6b3e26',textColor:'#f3ece2',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'820'},content:{text:'"I used it for 14 days and genuinely couldn\'t believe the difference. My skin feels like mine again."',fontSize:'24',lineHeight:'1.8',align:'center',maxWidth:'720'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#f3ece2',textColor:'#3d2414',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'Reviews that matter',titleSize:'36',items:[{name:'Yasmine · Algiers',text:'Two weeks in and my skin has never looked better. Period.',rating:5},{name:'Meriem · Oran',text:'Scent is gorgeous, finish is silky. Worth every dinar.',rating:5},{name:'Rania · Setif',text:'I\'ve repurchased three times already. Cult favorite.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#3d2414',textColor:'#f3ece2',padding:'64',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{text:'Launch offer — free mini with every full size',btnText:'Shop now',btnLink:'#products',fontSize:'28',align:'center'}},
  ]},
  {name:'Cream & Orange Organic Fashion',animation:'warm',desc:'Canva retail template. Warm cream with burnt-orange accents. Natural fashion & lifestyle.',colors:['#fdf6ec','#d97706','#fff8f0'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#fdf6ec',textColor:'#431407',padding:'100',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1280'},content:{title:'Softly woven. Sustainably made.',subtitle:'Linen, cotton, and slow style — for people who wear their values.',btnText:'Explore collection',btnLink:'#products',titleSize:'62',subtitleSize:'19',btnColor:'#d97706',bgImage:'',overlay:'0',align:'center',height:'580'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#d97706',textColor:'#fdf6ec',padding:'14',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1400'},content:{text:'✿   NEW SPRING COLLECTION IS LIVE   ·   CARBON-NEUTRAL SHIPPING   ·   100% NATURAL FIBERS   ✿',btnText:'',btnLink:'',fontSize:'12',align:'center'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#fff8f0',textColor:'#7c2d12',padding:'64',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🌾',title:'Natural fibers',desc:'Linen, organic cotton, hemp'},{icon:'✂️',title:'Small batch',desc:'Made ethically in Algeria'},{icon:'📦',title:'Plastic-free',desc:'Recycled paper packaging'},{icon:'♥',title:'Lifetime repairs',desc:'We mend it, you keep it'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#fdf6ec',textColor:'#431407',padding:'90',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1280'},content:{title:'Spring favorites',titleSize:'38',columns:'4',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#d97706',textColor:'#fff8f0',padding:'80',fontFamily:'Raleway',borderRadius:'0',maxWidth:'900'},content:{text:'Every piece is made slowly, on purpose. Fewer collections, better fabrics, longer lifespans. That\'s the only luxury we believe in.',fontSize:'20',lineHeight:'1.9',align:'center',maxWidth:'760'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fff8f0',textColor:'#431407',padding:'80',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1100'},content:{title:'What our community says',titleSize:'32',items:[{name:'Lina',text:'The linen dress is the most comfortable thing I own. Fits perfectly.',rating:5},{name:'Salim',text:'Finally a brand doing slow fashion properly in Algeria.',rating:5},{name:'Imène',text:'Bought one shirt, came back for five. Quality is unreal.',rating:5}]}},
  ]},
  {name:'Pastel Blocks Fashion',animation:'bouncy',desc:'Canva playful color-block style. Soft pinks, lilacs, mint. Gen-Z fashion & accessories.',colors:['#fde2e4','#b8a4e3','#d6f5e3'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#fde2e4',textColor:'#4a1d3e',padding:'100',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1280'},content:{title:'Soft era. Loud wardrobe.',subtitle:'Playful pieces for people who dress for themselves first.',btnText:'Shop the vibe',btnLink:'#products',titleSize:'70',subtitleSize:'19',btnColor:'#b8a4e3',bgImage:'',overlay:'0',align:'center',height:'580'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#d6f5e3',textColor:'#1f3d2a',padding:'56',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🎀',title:'Cute & comfy',desc:'All-day soft fabrics'},{icon:'🚚',title:'48h delivery',desc:'DZ-wide express'},{icon:'💌',title:'Gift-wrapped',desc:'Ribbon & note included'},{icon:'🌟',title:'Size-inclusive',desc:'XS to 3XL, always'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#b8a4e3',textColor:'#ffffff',padding:'90',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1280'},content:{title:'Loved this week 💖',titleSize:'34',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#fde2e4',textColor:'#4a1d3e',padding:'56',fontFamily:'Poppins',borderRadius:'32',maxWidth:'1100'},content:{text:'First order? Use SOFT10 for 10% off ✨',btnText:'Claim offer',btnLink:'#products',fontSize:'24',align:'center'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#d6f5e3',textColor:'#1f3d2a',padding:'80',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1100'},content:{title:'Real reviews from real besties',titleSize:'30',items:[{name:'Meriem',text:'Obsessed. Literally wear something from this store every day.',rating:5},{name:'Nour',text:'Packaging made me scream. Products made me scream louder.',rating:5},{name:'Lyna',text:'Finally a DZ brand that actually gets Gen-Z fashion.',rating:5}]}},
  ]},
  {name:'Minimal Furniture',animation:'calm',desc:'Canva home decor style. Warm stone, oak, cream. Interior, furniture, home goods.',colors:['#e8e0d4','#8c6b4a','#f6f1ea'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#e8e0d4',textColor:'#2e2318',padding:'110',fontFamily:'Lora',borderRadius:'0',maxWidth:'1320'},content:{title:'Quiet homes, better days.',subtitle:'Handcrafted furniture and homeware for spaces that feel like yours.',btnText:'Browse the house',btnLink:'#products',titleSize:'64',subtitleSize:'19',btnColor:'#8c6b4a',bgImage:'',overlay:'0',align:'center',height:'620'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#f6f1ea',textColor:'#2e2318',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1280'},content:{title:'Featured pieces',titleSize:'38',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'6',featured:true}},
      {id:uid(),type:'text',visible:true,style:{bg:'#8c6b4a',textColor:'#f6f1ea',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'860'},content:{text:'We build slowly, with solid oak, local craftsmen, and a stubborn belief that good furniture should outlive its owner.',fontSize:'20',lineHeight:'1.9',align:'center',maxWidth:'720'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#e8e0d4',textColor:'#2e2318',padding:'64',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🪵',title:'Solid wood',desc:'No veneer, no MDF'},{icon:'🔨',title:'Handmade in DZ',desc:'By 3rd-gen artisans'},{icon:'📏',title:'Made to order',desc:'Custom sizes welcome'},{icon:'🚚',title:'White-glove delivery',desc:'Placed & assembled'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#f6f1ea',textColor:'#2e2318',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1280'},content:{title:'New this season',titleSize:'32',columns:'4',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'8',featured:false}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#e8e0d4',textColor:'#2e2318',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'Living room stories',titleSize:'32',items:[{name:'Hakim & Sarah',text:'The dining table is the centerpiece of our home. Everyone asks about it.',rating:5},{name:'Fatima Z.',text:'Worth every dinar. Delivery team was incredibly professional.',rating:5},{name:'Ilyes B.',text:'I\'ve had the oak desk for a year. It still looks brand new.',rating:5}]}},
  ]},
  {name:'Bold Yellow Fitness',animation:'slam',desc:'Canva sports/fitness template. Electric yellow on black, bold sans caps. Gym, supplements, activewear.',colors:['#0a0a0a','#facc15','#1c1c1c'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0a0a0a',textColor:'#facc15',padding:'110',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1400'},content:{title:'TRAIN LIKE YOU MEAN IT.',subtitle:'Activewear, supplements, and gear built for athletes who don\'t skip leg day.',btnText:'SHOP THE GYM',btnLink:'#products',titleSize:'86',subtitleSize:'17',btnColor:'#facc15',bgImage:'',overlay:'0',align:'center',height:'620'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#facc15',textColor:'#0a0a0a',padding:'18',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1400'},content:{text:'▲  NEW CLIENTS GET 20% OFF FIRST ORDER  ·  CODE: PUMP20  ·  LIMITED TIME  ▲',btnText:'',btnLink:'',fontSize:'13',align:'center'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#1c1c1c',textColor:'#fafafa',padding:'64',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1200'},content:{items:[{icon:'💪',title:'PRO-GRADE',desc:'Used by national athletes'},{icon:'⚡',title:'48H DELIVERY',desc:'Express nationwide'},{icon:'🧪',title:'LAB-TESTED',desc:'Third-party verified'},{icon:'🏆',title:'GUARANTEED',desc:'60-day money-back'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#0a0a0a',textColor:'#facc15',padding:'90',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1320'},content:{title:'GEAR UP',titleSize:'36',columns:'4',mobileColumns:'2',cardStyle:'border',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#facc15',textColor:'#0a0a0a',padding:'80',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'900'},content:{text:'NO SHORTCUTS. NO EXCUSES. JUST THE GEAR YOU NEED TO SHOW UP EVERY DAY AND GO HARDER THAN YESTERDAY.',fontSize:'24',lineHeight:'1.6',align:'center',maxWidth:'780'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#1c1c1c',textColor:'#fafafa',padding:'90',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1100'},content:{title:'FROM THE COMMUNITY',titleSize:'30',items:[{name:'KARIM · CROSSFIT COACH',text:'The whey is pure fire. My whole gym switched over.',rating:5},{name:'LEILA · MARATHON RUNNER',text:'Finally activewear that actually survives hard training.',rating:5},{name:'SAMIR · BODYBUILDER',text:'Pre-workout hits hard without the crash. New staple.',rating:5}]}},
  ]},
  {name:'Modern Gadget Store',animation:'tech',desc:'Canva tech template. Dark navy with cyan accents, clean Inter. Electronics, gadgets, accessories.',colors:['#0c1220','#22d3ee','#1e293b'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0c1220',textColor:'#f1f5f9',padding:'120',fontFamily:'Inter',borderRadius:'0',maxWidth:'1400'},content:{title:'Tech that actually works.',subtitle:'Genuine electronics, real warranties, same-day delivery in Algiers.',btnText:'Browse the store',btnLink:'#products',titleSize:'70',subtitleSize:'20',btnColor:'#22d3ee',bgImage:'',overlay:'0',align:'center',height:'620'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#1e293b',textColor:'#cbd5e1',padding:'56',fontFamily:'Inter',borderRadius:'0',maxWidth:'1280'},content:{items:[{icon:'✓',title:'100% Genuine',desc:'Direct manufacturer sourcing'},{icon:'🛡',title:'1-Year Warranty',desc:'Official, not just store credit'},{icon:'⚡',title:'Same-day Algiers',desc:'Before 3 PM = today'},{icon:'💬',title:'Real tech support',desc:'Engineers on WhatsApp'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#0c1220',textColor:'#f1f5f9',padding:'90',fontFamily:'Inter',borderRadius:'0',maxWidth:'1320'},content:{title:'Featured gear',titleSize:'34',columns:'4',mobileColumns:'2',cardStyle:'border',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#22d3ee',textColor:'#0c1220',padding:'64',fontFamily:'Inter',borderRadius:'0',maxWidth:'1400'},content:{text:'Pay in 4 × zero interest — on every order over 15 000 DZD',btnText:'How it works',btnLink:'#products',fontSize:'26',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#1e293b',textColor:'#f1f5f9',padding:'90',fontFamily:'Inter',borderRadius:'0',maxWidth:'1320'},content:{title:'Staff picks this month',titleSize:'30',columns:'3',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'6',featured:true}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#0c1220',textColor:'#cbd5e1',padding:'90',fontFamily:'Inter',borderRadius:'0',maxWidth:'1100'},content:{title:'Verified customer reviews',titleSize:'30',items:[{name:'Omar · Algiers',text:'Ordered AirPods at 11 AM, delivered same day. Sealed, legit, warranty card included.',rating:5},{name:'Lyes · Oran',text:'Best tech store in DZ — fair prices, no fakes, real after-sales.',rating:5},{name:'Amina · Blida',text:'Support helped me pick the right laptop over WhatsApp. 10/10.',rating:5}]}},
  ]},
  {name:'Jewelry Elegance',animation:'glow',desc:'Canva luxury template. Ivory & champagne gold, Playfair display. Fine jewelry, watches, accessories.',colors:['#faf6ef','#b88a3b','#1a1a1a'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#faf6ef',textColor:'#1a1a1a',padding:'130',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1320'},content:{title:'Heirlooms in the making.',subtitle:'18k gold, ethically sourced stones, handcrafted in Algiers.',btnText:'View the collection',btnLink:'#products',titleSize:'72',subtitleSize:'18',btnColor:'#b88a3b',bgImage:'',overlay:'0',align:'center',height:'640'}},
      {id:uid(),type:'spacer',visible:true,style:{bg:'#faf6ef',textColor:'#000',padding:'0',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'},content:{height:'8'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#faf6ef',textColor:'#1a1a1a',padding:'64',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'◆',title:'Ethically sourced',desc:'Conflict-free stones only'},{icon:'✦',title:'Master goldsmiths',desc:'30+ years experience'},{icon:'✧',title:'Lifetime warranty',desc:'Cleaning & resizing free'}],columns:'3'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#1a1a1a',padding:'100',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{title:'The Signature Collection',titleSize:'44',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'6',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#1a1a1a',textColor:'#b88a3b',padding:'100',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'900'},content:{text:'"Every piece carries a promise — of quality, authenticity, and beauty that outlives trends."',fontSize:'28',lineHeight:'1.7',align:'center',maxWidth:'780'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#faf6ef',textColor:'#1a1a1a',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'Client stories',titleSize:'36',items:[{name:'Amira B.',text:'The ring took my breath away. Even more beautiful in person.',rating:5},{name:'Karim D.',text:'Bought a necklace for our anniversary — she cried happy tears.',rating:5},{name:'Lina S.',text:'The packaging alone felt like a luxury experience.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#b88a3b',textColor:'#faf6ef',padding:'64',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1320'},content:{text:'Complimentary engraving on every order',btnText:'Discover',btnLink:'#products',fontSize:'28',align:'center'}},
  ]},
  {name:'Cozy Bakery',animation:'rise',desc:'Canva bakery/food template. Warm cream & cinnamon, handwritten-feel serif. Bakeries, cafés, artisan food.',colors:['#fff4e6','#b45309','#fef3c7'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#fff4e6',textColor:'#5a2e0c',padding:'100',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{title:'Baked fresh. Every morning.',subtitle:'Sourdough, croissants, and little joys — made by hand in Algiers since 2019.',btnText:'Order today\'s batch',btnLink:'#products',titleSize:'68',subtitleSize:'19',btnColor:'#b45309',bgImage:'',overlay:'0',align:'center',height:'580'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#b45309',textColor:'#fff4e6',padding:'16',fontFamily:'Lora',borderRadius:'0',maxWidth:'1400'},content:{text:'🥐  FRESH DAILY FROM 6 AM  ·  ORDERS CLOSE AT 8 PM  ·  DELIVERY BEFORE 11 AM  🥐',btnText:'',btnLink:'',fontSize:'13',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#fef3c7',textColor:'#5a2e0c',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1280'},content:{title:'Today\'s menu',titleSize:'38',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'features',visible:true,style:{bg:'#fff4e6',textColor:'#5a2e0c',padding:'64',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🌾',title:'Stone-milled flour',desc:'From local farms'},{icon:'⏰',title:'24h fermentation',desc:'Real slow sourdough'},{icon:'🚲',title:'Hot delivery',desc:'Insulated boxes, always fresh'},{icon:'♻️',title:'Zero-waste',desc:'Unsold goes to shelters'}],columns:'4'}},
      {id:uid(),type:'text',visible:true,style:{bg:'#b45309',textColor:'#fff4e6',padding:'80',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'860'},content:{text:'"A little bakery with very big standards — and the best croissants in the city."',fontSize:'26',lineHeight:'1.7',align:'center',maxWidth:'740'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fef3c7',textColor:'#5a2e0c',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'Love from our regulars',titleSize:'32',items:[{name:'Meriem',text:'I\'ve tried every bakery in Algiers. Nothing comes close to this sourdough.',rating:5},{name:'Ahmed',text:'The pistachio croissant changed my life. I\'m not exaggerating.',rating:5},{name:'Nadia',text:'Fresh, warm, on time. My Sunday ritual now.',rating:5}]}},
  ]},
  {name:'متجر عربي راقي',animation:'noble',desc:'قالب كانفا بالعربية — كحلي وذهبي، خط Cairo، تجربة فاخرة للعلامات الجزائرية.',colors:['#0f1e2e','#d4a34a','#fcf8ef'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0f1e2e',textColor:'#fcf8ef',padding:'120',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1320'},content:{title:'تسوّق بثقة، استلم بفخامة',subtitle:'منتجات أصلية · توصيل سريع لكل الولايات · دفع عند الاستلام',btnText:'اكتشف المجموعة',btnLink:'#products',titleSize:'62',subtitleSize:'20',btnColor:'#d4a34a',bgImage:'',overlay:'0',align:'center',height:'620'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#fcf8ef',textColor:'#0f1e2e',padding:'64',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1200'},content:{items:[{icon:'🚚',title:'توصيل لكل الولايات',desc:'خلال 48 ساعة'},{icon:'💳',title:'الدفع عند الاستلام',desc:'أو CCP / BaridiMob'},{icon:'↩',title:'إرجاع مجاني',desc:'خلال 14 يوم'},{icon:'✓',title:'منتجات أصلية',desc:'ضمان جودة 100%'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0f1e2e',padding:'90',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1320'},content:{title:'الأكثر مبيعًا',titleSize:'40',columns:'4',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#d4a34a',textColor:'#0f1e2e',padding:'80',fontFamily:'Cairo',borderRadius:'0',maxWidth:'900'},content:{text:'"خدمة ممتازة، منتجات أصلية، وتوصيل سريع. أحسن متجر تعاملت معاه في الجزائر."',fontSize:'24',lineHeight:'1.8',align:'center',maxWidth:'780'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fcf8ef',textColor:'#0f1e2e',padding:'90',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1100'},content:{title:'آراء عملائنا',titleSize:'36',items:[{name:'أحمد · الجزائر',text:'طلبت ووصلني نفس اليوم. جودة عالية وتغليف راقي.',rating:5},{name:'فاطمة · وهران',text:'أحسن خدمة زبائن جربتها. كل شيء كما في الصور.',rating:5},{name:'ياسين · قسنطينة',text:'منتجات أصلية وأسعار معقولة. سأعود حتمًا.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#0f1e2e',textColor:'#d4a34a',padding:'64',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1400'},content:{text:'🎉 خصم 15% على أول طلب — استعمل كود WELCOME15',btnText:'تسوّق الآن',btnLink:'#products',fontSize:'26',align:'center'}},
  ]},
];

const defaultSection=(type)=>{
  const base={id:uid(),type,visible:true,style:{bg:'#ffffff',textColor:'#1f2937',padding:'60',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'}};
  const defs={hero:{title:'Welcome',subtitle:'Discover amazing products',btnText:'Shop Now',btnLink:'#products',titleSize:'48',subtitleSize:'20',btnColor:'#7C3AED',bgImage:'',overlay:'0.3',align:'center',height:'500'},products:{title:'Our Products',titleSize:'28',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false},text:{text:'Add your content here.',fontSize:'16',lineHeight:'1.7',align:'left',maxWidth:'800'},image:{src:'',alt:'',width:'100',height:'auto',align:'center',rounded:'12',link:''},banner:{text:'Special Offer!',btnText:'Shop Now',btnLink:'#',fontSize:'24',align:'center'},spacer:{height:'60'},features:{items:[{icon:'🚚',title:'Fast Delivery',desc:'All wilayas'},{icon:'💳',title:'Secure Payment',desc:'Multiple options'},{icon:'🔄',title:'Easy Returns',desc:'30-day policy'}],columns:'3'},testimonials:{title:'Reviews',titleSize:'28',items:[{name:'Ahmed',text:'Great!',rating:5},{name:'Sara',text:'Love it!',rating:5}]},custom_html:{html:'<div style="text-align:center;padding:20px"><h2>Custom</h2></div>'}};
  if(type==='banner')base.style={...base.style,bg:'#7C3AED',textColor:'#ffffff',padding:'40'};
  if(type==='spacer')base.style={...base.style,padding:'0',bg:'transparent'};
  return{...base,content:defs[type]||{}};
};

function StylePanel({section,onChange}){
  const s=section.style||{};const c=section.content||{};
  const set=(k,v)=>onChange({...section,style:{...s,[k]:v}});
  const setC=(k,v)=>onChange({...section,content:{...c,[k]:v}});
  return(<div className="space-y-3 text-sm">
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Background</p><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded cursor-pointer" value={s.bg||'#ffffff'} onChange={e=>set('bg',e.target.value)}/><input className="input-field flex-1 !py-1 text-xs" value={s.bg||''} onChange={e=>set('bg',e.target.value)}/></div></div>
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Text Color</p><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded cursor-pointer" value={s.textColor||'#1f2937'} onChange={e=>set('textColor',e.target.value)}/><input className="input-field flex-1 !py-1 text-xs" value={s.textColor||''} onChange={e=>set('textColor',e.target.value)}/></div></div>
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Font</p><select className="input-field !py-1 text-xs" value={s.fontFamily||'Inter'} onChange={e=>set('fontFamily',e.target.value)}>{FONTS.map(f=><option key={f} value={f}>{f}</option>)}</select></div>
    <div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Padding</p><input type="number" className="input-field !py-1 text-xs" value={s.padding||'60'} onChange={e=>set('padding',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Radius</p><input type="number" className="input-field !py-1 text-xs" value={s.borderRadius||'0'} onChange={e=>set('borderRadius',e.target.value)}/></div></div>
    <div><p className="text-[10px] text-gray-400">Max Width</p><input type="number" className="input-field !py-1 text-xs" value={s.maxWidth||'1200'} onChange={e=>set('maxWidth',e.target.value)}/></div>
    {section.type==='hero'&&<><hr/><p className="text-[10px] font-bold text-brand-500 uppercase">Hero</p><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Subtitle</p><input className="input-field !py-1 text-xs" value={c.subtitle||''} onChange={e=>setC('subtitle',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Title Size</p><input type="number" className="input-field !py-1 text-xs" value={c.titleSize||'48'} onChange={e=>setC('titleSize',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Sub Size</p><input type="number" className="input-field !py-1 text-xs" value={c.subtitleSize||'20'} onChange={e=>setC('subtitleSize',e.target.value)}/></div></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Button</p><input className="input-field !py-1 text-xs" value={c.btnText||''} onChange={e=>setC('btnText',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Btn Color</p><div className="flex gap-1"><input type="color" className="w-6 h-6 rounded" value={c.btnColor||'#7C3AED'} onChange={e=>setC('btnColor',e.target.value)}/><input className="input-field flex-1 !py-0.5 text-[10px]" value={c.btnColor||''} onChange={e=>setC('btnColor',e.target.value)}/></div></div></div><div><p className="text-[10px] text-gray-400">Height</p><input type="number" className="input-field !py-1 text-xs" value={c.height||'500'} onChange={e=>setC('height',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">BG Image</p><input className="input-field !py-1 text-xs" value={c.bgImage||''} onChange={e=>setC('bgImage',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Align</p><div className="flex gap-1">{['left','center','right'].map(a=><button key={a} onClick={()=>setC('align',a)} className={`flex-1 py-1 rounded text-xs font-bold ${c.align===a?'bg-brand-500 text-white':'bg-gray-100'}`}>{a}</button>)}</div></div></>}
    {section.type==='products'&&<><hr/><p className="text-[10px] font-bold text-brand-500 uppercase">Products</p><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Columns</p><select className="input-field !py-1 text-xs" value={c.columns||'4'} onChange={e=>setC('columns',e.target.value)}><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><div><p className="text-[10px] text-gray-400">Limit</p><input type="number" className="input-field !py-1 text-xs" value={c.limit||'8'} onChange={e=>setC('limit',e.target.value)}/></div></div><div><p className="text-[10px] text-gray-400">Card Style</p><select className="input-field !py-1 text-xs" value={c.cardStyle||'shadow'} onChange={e=>setC('cardStyle',e.target.value)}><option value="shadow">Shadow</option><option value="border">Border</option><option value="flat">Flat</option><option value="minimal">Minimal</option></select></div><label className="flex items-center gap-2"><input type="checkbox" checked={c.showPrice!==false} onChange={e=>setC('showPrice',e.target.checked)}/><span className="text-xs">Price</span></label><label className="flex items-center gap-2"><input type="checkbox" checked={c.showBtn!==false} onChange={e=>setC('showBtn',e.target.checked)}/><span className="text-xs">Cart btn</span></label><label className="flex items-center gap-2"><input type="checkbox" checked={c.featured||false} onChange={e=>setC('featured',e.target.checked)}/><span className="text-xs">Featured only</span></label></>}
    {section.type==='text'&&<><hr/><div><p className="text-[10px] text-gray-400">Content</p><textarea className="input-field !py-1 text-xs" rows={4} value={c.text||''} onChange={e=>setC('text',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Size</p><input type="number" className="input-field !py-1 text-xs" value={c.fontSize||'16'} onChange={e=>setC('fontSize',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Line H</p><input className="input-field !py-1 text-xs" value={c.lineHeight||'1.7'} onChange={e=>setC('lineHeight',e.target.value)}/></div></div><div><p className="text-[10px] text-gray-400">Align</p><div className="flex gap-1">{['left','center','right'].map(a=><button key={a} onClick={()=>setC('align',a)} className={`flex-1 py-1 rounded text-xs font-bold ${c.align===a?'bg-brand-500 text-white':'bg-gray-100'}`}>{a}</button>)}</div></div></>}
    {section.type==='image'&&<><hr/><div><p className="text-[10px] text-gray-400">Image URL</p><input className="input-field !py-1 text-xs" value={c.src||''} onChange={e=>setC('src',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Width %</p><input type="number" className="input-field !py-1 text-xs" value={c.width||'100'} onChange={e=>setC('width',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Rounded</p><input type="number" className="input-field !py-1 text-xs" value={c.rounded||'12'} onChange={e=>setC('rounded',e.target.value)}/></div></div></>}
    {section.type==='banner'&&<><hr/><div><p className="text-[10px] text-gray-400">Text</p><input className="input-field !py-1 text-xs" value={c.text||''} onChange={e=>setC('text',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Font Size</p><input type="number" className="input-field !py-1 text-xs" value={c.fontSize||'24'} onChange={e=>setC('fontSize',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Button</p><input className="input-field !py-1 text-xs" value={c.btnText||''} onChange={e=>setC('btnText',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Link</p><input className="input-field !py-1 text-xs" value={c.btnLink||''} onChange={e=>setC('btnLink',e.target.value)}/></div></div></>}
    {section.type==='spacer'&&<div><p className="text-[10px] text-gray-400">Height</p><input type="number" className="input-field !py-1 text-xs" value={c.height||'60'} onChange={e=>setC('height',e.target.value)}/></div>}
    {section.type==='features'&&<><hr/><div><p className="text-[10px] text-gray-400">Columns</p><select className="input-field !py-1 text-xs" value={c.columns||'3'} onChange={e=>setC('columns',e.target.value)}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div>{(c.items||[]).map((it,i)=><div key={i} className="p-2 bg-gray-50 rounded-lg space-y-1"><div className="flex gap-1"><input className="input-field !py-0.5 text-xs w-10" value={it.icon||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],icon:e.target.value};setC('items',a);}}/><input className="input-field !py-0.5 text-xs flex-1" value={it.title||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],title:e.target.value};setC('items',a);}}/><button onClick={()=>{const a=[...c.items];a.splice(i,1);setC('items',a);}} className="text-red-400"><X size={12}/></button></div><input className="input-field !py-0.5 text-xs" value={it.desc||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],desc:e.target.value};setC('items',a);}}/></div>)}<button onClick={()=>setC('items',[...(c.items||[]),{icon:'⭐',title:'Feature',desc:'Desc'}])} className="text-xs text-brand-600 font-bold">+ Add</button></>}
    {section.type==='testimonials'&&<><hr/><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div>{(c.items||[]).map((it,i)=><div key={i} className="p-2 bg-gray-50 rounded-lg space-y-1"><div className="flex gap-1"><input className="input-field !py-0.5 text-xs w-20" value={it.name||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],name:e.target.value};setC('items',a);}}/><select className="input-field !py-0.5 text-xs w-14" value={it.rating||5} onChange={e=>{const a=[...c.items];a[i]={...a[i],rating:parseInt(e.target.value)};setC('items',a);}}><option value={5}>5★</option><option value={4}>4★</option><option value={3}>3★</option></select><button onClick={()=>{const a=[...c.items];a.splice(i,1);setC('items',a);}} className="text-red-400"><X size={12}/></button></div><textarea className="input-field !py-0.5 text-xs" rows={2} value={it.text||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],text:e.target.value};setC('items',a);}}/></div>)}<button onClick={()=>setC('items',[...(c.items||[]),{name:'Customer',text:'Great!',rating:5}])} className="text-xs text-brand-600 font-bold">+ Add</button></>}
    {section.type==='custom_html'&&<><hr/><div><p className="text-[10px] text-gray-400">HTML</p><textarea className="input-field !py-1 text-xs font-mono" rows={6} value={c.html||''} onChange={e=>setC('html',e.target.value)}/></div></>}
  </div>);
}

function Preview({section}){
  const s=section.style||{};const c=section.content||{};
  const wrap={backgroundColor:s.bg||'#fff',color:s.textColor||'#1f2937',padding:`${(parseInt(s.padding)||60)/4}px`,fontFamily:s.fontFamily||'Inter',borderRadius:`${s.borderRadius||0}px`};
  if(section.type==='hero')return<div style={{...wrap,minHeight:`${(parseInt(c.height)||500)/4}px`,backgroundImage:c.bgImage?`url(${c.bgImage})`:'none',backgroundSize:'cover',backgroundPosition:'center',display:'flex',alignItems:'center',justifyContent:'center',textAlign:c.align||'center',position:'relative'}}>{c.bgImage&&<div style={{position:'absolute',inset:0,backgroundColor:`rgba(0,0,0,${c.overlay||0.3})`}}/>}<div style={{position:'relative',zIndex:1}}><p style={{fontSize:`${(parseInt(c.titleSize)||48)/3}px`,fontWeight:900}}>{c.title}</p><p style={{fontSize:`${(parseInt(c.subtitleSize)||20)/3}px`,opacity:0.7,marginTop:3}}>{c.subtitle}</p>{c.btnText&&<div style={{marginTop:6,display:'inline-block',padding:'3px 10px',backgroundColor:c.btnColor||'#7C3AED',color:'#fff',borderRadius:5,fontSize:9,fontWeight:700}}>{c.btnText}</div>}</div></div>;
  if(section.type==='products'){const cols=parseInt(c.columns)||4;return<div style={wrap}>{c.title&&<p style={{fontSize:`${(parseInt(c.titleSize)||28)/3}px`,fontWeight:800,textAlign:'center',marginBottom:6}}>{c.title}</p>}<div style={{display:'grid',gridTemplateColumns:`repeat(${cols},1fr)`,gap:4}}>{Array.from({length:Math.min(parseInt(c.limit)||4,6)}).map((_,i)=><div key={i} style={{backgroundColor:s.bg==='#ffffff'||!s.bg?'#f3f4f6':'rgba(255,255,255,0.1)',borderRadius:6,overflow:'hidden'}}><div style={{height:30,backgroundColor:s.bg==='#ffffff'||!s.bg?'#e5e7eb':'rgba(255,255,255,0.05)'}}/><div style={{padding:3}}><div style={{height:4,backgroundColor:'rgba(128,128,128,0.3)',borderRadius:2,width:'70%',marginBottom:2}}/>{c.showPrice!==false&&<div style={{height:4,backgroundColor:'rgba(128,128,255,0.4)',borderRadius:2,width:'40%'}}/>}</div></div>)}</div></div>;}
  if(section.type==='text')return<div style={{...wrap,textAlign:c.align||'left'}}><p style={{fontSize:`${(parseInt(c.fontSize)||16)/3}px`,lineHeight:c.lineHeight||'1.7'}}>{c.text}</p></div>;
  if(section.type==='image')return<div style={{...wrap,textAlign:c.align||'center'}}>{c.src?<img src={c.src} style={{width:`${c.width||100}%`,borderRadius:`${c.rounded||12}px`,maxWidth:'100%'}} alt=""/>:<div style={{height:40,backgroundColor:'#e5e7eb',borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',color:'#9ca3af',fontSize:10}}>No image</div>}</div>;
  if(section.type==='banner')return<div style={{...wrap,textAlign:c.align||'center'}}><p style={{fontSize:`${(parseInt(c.fontSize)||24)/3}px`,fontWeight:800}}>{c.text}</p>{c.btnText&&<div style={{marginTop:4,display:'inline-block',padding:'2px 8px',border:'1px solid currentColor',borderRadius:4,fontSize:8}}>{c.btnText}</div>}</div>;
  if(section.type==='spacer')return<div style={{height:`${(parseInt(c.height)||60)/4}px`,backgroundColor:s.bg||'transparent'}}/>;
  if(section.type==='features'){const cols=parseInt(c.columns)||3;return<div style={wrap}><div style={{display:'grid',gridTemplateColumns:`repeat(${cols},1fr)`,gap:6,textAlign:'center'}}>{(c.items||[]).map((f,i)=><div key={i}><span style={{fontSize:14}}>{f.icon}</span><p style={{fontWeight:700,fontSize:8,marginTop:1}}>{f.title}</p><p style={{fontSize:6,opacity:0.6}}>{f.desc}</p></div>)}</div></div>;}
  if(section.type==='testimonials')return<div style={wrap}>{c.title&&<p style={{fontSize:`${(parseInt(c.titleSize)||28)/3}px`,fontWeight:800,textAlign:'center',marginBottom:6}}>{c.title}</p>}<div style={{display:'grid',gridTemplateColumns:`repeat(${Math.min((c.items||[]).length,3)},1fr)`,gap:4}}>{(c.items||[]).map((t,i)=><div key={i} style={{backgroundColor:'rgba(128,128,128,0.08)',padding:4,borderRadius:6}}><p style={{fontSize:6}}>{t.text}</p><p style={{fontSize:5,fontWeight:700,marginTop:2}}>— {t.name}</p></div>)}</div></div>;
  if(section.type==='custom_html')return<div style={wrap}><div style={{fontSize:7,color:'#9ca3af',textAlign:'center'}}>Custom HTML</div></div>;
  return null;
}

export default function AdvancedBuilder(){
  const{currentStore,setCurrentStore}=useStoreManagement();
  const[sections,setSections]=useState([]);
  const[selected,setSelected]=useState(null);
  const[showAdd,setShowAdd]=useState(false);
  const[showTemplates,setShowTemplates]=useState(false);
  const[saving,setSaving]=useState(false);
  const[preview,setPreview]=useState('desktop');
  const[dirty,setDirty]=useState(false);

  useEffect(()=>{if(!currentStore)return;const cfg=currentStore.config||{};if(cfg.page_builder&&Array.isArray(cfg.page_builder)&&cfg.page_builder.length>0)setSections(cfg.page_builder);else{setSections([]);setShowTemplates(true);}},[currentStore?.id]);

  const upd=(i,s)=>{const n=[...sections];n[i]=s;setSections(n);setDirty(true);};
  const move=(i,d)=>{const n=[...sections];[n[i],n[i+d]]=[n[i+d],n[i]];setSections(n);setSelected(i+d);setDirty(true);};
  const rm=(i)=>{setSections(sections.filter((_,j)=>j!==i));if(selected===i)setSelected(null);setDirty(true);};
  const dup=(i)=>{const s={...JSON.parse(JSON.stringify(sections[i])),id:uid()};const n=[...sections];n.splice(i+1,0,s);setSections(n);setDirty(true);};
  const add=(type)=>{setSections([...sections,defaultSection(type)]);setSelected(sections.length);setShowAdd(false);setDirty(true);};
  const toggle=(i)=>{const n=[...sections];n[i]={...n[i],visible:!n[i].visible};setSections(n);setDirty(true);};
  const applyTemplate=(t)=>{const anim=t.animation||'calm';const fresh=JSON.parse(JSON.stringify(t.sections)).map((s,i)=>({...s,id:uid(),animation:anim,animationIndex:i}));setSections(fresh);setSelected(null);setShowTemplates(false);setDirty(true);toast.success(`"${t.name}" applied!`);};
  const save=async()=>{setSaving(true);try{const{data}=await ownerApi.updateStore(currentStore.id,{page_builder:sections});setCurrentStore(data);setDirty(false);toast.success('Saved!');}catch{toast.error('Failed');}setSaving(false);};

  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-4">
      <div><h1 className="text-2xl font-bold">Page Builder</h1><p className="text-sm text-gray-400 mt-1">Build your storefront exactly how you want</p></div>
      <div className="flex items-center gap-2">
        <button onClick={()=>setShowTemplates(true)} className="px-3 py-2 bg-purple-50 text-purple-600 rounded-xl text-sm font-bold flex items-center gap-1.5 hover:bg-purple-100"><Layers size={14}/>Templates</button>
        <div className="flex bg-gray-100 rounded-lg p-0.5"><button onClick={()=>setPreview('desktop')} className={`p-1.5 rounded-md ${preview==='desktop'?'bg-white shadow-sm':'text-gray-400'}`}><Monitor size={14}/></button><button onClick={()=>setPreview('mobile')} className={`p-1.5 rounded-md ${preview==='mobile'?'bg-white shadow-sm':'text-gray-400'}`}><Smartphone size={14}/></button></div>
        <button onClick={save} disabled={saving||!dirty} className="btn-primary text-sm flex items-center gap-2 disabled:opacity-50"><Save size={14}/>{saving?'Saving...':'Save'}</button>
      </div>
    </div>
    <div className="flex gap-4" style={{height:'calc(100vh - 160px)'}}>
      <div className="w-56 shrink-0 space-y-1.5 overflow-y-auto pr-1">
        {sections.map((sec,i)=>{const T=SECTION_TYPES.find(t=>t.type===sec.type);const Icon=T?.icon||Layout;return(
          <div key={sec.id} onClick={()=>setSelected(i)} className={`p-2.5 rounded-xl cursor-pointer transition-all ${selected===i?'bg-brand-50 ring-2 ring-brand-400':'bg-white border border-gray-200 hover:border-gray-300'} ${!sec.visible?'opacity-40':''}`}>
            <div className="flex items-center gap-2"><Icon size={13} className={selected===i?'text-brand-500':'text-gray-400'}/><span className="text-[11px] font-bold text-gray-700 flex-1 truncate">{T?.label||sec.type}</span>
              <div className="flex gap-px">{i>0&&<button onClick={e=>{e.stopPropagation();move(i,-1);}} className="p-0.5 hover:bg-gray-200 rounded"><ChevronUp size={10}/></button>}{i<sections.length-1&&<button onClick={e=>{e.stopPropagation();move(i,1);}} className="p-0.5 hover:bg-gray-200 rounded"><ChevronDown size={10}/></button>}<button onClick={e=>{e.stopPropagation();toggle(i);}} className="p-0.5 hover:bg-gray-200 rounded">{sec.visible?<Eye size={10}/>:<EyeOff size={10}/>}</button><button onClick={e=>{e.stopPropagation();dup(i);}} className="p-0.5 hover:bg-gray-200 rounded"><Copy size={10}/></button><button onClick={e=>{e.stopPropagation();rm(i);}} className="p-0.5 hover:bg-red-100 rounded text-red-400"><Trash2 size={10}/></button></div>
            </div></div>);})}
        <button onClick={()=>setShowAdd(true)} className="w-full p-2.5 rounded-xl border-2 border-dashed border-gray-300 text-gray-400 hover:border-brand-400 hover:text-brand-500 flex items-center justify-center gap-1.5 text-xs font-bold"><Plus size={13}/>Add Section</button>
      </div>
      <div className="flex-1 bg-gray-100 rounded-2xl overflow-y-auto p-3">
        <div className={`mx-auto bg-white rounded-xl shadow-sm overflow-hidden ${preview==='mobile'?'max-w-[375px]':'max-w-[900px]'}`}>
          {sections.filter(s=>s.visible).length===0?<div className="py-16 text-center"><Layers size={36} className="mx-auto text-gray-300 mb-3"/><p className="text-sm text-gray-400 mb-3">No sections yet</p><button onClick={()=>setShowTemplates(true)} className="px-4 py-2 bg-purple-500 text-white rounded-xl text-sm font-bold">Choose a Template</button></div>:
          sections.filter(s=>s.visible).map(sec=>(<div key={sec.id} onClick={()=>setSelected(sections.indexOf(sec))} className={`cursor-pointer transition-all ${selected===sections.indexOf(sec)?'ring-2 ring-brand-400 ring-inset':''}`}><Preview section={sec}/></div>))}
        </div>
      </div>
      <div className="w-64 shrink-0 bg-white rounded-2xl border border-gray-200 overflow-y-auto p-3">
        {selected!==null&&sections[selected]?<div><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-xs text-gray-900">{SECTION_TYPES.find(t=>t.type===sections[selected].type)?.label||'Section'}</h3><button onClick={()=>setSelected(null)} className="p-1 hover:bg-gray-100 rounded"><X size={12}/></button></div><StylePanel section={sections[selected]} onChange={s=>upd(selected,s)}/></div>:<div className="text-center py-10"><Layout size={28} className="mx-auto text-gray-300 mb-2"/><p className="text-xs text-gray-400">Click a section to edit</p></div>}
      </div>
    </div>
    {showAdd&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowAdd(false)}><div className="bg-white rounded-3xl p-5 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-3"><h2 className="text-lg font-bold">Add Section</h2><button onClick={()=>setShowAdd(false)}><X size={18}/></button></div><div className="space-y-1.5">{SECTION_TYPES.map(t=>{const Icon=t.icon;return<button key={t.type} onClick={()=>add(t.type)} className="w-full p-3 rounded-xl border-2 border-gray-200 hover:border-brand-400 text-left flex items-center gap-3 transition-all"><div className="w-9 h-9 rounded-lg bg-brand-50 flex items-center justify-center shrink-0"><Icon size={16} className="text-brand-500"/></div><div><p className="font-bold text-sm text-gray-900">{t.label}</p><p className="text-[10px] text-gray-400">{t.desc}</p></div></button>;})}</div></div></div>}
    {showTemplates&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4" onClick={()=>setShowTemplates(false)}><div className="bg-white rounded-3xl p-6 w-full max-w-6xl max-h-[92vh] overflow-y-auto shadow-2xl" onClick={e=>e.stopPropagation()}>
      <div className="flex items-center justify-between mb-6"><div><h2 className="text-2xl font-bold">Choose a Template</h2><p className="text-sm text-gray-500 mt-1">Pick a starting design — everything is fully customizable after you apply it</p></div><button onClick={()=>setShowTemplates(false)} className="p-2 hover:bg-gray-100 rounded-full"><X size={20}/></button></div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        {TEMPLATES.map((t,ti)=>{const hero=t.sections.find(s=>s.type==='hero');const heroStyle=hero?.style||{};const heroContent=hero?.content||{};const bgImg=heroContent.bgImage;return(
          <button key={ti} onClick={()=>{if(sections.length>0&&!confirm('Replace current page with this template?'))return;applyTemplate(t);}} className="group text-left rounded-2xl border-2 border-gray-200 hover:border-brand-400 overflow-hidden transition-all hover:shadow-xl hover:-translate-y-0.5 bg-white flex flex-col">
            {/* Realistic hero preview using the template's actual style */}
            <div className="relative h-56 overflow-hidden" style={{backgroundColor:heroStyle.bg||'#ffffff',backgroundImage:bgImg?`url(${bgImg})`:'none',backgroundSize:'cover',backgroundPosition:'center',fontFamily:heroStyle.fontFamily||'Inter'}}>
              {bgImg&&<div className="absolute inset-0" style={{backgroundColor:`rgba(0,0,0,${heroContent.overlay||0.3})`}}/>}
              <div className="relative z-10 h-full flex flex-col items-center justify-center text-center px-6" style={{color:heroStyle.textColor||'#1f2937',textAlign:heroContent.align||'center'}}>
                <p className="font-black leading-[1.05] mb-2 line-clamp-2" style={{fontSize:`${Math.min(parseInt(heroContent.titleSize)||48,64)*0.42}px`,fontFamily:heroStyle.fontFamily||'Inter'}}>{heroContent.title||t.name}</p>
                {heroContent.subtitle&&<p className="opacity-75 mb-3 line-clamp-2 max-w-[90%]" style={{fontSize:`${Math.min(parseInt(heroContent.subtitleSize)||16,20)*0.7}px`}}>{heroContent.subtitle}</p>}
                {heroContent.btnText&&<span className="inline-block px-3 py-1.5 rounded-md font-bold text-[11px]" style={{backgroundColor:heroContent.btnColor||'#7C3AED',color:'#ffffff'}}>{heroContent.btnText}</span>}
              </div>
              {/* Section strip below hero preview - shows the template's color rhythm */}
              <div className="absolute bottom-0 left-0 right-0 h-3 flex">
                {t.sections.filter(s=>s.visible).slice(1,8).map((sec,si)=>(<div key={si} className="flex-1" style={{backgroundColor:sec.style?.bg||'#f3f4f6'}}/>))}
              </div>
            </div>
            {/* Info footer */}
            <div className="p-4 border-t border-gray-100 flex-1 flex flex-col">
              <div className="flex items-start justify-between gap-2 mb-1.5">
                <p className="font-bold text-gray-900 text-base leading-tight">{t.name}</p>
                <div className="flex gap-1 shrink-0 mt-0.5">{t.colors.map((c,ci)=><div key={ci} style={{backgroundColor:c}} className="w-4 h-4 rounded-full border border-gray-200 shadow-sm"/>)}</div>
              </div>
              {t.animation&&<span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 bg-gradient-to-r from-violet-50 to-pink-50 text-violet-600 rounded-full w-fit mb-1.5"><Sparkles size={9}/>{t.animation} motion</span>}
              <p className="text-[11px] text-gray-500 leading-relaxed line-clamp-2 flex-1">{t.desc}</p>
              <div className="mt-3 flex items-center justify-between">
                <div className="flex items-center gap-1.5 flex-wrap">
                  {[...new Set(t.sections.filter(s=>s.visible).map(s=>s.type))].slice(0,5).map((st,i)=>{const T=SECTION_TYPES.find(x=>x.type===st);return T?<span key={i} className="text-[9px] font-bold uppercase px-1.5 py-0.5 bg-gray-100 text-gray-600 rounded">{T.label.split(' ')[0]}</span>:null;})}
                </div>
                <span className="text-[10px] font-bold text-brand-500 flex items-center gap-1 opacity-0 group-hover:opacity-100 transition">Use this →</span>
              </div>
            </div>
          </button>
        );})}
      </div>
    </div></div>}
  </DashboardLayout>);
}
