import React,{useState,useEffect} from'react';
import DashboardLayout from'../../components/shared/DashboardLayout';
import{useStoreManagement}from'../../hooks/useStore';
import{ownerApi}from'../../utils/api';
import toast from'react-hot-toast';
import{Plus,X,Save,Trash2,ChevronUp,ChevronDown,Eye,EyeOff,Type,Image,Layout,Package,Copy,Monitor,Smartphone,Star,Sparkles,Zap,Layers}from'lucide-react';

const FONTS=['Inter','Arial','Georgia','Playfair Display','Poppins','Roboto','Montserrat','Lora','Raleway','Cairo','Tajawal','DM Sans','Space Grotesk'];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);

const SECTION_TYPES=[
  {type:'hero',label:'Hero Banner',icon:Layout,desc:'Large banner with title and subtitle'},
  {type:'products',label:'Products Grid',icon:Package,desc:'Display products in a grid'},
  {type:'text',label:'Text Block',icon:Type,desc:'Custom text content'},
  {type:'image',label:'Image',icon:Image,desc:'Full-width or contained image'},
  {type:'banner',label:'Promo Banner',icon:Sparkles,desc:'Promotional banner with CTA'},
  {type:'spacer',label:'Spacer',icon:ChevronDown,desc:'Empty space between sections'},
  {type:'features',label:'Features/Trust',icon:Star,desc:'Feature icons with text'},
  {type:'testimonials',label:'Testimonials',icon:Star,desc:'Customer reviews showcase'},
  {type:'custom_html',label:'Custom HTML',icon:Zap,desc:'Raw HTML content'},
];

// Templates reworked with UI/UX Pro Max design principles: verified font pairings,
// WCAG-accessible color systems, conversion-focused section rhythm, modern layout patterns.
const TEMPLATES=[
  {name:'Neon Pulse',desc:'High-contrast dark with electric mint. Built for drops, hype launches, and flash sales.',colors:['#0a0a0a','#39ff88','#171717'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0a0a0a',textColor:'#fafafa',padding:'100',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1280'},content:{title:'The Drop Is Live.',subtitle:'Numbered pieces. Gone in minutes. No restocks.',btnText:'Shop The Drop →',btnLink:'#products',titleSize:'84',subtitleSize:'20',btnColor:'#39ff88',bgImage:'',overlay:'0',align:'center',height:'620'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#39ff88',textColor:'#0a0a0a',padding:'14',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1400'},content:{text:'● LIVE NOW  ·  FREE DZ-WIDE SHIPPING OVER 5 000 DZD  ·  ENDS TONIGHT ●',btnText:'',btnLink:'',fontSize:'13',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#0a0a0a',textColor:'#fafafa',padding:'80',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1280'},content:{title:'Trending Now',titleSize:'36',columns:'4',mobileColumns:'2',cardStyle:'border',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'features',visible:true,style:{bg:'#171717',textColor:'#d4d4d4',padding:'56',fontFamily:'Inter',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'⚡',title:'24h Express',desc:'Same-day in Algiers'},{icon:'🔒',title:'Secure Checkout',desc:'SSL + BaridiMob'},{icon:'↩',title:'Free Returns',desc:'14 days, no questions'},{icon:'💬',title:'Live Support',desc:'WhatsApp 7/7'}],columns:'4'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#171717',textColor:'#fafafa',padding:'70',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1100'},content:{text:'25 000+ already copped. You next?',btnText:'Shop All →',btnLink:'#products',fontSize:'34',align:'center'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#0a0a0a',textColor:'#e5e5e5',padding:'70',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1100'},content:{title:'Word On The Street',titleSize:'30',items:[{name:'Yacine · Algiers',text:'Dropped my order on Friday, had it Sunday. Box was straight fire.',rating:5},{name:'Sarah · Oran',text:'Quality is insane for the price. Already reordered twice.',rating:5},{name:'Mehdi · Constantine',text:'Easily the most premium store in DZ right now.',rating:5}]}},
  ]},
  {name:'Maison Luxe',desc:'Refined navy & champagne gold with classic Playfair pairing. Jewelry, watches, couture.',colors:['#0b1a2f','#c9a362','#f6f1e7'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0b1a2f',textColor:'#f6f1e7',padding:'120',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{title:'Exquisite by design.',subtitle:'Handcrafted heirlooms, made to outlive trends.',btnText:'View the Collection',btnLink:'#products',titleSize:'64',subtitleSize:'17',btnColor:'#c9a362',bgImage:'',overlay:'0',align:'center',height:'600'}},
      {id:uid(),type:'spacer',visible:true,style:{bg:'#f6f1e7',textColor:'#000',padding:'0',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'},content:{height:'12'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#f6f1e7',textColor:'#0b1a2f',padding:'64',fontFamily:'Lora',borderRadius:'0',maxWidth:'1000'},content:{items:[{icon:'◆',title:'Ethical Sourcing',desc:'Conflict-free gemstones'},{icon:'✦',title:'Master Artisans',desc:'15+ years craftsmanship'},{icon:'✧',title:'Certified Authentic',desc:'Guarantee with every piece'}],columns:'3'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0b1a2f',padding:'90',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1200'},content:{title:'The Signature Edit',titleSize:'42',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'6',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#0b1a2f',textColor:'#c9a362',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'800'},content:{text:'"We don\'t chase trends — we set the standard. Every piece carries our promise of quality, authenticity, and timeless beauty."',fontSize:'22',lineHeight:'1.9',align:'center',maxWidth:'700'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#f6f1e7',textColor:'#0b1a2f',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'Stories from our clients',titleSize:'34',items:[{name:'Amira B.',text:'The ring was even more breathtaking in person. Impeccable craftsmanship.',rating:5},{name:'Karim D.',text:'Bought a necklace for our anniversary — she teared up the moment she opened it.',rating:5},{name:'Lina S.',text:'The packaging alone felt like a private luxury experience.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#c9a362',textColor:'#0b1a2f',padding:'56',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1280'},content:{text:'Complimentary engraving on orders over 30 000 DZD',btnText:'Discover',btnLink:'#products',fontSize:'24',align:'center'}},
  ]},
  {name:'Noir Editorial',desc:'Pure monochrome with oversized Playfair headlines and DM Sans body. Magazine-grade fashion.',colors:['#ffffff','#0a0a0a','#f4f4f4'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#ffffff',textColor:'#0a0a0a',padding:'90',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'1400'},content:{title:'New Season.',subtitle:'— THE ART OF GETTING DRESSED —',btnText:'Explore',btnLink:'#products',titleSize:'96',subtitleSize:'13',btnColor:'#0a0a0a',bgImage:'',overlay:'0',align:'center',height:'560'}},
      {id:uid(),type:'spacer',visible:true,style:{bg:'#0a0a0a',textColor:'#fff',padding:'0',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'},content:{height:'2'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#ffffff',textColor:'#0a0a0a',padding:'18',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1400'},content:{text:'ISSUE N°01  ·  SPRING/SUMMER 2025  ·  COMPLIMENTARY SHIPPING',btnText:'',btnLink:'',fontSize:'11',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0a0a0a',padding:'80',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1280'},content:{title:'THE EDIT',titleSize:'14',columns:'4',mobileColumns:'2',cardStyle:'minimal',showPrice:true,showName:true,showBtn:false,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#f4f4f4',textColor:'#0a0a0a',padding:'90',fontFamily:'Playfair Display',borderRadius:'0',maxWidth:'900'},content:{text:'"Fashion fades. Style is eternal."',fontSize:'32',lineHeight:'1.6',align:'center',maxWidth:'700'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0a0a0a',padding:'80',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1280'},content:{title:'BESTSELLERS',titleSize:'14',columns:'3',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'3',featured:true}},
      {id:uid(),type:'features',visible:true,style:{bg:'#0a0a0a',textColor:'#ffffff',padding:'64',fontFamily:'DM Sans',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'◼',title:'CURATED',desc:'Every piece hand-selected'},{icon:'◼',title:'SUSTAINABLE',desc:'Eco-conscious sourcing'},{icon:'◼',title:'WORLDWIDE',desc:'Ships to 50+ countries'}],columns:'3'}},
  ]},
  {name:'Botanica',desc:'Warm earth tones with forest accents, Lora serif. Skincare, wellness, natural foods.',colors:['#efe9dc','#3e6b47','#fbf8f1'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#efe9dc',textColor:'#253827',padding:'90',fontFamily:'Lora',borderRadius:'0',maxWidth:'1280'},content:{title:'Pure. Rooted. Yours.',subtitle:'Ingredients you can pronounce. Rituals you\'ll keep. Made with care in Algeria.',btnText:'Discover the range',btnLink:'#products',titleSize:'58',subtitleSize:'18',btnColor:'#3e6b47',bgImage:'',overlay:'0',align:'center',height:'540'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#fbf8f1',textColor:'#3e5a44',padding:'56',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🌿',title:'100% Botanical',desc:'No parabens, no sulfates'},{icon:'🐇',title:'Cruelty-Free',desc:'Never tested on animals'},{icon:'♻️',title:'Zero-Waste',desc:'Refillable glass packaging'},{icon:'🇩🇿',title:'Local Artisans',desc:'Women-led cooperatives'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#efe9dc',textColor:'#253827',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'1280'},content:{title:'Everyday Rituals',titleSize:'34',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#3e6b47',textColor:'#efe9dc',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'800'},content:{text:'It started in a small kitchen in Algiers with one belief: nature already has everything your skin needs. Three years and 15 000 happy customers later — that belief has never been stronger.',fontSize:'18',lineHeight:'1.9',align:'center',maxWidth:'680'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fbf8f1',textColor:'#253827',padding:'80',fontFamily:'Lora',borderRadius:'0',maxWidth:'1100'},content:{title:'From our community',titleSize:'32',items:[{name:'Yasmine',text:'My skin has never been this clear. Switched every product to Botanica.',rating:5},{name:'Dalia',text:'The lavender soap is heavenly. I order 5 at a time now.',rating:5},{name:'Nour',text:'Finally, natural products that actually work — and smell incredible.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#efe9dc',textColor:'#253827',padding:'48',fontFamily:'Lora',borderRadius:'20',maxWidth:'1050'},content:{text:'🎁 Free sample trio with your first order',btnText:'Start shopping',btnLink:'#products',fontSize:'22',align:'center'}},
  ]},
  {name:'Drop Culture',desc:'Urban streetwear with blood-red accents and all-caps Montserrat. Hypebeast ready.',colors:['#111111','#e11d2b','#f5f5f5'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#111111',textColor:'#f5f5f5',padding:'90',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1400'},content:{title:'WEAR YOUR ATTITUDE.',subtitle:'Limited drops. Unlimited style. Made for the ones who refuse to blend in.',btnText:'SHOP THE DROP',btnLink:'#products',titleSize:'72',subtitleSize:'16',btnColor:'#e11d2b',bgImage:'',overlay:'0',align:'center',height:'600'}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#e11d2b',textColor:'#ffffff',padding:'16',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1400'},content:{text:'▲ NEW DROP EVERY FRIDAY · 8 PM SHARP · SET YOUR ALARM ▲',btnText:'',btnLink:'',fontSize:'13',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#111111',textColor:'#f5f5f5',padding:'80',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1280'},content:{title:'LATEST DROP',titleSize:'32',columns:'4',mobileColumns:'2',cardStyle:'border',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#1c1c1c',textColor:'#a3a3a3',padding:'64',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'800'},content:{text:'BORN IN THE STREETS OF ALGIERS. Every piece designed to stand out, built to last, and made for those who wear their attitude on their sleeve — literally.',fontSize:'17',lineHeight:'1.9',align:'center',maxWidth:'700'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#111111',textColor:'#d4d4d4',padding:'56',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'📦',title:'FREE SHIPPING',desc:'Orders over 4 000 DZD'},{icon:'✓',title:'AUTHENTIC ONLY',desc:'100% genuine guarantee'},{icon:'↻',title:'EASY EXCHANGE',desc:'7-day swap window'}],columns:'3'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#1c1c1c',textColor:'#e5e5e5',padding:'70',fontFamily:'Montserrat',borderRadius:'0',maxWidth:'1100'},content:{title:'THE COMMUNITY',titleSize:'28',items:[{name:'RAFIK',text:'Copped the last drop in 3 minutes. Quality is insane.',rating:5},{name:'INES',text:'My boyfriend wears nothing else now. Obsessed.',rating:5},{name:'ADAM',text:'DZ streetwear is finally on another level.',rating:5}]}},
  ]},
  {name:'Sunrise',desc:'Soft peach pastels with rounded edges and Poppins. Warm, friendly, small-business charm.',colors:['#fff4e6','#f97316','#ffedd5'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#fff4e6',textColor:'#431407',padding:'80',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1280'},content:{title:'Welcome to our little shop ☀️',subtitle:'We hand-pick the best so you don\'t have to. Quality, care, and a smile with every order.',btnText:'Start browsing →',btnLink:'#products',titleSize:'50',subtitleSize:'18',btnColor:'#f97316',bgImage:'',overlay:'0',align:'center',height:'500'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#ffffff',textColor:'#431407',padding:'56',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🎁',title:'Gift Ready',desc:'Beautiful packaging, always'},{icon:'🚚',title:'Fast Delivery',desc:'1–3 days to your door'},{icon:'💝',title:'Made with Love',desc:'Every detail matters'},{icon:'📞',title:'Real Humans',desc:'Friendly support on WhatsApp'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffedd5',textColor:'#431407',padding:'80',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1280'},content:{title:'Customers love these ❤️',titleSize:'32',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#f97316',textColor:'#ffffff',padding:'48',fontFamily:'Poppins',borderRadius:'24',maxWidth:'1100'},content:{text:'✨ First order? Use code HELLO10 for 10% off',btnText:'Claim offer',btnLink:'#products',fontSize:'22',align:'center'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fff4e6',textColor:'#431407',padding:'72',fontFamily:'Poppins',borderRadius:'0',maxWidth:'1100'},content:{title:'Happy customers 😊',titleSize:'30',items:[{name:'Meriem',text:'The handwritten note inside my package made my whole week!',rating:5},{name:'Amine',text:'I keep coming back. Best customer service in Algeria, honestly.',rating:5},{name:'Chaima',text:'From order to unboxing — everything was perfect. Love this shop!',rating:5}]}},
      {id:uid(),type:'text',visible:true,style:{bg:'#ffffff',textColor:'#9a3412',padding:'48',fontFamily:'Poppins',borderRadius:'0',maxWidth:'800'},content:{text:'Thank you for supporting a small Algerian business. Every order means the world to us 🧡',fontSize:'17',lineHeight:'1.8',align:'center',maxWidth:'680'}},
  ]},
  {name:'Volt Tech',desc:'Deep slate with electric indigo gradients. Inter sans throughout. Electronics, gadgets, SaaS.',colors:['#0b1120','#6366f1','#1e293b'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0b1120',textColor:'#e2e8f0',padding:'110',fontFamily:'Inter',borderRadius:'0',maxWidth:'1400'},content:{title:'Tech that keeps up.',subtitle:'The latest gadgets, genuine stock, shipped fast across Algeria.',btnText:'Browse Gadgets',btnLink:'#products',titleSize:'68',subtitleSize:'18',btnColor:'#6366f1',bgImage:'',overlay:'0',align:'center',height:'580'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#1e293b',textColor:'#cbd5e1',padding:'48',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'},content:{items:[{icon:'⚡',title:'Genuine Stock',desc:'Direct from manufacturers'},{icon:'🛡️',title:'1-Year Warranty',desc:'On every electronic'},{icon:'🚀',title:'Same-Day in Algiers',desc:'Express nationwide 48h'},{icon:'🧰',title:'Free Setup Help',desc:'We configure it for you'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#0b1120',textColor:'#e2e8f0',padding:'80',fontFamily:'Inter',borderRadius:'0',maxWidth:'1280'},content:{title:'Featured Gear',titleSize:'32',columns:'4',mobileColumns:'2',cardStyle:'border',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#6366f1',textColor:'#ffffff',padding:'56',fontFamily:'Inter',borderRadius:'0',maxWidth:'1400'},content:{text:'💳 Split payments — 4× interest-free',btnText:'How it works',btnLink:'#products',fontSize:'24',align:'center'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#1e293b',textColor:'#e2e8f0',padding:'80',fontFamily:'Inter',borderRadius:'0',maxWidth:'1280'},content:{title:'Staff Picks',titleSize:'28',columns:'3',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'6',featured:true}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#0b1120',textColor:'#cbd5e1',padding:'80',fontFamily:'Inter',borderRadius:'0',maxWidth:'1100'},content:{title:'What customers say',titleSize:'28',items:[{name:'Omar · Algiers',text:'Got my AirPods in 2 days — sealed, genuine, zero stress. Legit store.',rating:5},{name:'Lyes · Oran',text:'Best tech shop in DZ. Fair prices, fast shipping, real warranty.',rating:5},{name:'Amina · Blida',text:'WhatsApp support helped me pick the right laptop. Top service.',rating:5}]}},
  ]},
  {name:'Bento Studio',desc:'Modern light SaaS look with Space Grotesk headlines. Digital products, courses, studios.',colors:['#fafafa','#7c3aed','#f4f4f5'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#fafafa',textColor:'#0a0a0a',padding:'100',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1280'},content:{title:'Ship beautiful. Ship fast.',subtitle:'A studio-grade toolkit for makers who care about the details.',btnText:'Get Started Free',btnLink:'#products',titleSize:'66',subtitleSize:'19',btnColor:'#7c3aed',bgImage:'',overlay:'0',align:'center',height:'560'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#ffffff',textColor:'#18181b',padding:'64',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'},content:{items:[{icon:'◐',title:'Design-first',desc:'Templates by pros'},{icon:'◇',title:'Ship in minutes',desc:'Zero setup friction'},{icon:'◆',title:'Built to scale',desc:'From side-project to startup'}],columns:'3'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#f4f4f5',textColor:'#18181b',padding:'80',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1280'},content:{title:'Featured products',titleSize:'36',columns:'3',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'6',featured:true}},
      {id:uid(),type:'text',visible:true,style:{bg:'#7c3aed',textColor:'#ffffff',padding:'80',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'900'},content:{text:'"I shipped my first product in one weekend. The templates are absurdly good."',fontSize:'26',lineHeight:'1.6',align:'center',maxWidth:'780'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#18181b',padding:'80',fontFamily:'Space Grotesk',borderRadius:'0',maxWidth:'1280'},content:{title:'Everything else',titleSize:'28',columns:'4',mobileColumns:'2',cardStyle:'flat',showPrice:true,showName:true,showBtn:false,limit:'8',featured:false}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#fafafa',textColor:'#18181b',padding:'80',fontFamily:'Inter',borderRadius:'0',maxWidth:'1100'},content:{title:'Trusted by 12 000+ creators',titleSize:'30',items:[{name:'Sofia · Designer',text:'My go-to toolkit. Saves me entire days on every project.',rating:5},{name:'Karim · Founder',text:'Launched my MVP in a weekend. Support was lightning-fast.',rating:5},{name:'Nassim · Dev',text:'Clean code, thoughtful defaults. Exactly what I needed.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#18181b',textColor:'#fafafa',padding:'56',fontFamily:'Space Grotesk',borderRadius:'24',maxWidth:'1100'},content:{text:'Ready to ship? Start free today.',btnText:'Create account',btnLink:'#products',fontSize:'26',align:'center'}},
  ]},
  {name:'Coastal Breeze',desc:'Airy sky-blue & cream with Raleway. Calming wellness, travel, spa, lifestyle.',colors:['#eaf4fb','#2c6ba0','#fbf8f3'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#eaf4fb',textColor:'#0e2a43',padding:'90',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1280'},content:{title:'Breathe easier.',subtitle:'Wellness essentials inspired by the Mediterranean coast.',btnText:'Explore collection',btnLink:'#products',titleSize:'60',subtitleSize:'19',btnColor:'#2c6ba0',bgImage:'',overlay:'0',align:'center',height:'540'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#fbf8f3',textColor:'#0e2a43',padding:'56',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🌊',title:'Clean ingredients',desc:'Marine-sourced, lab-tested'},{icon:'☀️',title:'Sun-ready',desc:'Broad-spectrum protection'},{icon:'🧴',title:'Refill program',desc:'50% off on refills'},{icon:'🚚',title:'Free delivery',desc:'Orders over 6 000 DZD'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0e2a43',padding:'80',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1280'},content:{title:'Daily essentials',titleSize:'34',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'text',visible:true,style:{bg:'#2c6ba0',textColor:'#eaf4fb',padding:'72',fontFamily:'Raleway',borderRadius:'0',maxWidth:'820'},content:{text:'Slow mornings. Clear skies. Good rituals. Everything we make is designed to help you feel that — every day, anywhere.',fontSize:'19',lineHeight:'1.9',align:'center',maxWidth:'700'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#eaf4fb',textColor:'#0e2a43',padding:'72',fontFamily:'Raleway',borderRadius:'0',maxWidth:'1100'},content:{title:'Loved along the coast',titleSize:'30',items:[{name:'Sara · Tipaza',text:'Smells like a summer morning. My new daily ritual.',rating:5},{name:'Hichem · Bejaia',text:'Quality packaging, fast shipping, products that just work.',rating:5},{name:'Nadia · Algiers',text:'Finally a brand that feels genuinely calming to use.',rating:5}]}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#fbf8f3',textColor:'#0e2a43',padding:'52',fontFamily:'Raleway',borderRadius:'20',maxWidth:'1100'},content:{text:'Subscribe & save 15% on every refill',btnText:'Join the club',btnLink:'#products',fontSize:'22',align:'center'}},
  ]},
  {name:'متجر الفخامة',desc:'تصميم عربي راقي بخط Cairo وألوان كحلية وذهبية. للعلامات الجزائرية الفاخرة.',colors:['#0b1a2f','#d4a34a','#faf7f0'],
    sections:[
      {id:uid(),type:'hero',visible:true,style:{bg:'#0b1a2f',textColor:'#faf7f0',padding:'100',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1280'},content:{title:'تسوّق بثقة، استلم بفخامة',subtitle:'منتجات أصلية ✦ توصيل سريع لكل الولايات ✦ دفع آمن',btnText:'تصفّح المجموعة',btnLink:'#products',titleSize:'58',subtitleSize:'19',btnColor:'#d4a34a',bgImage:'',overlay:'0',align:'center',height:'540'}},
      {id:uid(),type:'features',visible:true,style:{bg:'#faf7f0',textColor:'#0b1a2f',padding:'56',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1100'},content:{items:[{icon:'🚚',title:'توصيل لكل الولايات',desc:'خلال 48 ساعة كحد أقصى'},{icon:'💳',title:'الدفع عند الاستلام',desc:'أو عبر CCP و BaridiMob'},{icon:'↩',title:'إرجاع مجاني',desc:'خلال 14 يوم بدون أسئلة'},{icon:'✓',title:'منتجات أصلية',desc:'ضمان الجودة 100%'}],columns:'4'}},
      {id:uid(),type:'products',visible:true,style:{bg:'#ffffff',textColor:'#0b1a2f',padding:'80',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1280'},content:{title:'الأكثر مبيعًا',titleSize:'36',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false}},
      {id:uid(),type:'banner',visible:true,style:{bg:'#d4a34a',textColor:'#0b1a2f',padding:'48',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1400'},content:{text:'🎉 سجّل الآن واحصل على خصم 15% على أول طلب',btnText:'سجّل الآن',btnLink:'#products',fontSize:'24',align:'center'}},
      {id:uid(),type:'testimonials',visible:true,style:{bg:'#faf7f0',textColor:'#0b1a2f',padding:'72',fontFamily:'Cairo',borderRadius:'0',maxWidth:'1100'},content:{title:'ماذا يقول عملاؤنا',titleSize:'32',items:[{name:'أحمد · الجزائر',text:'طلبت ووصلني في نفس اليوم. خدمة ممتازة والمنتج أصلي 100%',rating:5},{name:'فاطمة · وهران',text:'أحسن متجر تعاملت معه. الأسعار معقولة والجودة عالية جدًا',rating:5},{name:'ياسين · قسنطينة',text:'التغليف راقي والتوصيل سريع. شكرًا لكم على الاحترافية',rating:5}]}},
      {id:uid(),type:'text',visible:true,style:{bg:'#0b1a2f',textColor:'#d4a34a',padding:'64',fontFamily:'Cairo',borderRadius:'0',maxWidth:'800'},content:{text:'نحن متجر جزائري نفتخر بخدمة أكثر من 20 000 عميل سعيد. هدفنا تقديم تجربة تسوّق لا تُنسى، بجودة تليق بك.',fontSize:'19',lineHeight:'1.9',align:'center',maxWidth:'700'}},
  ]},
];

const defaultSection=(type)=>{
  const base={id:uid(),type,visible:true,style:{bg:'#ffffff',textColor:'#1f2937',padding:'60',fontFamily:'Inter',borderRadius:'0',maxWidth:'1200'}};
  const defs={hero:{title:'Welcome',subtitle:'Discover amazing products',btnText:'Shop Now',btnLink:'#products',titleSize:'48',subtitleSize:'20',btnColor:'#7C3AED',bgImage:'',overlay:'0.3',align:'center',height:'500'},products:{title:'Our Products',titleSize:'28',columns:'4',mobileColumns:'2',cardStyle:'shadow',showPrice:true,showName:true,showBtn:true,limit:'8',featured:false},text:{text:'Add your content here.',fontSize:'16',lineHeight:'1.7',align:'left',maxWidth:'800'},image:{src:'',alt:'',width:'100',height:'auto',align:'center',rounded:'12',link:''},banner:{text:'Special Offer!',btnText:'Shop Now',btnLink:'#',fontSize:'24',align:'center'},spacer:{height:'60'},features:{items:[{icon:'🚚',title:'Fast Delivery',desc:'All wilayas'},{icon:'💳',title:'Secure Payment',desc:'Multiple options'},{icon:'🔄',title:'Easy Returns',desc:'30-day policy'}],columns:'3'},testimonials:{title:'Reviews',titleSize:'28',items:[{name:'Ahmed',text:'Great!',rating:5},{name:'Sara',text:'Love it!',rating:5}]},custom_html:{html:'<div style="text-align:center;padding:20px"><h2>Custom</h2></div>'}};
  if(type==='banner')base.style={...base.style,bg:'#7C3AED',textColor:'#ffffff',padding:'40'};
  if(type==='spacer')base.style={...base.style,padding:'0',bg:'transparent'};
  return{...base,content:defs[type]||{}};
};

function StylePanel({section,onChange}){
  const s=section.style||{};const c=section.content||{};
  const set=(k,v)=>onChange({...section,style:{...s,[k]:v}});
  const setC=(k,v)=>onChange({...section,content:{...c,[k]:v}});
  return(<div className="space-y-3 text-sm">
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Background</p><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded cursor-pointer" value={s.bg||'#ffffff'} onChange={e=>set('bg',e.target.value)}/><input className="input-field flex-1 !py-1 text-xs" value={s.bg||''} onChange={e=>set('bg',e.target.value)}/></div></div>
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Text Color</p><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded cursor-pointer" value={s.textColor||'#1f2937'} onChange={e=>set('textColor',e.target.value)}/><input className="input-field flex-1 !py-1 text-xs" value={s.textColor||''} onChange={e=>set('textColor',e.target.value)}/></div></div>
    <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1">Font</p><select className="input-field !py-1 text-xs" value={s.fontFamily||'Inter'} onChange={e=>set('fontFamily',e.target.value)}>{FONTS.map(f=><option key={f} value={f}>{f}</option>)}</select></div>
    <div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Padding</p><input type="number" className="input-field !py-1 text-xs" value={s.padding||'60'} onChange={e=>set('padding',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Radius</p><input type="number" className="input-field !py-1 text-xs" value={s.borderRadius||'0'} onChange={e=>set('borderRadius',e.target.value)}/></div></div>
    <div><p className="text-[10px] text-gray-400">Max Width</p><input type="number" className="input-field !py-1 text-xs" value={s.maxWidth||'1200'} onChange={e=>set('maxWidth',e.target.value)}/></div>
    {section.type==='hero'&&<><hr/><p className="text-[10px] font-bold text-brand-500 uppercase">Hero</p><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Subtitle</p><input className="input-field !py-1 text-xs" value={c.subtitle||''} onChange={e=>setC('subtitle',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Title Size</p><input type="number" className="input-field !py-1 text-xs" value={c.titleSize||'48'} onChange={e=>setC('titleSize',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Sub Size</p><input type="number" className="input-field !py-1 text-xs" value={c.subtitleSize||'20'} onChange={e=>setC('subtitleSize',e.target.value)}/></div></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Button</p><input className="input-field !py-1 text-xs" value={c.btnText||''} onChange={e=>setC('btnText',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Btn Color</p><div className="flex gap-1"><input type="color" className="w-6 h-6 rounded" value={c.btnColor||'#7C3AED'} onChange={e=>setC('btnColor',e.target.value)}/><input className="input-field flex-1 !py-0.5 text-[10px]" value={c.btnColor||''} onChange={e=>setC('btnColor',e.target.value)}/></div></div></div><div><p className="text-[10px] text-gray-400">Height</p><input type="number" className="input-field !py-1 text-xs" value={c.height||'500'} onChange={e=>setC('height',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">BG Image</p><input className="input-field !py-1 text-xs" value={c.bgImage||''} onChange={e=>setC('bgImage',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Align</p><div className="flex gap-1">{['left','center','right'].map(a=><button key={a} onClick={()=>setC('align',a)} className={`flex-1 py-1 rounded text-xs font-bold ${c.align===a?'bg-brand-500 text-white':'bg-gray-100'}`}>{a}</button>)}</div></div></>}
    {section.type==='products'&&<><hr/><p className="text-[10px] font-bold text-brand-500 uppercase">Products</p><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Columns</p><select className="input-field !py-1 text-xs" value={c.columns||'4'} onChange={e=>setC('columns',e.target.value)}><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><div><p className="text-[10px] text-gray-400">Limit</p><input type="number" className="input-field !py-1 text-xs" value={c.limit||'8'} onChange={e=>setC('limit',e.target.value)}/></div></div><div><p className="text-[10px] text-gray-400">Card Style</p><select className="input-field !py-1 text-xs" value={c.cardStyle||'shadow'} onChange={e=>setC('cardStyle',e.target.value)}><option value="shadow">Shadow</option><option value="border">Border</option><option value="flat">Flat</option><option value="minimal">Minimal</option></select></div><label className="flex items-center gap-2"><input type="checkbox" checked={c.showPrice!==false} onChange={e=>setC('showPrice',e.target.checked)}/><span className="text-xs">Price</span></label><label className="flex items-center gap-2"><input type="checkbox" checked={c.showBtn!==false} onChange={e=>setC('showBtn',e.target.checked)}/><span className="text-xs">Cart btn</span></label><label className="flex items-center gap-2"><input type="checkbox" checked={c.featured||false} onChange={e=>setC('featured',e.target.checked)}/><span className="text-xs">Featured only</span></label></>}
    {section.type==='text'&&<><hr/><div><p className="text-[10px] text-gray-400">Content</p><textarea className="input-field !py-1 text-xs" rows={4} value={c.text||''} onChange={e=>setC('text',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Size</p><input type="number" className="input-field !py-1 text-xs" value={c.fontSize||'16'} onChange={e=>setC('fontSize',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Line H</p><input className="input-field !py-1 text-xs" value={c.lineHeight||'1.7'} onChange={e=>setC('lineHeight',e.target.value)}/></div></div><div><p className="text-[10px] text-gray-400">Align</p><div className="flex gap-1">{['left','center','right'].map(a=><button key={a} onClick={()=>setC('align',a)} className={`flex-1 py-1 rounded text-xs font-bold ${c.align===a?'bg-brand-500 text-white':'bg-gray-100'}`}>{a}</button>)}</div></div></>}
    {section.type==='image'&&<><hr/><div><p className="text-[10px] text-gray-400">Image URL</p><input className="input-field !py-1 text-xs" value={c.src||''} onChange={e=>setC('src',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Width %</p><input type="number" className="input-field !py-1 text-xs" value={c.width||'100'} onChange={e=>setC('width',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Rounded</p><input type="number" className="input-field !py-1 text-xs" value={c.rounded||'12'} onChange={e=>setC('rounded',e.target.value)}/></div></div></>}
    {section.type==='banner'&&<><hr/><div><p className="text-[10px] text-gray-400">Text</p><input className="input-field !py-1 text-xs" value={c.text||''} onChange={e=>setC('text',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Font Size</p><input type="number" className="input-field !py-1 text-xs" value={c.fontSize||'24'} onChange={e=>setC('fontSize',e.target.value)}/></div><div className="grid grid-cols-2 gap-2"><div><p className="text-[10px] text-gray-400">Button</p><input className="input-field !py-1 text-xs" value={c.btnText||''} onChange={e=>setC('btnText',e.target.value)}/></div><div><p className="text-[10px] text-gray-400">Link</p><input className="input-field !py-1 text-xs" value={c.btnLink||''} onChange={e=>setC('btnLink',e.target.value)}/></div></div></>}
    {section.type==='spacer'&&<div><p className="text-[10px] text-gray-400">Height</p><input type="number" className="input-field !py-1 text-xs" value={c.height||'60'} onChange={e=>setC('height',e.target.value)}/></div>}
    {section.type==='features'&&<><hr/><div><p className="text-[10px] text-gray-400">Columns</p><select className="input-field !py-1 text-xs" value={c.columns||'3'} onChange={e=>setC('columns',e.target.value)}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div>{(c.items||[]).map((it,i)=><div key={i} className="p-2 bg-gray-50 rounded-lg space-y-1"><div className="flex gap-1"><input className="input-field !py-0.5 text-xs w-10" value={it.icon||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],icon:e.target.value};setC('items',a);}}/><input className="input-field !py-0.5 text-xs flex-1" value={it.title||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],title:e.target.value};setC('items',a);}}/><button onClick={()=>{const a=[...c.items];a.splice(i,1);setC('items',a);}} className="text-red-400"><X size={12}/></button></div><input className="input-field !py-0.5 text-xs" value={it.desc||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],desc:e.target.value};setC('items',a);}}/></div>)}<button onClick={()=>setC('items',[...(c.items||[]),{icon:'⭐',title:'Feature',desc:'Desc'}])} className="text-xs text-brand-600 font-bold">+ Add</button></>}
    {section.type==='testimonials'&&<><hr/><div><p className="text-[10px] text-gray-400">Title</p><input className="input-field !py-1 text-xs" value={c.title||''} onChange={e=>setC('title',e.target.value)}/></div>{(c.items||[]).map((it,i)=><div key={i} className="p-2 bg-gray-50 rounded-lg space-y-1"><div className="flex gap-1"><input className="input-field !py-0.5 text-xs w-20" value={it.name||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],name:e.target.value};setC('items',a);}}/><select className="input-field !py-0.5 text-xs w-14" value={it.rating||5} onChange={e=>{const a=[...c.items];a[i]={...a[i],rating:parseInt(e.target.value)};setC('items',a);}}><option value={5}>5★</option><option value={4}>4★</option><option value={3}>3★</option></select><button onClick={()=>{const a=[...c.items];a.splice(i,1);setC('items',a);}} className="text-red-400"><X size={12}/></button></div><textarea className="input-field !py-0.5 text-xs" rows={2} value={it.text||''} onChange={e=>{const a=[...c.items];a[i]={...a[i],text:e.target.value};setC('items',a);}}/></div>)}<button onClick={()=>setC('items',[...(c.items||[]),{name:'Customer',text:'Great!',rating:5}])} className="text-xs text-brand-600 font-bold">+ Add</button></>}
    {section.type==='custom_html'&&<><hr/><div><p className="text-[10px] text-gray-400">HTML</p><textarea className="input-field !py-1 text-xs font-mono" rows={6} value={c.html||''} onChange={e=>setC('html',e.target.value)}/></div></>}
  </div>);
}

function Preview({section}){
  const s=section.style||{};const c=section.content||{};
  const wrap={backgroundColor:s.bg||'#fff',color:s.textColor||'#1f2937',padding:`${(parseInt(s.padding)||60)/4}px`,fontFamily:s.fontFamily||'Inter',borderRadius:`${s.borderRadius||0}px`};
  if(section.type==='hero')return<div style={{...wrap,minHeight:`${(parseInt(c.height)||500)/4}px`,backgroundImage:c.bgImage?`url(${c.bgImage})`:'none',backgroundSize:'cover',backgroundPosition:'center',display:'flex',alignItems:'center',justifyContent:'center',textAlign:c.align||'center',position:'relative'}}>{c.bgImage&&<div style={{position:'absolute',inset:0,backgroundColor:`rgba(0,0,0,${c.overlay||0.3})`}}/>}<div style={{position:'relative',zIndex:1}}><p style={{fontSize:`${(parseInt(c.titleSize)||48)/3}px`,fontWeight:900}}>{c.title}</p><p style={{fontSize:`${(parseInt(c.subtitleSize)||20)/3}px`,opacity:0.7,marginTop:3}}>{c.subtitle}</p>{c.btnText&&<div style={{marginTop:6,display:'inline-block',padding:'3px 10px',backgroundColor:c.btnColor||'#7C3AED',color:'#fff',borderRadius:5,fontSize:9,fontWeight:700}}>{c.btnText}</div>}</div></div>;
  if(section.type==='products'){const cols=parseInt(c.columns)||4;return<div style={wrap}>{c.title&&<p style={{fontSize:`${(parseInt(c.titleSize)||28)/3}px`,fontWeight:800,textAlign:'center',marginBottom:6}}>{c.title}</p>}<div style={{display:'grid',gridTemplateColumns:`repeat(${cols},1fr)`,gap:4}}>{Array.from({length:Math.min(parseInt(c.limit)||4,6)}).map((_,i)=><div key={i} style={{backgroundColor:s.bg==='#ffffff'||!s.bg?'#f3f4f6':'rgba(255,255,255,0.1)',borderRadius:6,overflow:'hidden'}}><div style={{height:30,backgroundColor:s.bg==='#ffffff'||!s.bg?'#e5e7eb':'rgba(255,255,255,0.05)'}}/><div style={{padding:3}}><div style={{height:4,backgroundColor:'rgba(128,128,128,0.3)',borderRadius:2,width:'70%',marginBottom:2}}/>{c.showPrice!==false&&<div style={{height:4,backgroundColor:'rgba(128,128,255,0.4)',borderRadius:2,width:'40%'}}/>}</div></div>)}</div></div>;}
  if(section.type==='text')return<div style={{...wrap,textAlign:c.align||'left'}}><p style={{fontSize:`${(parseInt(c.fontSize)||16)/3}px`,lineHeight:c.lineHeight||'1.7'}}>{c.text}</p></div>;
  if(section.type==='image')return<div style={{...wrap,textAlign:c.align||'center'}}>{c.src?<img src={c.src} style={{width:`${c.width||100}%`,borderRadius:`${c.rounded||12}px`,maxWidth:'100%'}} alt=""/>:<div style={{height:40,backgroundColor:'#e5e7eb',borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',color:'#9ca3af',fontSize:10}}>No image</div>}</div>;
  if(section.type==='banner')return<div style={{...wrap,textAlign:c.align||'center'}}><p style={{fontSize:`${(parseInt(c.fontSize)||24)/3}px`,fontWeight:800}}>{c.text}</p>{c.btnText&&<div style={{marginTop:4,display:'inline-block',padding:'2px 8px',border:'1px solid currentColor',borderRadius:4,fontSize:8}}>{c.btnText}</div>}</div>;
  if(section.type==='spacer')return<div style={{height:`${(parseInt(c.height)||60)/4}px`,backgroundColor:s.bg||'transparent'}}/>;
  if(section.type==='features'){const cols=parseInt(c.columns)||3;return<div style={wrap}><div style={{display:'grid',gridTemplateColumns:`repeat(${cols},1fr)`,gap:6,textAlign:'center'}}>{(c.items||[]).map((f,i)=><div key={i}><span style={{fontSize:14}}>{f.icon}</span><p style={{fontWeight:700,fontSize:8,marginTop:1}}>{f.title}</p><p style={{fontSize:6,opacity:0.6}}>{f.desc}</p></div>)}</div></div>;}
  if(section.type==='testimonials')return<div style={wrap}>{c.title&&<p style={{fontSize:`${(parseInt(c.titleSize)||28)/3}px`,fontWeight:800,textAlign:'center',marginBottom:6}}>{c.title}</p>}<div style={{display:'grid',gridTemplateColumns:`repeat(${Math.min((c.items||[]).length,3)},1fr)`,gap:4}}>{(c.items||[]).map((t,i)=><div key={i} style={{backgroundColor:'rgba(128,128,128,0.08)',padding:4,borderRadius:6}}><p style={{fontSize:6}}>{t.text}</p><p style={{fontSize:5,fontWeight:700,marginTop:2}}>— {t.name}</p></div>)}</div></div>;
  if(section.type==='custom_html')return<div style={wrap}><div style={{fontSize:7,color:'#9ca3af',textAlign:'center'}}>Custom HTML</div></div>;
  return null;
}

export default function AdvancedBuilder(){
  const{currentStore,setCurrentStore}=useStoreManagement();
  const[sections,setSections]=useState([]);
  const[selected,setSelected]=useState(null);
  const[showAdd,setShowAdd]=useState(false);
  const[showTemplates,setShowTemplates]=useState(false);
  const[saving,setSaving]=useState(false);
  const[preview,setPreview]=useState('desktop');
  const[dirty,setDirty]=useState(false);

  useEffect(()=>{if(!currentStore)return;const cfg=currentStore.config||{};if(cfg.page_builder&&Array.isArray(cfg.page_builder)&&cfg.page_builder.length>0)setSections(cfg.page_builder);else{setSections([]);setShowTemplates(true);}},[currentStore?.id]);

  const upd=(i,s)=>{const n=[...sections];n[i]=s;setSections(n);setDirty(true);};
  const move=(i,d)=>{const n=[...sections];[n[i],n[i+d]]=[n[i+d],n[i]];setSections(n);setSelected(i+d);setDirty(true);};
  const rm=(i)=>{setSections(sections.filter((_,j)=>j!==i));if(selected===i)setSelected(null);setDirty(true);};
  const dup=(i)=>{const s={...JSON.parse(JSON.stringify(sections[i])),id:uid()};const n=[...sections];n.splice(i+1,0,s);setSections(n);setDirty(true);};
  const add=(type)=>{setSections([...sections,defaultSection(type)]);setSelected(sections.length);setShowAdd(false);setDirty(true);};
  const toggle=(i)=>{const n=[...sections];n[i]={...n[i],visible:!n[i].visible};setSections(n);setDirty(true);};
  const applyTemplate=(t)=>{const fresh=JSON.parse(JSON.stringify(t.sections)).map(s=>({...s,id:uid()}));setSections(fresh);setSelected(null);setShowTemplates(false);setDirty(true);toast.success(`"${t.name}" applied!`);};
  const save=async()=>{setSaving(true);try{const{data}=await ownerApi.updateStore(currentStore.id,{page_builder:sections});setCurrentStore(data);setDirty(false);toast.success('Saved!');}catch{toast.error('Failed');}setSaving(false);};

  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-4">
      <div><h1 className="text-2xl font-bold">Page Builder</h1><p className="text-sm text-gray-400 mt-1">Build your storefront exactly how you want</p></div>
      <div className="flex items-center gap-2">
        <button onClick={()=>setShowTemplates(true)} className="px-3 py-2 bg-purple-50 text-purple-600 rounded-xl text-sm font-bold flex items-center gap-1.5 hover:bg-purple-100"><Layers size={14}/>Templates</button>
        <div className="flex bg-gray-100 rounded-lg p-0.5"><button onClick={()=>setPreview('desktop')} className={`p-1.5 rounded-md ${preview==='desktop'?'bg-white shadow-sm':'text-gray-400'}`}><Monitor size={14}/></button><button onClick={()=>setPreview('mobile')} className={`p-1.5 rounded-md ${preview==='mobile'?'bg-white shadow-sm':'text-gray-400'}`}><Smartphone size={14}/></button></div>
        <button onClick={save} disabled={saving||!dirty} className="btn-primary text-sm flex items-center gap-2 disabled:opacity-50"><Save size={14}/>{saving?'Saving...':'Save'}</button>
      </div>
    </div>
    <div className="flex gap-4" style={{height:'calc(100vh - 160px)'}}>
      <div className="w-56 shrink-0 space-y-1.5 overflow-y-auto pr-1">
        {sections.map((sec,i)=>{const T=SECTION_TYPES.find(t=>t.type===sec.type);const Icon=T?.icon||Layout;return(
          <div key={sec.id} onClick={()=>setSelected(i)} className={`p-2.5 rounded-xl cursor-pointer transition-all ${selected===i?'bg-brand-50 ring-2 ring-brand-400':'bg-white border border-gray-200 hover:border-gray-300'} ${!sec.visible?'opacity-40':''}`}>
            <div className="flex items-center gap-2"><Icon size={13} className={selected===i?'text-brand-500':'text-gray-400'}/><span className="text-[11px] font-bold text-gray-700 flex-1 truncate">{T?.label||sec.type}</span>
              <div className="flex gap-px">{i>0&&<button onClick={e=>{e.stopPropagation();move(i,-1);}} className="p-0.5 hover:bg-gray-200 rounded"><ChevronUp size={10}/></button>}{i<sections.length-1&&<button onClick={e=>{e.stopPropagation();move(i,1);}} className="p-0.5 hover:bg-gray-200 rounded"><ChevronDown size={10}/></button>}<button onClick={e=>{e.stopPropagation();toggle(i);}} className="p-0.5 hover:bg-gray-200 rounded">{sec.visible?<Eye size={10}/>:<EyeOff size={10}/>}</button><button onClick={e=>{e.stopPropagation();dup(i);}} className="p-0.5 hover:bg-gray-200 rounded"><Copy size={10}/></button><button onClick={e=>{e.stopPropagation();rm(i);}} className="p-0.5 hover:bg-red-100 rounded text-red-400"><Trash2 size={10}/></button></div>
            </div></div>);})}
        <button onClick={()=>setShowAdd(true)} className="w-full p-2.5 rounded-xl border-2 border-dashed border-gray-300 text-gray-400 hover:border-brand-400 hover:text-brand-500 flex items-center justify-center gap-1.5 text-xs font-bold"><Plus size={13}/>Add Section</button>
      </div>
      <div className="flex-1 bg-gray-100 rounded-2xl overflow-y-auto p-3">
        <div className={`mx-auto bg-white rounded-xl shadow-sm overflow-hidden ${preview==='mobile'?'max-w-[375px]':'max-w-[900px]'}`}>
          {sections.filter(s=>s.visible).length===0?<div className="py-16 text-center"><Layers size={36} className="mx-auto text-gray-300 mb-3"/><p className="text-sm text-gray-400 mb-3">No sections yet</p><button onClick={()=>setShowTemplates(true)} className="px-4 py-2 bg-purple-500 text-white rounded-xl text-sm font-bold">Choose a Template</button></div>:
          sections.filter(s=>s.visible).map(sec=>(<div key={sec.id} onClick={()=>setSelected(sections.indexOf(sec))} className={`cursor-pointer transition-all ${selected===sections.indexOf(sec)?'ring-2 ring-brand-400 ring-inset':''}`}><Preview section={sec}/></div>))}
        </div>
      </div>
      <div className="w-64 shrink-0 bg-white rounded-2xl border border-gray-200 overflow-y-auto p-3">
        {selected!==null&&sections[selected]?<div><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-xs text-gray-900">{SECTION_TYPES.find(t=>t.type===sections[selected].type)?.label||'Section'}</h3><button onClick={()=>setSelected(null)} className="p-1 hover:bg-gray-100 rounded"><X size={12}/></button></div><StylePanel section={sections[selected]} onChange={s=>upd(selected,s)}/></div>:<div className="text-center py-10"><Layout size={28} className="mx-auto text-gray-300 mb-2"/><p className="text-xs text-gray-400">Click a section to edit</p></div>}
      </div>
    </div>
    {showAdd&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowAdd(false)}><div className="bg-white rounded-3xl p-5 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-3"><h2 className="text-lg font-bold">Add Section</h2><button onClick={()=>setShowAdd(false)}><X size={18}/></button></div><div className="space-y-1.5">{SECTION_TYPES.map(t=>{const Icon=t.icon;return<button key={t.type} onClick={()=>add(t.type)} className="w-full p-3 rounded-xl border-2 border-gray-200 hover:border-brand-400 text-left flex items-center gap-3 transition-all"><div className="w-9 h-9 rounded-lg bg-brand-50 flex items-center justify-center shrink-0"><Icon size={16} className="text-brand-500"/></div><div><p className="font-bold text-sm text-gray-900">{t.label}</p><p className="text-[10px] text-gray-400">{t.desc}</p></div></button>;})}</div></div></div>}
    {showTemplates&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowTemplates(false)}><div className="bg-white rounded-3xl p-6 w-full max-w-3xl max-h-[85vh] overflow-y-auto shadow-2xl" onClick={e=>e.stopPropagation()}>
      <div className="flex items-center justify-between mb-5"><div><h2 className="text-xl font-bold">Choose a Template</h2><p className="text-sm text-gray-400 mt-1">Pick a design — fully customizable after applying</p></div><button onClick={()=>setShowTemplates(false)}><X size={20}/></button></div>
      <div className="grid grid-cols-2 gap-4">
        {TEMPLATES.map((t,ti)=>(
          <button key={ti} onClick={()=>{if(sections.length>0&&!confirm('Replace current page with this template?'))return;applyTemplate(t);}} className="text-left rounded-2xl border-2 border-gray-200 hover:border-brand-400 overflow-hidden transition-all hover:shadow-lg">
            <div className="h-40 overflow-hidden relative">
              <div className="transform scale-[0.22] origin-top-left w-[455%]">{t.sections.filter(s=>s.visible).slice(0,3).map((sec,si)=><Preview key={si} section={sec}/>)}</div>
              <div className="absolute inset-0 bg-gradient-to-t from-white/90 via-transparent to-transparent"/>
            </div>
            <div className="p-4">
              <div className="flex items-center gap-2 mb-1"><p className="font-bold text-gray-900">{t.name}</p><div className="flex gap-1 ml-auto">{t.colors.map((c,ci)=><div key={ci} style={{backgroundColor:c}} className="w-4 h-4 rounded-full border border-gray-200"/>)}</div></div>
              <p className="text-xs text-gray-400">{t.desc}</p>
              <p className="text-[10px] text-brand-500 font-bold mt-2">{t.sections.length} sections</p>
            </div>
          </button>
        ))}
      </div>
    </div></div>}
  </DashboardLayout>);
}
