import React,{useState} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import toast from'react-hot-toast';import{Shield,Phone,Users,RefreshCw}from'lucide-react';
export default function Blacklist(){const[enabled,setEnabled]=useState(false);const[phone,setPhone]=useState('');const[blocked,setBlocked]=useState([]);
const block=()=>{if(!phone.trim())return;setBlocked([...blocked,{id:Date.now(),name:'Blacklisted Guest',phone,email:`blocked_${phone}@blacklisted.local`,cancelled:0}]);setPhone('');toast.success('Phone blocked!');};
const unblock=(id)=>{setBlocked(blocked.filter(b=>b.id!==id));toast.success('Unblocked');};
return(<DashboardLayout>
<h1 className="text-2xl font-bold text-gray-900 mb-1">Blacklist Management</h1>
<p className="text-sm text-gray-500 mb-6">Manage blocking rules and blacklisted customers</p>
<div className="glass-card-solid p-6 mb-6"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-red-50 flex items-center justify-center"><Shield size={20} className="text-red-500"/></div><div><h3 className="font-bold text-gray-900">Automatic Blacklist</h3><p className="text-xs text-gray-400">Configure how customers are automatically blacklisted</p></div></div>
<label className="flex items-center justify-between p-4 bg-gray-50 rounded-xl cursor-pointer"><div><p className="font-medium text-sm">Enable Automatic Blacklist</p><p className="text-xs text-gray-400">Increment cancelled orders count and blacklist customers automatically.</p></div><div className={`w-11 h-6 rounded-full transition-colors ${enabled?'bg-brand-500':'bg-gray-300'} relative`}><div className={`absolute top-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${enabled?'translate-x-5':'translate-x-0.5'}`}/></div><input type="checkbox" className="sr-only" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label></div>
<div className="glass-card-solid p-6 mb-6"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center"><Phone size={20} className="text-orange-500"/></div><div><h3 className="font-bold text-gray-900">Block by Phone Number</h3><p className="text-xs text-gray-400">Manually block customers matching a phone number</p></div></div>
<div className="flex gap-3"><div className="flex-1"><label className="input-label text-xs">Phone Number</label><input className="input-field" placeholder="Enter phone number to block..." value={phone} onChange={e=>setPhone(e.target.value)}/></div><button onClick={block} className="btn-danger flex items-center gap-2 self-end"><Users size={16}/>Block</button></div></div>
<div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gray-100 flex items-center justify-center"><Users size={20} className="text-gray-500"/></div><div><h3 className="font-bold text-gray-900">Blacklisted Customers</h3><p className="text-xs text-gray-400">{blocked.length} customers blocked</p></div></div><button className="btn-ghost text-xs flex items-center gap-1"><RefreshCw size={14}/>Refresh</button></div>
{blocked.length===0?<p className="text-center py-8 text-gray-400">No blacklisted customers</p>:blocked.map(b=>(<div key={b.id} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl mb-2"><div><p className="font-bold text-gray-800">{b.name}</p><p className="text-xs text-gray-400">{b.phone} 📱 · {b.email}</p><p className="text-xs text-red-500">Cancelled Orders: {b.cancelled}</p></div><button onClick={()=>unblock(b.id)} className="text-sm text-red-500 font-medium hover:underline">Unblock</button></div>))}</div>
</DashboardLayout>);}
