import React,{useState,useEffect} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useStoreManagement}from'../../hooks/useStore';import{orderApi}from'../../utils/api';import toast from'react-hot-toast';import{Shield,Phone,Trash2,Plus,X,RefreshCw,Search,AlertTriangle}from'lucide-react';
export default function Blacklist(){
  const{currentStore}=useStoreManagement();
  const[list,setList]=useState([]);const[loading,setLoading]=useState(true);
  const[showAdd,setShowAdd]=useState(false);const[form,setForm]=useState({phone:'',name:'',reason:''});
  const[search,setSearch]=useState('');
  const load=()=>{if(!currentStore?.id)return;setLoading(true);orderApi.getBlacklist(currentStore.id).then(r=>setList(r.data)).catch(()=>{}).finally(()=>setLoading(false));};
  useEffect(()=>{load();},[currentStore?.id]);
  const add=async()=>{if(!form.phone.trim())return toast.error('Phone required');try{await orderApi.addBlacklist(currentStore.id,form);toast.success('Blocked!');setShowAdd(false);setForm({phone:'',name:'',reason:''});load();}catch(e){toast.error(e.response?.data?.error||'Failed');}};
  const remove=async(id)=>{if(!confirm('Unblock?'))return;try{await orderApi.removeBlacklist(currentStore.id,id);toast.success('Unblocked');load();}catch{toast.error('Failed');}};
  const filtered=list.filter(b=>!search||b.phone.includes(search)||(b.name||'').toLowerCase().includes(search.toLowerCase()));
  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Shield size={24} className="text-red-500"/>Blacklist</h1><p className="text-sm text-gray-400 mt-1">{list.length} blocked numbers</p></div><div className="flex gap-2"><button onClick={load} className="btn-ghost text-xs"><RefreshCw size={14}/></button><button onClick={()=>setShowAdd(true)} className="btn-primary text-sm flex items-center gap-2"><Plus size={16}/>Block Number</button></div></div>
    <div className="relative max-w-sm mb-6"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input-field !pl-9 !py-2 text-sm" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
    {loading?<div className="py-20 text-center"><div className="w-8 h-8 border-3 border-gray-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>:filtered.length===0?<div className="glass-card-solid p-16 text-center"><Shield size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500">{search?'No matches':'No blocked numbers'}</p></div>:
    <div className="space-y-2">{filtered.map(b=><div key={b.id} className="glass-card-solid p-4 flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-red-100 flex items-center justify-center shrink-0"><Phone size={16} className="text-red-600"/></div><div className="flex-1"><p className="font-bold text-gray-900">{b.phone}</p><p className="text-xs text-gray-400">{b.name||'Unknown'} · {b.reason||'Manual'}</p>{b.cancelled_count>0&&<p className="text-[10px] text-red-500 font-bold">{b.cancelled_count} cancellations</p>}</div><div className="text-xs text-gray-400 shrink-0">{new Date(b.created_at).toLocaleDateString()}</div><button onClick={()=>remove(b.id)} className="p-2 hover:bg-red-50 rounded-xl text-gray-400 hover:text-red-500"><Trash2 size={16}/></button></div>)}</div>}
    {showAdd&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowAdd(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">Block Phone Number</h2><button onClick={()=>setShowAdd(false)}><X size={20}/></button></div><div className="space-y-4"><div><label className="input-label">Phone *</label><input className="input-field" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="0555123456"/></div><div><label className="input-label">Name</label><input className="input-field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="input-label">Reason</label><input className="input-field" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Spam, fraud, etc."/></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowAdd(false)} className="btn-ghost flex-1">Cancel</button><button onClick={add} className="btn-primary flex-1 bg-red-500 hover:bg-red-600">Block</button></div></div></div>}
  </DashboardLayout>);
}
