import React,{useState,useEffect} from'react';import{useTranslation}from'react-i18next';import{useStoreManagement}from'../../hooks/useStore';import{ownerApi}from'../../utils/api';import DashboardLayout from'../../components/shared/DashboardLayout';import toast from'react-hot-toast';import{Save,Eye,Upload}from'lucide-react';
export default function HomePageEditor(){const{t}=useTranslation();const{currentStore,setCurrentStore}=useStoreManagement();const[title,setTitle]=useState('');const[subtitle,setSubtitle]=useState('');const[saving,setSaving]=useState(false);
useEffect(()=>{if(currentStore){setTitle(currentStore.hero_title||currentStore.name||currentStore.store_name||'');setSubtitle(currentStore.hero_subtitle||'');}},[currentStore?.id]);
const save=async()=>{setSaving(true);try{const{data}=await ownerApi.updateStore(currentStore.id,{hero_title:title,hero_subtitle:subtitle});setCurrentStore(data);toast.success(t('storePage.saved','Saved!'));}catch{toast.error(t('storePage.failed','Failed'));}setSaving(false);};
return(<DashboardLayout>
<div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">{t('storePage.homePage','Home page')}</h1><p className="text-sm text-gray-500">{t('storePage.homePageDesc',"Customize your store's home page content")}</p></div><div className="flex gap-3"><a href={`/s/${currentStore?.slug}`} target="_blank" rel="noopener noreferrer" className="btn-ghost flex items-center gap-1"><Eye size={16}/>{t('storePage.preview','Preview')}</a><button onClick={save} disabled={saving} className="btn-primary flex items-center gap-2"><Save size={16}/>{saving?t('storePage.saving','Saving...'):t('storePage.save','Save')}</button></div></div>
<div className="glass-card-solid p-6 space-y-4">
<div><label className="input-label">{t('storePage.homepageTitle','Homepage Title')}</label><input className="input-field" value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('storePage.homepageTitlePh','MyMarket')}/><p className="text-xs text-gray-400 mt-1">{t('storePage.homepageTitleHelp',"The main headline shown on your store's homepage")}</p></div>
<div><label className="input-label">{t('storePage.homepageSubtitle','Homepage Subtitle')}</label><textarea className="input-field" rows={3} value={subtitle} onChange={e=>setSubtitle(e.target.value)} placeholder={t('storePage.homepageSubtitlePh','Discover our amazing products')}/><p className="text-xs text-gray-400 mt-1">{t('storePage.homepageSubtitleHelp','A brief description or tagline for your store')}</p></div>
<div><p className="input-label">{t('storePage.preview','Preview')}</p><div className="bg-gray-50 rounded-xl p-8 text-center"><h2 className="text-3xl font-black text-gray-900 italic" style={{fontFamily:'Georgia,serif'}}>{title||t('storePage.yourStoreName','Your Store Name')}</h2><p className="text-gray-500 mt-2">{subtitle||t('storePage.yourSubtitleHere','Your subtitle will appear here')}</p></div></div></div>
</DashboardLayout>);}
