import React,{useState,useEffect} from'react';import{useStoreManagement}from'../../hooks/useStore';import{ownerApi}from'../../utils/api';import DashboardLayout from'../../components/shared/DashboardLayout';import toast from'react-hot-toast';import{Save,Eye}from'lucide-react';
export default function HomePageEditor(){const{currentStore}=useStoreManagement();const[title,setTitle]=useState('');const[subtitle,setSubtitle]=useState('');
useEffect(()=>{if(currentStore){setTitle(currentStore.hero_title||currentStore.name||currentStore.store_name||'');setSubtitle(currentStore.hero_subtitle||'');};},[currentStore]);
const save=async()=>{try{await ownerApi.updateStore(currentStore.id,{hero_title:title,hero_subtitle:subtitle});toast.success('Saved!');}catch{toast.error('Failed');}};
return(<DashboardLayout>
<div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">Home page</h1><p className="text-sm text-gray-500">Customize your store's home page content</p></div><div className="flex gap-3"><button className="btn-ghost flex items-center gap-1"><Eye size={16}/>Preview (Global)</button><button onClick={save} className="btn-primary flex items-center gap-2"><Save size={16}/>Save</button></div></div>
<div className="glass-card-solid p-6 space-y-4">
<div><label className="input-label">Homepage Title</label><input className="input-field" value={title} onChange={e=>setTitle(e.target.value)} placeholder="MyMarket"/><p className="text-xs text-gray-400 mt-1">The main headline shown on your store's homepage</p></div>
<div><label className="input-label">Homepage Subtitle</label><textarea className="input-field" rows={3} value={subtitle} onChange={e=>setSubtitle(e.target.value)} placeholder="Discover our amazing products"/><p className="text-xs text-gray-400 mt-1">A brief description or tagline for your store</p></div>
<div><p className="input-label">Preview</p><div className="bg-gray-50 rounded-xl p-8 text-center"><h2 className="text-3xl font-black text-gray-900 italic" style={{fontFamily:'Georgia,serif'}}>{title||'Your Store Name'}</h2><p className="text-gray-500 mt-2">{subtitle||'Your subtitle will appear here'}</p></div></div></div>
</DashboardLayout>);}
