import React from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{Shield,Zap,Lock,ArrowRight,FileText,Truck}from'lucide-react';
export default function HowToConnect(){return(<DashboardLayout>
<div className="grid lg:grid-cols-2 gap-6">
<div className="glass-card-solid p-8"><div className="flex items-center gap-3 mb-6"><div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center"><Shield size={24} className="text-blue-500"/></div><div><h2 className="text-xl font-bold text-gray-900">Technical Integration</h2><p className="text-sm text-gray-400">Step-by-step connection guide</p></div></div>
{[{n:'01',t:'Obtain Credentials',d:'Get API keys from your delivery partner'},{n:'02',t:'Choose Partner',d:'Select from our marketplace'},{n:'03',t:'Authentication',d:'Enter your API ID and Token'},{n:'04',t:'Verify Link',d:'Test the connection'}].map(s=>(<div key={s.n} className="flex items-center gap-4 mb-6"><div className="w-10 h-10 rounded-full bg-gray-900 text-white flex items-center justify-center text-sm font-bold shrink-0">{s.n}</div><div><p className="font-bold text-gray-800">{s.t}</p><p className="text-xs text-gray-400">{s.d}</p></div></div>))}
<button className="w-full py-3 bg-gray-900 text-white rounded-xl font-medium flex items-center justify-center gap-2"><FileText size={16}/>Developer Documentation</button></div>
<div className="bg-gradient-to-br from-gray-700 to-gray-800 rounded-2xl p-8 text-white"><div className="flex items-center gap-3 mb-6"><div className="w-12 h-12 rounded-xl bg-orange-500/20 flex items-center justify-center"><Truck size={24} className="text-orange-400"/></div><div><h2 className="text-xl font-bold">Shipping Workflow</h2></div></div>
{[{icon:Lock,t:'Safe Data Relay',d:'All customer data are pushed through encrypted endpoints.'},{icon:Zap,t:'Instant Tracking',d:'Tracking numbers are returned instantly and saved back.'},{icon:Shield,t:'Bulk Actions',d:'Connect multiple partners and choose the best rate.'}].map((s,i)=>{const I=s.icon;return(<div key={i} className="flex items-center gap-4 mb-4 bg-white/5 rounded-xl p-4"><I size={20} className="text-white/60 shrink-0"/><div><p className="font-semibold text-sm">{s.t}</p><p className="text-xs text-white/50">{s.d}</p></div></div>);})}
</div></div>
<div className="bg-gradient-to-r from-brand-600 to-purple-700 rounded-2xl p-8 mt-6 text-white"><p className="text-[10px] text-white/50 uppercase font-bold mb-2">COMMUNITY STEP</p><h3 className="text-2xl font-bold mb-2">Ready to automate? Connection takes less than 2 minutes.</h3><button className="mt-4 px-6 py-3 bg-white text-brand-600 font-bold rounded-xl flex items-center gap-2">Return to Marketplace <ArrowRight size={16}/></button></div>
</DashboardLayout>);}
