import React,{useState} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import toast from'react-hot-toast';import{Save,Eye,Globe,Palette,Search,Clock}from'lucide-react';
const T=({label,desc,checked,onChange})=>(<label className="flex items-center justify-between p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-brand-100 flex items-center justify-center"><div className="w-2 h-2 bg-brand-500 rounded-full"/></div><div><p className="font-medium text-sm">{label}</p>{desc&&<p className="text-xs text-gray-400">{desc}</p>}</div></div><div className={`w-11 h-6 rounded-full transition-colors ${checked?'bg-brand-500':'bg-gray-300'} relative`}><div className={`absolute top-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${checked?'translate-x-5':'translate-x-0.5'}`}/></div><input type="checkbox" className="sr-only" checked={checked||false} onChange={onChange}/></label>);
export default function OrderTracking(){const[tab,setTab]=useState('general');const[s,setS]=useState({enabled:true,heroTitle:'Track Your Order',heroSub:'Enter your phone number to see the current status of your orders.',showPrice:true,showItems:true,showTimeline:true,showAddress:true,showDelivery:false});
return(<DashboardLayout>
<div className="mb-6"><span className="badge bg-brand-100 text-brand-600 text-[10px] mb-2">STOREFRONT</span><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Order <span className="text-brand-500 italic">Tracking</span></h1><p className="text-sm text-gray-500">Design a professional multi-method tracking experience for your customers.</p></div><div className="flex gap-3"><button className="btn-ghost flex items-center gap-1"><Eye size={16}/>Preview</button><button onClick={()=>toast.success('Saved!')} className="btn-primary flex items-center gap-2"><Save size={16}/>Save</button></div></div></div>
<div className="flex gap-6 border-b border-gray-200 mb-6">{[{id:'general',icon:Globe,l:'General'},{id:'interface',icon:Palette,l:'Interface'},{id:'search',icon:Search,l:'Search & Logic'},{id:'statuses',icon:Clock,l:'Statuses'}].map(t=>{const I=t.icon;return(<button key={t.id} onClick={()=>setTab(t.id)} className={`flex items-center gap-2 pb-3 px-4 text-sm font-medium border-b-2 transition-colors ${tab===t.id?'border-brand-500 text-brand-600':'border-transparent text-gray-400'}`}><I size={16}/>{t.l}</button>);})}</div>
<div className="grid lg:grid-cols-3 gap-6">
<div className="lg:col-span-2 space-y-6">
{tab==='general'&&<div className="glass-card-solid p-6"><div className="flex items-center gap-3 mb-4"><Globe size={20} className="text-brand-500"/><div><h3 className="font-bold">Core Feature</h3><p className="text-xs text-gray-400">Toggle visibility and basic functionality of the tracking module.</p></div></div><T label="Enable Public Tracking" desc="Makes the tracking page accessible via your store header and direct URL." checked={s.enabled} onChange={e=>setS({...s,enabled:e.target.checked})}/><div className="mt-3 bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-700">ℹ When enabled, a tracking icon will automatically appear in your store's navigation bar.</div></div>}
{tab==='interface'&&<div className="glass-card-solid p-6 space-y-4"><div className="flex items-center gap-3 mb-2"><Palette size={20} className="text-brand-500"/><div><h3 className="font-bold">Interface Customization</h3><p className="text-xs text-gray-400">Craft the visual narrative of your tracking page.</p></div></div>
<div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Page Hero Title</label><input className="input-field" value={s.heroTitle} onChange={e=>setS({...s,heroTitle:e.target.value})}/></div><div><p className="text-xs font-bold text-gray-400 uppercase mb-2">Element Visibility</p><T label="Show Order Price" desc="Display total amount." checked={s.showPrice} onChange={e=>setS({...s,showPrice:e.target.checked})}/></div></div>
<div><label className="input-label text-xs">Hero Subtitle</label><textarea className="input-field" rows={2} value={s.heroSub} onChange={e=>setS({...s,heroSub:e.target.value})}/></div>
<T label="Show Item List" desc="Display products ordered." checked={s.showItems} onChange={e=>setS({...s,showItems:e.target.checked})}/>
<T label="Status Timeline" desc="Show progressive steps." checked={s.showTimeline} onChange={e=>setS({...s,showTimeline:e.target.checked})}/>
<T label="Show Address" desc="Display Wilaya and Commune." checked={s.showAddress} onChange={e=>setS({...s,showAddress:e.target.checked})}/>
<T label="Est. Delivery Date" desc="Show predicted arrival." checked={s.showDelivery} onChange={e=>setS({...s,showDelivery:e.target.checked})}/>
</div>}
{(tab==='search'||tab==='statuses')&&<div className="glass-card-solid p-12 text-center"><p className="text-gray-400">This tab is under development.</p></div>}
</div>
<div><p className="text-xs font-bold text-gray-400 uppercase text-center mb-3">LIVE PREVIEW</p><div className="bg-gray-900 rounded-3xl p-6 text-white mx-auto max-w-[280px]"><div className="w-16 h-1 bg-white/20 rounded-full mx-auto mb-6"/><h3 className="text-lg font-bold text-center mb-1">{s.heroTitle}</h3><p className="text-xs text-white/50 text-center mb-4">{s.heroSub}</p><div className="flex items-center gap-2 bg-white/5 rounded-xl p-3 mb-4"><div className="w-3 h-3 bg-white/20 rounded-full"/><div className="flex-1 h-2 bg-white/10 rounded"/></div><button className="w-full py-3 bg-brand-500 rounded-xl font-bold text-sm">Track Order</button><div className="mt-4 space-y-2">{[1,2].map(i=>(<div key={i} className="flex gap-3"><div className="w-12 h-3 bg-white/10 rounded"/><div className="flex-1 h-3 bg-white/5 rounded"/></div>))}</div><div className="mt-6 flex items-center justify-center gap-2 text-xs text-white/30"><div className="w-4 h-4 border border-white/20 rounded"/><span>Contact Support</span></div><p className="text-[8px] text-white/20 text-center mt-4">RENDER ENGINE V2.0</p></div></div>
</div>
</DashboardLayout>);}
