import React,{useState,useEffect} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useStoreManagement}from'../../hooks/useStore';import{ownerApi}from'../../utils/api';import toast from'react-hot-toast';import{Save,Eye,Search,Clock,Package,MapPin}from'lucide-react';
const T=({label,desc,checked,onChange})=>(<label className="flex items-center justify-between p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100"><div><p className="font-medium text-sm">{label}</p>{desc&&<p className="text-xs text-gray-400">{desc}</p>}</div><div className={`w-11 h-6 rounded-full transition-colors ${checked?'bg-brand-500':'bg-gray-300'} relative`}><div className={`absolute top-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${checked?'translate-x-5':'translate-x-0.5'}`}/></div><input type="checkbox" className="sr-only" checked={checked||false} onChange={onChange}/></label>);
export default function OrderTracking(){
  const{currentStore,setCurrentStore}=useStoreManagement();
  const[s,setS]=useState({});const[saving,setSaving]=useState(false);
  useEffect(()=>{if(currentStore)setS({tracking_enabled:currentStore.tracking_enabled!==false,tracking_hero_title:currentStore.tracking_hero_title||'Track Your Order',tracking_hero_sub:currentStore.tracking_hero_sub||'Enter your phone number to see the status of your orders.',tracking_show_price:currentStore.tracking_show_price!==false,tracking_show_items:currentStore.tracking_show_items!==false,tracking_show_timeline:currentStore.tracking_show_timeline!==false,tracking_show_address:currentStore.tracking_show_address!==false});},[currentStore?.id]);
  const set=(k,v)=>setS({...s,[k]:v});
  const save=async()=>{setSaving(true);try{const{data}=await ownerApi.updateStore(currentStore.id,s);setCurrentStore(data);toast.success('Saved!');}catch{toast.error('Failed');}setSaving(false);};
  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><div><span className="badge bg-brand-100 text-brand-600 text-[10px] mb-2">STOREFRONT</span><h1 className="text-2xl font-bold">Order Tracking</h1><p className="text-sm text-gray-400 mt-1">Configure the tracking experience for customers</p></div><button onClick={save} disabled={saving} className="btn-primary text-sm flex items-center gap-2"><Save size={16}/>{saving?'Saving...':'Save'}</button></div>
    <div className="grid lg:grid-cols-2 gap-6">
      <div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold flex items-center gap-2"><Clock size={16} className="text-brand-500"/>General</h3><T label="Enable Order Tracking" desc="Allow customers to track orders by phone number" checked={s.tracking_enabled} onChange={e=>set('tracking_enabled',e.target.checked)}/><div><label className="input-label text-xs">Hero Title</label><input className="input-field" value={s.tracking_hero_title||''} onChange={e=>set('tracking_hero_title',e.target.value)}/></div><div><label className="input-label text-xs">Subtitle</label><input className="input-field" value={s.tracking_hero_sub||''} onChange={e=>set('tracking_hero_sub',e.target.value)}/></div></div>
      <div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold flex items-center gap-2"><Package size={16} className="text-purple-500"/>Display Options</h3><T label="Show Price" desc="Display order total on tracking page" checked={s.tracking_show_price} onChange={e=>set('tracking_show_price',e.target.checked)}/><T label="Show Items" desc="Show ordered products list" checked={s.tracking_show_items} onChange={e=>set('tracking_show_items',e.target.checked)}/><T label="Show Timeline" desc="Visual status timeline" checked={s.tracking_show_timeline} onChange={e=>set('tracking_show_timeline',e.target.checked)}/><T label="Show Address" desc="Display delivery address" checked={s.tracking_show_address} onChange={e=>set('tracking_show_address',e.target.checked)}/></div>
    </div>
  </DashboardLayout>);
}
