import React,{useState,useEffect} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useStoreManagement}from'../../hooks/useStore';import api from'../../utils/api';import toast from'react-hot-toast';import{Search,Truck,Plus,X,Trash2,ExternalLink,AlertTriangle}from'lucide-react';
export default function ShippingPartners(){const{currentStore}=useStoreManagement();const[companies,setCompanies]=useState([]);const[loading,setLoading]=useState(true);const[showAdd,setShowAdd]=useState(false);const[form,setForm]=useState({name:'',api_key:'',base_rate:''});
const load=()=>{if(!currentStore?.id)return;api.get(`/manage/stores/${currentStore.id}/delivery-companies`).then(r=>setCompanies(r.data||[])).catch(()=>{}).finally(()=>setLoading(false));};
useEffect(()=>{load();},[currentStore?.id]);
const add=async()=>{if(!form.name)return toast.error('Name required');try{await api.post(`/manage/stores/${currentStore.id}/delivery-companies`,form);toast.success('Added!');setShowAdd(false);setForm({name:'',api_key:'',base_rate:''});load();}catch{toast.error('Failed');}};
return(<DashboardLayout>
<div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">Delivery Companies</h1><p className="text-sm text-gray-400 mt-1">Manage your shipping partners</p></div><button onClick={()=>setShowAdd(true)} className="btn-primary flex items-center gap-2 text-sm"><Plus size={16}/>Add Company</button></div>
<div className="glass-card-solid p-5 bg-amber-50 border border-amber-200 mb-6 flex items-start gap-3"><AlertTriangle size={18} className="text-amber-500 mt-0.5 shrink-0"/><div><p className="font-bold text-sm text-amber-800">API Integration Coming Soon</p><p className="text-xs text-amber-700 mt-1">Direct API integration with Yalidine, NOEST, ZR Express and others is under development. For now, add your delivery partners manually and manage shipping via their platforms.</p></div></div>
{loading?<div className="py-20 text-center"><div className="w-8 h-8 border-3 border-gray-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>:companies.length===0?<div className="glass-card-solid p-16 text-center"><Truck size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500 font-medium">No delivery companies added yet</p><p className="text-sm text-gray-400 mt-1">Click "Add Company" to register your shipping partners</p></div>:<div className="grid grid-cols-2 lg:grid-cols-3 gap-4">{companies.map(c=><div key={c.id} className="glass-card-solid p-5"><div className="flex items-center gap-3 mb-3"><div className="w-12 h-12 rounded-xl bg-brand-50 flex items-center justify-center text-brand-600 font-bold text-lg">{(c.name||'?')[0].toUpperCase()}</div><div><p className="font-bold text-gray-800">{c.name}</p><p className="text-xs text-gray-400">{c.api_key?'API Connected':'Manual'}</p></div></div>{c.base_rate&&<p className="text-sm text-gray-500">Base rate: <span className="font-bold">{c.base_rate} DZD</span></p>}<div className="mt-3 flex items-center gap-2"><span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${c.api_key?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{c.api_key?'CONNECTED':'MANUAL'}</span></div></div>)}</div>}
{showAdd&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowAdd(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">Add Delivery Company</h2><button onClick={()=>setShowAdd(false)}><X size={20}/></button></div><div className="space-y-3"><div><label className="input-label">Company Name *</label><input className="input-field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Yalidine, NOEST, etc."/></div><div><label className="input-label">API Key (optional)</label><input className="input-field font-mono" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} placeholder="Leave empty for manual"/></div><div><label className="input-label">Base Rate (DZD)</label><input type="number" className="input-field" value={form.base_rate} onChange={e=>setForm({...form,base_rate:e.target.value})}/></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowAdd(false)} className="btn-ghost flex-1">Cancel</button><button onClick={add} className="btn-primary flex-1">Add Company</button></div></div></div>}
</DashboardLayout>);}
