import React,{useState,useEffect} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useStoreManagement}from'../../hooks/useStore';import{productApi,orderApi}from'../../utils/api';import toast from'react-hot-toast';import{Package,AlertTriangle,Search,RefreshCw,Save,Check}from'lucide-react';
export default function StockManager(){
  const{currentStore}=useStoreManagement();
  const[products,setProducts]=useState([]);const[loading,setLoading]=useState(true);
  const[search,setSearch]=useState('');const[editingId,setEditingId]=useState(null);const[editVal,setEditVal]=useState(0);
  const[filter,setFilter]=useState('all');
  const load=()=>{if(!currentStore?.id)return;setLoading(true);productApi.getAll(currentStore.id,{}).then(r=>setProducts(r.data.products||[])).catch(()=>{}).finally(()=>setLoading(false));};
  useEffect(()=>{load();},[currentStore?.id]);
  const saveStock=async(pid)=>{try{await orderApi.updateStock(currentStore.id,pid,{stock_quantity:editVal});toast.success('Stock updated!');setEditingId(null);load();}catch{toast.error('Failed');}};
  const lowThreshold=parseInt(currentStore?.low_stock_threshold)||5;
  let filtered=products.filter(p=>!search||(p.name_en||p.name||'').toLowerCase().includes(search.toLowerCase()));
  if(filter==='low')filtered=filtered.filter(p=>(p.stock_quantity||0)<=lowThreshold&&(p.stock_quantity||0)>0);
  if(filter==='out')filtered=filtered.filter(p=>(p.stock_quantity||0)===0);
  if(filter==='in')filtered=filtered.filter(p=>(p.stock_quantity||0)>lowThreshold);
  const totalSku=products.length;const outOfStock=products.filter(p=>(p.stock_quantity||0)===0).length;const lowStock=products.filter(p=>(p.stock_quantity||0)<=lowThreshold&&(p.stock_quantity||0)>0).length;
  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">Stock Manager</h1><p className="text-sm text-gray-400 mt-1">Click any stock number to edit inline</p></div><button onClick={load} className="btn-ghost text-sm flex items-center gap-1"><RefreshCw size={14}/>Refresh</button></div>
    <div className="grid grid-cols-4 gap-4 mb-6"><div className="glass-card-solid p-4 cursor-pointer hover:ring-2 hover:ring-brand-400" onClick={()=>setFilter('all')}><p className="text-xs text-gray-400">Total Products</p><p className="text-2xl font-black">{totalSku}</p></div><div className="glass-card-solid p-4 cursor-pointer hover:ring-2 hover:ring-emerald-400" onClick={()=>setFilter('in')}><p className="text-xs text-gray-400">In Stock</p><p className="text-2xl font-black text-emerald-600">{totalSku-outOfStock-lowStock}</p></div><div className="glass-card-solid p-4 cursor-pointer hover:ring-2 hover:ring-amber-400" onClick={()=>setFilter('low')}><p className="text-xs text-gray-400">Low Stock</p><p className="text-2xl font-black text-amber-600">{lowStock}</p></div><div className="glass-card-solid p-4 cursor-pointer hover:ring-2 hover:ring-red-400" onClick={()=>setFilter('out')}><p className="text-xs text-gray-400">Out of Stock</p><p className="text-2xl font-black text-red-600">{outOfStock}</p></div></div>
    <div className="relative max-w-sm mb-4"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input-field !pl-9 !py-2 text-sm" placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
    {loading?<div className="py-20 text-center"><div className="w-8 h-8 border-3 border-gray-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>:filtered.length===0?<div className="glass-card-solid p-16 text-center"><Package size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500">No products found</p></div>:
    <div className="glass-card-solid overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs text-gray-400 uppercase"><th className="p-3">Product</th><th className="p-3">SKU</th><th className="p-3">Price</th><th className="p-3 text-center">Stock</th><th className="p-3">Status</th></tr></thead><tbody>{filtered.map(p=>{const stock=p.stock_quantity||0;const isLow=stock<=lowThreshold&&stock>0;const isOut=stock===0;return<tr key={p.id} className="border-t border-gray-50 hover:bg-gray-50"><td className="p-3"><div className="flex items-center gap-3">{p.thumbnail?<img src={p.thumbnail} className="w-10 h-10 rounded-lg object-cover"/>:<div className="w-10 h-10 rounded-lg bg-gray-100 flex items-center justify-center"><Package size={16} className="text-gray-300"/></div>}<div><p className="font-medium text-gray-800">{p.name_en||p.name}</p></div></div></td><td className="p-3 text-xs text-gray-400 font-mono">{p.sku||'-'}</td><td className="p-3 font-bold">{parseFloat(p.price).toLocaleString()} DZD</td><td className="p-3 text-center">{editingId===p.id?<div className="flex items-center justify-center gap-1"><input type="number" className="input-field !w-20 !py-1 text-center text-sm" value={editVal} onChange={e=>setEditVal(parseInt(e.target.value)||0)} autoFocus onKeyDown={e=>e.key==='Enter'&&saveStock(p.id)}/><button onClick={()=>saveStock(p.id)} className="p-1 bg-emerald-500 text-white rounded"><Check size={12}/></button></div>:<button onClick={()=>{setEditingId(p.id);setEditVal(stock);}} className={`font-bold text-lg cursor-pointer hover:underline ${isOut?'text-red-600':isLow?'text-amber-600':'text-gray-900'}`}>{stock}</button>}</td><td className="p-3">{isOut?<span className="flex items-center gap-1 text-xs font-bold text-red-600"><AlertTriangle size={12}/>OUT</span>:isLow?<span className="flex items-center gap-1 text-xs font-bold text-amber-600"><AlertTriangle size={12}/>LOW</span>:<span className="text-xs font-bold text-emerald-600">OK</span>}</td></tr>})}</tbody></table></div>}
  </DashboardLayout>);
}
