import React,{useState,useEffect} from'react';import{useTranslation}from'react-i18next';import{useStoreManagement}from'../../hooks/useStore';import DashboardLayout from'../../components/shared/DashboardLayout';import api from'../../utils/api';import toast from'react-hot-toast';import{Package,AlertTriangle,XCircle,TrendingUp,RefreshCw,Download,Save,Search,Minus,Plus}from'lucide-react';
export default function StockManager(){const{t}=useTranslation();const{currentStore}=useStoreManagement();const[products,setProducts]=useState([]);const[filter,setFilter]=useState('all');const[search,setSearch]=useState('');const[changes,setChanges]=useState({});
useEffect(()=>{if(!currentStore?.id)return;api.get(`/manage/stores/${currentStore.id}/products`).then(r=>setProducts(r.data.products||[])).catch(()=>{});},[currentStore?.id]);
const total=products.length;const low=products.filter(p=>(p.stock_quantity||0)>0&&(p.stock_quantity||0)<=10).length;const oos=products.filter(p=>(p.stock_quantity||0)===0).length;const inStock=total-oos;
const filtered=products.filter(p=>{if(filter==='low')return(p.stock_quantity||0)>0&&(p.stock_quantity||0)<=10;if(filter==='out')return(p.stock_quantity||0)===0;return true;}).filter(p=>!search||((p.name_en||p.name||'')+(p.sku||'')).toLowerCase().includes(search.toLowerCase()));
const updateStock=(id,delta)=>{const curr=changes[id]||products.find(p=>p.id===id)?.stock_quantity||0;setChanges({...changes,[id]:Math.max(0,curr+delta)});};
const setStock=(id,val)=>setChanges({...changes,[id]:Math.max(0,parseInt(val)||0)});
const getStock=(p)=>changes[p.id]!==undefined?changes[p.id]:(p.stock_quantity||0);
const saveAll=async()=>{for(const[id,qty]of Object.entries(changes)){try{await api.put(`/manage/stores/${currentStore.id}/products/${id}`,{stock_quantity:qty});}catch(e){}}toast.success('Stock updated!');setChanges({});api.get(`/manage/stores/${currentStore.id}/products`).then(r=>setProducts(r.data.products||[])).catch(()=>{});};
const getThumb=(p)=>{if(p.thumbnail)return p.thumbnail;if(Array.isArray(p.images)&&p.images.length)return typeof p.images[0]==='string'?p.images[0]:null;return null;};
return(<DashboardLayout><div className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-brand-50 flex items-center justify-center"><Package size={24} className="text-brand-500"/></div><div><h1 className="page-header">Stock Manager</h1><p className="text-sm text-gray-400">Centralized inventory control and monitoring</p></div></div><div className="flex gap-2"><button className="btn-ghost text-sm flex items-center gap-1"><Download size={14}/>Export CSV</button><button className="btn-ghost text-sm flex items-center gap-1" onClick={()=>window.location.reload()}><RefreshCw size={14}/>Refresh</button>{Object.keys(changes).length>0&&<button onClick={saveAll} className="btn-primary text-sm flex items-center gap-1"><Save size={14}/>Save Changes</button>}</div></div>
<div className="grid grid-cols-4 gap-4 mb-6">{[{l:'TOTAL PRODUCTS',v:total,d:`${total} units total`,icon:Package,cls:'bg-white'},{l:'LOW STOCK',v:low,d:'≤10 units',icon:AlertTriangle,cls:'bg-white',tc:'text-amber-500'},{l:'OUT OF STOCK',v:oos,d:'Needs restocking',icon:XCircle,cls:'bg-white',tc:'text-red-500'},{l:'IN STOCK',v:inStock,d:'Ready to sell',icon:TrendingUp,cls:'bg-gradient-to-r from-brand-500 to-purple-500 text-white'}].map((c,i)=>{const I=c.icon;return(<div key={i} className={`rounded-2xl p-5 border border-gray-100 shadow-sm ${c.cls}`}><div className="flex items-center justify-between mb-2"><p className={`text-[10px] font-bold uppercase tracking-wider ${c.cls.includes('gradient')?'text-white/70':'text-gray-400'}`}>{c.l}</p><I size={20} className={c.cls.includes('gradient')?'text-white/50':(c.tc||'text-brand-300')}/></div><p className={`text-3xl font-black ${c.cls.includes('gradient')?'text-white':'text-gray-900'}`}>{c.v}</p><p className={`text-xs mt-1 ${c.cls.includes('gradient')?'text-white/60':'text-gray-400'}`}>{c.d}</p></div>);})}</div>
<div className="glass-card-solid p-6"><div className="flex items-center gap-4 mb-4"><div className="relative flex-1 max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input-field !pl-9 !py-2 text-sm" placeholder="Search by product name, SKU, or variant..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="flex gap-2">{[{k:'all',l:'All Stock'},{k:'low',l:'Low Stock'},{k:'out',l:'Out Of Stock'}].map(f=>(<button key={f.k} onClick={()=>setFilter(f.k)} className={`px-4 py-2 rounded-full text-xs font-bold transition-all ${filter===f.k?'bg-brand-500 text-white':'bg-gray-100 text-gray-500 hover:bg-gray-200'}`}>{f.k==='low'&&'⚠ '}{f.k==='out'&&'🔴 '}{f.l}</button>))}</div></div>
<table className="w-full text-sm"><thead><tr className="text-left text-xs text-gray-400 uppercase"><th className="pb-3">Product</th><th className="pb-3">SKU</th><th className="pb-3">Category</th><th className="pb-3">Status</th><th className="pb-3">Stock Level</th><th className="pb-3">Actions</th></tr></thead><tbody>{filtered.map(p=>{const stk=getStock(p);const changed=changes[p.id]!==undefined;const thumb=getThumb(p);return(<tr key={p.id} className={`border-t border-gray-50 ${changed?'bg-brand-50/30':''}`}><td className="py-3"><div className="flex items-center gap-3">{thumb?<img src={thumb} className="w-10 h-10 rounded-lg object-cover"/>:<div className="w-10 h-10 rounded-lg bg-gray-100 flex items-center justify-center"><Package size={16} className="text-gray-300"/></div>}<span className="font-medium text-gray-800">{p.name_en||p.name}</span></div></td><td className="text-gray-400 font-mono text-xs">{p.sku||'-'}</td><td className="text-gray-500">{p.category_name||'Uncategorized'}</td><td>{stk===0?<span className="badge badge-danger text-[10px]">Out of Stock</span>:stk<=10?<span className="badge badge-warning text-[10px]">Low Stock</span>:<span className="badge badge-success text-[10px]">In Stock</span>}</td>
<td><div className="flex items-center gap-1"><button onClick={()=>updateStock(p.id,-1)} className="w-8 h-8 rounded-lg bg-gray-100 flex items-center justify-center hover:bg-gray-200"><Minus size={14}/></button><input type="number" className="w-16 text-center border border-gray-200 rounded-lg py-1 text-sm font-bold" value={stk} onChange={e=>setStock(p.id,e.target.value)}/><button onClick={()=>updateStock(p.id,1)} className="w-8 h-8 rounded-lg bg-gray-100 flex items-center justify-center hover:bg-gray-200"><Plus size={14}/></button></div></td>
<td><button onClick={()=>updateStock(p.id,10)} className="px-2 py-1 text-xs text-brand-600 bg-brand-50 rounded-lg font-bold hover:bg-brand-100">+10</button></td></tr>);})}</tbody></table>{filtered.length===0&&<p className="text-center py-12 text-gray-400">No products found</p>}</div>
</DashboardLayout>);}
