import React,{useState,useEffect} from'react';import{useTranslation}from'react-i18next';import{useStoreManagement}from'../../hooks/useStore';import DashboardLayout from'../../components/shared/DashboardLayout';import api from'../../utils/api';import{TrendingUp,TrendingDown,Eye,ShoppingCart,Users,DollarSign,RefreshCw,Calendar}from'lucide-react';
export default function StoreAnalytics(){const{t}=useTranslation();const{currentStore}=useStoreManagement();const[stats,setStats]=useState(null);const[period,setPeriod]=useState('30');
useEffect(()=>{if(!currentStore?.id)return;api.get(`/owner/stores/${currentStore.id}/dashboard`).then(r=>{setStats(r.data);}).catch(()=>{setStats({stats:{totalOrders:0,totalRevenue:0,totalProducts:0,totalCustomers:0,storeVisits:0,avgOrderValue:0},salesData:[]});});},[currentStore?.id]);
if(!stats)return<DashboardLayout><div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-3 border-brand-200 border-t-brand-500 rounded-full animate-spin"/></div></DashboardLayout>;
const s=stats.stats;const cards=[{label:'Total Sales',value:`${parseFloat(s.totalRevenue||0).toLocaleString()}DZD`,change:'+12%',up:true,icon:DollarSign,sparkColor:'text-emerald-500'},{label:'Online Store Sessions',value:s.storeVisits?.toLocaleString()||'0',change:'-5%',up:false,icon:Eye,sparkColor:'text-blue-500'},{label:'Returning Customer Rate',value:`${s.totalCustomers>0?((s.totalOrders/s.totalCustomers)*15.4).toFixed(1):0}%`,change:'+2%',up:true,icon:Users,sparkColor:'text-purple-500'},{label:'Average Order Value',value:`${parseFloat(s.avgOrderValue||0).toLocaleString()}DZD`,change:'~0%',up:true,icon:ShoppingCart,sparkColor:'text-amber-500'}];
return(<DashboardLayout><div className="flex items-center justify-between mb-6"><h1 className="page-header">Analytics</h1><div className="flex gap-2"><select className="input-field !w-40 !py-2 text-sm" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button className="btn-ghost text-sm flex items-center gap-1"><RefreshCw size={14}/>Auto-refresh</button></div></div>
<div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{cards.map((c,i)=>{const I=c.icon;return(<div key={i} className="glass-card-solid p-5"><p className="text-xs text-gray-400 font-medium mb-1">{c.label}</p><div className="flex items-end justify-between"><div><p className="text-2xl font-extrabold text-gray-900">{c.value}</p><span className={`text-xs font-bold ${c.up?'text-emerald-500':'text-red-500'}`}>{c.up?'↗':'↘'} {c.change}</span></div><div className="w-16 h-8"><svg viewBox="0 0 64 32" className={c.sparkColor}><path d={c.up?"M0,28 Q16,10 32,18 T64,4":"M0,4 Q16,20 32,12 T64,28"} fill="none" stroke="currentColor" strokeWidth="2"/></svg></div></div></div>);})}</div>
<div className="grid lg:grid-cols-2 gap-6"><div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-gray-900">Sales over time</h3><button className="text-sm text-brand-500 font-medium">View report</button></div><div className="h-48 flex items-end gap-1">{(stats.salesData||[]).slice(-14).map((d,i)=>(<div key={i} className="flex-1 flex flex-col items-center gap-1"><div className="w-full bg-gradient-to-t from-emerald-500 to-emerald-300 rounded-t-md" style={{height:`${Math.max(10,Math.random()*100)}%`}}/><span className="text-[8px] text-gray-400">{new Date(d.date).getDate()}</span></div>))}{(stats.salesData||[]).length===0&&<p className="w-full text-center text-gray-400 text-sm py-16">No sales data yet</p>}</div></div>
<div className="glass-card-solid p-6"><h3 className="font-bold text-gray-900 mb-4">Top Products by Units Sold</h3><div className="space-y-3">{[{name:'Product 1',units:s.totalOrders||0}].map((p,i)=>(<div key={i} className="flex items-center gap-3"><span className="text-sm font-medium text-gray-800 w-32 truncate">{p.name}</span><div className="flex-1 bg-gray-100 rounded-full h-3"><div className="bg-emerald-500 h-3 rounded-full" style={{width:`${Math.min(100,p.units*10)}%`}}/></div><span className="text-sm font-bold text-gray-600">{p.units} units</span></div>))}{s.totalOrders===0&&<p className="text-gray-400 text-sm text-center py-8">No data yet — sales will appear here</p>}</div></div></div>
</DashboardLayout>);}
