import React,{useState,useEffect} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useStoreManagement}from'../../hooks/useStore';import{orderApi}from'../../utils/api';import toast from'react-hot-toast';import{Plus,DollarSign,TrendingUp,Edit,Trash2,X,RefreshCw}from'lucide-react';
import { useTranslation } from 'react-i18next';
const CATS=['Operations','Marketing','Utilities','Inventory','Salaries','Rent','Shipping','Other'];
export default function StoreCosts(){
  const { t } = useTranslation();
  const{currentStore}=useStoreManagement();
  const[expenses,setExpenses]=useState([]);const[loading,setLoading]=useState(true);
  const[showModal,setShowModal]=useState(false);const[editing,setEditing]=useState(null);
  const[form,setForm]=useState({description:'',category:'Other',amount:'',date:new Date().toISOString().split('T')[0],status:'Paid'});
  const load=()=>{if(!currentStore?.id)return;setLoading(true);orderApi.getExpenses(currentStore.id).then(r=>setExpenses(r.data||[])).catch(()=>{}).finally(()=>setLoading(false));};
  useEffect(()=>{load();},[currentStore?.id]);
  const save=async()=>{if(!form.description||!form.amount)return toast.error(t('storePage.descAmountRequired','Description and amount required'));try{if(editing){await orderApi.updateExpense(currentStore.id,editing.id,form);toast.success(t('storePage.updated','Updated!'));}else{await orderApi.addExpense(currentStore.id,form);toast.success(t('storePage.added','Added!'));}setShowModal(false);setEditing(null);setForm({description:'',category:'Other',amount:'',date:new Date().toISOString().split('T')[0],status:'Paid'});load();}catch(e){toast.error(e.response?.data?.error||t('storePage.failed','Failed'));}};
  const del=async(id)=>{if(!confirm(t('storePage.deleteConfirm','Delete?')))return;try{await orderApi.deleteExpense(currentStore.id,id);toast.success(t('storePage.deleted','Deleted'));load();}catch{toast.error(t('storePage.failed','Failed'));}};
  const edit=(e)=>{setEditing(e);setForm({description:e.description,category:e.category,amount:e.amount,date:e.date?.split('T')[0]||'',status:e.status});setShowModal(true);};
  const total=expenses.reduce((s,e)=>s+parseFloat(e.amount||0),0);
  const thisMonth=expenses.filter(e=>{const d=new Date(e.date);const now=new Date();return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();}).reduce((s,e)=>s+parseFloat(e.amount||0),0);
  const byCat={};expenses.forEach(e=>{byCat[e.category]=(byCat[e.category]||0)+parseFloat(e.amount||0);});
  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">{t('storePage.costsTitle','Costs & Expenses')}</h1><p className="text-sm text-gray-400 mt-1">{t('storePage.costsSubtitle','Track your business expenses')}</p></div><div className="flex gap-2"><button onClick={load} className="btn-ghost text-xs"><RefreshCw size={14}/></button><button onClick={()=>{setEditing(null);setForm({description:'',category:'Other',amount:'',date:new Date().toISOString().split('T')[0],status:'Paid'});setShowModal(true);}} className="btn-primary text-sm flex items-center gap-2"><Plus size={16}/>{t('storePage.addExpense','Add Expense')}</button></div></div>
    <div className="grid grid-cols-3 gap-4 mb-6"><div className="glass-card-solid p-5"><p className="text-xs text-gray-400">{t('storePage.totalExpenses','Total Expenses')}</p><p className="text-2xl font-black mt-1">{total.toLocaleString()} <span className="text-xs font-normal text-gray-400">{t('storePage.dzd','DZD')}</span></p></div><div className="glass-card-solid p-5"><p className="text-xs text-gray-400">{t('storePage.thisMonth','This Month')}</p><p className="text-2xl font-black mt-1">{thisMonth.toLocaleString()} <span className="text-xs font-normal text-gray-400">{t('storePage.dzd','DZD')}</span></p></div><div className="glass-card-solid p-5"><p className="text-xs text-gray-400">{t('storePage.entries','Entries')}</p><p className="text-2xl font-black mt-1">{expenses.length}</p></div></div>
    {Object.keys(byCat).length>0&&<div className="glass-card-solid p-4 mb-6"><p className="text-xs font-bold text-gray-400 uppercase mb-3">{t('storePage.byCategory','By Category')}</p><div className="flex flex-wrap gap-2">{Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([cat,amt])=><span key={cat} className="px-3 py-1.5 bg-gray-50 rounded-xl text-sm"><span className="font-bold text-gray-700">{cat}</span> <span className="text-gray-400">{amt.toLocaleString()} {t('storePage.dzd','DZD')}</span></span>)}</div></div>}
    {loading?<div className="py-20 text-center"><div className="w-8 h-8 border-3 border-gray-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>:expenses.length===0?<div className="glass-card-solid p-16 text-center"><DollarSign size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500">{t('storePage.noExpenses','No expenses recorded')}</p></div>:
    <div className="glass-card-solid overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs text-gray-400 uppercase"><th className="p-3">{t('storePage.date','Date')}</th><th className="p-3">{t('storePage.description','Description')}</th><th className="p-3">{t('storePage.category','Category')}</th><th className="p-3">{t('storePage.amount','Amount')}</th><th className="p-3">{t('storePage.status','Status')}</th><th className="p-3"></th></tr></thead><tbody>{expenses.map(e=><tr key={e.id} className="border-t border-gray-50 hover:bg-gray-50"><td className="p-3 text-xs text-gray-500">{e.date?.split('T')[0]}</td><td className="p-3 font-medium text-gray-800">{e.description}</td><td className="p-3"><span className="px-2 py-0.5 bg-gray-100 rounded text-xs text-gray-600">{e.category}</span></td><td className="p-3 font-bold">{parseFloat(e.amount).toLocaleString()} {t('storePage.dzd','DZD')}</td><td className="p-3"><span className={`text-xs font-bold ${e.status==='Paid'?'text-emerald-600':'text-amber-600'}`}>{e.status}</span></td><td className="p-3"><div className="flex gap-1"><button onClick={()=>edit(e)} className="p-1.5 hover:bg-gray-100 rounded"><Edit size={14} className="text-gray-400"/></button><button onClick={()=>del(e.id)} className="p-1.5 hover:bg-red-50 rounded"><Trash2 size={14} className="text-red-400"/></button></div></td></tr>)}</tbody></table></div>}
    {showModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowModal(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">{editing?t('storePage.edit','Edit'):t('storePage.add','Add')} {t('storePage.expense','Expense')}</h2><button onClick={()=>setShowModal(false)}><X size={20}/></button></div><div className="space-y-4"><div><label className="input-label">{t('storePage.descriptionRequired','Description *')}</label><input className="input-field" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="input-label">{t('storePage.amountDzdRequired','Amount (DZD) *')}</label><input type="number" className="input-field" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div><label className="input-label">{t('storePage.date','Date')}</label><input type="date" className="input-field" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div></div><div className="grid grid-cols-2 gap-3"><div><label className="input-label">{t('storePage.category','Category')}</label><select className="input-field" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATS.map(c=><option key={c} value={c}>{c}</option>)}</select></div><div><label className="input-label">{t('storePage.status','Status')}</label><select className="input-field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="Paid">{t('storePage.paid','Paid')}</option><option value="Pending">{t('storePage.pending','Pending')}</option><option value="Overdue">{t('storePage.overdue','Overdue')}</option></select></div></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowModal(false)} className="btn-ghost flex-1">{t('storePage.cancel','Cancel')}</button><button onClick={save} className="btn-primary flex-1">{editing?t('storePage.update','Update'):t('storePage.add','Add')}</button></div></div></div>}
  </DashboardLayout>);
}
