import React, { useState, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { ownerApi } from '../../utils/api';
import { useStoreManagement, useAuthStore } from '../../hooks/useStore';
import DashboardLayout from '../../components/shared/DashboardLayout';
import toast from 'react-hot-toast';
import api from '../../utils/api';
import { Save,Store,Palette,CreditCard,Truck,Bot,Upload,Globe,Users,ShoppingCart,Settings as SI,Bell,BarChart3,Shield,Tag,Code,Type,MessageSquare,Eye,Trash2,Plus,Check,Layout,Sliders,Zap,Lock,Package,Percent,AlertTriangle,Mail,Smartphone,QrCode,Copy,ExternalLink,RefreshCw,Key,User,Activity,Hash,TrendingUp } from 'lucide-react';

const themes=[{id:'classic',name:'Classic Store',desc:'PROFESSIONAL & CLEAN',c:'#7C3AED'},{id:'nova-dark',name:'Nova Dark',desc:'FUTURISTIC & SLEEK',c:'#8B5CF6'},{id:'enterprise',name:'Enterprise',desc:'DENSE & FUNCTIONAL',c:'#3B82F6'},{id:'ocean-bloom',name:'Ocean Bloom',desc:'SOFT & FRIENDLY',c:'#06B6D4'},{id:'nzxt-pro',name:'NZXT Pro',desc:'HIGH CONTRAST',c:'#A855F7'},{id:'moonlight',name:'Moonlight',desc:'ETHEREAL & CALM',c:'#818CF8'}];
const brandColors=['#10B981','#06B6D4','#3B82F6','#6366F1','#8B5CF6','#A855F7','#D946EF','#EC4899','#F43F5E','#EF4444','#F97316','#EAB308','#84CC16','#22C55E','#14B8A6','#0EA5E9'];
const roles={admin:{label:'Admin',desc:'Full access',color:'bg-brand-500',perms:['View Dashboard','View Orders','Manage Orders','Delete Orders','Confirm Orders','Prepare Orders','View Products','Manage Products','View Customers','Manage Customers']},manager:{label:'Manager',desc:'Orders + Customers',color:'bg-blue-500',perms:['View Dashboard','View Orders','Manage Orders','Confirm Orders','View Products','View Customers']},staff:{label:'Staff',desc:'Orders only',color:'bg-emerald-500',perms:['View Orders','Manage Orders','View Products','View Customers']},viewer:{label:'Viewer',desc:'Read-only',color:'bg-gray-500',perms:['View Dashboard','View Orders','View Products']},confirmer:{label:'Confirmer',desc:'Validate orders',color:'bg-green-500',perms:['View Orders','Confirm Orders','View Customers']}};

// Section header component — left accent border style
const SH=({icon:Icon,title,subtitle,accent='brand'})=>{const colors={brand:'border-brand-500 bg-brand-50',blue:'border-blue-500 bg-blue-50',emerald:'border-emerald-500 bg-emerald-50',amber:'border-amber-500 bg-amber-50',red:'border-red-500 bg-red-50',purple:'border-purple-500 bg-purple-50',orange:'border-orange-500 bg-orange-50',gray:'border-gray-500 bg-gray-50'};return(<div className={`border-l-4 ${colors[accent]||colors.brand} rounded-r-xl p-4 flex items-center gap-3`}><Icon size={22} className="text-gray-700"/><div><h3 className="font-bold text-gray-900">{title}</h3>{subtitle&&<p className="text-xs text-gray-500 mt-0.5">{subtitle}</p>}</div></div>);};
// Stat pill
const SP=({label,value,color='brand'})=>{const bg={brand:'bg-brand-100 text-brand-700',emerald:'bg-emerald-100 text-emerald-700',blue:'bg-blue-100 text-blue-700',amber:'bg-amber-100 text-amber-700',red:'bg-red-100 text-red-700',purple:'bg-purple-100 text-purple-700'};return(<div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full ${bg[color]||bg.brand}`}><span className="text-xs font-medium">{label}</span><span className="font-black text-sm">{value}</span></div>);};

function SubscriptionSection(){
  const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
  const[selectedPlan,setSelectedPlan]=useState(null);const[period,setPeriod]=useState('monthly');
  const[showPay,setShowPay]=useState(false);const[receipt,setReceipt]=useState('');const[submitting,setSubmitting]=useState(false);
  const fileRef=React.useRef(null);
  const load=()=>{setLoading(true);ownerApi.getSubscription().then(r=>setData(r.data)).catch(()=>{}).finally(()=>setLoading(false));};
  React.useEffect(()=>{load();},[]);
  const uploadReceipt=(e)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setReceipt(r.result);r.readAsDataURL(f);};
  const submitPayment=async()=>{if(!receipt)return toast.error('Upload receipt first');if(!selectedPlan)return toast.error('Select a plan');setSubmitting(true);try{const price=period==='yearly'?data.plans[selectedPlan].yearly:data.plans[selectedPlan].monthly;await ownerApi.paySubscription({plan:selectedPlan,period,amount:price,payment_method:'ccp',receipt_image:receipt});toast.success('Payment submitted! Waiting for approval.');setShowPay(false);setReceipt('');setSelectedPlan(null);load();}catch(e){toast.error(e.response?.data?.error||'Failed');}setSubmitting(false);};
  const copy=(t)=>{navigator.clipboard.writeText(t);toast.success('Copied!');};
  if(loading)return<div className="py-12 text-center"><div className="w-8 h-8 border-3 border-gray-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>;
  const plans=data?.plans||{};const isActive=data?.status==='active';const isSuspended=data?.status==='suspended';
  const expDate=data?.expires_at?new Date(data.expires_at).toLocaleDateString():null;
  return(<>
    {/* Status */}
    <div className={`glass-card-solid p-6 ${isSuspended?'border-2 border-red-300 bg-red-50':''}`}><div className="flex items-center justify-between"><div className="flex items-center gap-4"><div className={`w-12 h-12 rounded-2xl flex items-center justify-center ${isSuspended?'bg-red-500':'bg-brand-500'} text-white`}><Zap size={20}/></div><div><p className="text-[10px] text-gray-400 uppercase font-bold">Current Plan</p><p className="text-xl font-black capitalize">{data?.plan||'Free'}</p></div></div><div className="text-right"><span className={`px-3 py-1 rounded-full text-xs font-bold ${isSuspended?'bg-red-500 text-white':isActive?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{isSuspended?'SUSPENDED':isActive?'ACTIVE':'FREE'}</span>{expDate&&<p className="text-xs text-gray-400 mt-1">Expires: {expDate}</p>}</div></div>{isSuspended&&<div className="mt-4 p-3 bg-red-100 rounded-xl text-sm text-red-700 font-medium">Your subscription is suspended. Renew below to restore access.</div>}</div>
    {/* Period toggle */}
    <div className="flex items-center justify-center gap-3 mt-4"><button onClick={()=>setPeriod('monthly')} className={`px-6 py-2 rounded-xl text-sm font-bold ${period==='monthly'?'bg-brand-500 text-white':'bg-gray-100 text-gray-500'}`}>Monthly</button><button onClick={()=>setPeriod('yearly')} className={`px-6 py-2 rounded-xl text-sm font-bold ${period==='yearly'?'bg-brand-500 text-white':'bg-gray-100 text-gray-500'}`}>Yearly <span className="text-[10px] opacity-70">Save 20%</span></button></div>
    {/* Plans */}
    <div className="grid grid-cols-2 gap-4 mt-4">{Object.entries(plans).map(([key,plan])=>{const price=period==='yearly'?plan.yearly:plan.monthly;const isCurrent=data?.plan===key&&isActive;return(<div key={key} className={`glass-card-solid p-5 relative ${key==='advanced'?'ring-2 ring-brand-400':''}`}>{key==='advanced'&&<div className="absolute top-0 right-0 bg-brand-500 text-white text-[9px] font-bold px-2 py-0.5 rounded-bl-xl">POPULAR</div>}<h3 className="font-bold text-lg">{plan.name}</h3><div className="mt-2 flex items-baseline gap-1"><span className="text-2xl font-black text-brand-600">{price.toLocaleString()}</span><span className="text-gray-400 text-xs">DZD/{period==='yearly'?'yr':'mo'}</span></div><div className="mt-3 space-y-1.5">{plan.features.map((f,i)=><div key={i} className="flex items-center gap-2 text-xs"><Check size={12} className="text-emerald-500 shrink-0"/><span className="text-gray-600">{f}</span></div>)}</div><button onClick={()=>{if(!isCurrent){setSelectedPlan(key);setShowPay(true);}}} disabled={isCurrent} className={`w-full mt-4 py-2.5 rounded-xl font-bold text-sm ${isCurrent?'bg-emerald-100 text-emerald-700':'bg-brand-500 text-white hover:bg-brand-600'}`}>{isCurrent?'Current Plan':'Subscribe'}</button></div>);})}</div>
    {/* Payment history */}
    {data?.payments?.length>0&&<div className="glass-card-solid p-5 mt-4"><h3 className="font-bold text-sm mb-3">Payment History</h3><div className="space-y-2">{data.payments.slice(0,5).map(p=><div key={p.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-xl"><div><p className="text-sm font-medium capitalize">{p.plan} — {p.period}</p><p className="text-[10px] text-gray-400">{new Date(p.created_at).toLocaleDateString()}</p></div><div className="text-right"><p className="font-bold text-sm">{parseFloat(p.amount).toLocaleString()} DZD</p><span className={`text-[10px] font-bold ${p.status==='approved'?'text-emerald-600':p.status==='rejected'?'text-red-600':'text-amber-600'}`}>{p.status?.toUpperCase()}</span></div></div>)}</div></div>}
    {/* Pay modal */}
    {showPay&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowPay(false)}><div className="bg-white rounded-3xl p-6 w-full max-w-md max-h-[85vh] overflow-y-auto shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-bold">Subscribe — {plans[selectedPlan]?.name}</h2><button onClick={()=>setShowPay(false)}>✕</button></div><div className="p-4 bg-brand-50 rounded-xl text-center mb-4"><p className="text-3xl font-black text-brand-600">{(period==='yearly'?plans[selectedPlan]?.yearly:plans[selectedPlan]?.monthly)?.toLocaleString()} DZD</p><p className="text-xs text-gray-400 capitalize">{period}</p></div>
    {data?.billing_ccp&&<div className="p-4 bg-gray-50 rounded-xl mb-3"><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">CCP Transfer</p><div className="flex items-center justify-between"><div><p className="font-mono font-bold">{data.billing_ccp}</p><p className="text-xs text-gray-400">{data.billing_ccp_name}</p></div><button onClick={()=>copy(data.billing_ccp)} className="p-1.5 hover:bg-gray-200 rounded"><Copy size={14}/></button></div></div>}
    {data?.billing_baridimob_rip&&<div className="p-4 bg-gray-50 rounded-xl mb-3"><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">BaridiMob</p><div className="flex items-center justify-between"><p className="font-mono font-bold">{data.billing_baridimob_rip}</p><button onClick={()=>copy(data.billing_baridimob_rip)} className="p-1.5 hover:bg-gray-200 rounded"><Copy size={14}/></button></div>{data.billing_baridimob_qr&&<img src={data.billing_baridimob_qr} className="w-36 mx-auto mt-3 rounded-xl border"/>}</div>}
    {!data?.billing_ccp&&!data?.billing_baridimob_rip&&<div className="p-4 bg-amber-50 rounded-xl mb-3 text-center"><p className="text-sm text-amber-700">Payment details not configured yet. Contact the platform admin.</p></div>}
    <div className="mb-4"><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">Upload Receipt</p>{receipt?<div className="relative"><img src={receipt} className="w-full rounded-xl border"/><button onClick={()=>setReceipt('')} className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full"><span className="text-xs">✕</span></button></div>:<div className="border-2 border-dashed border-gray-300 rounded-xl p-6 text-center cursor-pointer hover:border-brand-400" onClick={()=>fileRef.current?.click()}><Upload size={20} className="mx-auto text-gray-400 mb-1"/><p className="text-xs text-gray-500">Upload payment screenshot</p></div>}<input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={uploadReceipt}/></div>
    <button onClick={submitPayment} disabled={submitting||!receipt} className="btn-primary w-full py-3 disabled:opacity-50">{submitting?'Submitting...':'Submit Payment'}</button><p className="text-[10px] text-gray-400 text-center mt-2">Reviewed within 24 hours</p></div></div>}
  </>);
}

export default function StoreSettings(){
  const{t}=useTranslation();const{currentStore,setCurrentStore}=useStoreManagement();const{user,logout}=useAuthStore();
  const[s,setS]=useState({});const[sec,setSec]=useState('store-details');const[loading,setLoading]=useState(false);
  const[staff,setStaff]=useState([]);const[wilayas,setWilayas]=useState([]);const[showRole,setShowRole]=useState(null);
  const[showStaff,setShowStaff]=useState(false);const[sf,setSf]=useState({name:'',email:'',phone:'',password:'',role:'viewer'});
  const logoR=useRef(null);const coverR=useRef(null);
  const[profile,setProfile]=useState({full_name:'',email:'',phone:'',username:'',two_fa_enabled:false});
  const[pwForm,setPwForm]=useState({current_password:'',new_password:'',confirm_password:''});
  const[usernameEdit,setUsernameEdit]=useState(false);const[emailEdit,setEmailEdit]=useState(false);
  const[emailPw,setEmailPw]=useState('');const[newEmail,setNewEmail]=useState('');const[newUsername,setNewUsername]=useState('');
  const[deleteConfirm,setDeleteConfirm]=useState(false);const[deletePw,setDeletePw]=useState('');const[profileLoading,setProfileLoading]=useState(false);
  const[qrGenerated,setQrGenerated]=useState(false);const[showPwSection,setShowPwSection]=useState(false);

  useEffect(()=>{if(currentStore){setS({...currentStore,theme:currentStore.theme||'classic'});loadData();}},[currentStore?.id]);
  useEffect(()=>{if(sec==='account')loadProfile();},[sec]);
  const loadData=()=>{if(!currentStore?.id)return;api.get(`/owner/stores/${currentStore.id}/staff`).then(r=>setStaff(r.data)).catch(()=>{});api.get(`/manage/stores/${currentStore.id}/shipping-wilayas`).then(r=>setWilayas(r.data)).catch(()=>{});};
  const loadProfile=async()=>{try{const{data}=await ownerApi.getProfile();setProfile(data);setNewUsername(data.username||'');setNewEmail(data.email||'');}catch(e){}};
  const save=async()=>{setLoading(true);try{const{data}=await ownerApi.updateStore(currentStore.id,s);setCurrentStore(data);toast.success('Saved ✓');}catch{toast.error('Failed');}setLoading(false);};
  const set=(k)=>(e)=>setS({...s,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
  const setV=(k,v)=>setS({...s,[k]:v});
  const imgUp=(field,sz=400)=>(e)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const i=new window.Image();i.onload=()=>{const c=document.createElement('canvas');c.width=sz;c.height=sz;c.getContext('2d').drawImage(i,0,0,sz,sz);setS({...s,[field]:c.toDataURL('image/jpeg',0.7)});toast.success('Uploaded!');};i.src=r.result;};r.readAsDataURL(f);};
  const seedW=async()=>{try{await api.post(`/manage/stores/${currentStore.id}/shipping-wilayas/seed`);toast.success('58 wilayas loaded!');loadData();}catch{toast.error('Failed');}};
  const addStaff=async()=>{try{await api.post(`/owner/stores/${currentStore.id}/staff`,sf);toast.success('Added!');setShowStaff(false);setSf({name:'',email:'',phone:'',password:'',role:'viewer'});loadData();}catch{toast.error('Failed');}};
  const saveProfile=async()=>{setProfileLoading(true);try{await ownerApi.updateProfile({full_name:profile.full_name,phone:profile.phone});toast.success('Profile updated!');}catch{toast.error('Failed');}setProfileLoading(false);};
  const saveUsername=async()=>{try{await ownerApi.updateUsername({username:newUsername});setProfile({...profile,username:newUsername});setUsernameEdit(false);toast.success('Username updated!');}catch(e){toast.error(e.response?.data?.error||'Failed');}};
  const saveEmail=async()=>{try{await ownerApi.updateEmail({email:newEmail,password:emailPw});setProfile({...profile,email:newEmail});setEmailEdit(false);setEmailPw('');toast.success('Email updated!');}catch(e){toast.error(e.response?.data?.error||'Failed');}};
  const changePassword=async()=>{if(pwForm.new_password!==pwForm.confirm_password)return toast.error('Passwords do not match');try{await ownerApi.updatePassword({current_password:pwForm.current_password,new_password:pwForm.new_password});setPwForm({current_password:'',new_password:'',confirm_password:''});setShowPwSection(false);toast.success('Password updated!');}catch(e){toast.error(e.response?.data?.error||'Failed');}};
  const toggleTwoFa=async()=>{try{const{data}=await ownerApi.toggleTwoFa({enabled:!profile.two_fa_enabled});setProfile({...profile,two_fa_enabled:data.two_fa_enabled});toast.success(data.two_fa_enabled?'2FA enabled!':'2FA disabled');}catch{toast.error('Failed');}};
  const deleteAccount=async()=>{try{await ownerApi.deleteAccount({password:deletePw});toast.success('Account deleted');logout();window.location.href='/';}catch(e){toast.error(e.response?.data?.error||'Failed');}};

  const T=({label,desc,checked,onChange})=>(<label className="flex items-center justify-between p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors"><div><p className="font-medium text-sm text-gray-800">{label}</p>{desc&&<p className="text-xs text-gray-400 mt-0.5">{desc}</p>}</div><div className={`w-11 h-6 rounded-full transition-colors ${checked?'bg-brand-500':'bg-gray-300'} relative`}><div className={`absolute top-0.5 w-5 h-5 bg-white rounded-full shadow-md transition-transform ${checked?'translate-x-5':'translate-x-0.5'}`}/></div><input type="checkbox" className="sr-only" checked={checked||false} onChange={onChange}/></label>);
  const secs=[{id:'store-details',icon:Store,l:'Store Details'},{id:'customization',icon:Palette,l:'Customization'},{id:'dashboard-config',icon:Layout,l:'Dashboard'},{id:'users',icon:Users,l:'Users & Permissions'},{id:'checkout',icon:ShoppingCart,l:'Checkout'},{id:'shipping',icon:Truck,l:'Shipping'},{id:'payments',icon:CreditCard,l:'Payments'},{id:'taxes',icon:Percent,l:'Taxes'},{id:'notifications',icon:Bell,l:'Notifications'},{id:'orders-config',icon:Package,l:'Orders'},{id:'customers-config',icon:Users,l:'Customers'},{id:'inventory',icon:BarChart3,l:'Inventory'},{id:'marketing',icon:Tag,l:'Marketing & Pixels'},{id:'domains',icon:Globe,l:'Domains'},{id:'ai',icon:Bot,l:'AI Messaging'},{id:'subscription',icon:Zap,l:'Subscription'},{id:'account',icon:SI,l:'Account'}];
  const storeDomain=currentStore?.slug?`${currentStore.slug}.ender-store.com`:'';

  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><h1 className="page-header">{t('sidebar.settings')}</h1><button onClick={save} disabled={loading} className="btn-primary flex items-center gap-2 text-sm">{loading?<div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>:<Save size={16}/>}Save Changes</button></div>
    <div className="flex gap-6">
      <div className="w-56 shrink-0 space-y-0.5">{secs.map(x=>{const I=x.icon;return(<button key={x.id} onClick={()=>setSec(x.id)} className={`w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm font-medium transition-all text-left ${sec===x.id?'bg-brand-50 text-brand-600':'text-gray-500 hover:text-gray-700 hover:bg-gray-50'}`}><I size={16}/>{x.l}</button>);})}</div>
      <div className="flex-1 space-y-6 animate-fade-in">

{sec==='store-details'&&<><div className="grid lg:grid-cols-2 gap-6">
<div className="glass-card-solid p-6 space-y-4"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center"><Store size={20} className="text-brand-500"/></div><div><h3 className="font-bold text-gray-900">Store Identity</h3><p className="text-xs text-gray-400">Manage how your business appears to the world.</p></div></div><div><label className="input-label">Store Name</label><input className="input-field" value={s.name||s.store_name||''} onChange={e=>setS({...s,name:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label className="input-label">Store Phone</label><input className="input-field" value={s.contact_phone||''} onChange={set('contact_phone')}/></div><div><label className="input-label">Support Phone</label><input className="input-field" value={s.support_phone||''} onChange={set('support_phone')}/></div></div>
<p className="text-xs font-bold text-gray-400 uppercase tracking-wider pt-2">Brand Assets</p><div className="flex gap-4"><div><p className="text-xs font-semibold text-gray-600 mb-1">Store Logo</p><div className="w-24 h-24 rounded-xl bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden cursor-pointer hover:border-brand-400" onClick={()=>logoR.current?.click()}>{s.logo?<img src={s.logo} className="w-full h-full object-cover"/>:<Upload size={20} className="text-gray-400"/>}</div><input ref={logoR} type="file" accept="image/*" className="hidden" onChange={imgUp('logo')}/>{s.logo&&<p className="text-[10px] text-emerald-500 font-bold mt-1"><Check size={10} className="inline"/>READY</p>}</div><div><p className="text-xs font-semibold text-gray-600 mb-1">Cover Image</p><div className="w-36 h-24 rounded-xl bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden cursor-pointer hover:border-brand-400" onClick={()=>coverR.current?.click()}>{s.cover_image?<img src={s.cover_image} className="w-full h-full object-cover"/>:<div className="text-center"><Upload size={16} className="text-gray-400 mx-auto"/><p className="text-[10px] text-gray-400 mt-1">Click to upload</p></div>}</div><input ref={coverR} type="file" accept="image/*" className="hidden" onChange={imgUp('cover_image',800)}/></div></div></div>
<div className="glass-card-solid p-6 space-y-4"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center"><Globe size={20} className="text-cyan-500"/></div><div><h3 className="font-bold text-gray-900">Regional Settings</h3><p className="text-xs text-gray-400">CURRENCY & LANGUAGE</p></div></div><div><label className="input-label text-xs uppercase tracking-wider">Store Currency</label><select className="input-field" value={s.currency||'DZD'} onChange={set('currency')}><option value="DZD">DZD - Algerian Dinar</option><option value="EUR">EUR - Euro</option><option value="USD">USD - Dollar</option></select></div><div><label className="input-label text-xs uppercase tracking-wider">Default Language</label><div className="grid grid-cols-3 gap-3 mt-2">{[{c:'ar',l:'العربية',f:'🇩🇿'},{c:'fr',l:'Français',f:'🇫🇷'},{c:'en',l:'English',f:'🇬🇧'}].map(x=>(<button key={x.c} onClick={()=>setV('default_language',x.c)} className={`p-3 rounded-xl border-2 text-center transition-all ${(s.default_language||'en')===x.c?'border-brand-500 bg-brand-50':'border-gray-200 hover:border-gray-300'}`}><span className="text-2xl block mb-1">{x.f}</span><span className="text-xs font-semibold">{x.l}</span>{(s.default_language||'en')===x.c&&<Check size={14} className="text-brand-500 mx-auto mt-1"/>}</button>))}</div></div></div>
</div>
<div className="grid lg:grid-cols-2 gap-6"><div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center"><Globe size={20} className="text-blue-500"/></div><div><h3 className="font-bold text-gray-900">Social Media</h3><p className="text-xs text-gray-400">CONNECT YOUR PLATFORMS</p></div></div><input className="input-field" placeholder="Facebook Page URL" value={s.social_facebook||''} onChange={set('social_facebook')}/><input className="input-field" placeholder="Instagram Profile URL" value={s.social_instagram||''} onChange={set('social_instagram')}/><input className="input-field" placeholder="TikTok Profile URL" value={s.social_tiktok||''} onChange={set('social_tiktok')}/><input className="input-field" placeholder="YouTube Channel URL" value={s.youtube||''} onChange={set('youtube')}/></div>
<div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center"><BarChart3 size={20} className="text-purple-500"/></div><div><h3 className="font-bold text-gray-900">SEO</h3><p className="text-xs text-gray-400">IMPROVE VISIBILITY ON GOOGLE</p></div></div><div><label className="input-label text-xs">Homepage Title</label><input className="input-field" value={s.meta_title||''} onChange={set('meta_title')}/><p className="text-[10px] text-gray-400 mt-1">70 chars max</p></div><div><label className="input-label text-xs">Meta Description</label><textarea className="input-field" rows={3} value={s.meta_description||''} onChange={set('meta_description')}/><p className="text-[10px] text-gray-400 mt-1">160 chars max</p></div></div></div></>}

{sec==='customization'&&<><div className="glass-card-solid p-6"><div className="flex items-center gap-3 mb-4"><Palette size={20} className="text-brand-500"/><div><h3 className="font-bold text-gray-900">Design Studio</h3><p className="text-xs text-gray-400">Choose a starting point or craft your unique style.</p></div></div><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{themes.map(th=>(<button key={th.id} onClick={()=>setS({...s,theme:th.id,primary_color:th.c})} className={`p-4 rounded-xl border-2 text-left transition-all ${s.theme===th.id?'border-brand-500 bg-brand-50 ring-2 ring-brand-200':'border-gray-200 hover:border-gray-300'}`}><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg" style={{backgroundColor:th.c}}/><div><p className="font-bold text-sm">{th.name}</p><p className="text-[10px] text-gray-400 uppercase">{th.desc}</p></div></div>{s.theme===th.id&&<Check size={14} className="text-brand-500 mt-2"/>}</button>))}</div></div>
<div className="glass-card-solid p-6"><p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">Brand Essence</p><div className="grid lg:grid-cols-2 gap-6"><div><p className="text-sm font-bold text-gray-800 mb-2"><span className="text-red-500">*</span> Primary Brand Color</p><div className="flex flex-wrap gap-2 mb-3">{brandColors.map(c=>(<button key={c} onClick={()=>setV('primary_color',c)} className={`w-8 h-8 rounded-full transition-transform hover:scale-110 ${s.primary_color===c?'ring-2 ring-offset-2 ring-brand-500 scale-110':''}`} style={{backgroundColor:c}}/>))}</div><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg" style={{backgroundColor:s.primary_color||'#7C3AED'}}/><input className="input-field !w-32 text-sm" value={s.primary_color||'#7C3AED'} onChange={set('primary_color')}/></div></div><div><p className="text-sm font-bold text-gray-800 mb-2"><span className="text-red-500">*</span> Text Colors</p><div className="space-y-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gray-900"/><div><p className="text-[10px] text-gray-400 uppercase">Primary Text</p><input className="input-field !w-32 text-sm" value={s.text_color||'#202223'} onChange={set('text_color')}/></div></div><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gray-400"/><div><p className="text-[10px] text-gray-400 uppercase">Secondary Text</p><input className="input-field !w-32 text-sm" value={s.secondary_text||'#6d7175'} onChange={set('secondary_text')}/></div></div></div></div></div></div>
<div className="glass-card-solid p-6 space-y-3"><p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Advanced Config</p><div className="grid grid-cols-2 gap-3"><T label="Sticky Header" checked={s.sticky_header!==false} onChange={e=>setV('sticky_header',e.target.checked)}/><T label="Page Transitions" checked={s.page_transitions!==false} onChange={e=>setV('page_transitions',e.target.checked)}/></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><Type size={16}/><h4 className="font-bold text-sm">Button Text</h4></div><div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Add to Cart</label><input className="input-field" value={s.btn_add_cart||'Add to Cart'} onChange={set('btn_add_cart')}/></div><div><label className="input-label text-xs">Order Now</label><input className="input-field" value={s.btn_order_now||'Order Now'} onChange={set('btn_order_now')}/></div></div></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><MessageSquare size={16}/><h4 className="font-bold text-sm">Store Messages</h4></div><div><label className="input-label text-xs">Welcome Message</label><textarea className="input-field" rows={2} value={s.welcome_message||''} onChange={set('welcome_message')}/></div><div><label className="input-label text-xs">Success Message</label><textarea className="input-field" rows={2} value={s.success_message||''} onChange={set('success_message')}/></div></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><Tag size={16} className="text-red-500"/><h4 className="font-bold text-sm">Offer & Sale Branding</h4></div><T label="Enable Offer Banner" desc="Show promotional banner with countdown" checked={s.offer_enabled} onChange={set('offer_enabled')}/>{s.offer_enabled&&<><div className="grid grid-cols-2 gap-3"><div><label className="input-label text-xs">Offer Title</label><input className="input-field" value={s.offer_title||'Limited Offer'} onChange={set('offer_title')}/></div><div><label className="input-label text-xs">Discount Text</label><input className="input-field" value={s.offer_discount||'40% OFF'} onChange={set('offer_discount')}/></div></div><div className="grid grid-cols-3 gap-3"><div><label className="input-label text-xs">Timer Label</label><input className="input-field" value={s.offer_label||'Ends in:'} onChange={set('offer_label')}/></div><div><label className="input-label text-xs">Hours</label><input type="number" className="input-field" value={s.offer_hours||15} onChange={set('offer_hours')}/></div><div><label className="input-label text-xs">Minutes</label><input type="number" className="input-field" value={s.offer_minutes||33} onChange={set('offer_minutes')}/></div></div></>}</div></div></>}

{sec==='dashboard-config'&&<div className="glass-card-solid p-6"><SH icon={Layout} title="Command Center" subtitle="Configure your primary workflow hub." accent="brand"/><div className="mt-6 space-y-4"><div className="flex items-center gap-2"><Sliders size={16} className="text-brand-500"/><h4 className="font-bold text-sm">Module Visibility</h4></div><div className="grid grid-cols-2 gap-3"><T label="Action Bar" desc="Quick-entry tools" checked={s.dash_action!==false} onChange={e=>setV('dash_action',e.target.checked)}/><T label="Telemetry" desc="Core financial metrics" checked={s.dash_telemetry!==false} onChange={e=>setV('dash_telemetry',e.target.checked)}/><T label="Pulse Charts" desc="Visual trend analysis" checked={s.dash_pulse!==false} onChange={e=>setV('dash_pulse',e.target.checked)}/><T label="Log Stream" desc="Real-time order data" checked={s.dash_log!==false} onChange={e=>setV('dash_log',e.target.checked)}/></div></div><div className="grid grid-cols-2 gap-4 mt-4"><div className="p-5 bg-gray-50 rounded-xl"><h4 className="font-bold text-sm mb-2">Greeting</h4><input className="input-field" value={s.dash_greeting||'Welcome back! 👋'} onChange={set('dash_greeting')}/><T label="Show Date" desc="Display system date" checked={s.dash_date!==false} onChange={e=>setV('dash_date',e.target.checked)}/></div><div className="p-5 bg-gray-50 rounded-xl"><h4 className="font-bold text-sm mb-2">Chart Type</h4><div className="flex gap-2 mb-2">{['AREA','LINE','BAR'].map(t=>(<button key={t} onClick={()=>setV('chart_type',t)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${(s.chart_type||'AREA')===t?'bg-brand-500 text-white':'bg-gray-200 text-gray-500'}`}>{t}</button>))}</div></div></div></div>}

{sec==='users'&&<><div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><div className="flex gap-4"><span className="text-sm font-bold text-brand-600 border-b-2 border-brand-500 pb-2">Team Members</span></div><button onClick={()=>setShowStaff(true)} className="btn-primary text-xs flex items-center gap-1"><Plus size={14}/>Create New User</button></div>
<table className="w-full text-sm"><thead><tr className="text-left text-xs text-gray-400 uppercase"><th className="pb-2">User</th><th className="pb-2">Role</th><th className="pb-2">Actions</th></tr></thead><tbody>{staff.map(x=>(<tr key={x.id} className="border-t border-gray-100"><td className="py-3"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-brand-100 flex items-center justify-center text-brand-600 font-bold text-sm">{x.name?.[0]?.toUpperCase()}</div><div><p className="font-semibold text-gray-800">{x.name}</p><p className="text-xs text-gray-400">{x.email}</p></div></div></td><td><select className="input-field !py-1.5 !w-36 text-sm" defaultValue={x.role}><option value="admin">Admin</option><option value="preparer">Preparer</option><option value="confirmer">Confirmer</option><option value="accountant">Accountant</option><option value="viewer">Viewer</option></select></td><td><div className="flex gap-1"><button className="p-1.5 hover:bg-gray-100 rounded text-gray-400"><Eye size={14}/></button><button className="p-1.5 hover:bg-red-50 rounded text-red-400"><Trash2 size={14}/></button></div></td></tr>))}</tbody></table>{staff.length===0&&<p className="text-center py-8 text-gray-400 text-sm">No team members yet</p>}</div>
<div className="glass-card-solid p-6"><h3 className="font-bold text-gray-900 mb-4">Roles & Permissions</h3><div className="space-y-3">{Object.entries(roles).map(([k,r])=>(<div key={k} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-xl ${r.color} flex items-center justify-center text-white font-bold text-sm`}>{r.label[0]}</div><div><p className="font-bold text-gray-800">{r.label} <span className="badge badge-neutral text-[9px] ml-1">SYSTEM</span></p><p className="text-xs text-gray-400">{r.desc}</p></div></div><button onClick={()=>setShowRole(k)} className="text-sm text-brand-600 font-medium hover:underline">View</button></div>))}</div></div></>}

{sec==='checkout'&&<><SH icon={ShoppingCart} title="Purchase Flow" subtitle="Optimize visitor to customer conversion." accent="purple"/>
<div className="glass-card-solid p-6 space-y-3 mt-4"><h3 className="font-bold flex items-center gap-2"><Lock size={16}/>Data Collection</h3><div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl"><div><p className="font-semibold text-sm">Full Name</p><p className="text-[10px] text-gray-400">Primary identifier</p></div><span className="badge badge-danger text-[10px]">REQUIRED</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl"><div><p className="font-semibold text-sm">Phone Number</p><p className="text-[10px] text-gray-400">Delivery coordination</p></div><span className="badge badge-danger text-[10px]">REQUIRED</span></div><T label="Email Collection" desc="Automated invoice flow." checked={s.checkout_email} onChange={e=>setV('checkout_email',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold flex items-center gap-2"><Zap size={16}/>Experience</h3><T label="Cart Drawer" desc="Side-cart on click." checked={s.cart_drawer} onChange={e=>setV('cart_drawer',e.target.checked)}/><T label="Order Notes" desc="Special instructions." checked={s.order_notes} onChange={e=>setV('order_notes',e.target.checked)}/><T label="Trust Signals" desc="Security badges." checked={s.trust_signals!==false} onChange={e=>setV('trust_signals',e.target.checked)}/><T label="Sticky Checkout" desc="Always visible Buy Now." checked={s.sticky_checkout} onChange={e=>setV('sticky_checkout',e.target.checked)}/><T label="Show Savings" desc="Highlight discounts." checked={s.show_savings} onChange={e=>setV('show_savings',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-2"><Code size={16}/><h3 className="font-bold">Custom Scripts</h3></div><textarea className="input-field font-mono text-xs" rows={3} value={s.post_script||''} onChange={set('post_script')} placeholder="<script>...</script>"/><p className="text-[10px] text-gray-400">Runs on checkout page only.</p></div></>}

{sec==='shipping'&&<><div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-gray-900">Shipping Wilayas ({wilayas.length}/58)</h3><button onClick={seedW} className="btn-primary text-xs">Load All 58 Wilayas</button></div>{wilayas.length===0?<p className="text-center py-8 text-gray-400">Click "Load All 58 Wilayas" to set up rates.</p>:<div className="max-h-96 overflow-y-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-white"><tr className="text-left text-xs text-gray-400 uppercase"><th className="pb-2">Code</th><th className="pb-2">Wilaya</th><th className="pb-2">Desk</th><th className="pb-2">Home</th><th className="pb-2">Days</th></tr></thead><tbody>{wilayas.map(w=>(<tr key={w.id} className="border-t border-gray-50"><td className="py-2 font-mono text-xs text-gray-400">{w.wilaya_code}</td><td className="font-medium">{w.wilaya_name}</td><td>{w.desk_delivery_price} DZD</td><td>{w.home_delivery_price} DZD</td><td>{w.delivery_days}d</td></tr>))}</tbody></table></div>}</div></>}

{sec==='payments'&&<div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold mb-2">Payment Methods</h3><T label="Cash on Delivery (COD)" desc="Pay in cash upon delivery." checked={s.enable_cod} onChange={set('enable_cod')}/><T label="CCP Direct Transfer" checked={s.enable_ccp} onChange={set('enable_ccp')}/>{s.enable_ccp&&<div className="grid grid-cols-2 gap-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">CCP Account</label><input className="input-field" value={s.ccp_account||''} onChange={set('ccp_account')}/></div><div><label className="input-label text-xs">CCP Name</label><input className="input-field" value={s.ccp_name||''} onChange={set('ccp_name')}/></div></div>}<T label="BaridiMob QR" checked={s.enable_baridimob} onChange={set('enable_baridimob')}/>{s.enable_baridimob&&<div className="pl-4 border-l-2 border-brand-200 space-y-3"><div><label className="input-label text-xs">RIP</label><input className="input-field" value={s.baridimob_rip||''} onChange={set('baridimob_rip')}/></div><div><label className="input-label text-xs">BaridiMob QR Code (shown to buyers at checkout)</label><div className="flex items-center gap-4 mt-1">{s.baridimob_qr&&<img src={s.baridimob_qr} className="w-24 h-24 rounded-xl border object-cover" alt="QR"/>}<div className="flex-1"><div className="border-2 border-dashed border-gray-300 rounded-xl p-4 text-center cursor-pointer hover:border-emerald-400" onClick={()=>{const inp=document.createElement('input');inp.type='file';inp.accept='image/*';inp.onchange=(e)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{setS({...s,baridimob_qr:r.result});toast.success('QR uploaded!');};r.readAsDataURL(f);};inp.click();}}><Upload size={16} className="mx-auto text-gray-400 mb-1"/><p className="text-xs text-gray-500">{s.baridimob_qr?'Replace QR':'Upload QR image'}</p></div></div></div></div></div>}<T label="Bank Transfer" checked={s.enable_bank_transfer} onChange={set('enable_bank_transfer')}/>{s.enable_bank_transfer&&<div className="grid grid-cols-3 gap-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">Bank</label><input className="input-field" value={s.bank_name||''} onChange={set('bank_name')}/></div><div><label className="input-label text-xs">Account</label><input className="input-field" value={s.bank_account||''} onChange={set('bank_account')}/></div><div><label className="input-label text-xs">RIB</label><input className="input-field" value={s.bank_rib||''} onChange={set('bank_rib')}/></div></div>}</div>}

{sec==='notifications'&&<><SH icon={Bell} title="Notification Center" subtitle="Configure alerts for your store events." accent="purple"/>
<div className="glass-card-solid p-6 space-y-4 mt-4"><h3 className="font-bold text-sm flex items-center gap-2"><Smartphone size={16} className="text-blue-500"/>Push Alerts</h3><T label="Order updates" desc="New orders and status changes" checked={s.notify_orders!==false} onChange={e=>setV('notify_orders',e.target.checked)}/><T label="Stock alerts" desc="Low stock notifications" checked={s.notify_stock!==false} onChange={e=>setV('notify_stock',e.target.checked)}/><T label="Customer activity" desc="New registrations" checked={s.notify_customers} onChange={e=>setV('notify_customers',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold text-sm flex items-center gap-2"><Mail size={16} className="text-purple-500"/>Email Digests</h3><T label="Email alerts" desc="Daily summary and critical alerts" checked={s.email_alerts!==false} onChange={e=>setV('email_alerts',e.target.checked)}/><div className="p-4 bg-gray-50 rounded-xl flex items-center gap-3"><Mail size={16} className="text-gray-400"/><div><p className="text-sm font-medium text-gray-700">{profile.email||user?.email||'admin@store.com'}</p><p className="text-[10px] text-gray-400">Admin recipient for all system emails</p></div></div></div></>}

{sec==='orders-config'&&<><SH icon={Package} title="Order Configuration" subtitle="Sequencing logic and archiving rules." accent="blue"/>
<div className="glass-card-solid p-6 space-y-4 mt-4"><h3 className="font-bold text-sm flex items-center gap-2"><Hash size={16} className="text-blue-500"/>Order ID Format</h3><div className="p-4 bg-blue-50 rounded-xl text-center mb-4"><p className="text-[10px] font-bold text-blue-400 uppercase">Preview</p><p className="text-2xl font-black text-gray-900 mt-1">{s.order_prefix||'DZ-'}<span className="text-brand-500">{s.order_start_number||'100000'}</span>{s.order_suffix?`-${s.order_suffix}`:''}</p></div><div className="grid grid-cols-3 gap-4"><div><label className="input-label text-xs">Prefix</label><input className="input-field font-mono" value={s.order_prefix||'DZ-'} onChange={set('order_prefix')}/></div><div><label className="input-label text-xs">Start Number</label><input type="number" className="input-field font-mono" value={s.order_start_number||100000} onChange={set('order_start_number')}/></div><div><label className="input-label text-xs">Suffix</label><input className="input-field font-mono" value={s.order_suffix||''} onChange={set('order_suffix')} placeholder="Optional"/></div></div></div>
<div className="glass-card-solid p-6"><T label="Auto-Archive" desc="Move completed orders to archive after 30 days." checked={s.auto_archive!==false} onChange={e=>setV('auto_archive',e.target.checked)}/></div></>}

{sec==='customers-config'&&<><SH icon={Shield} title="Security & Filtering" subtitle="Protect your store from fraudulent transactions." accent="emerald"/>
<div className="glass-card-solid p-6 space-y-4 mt-4"><h3 className="font-bold text-sm flex items-center gap-2"><AlertTriangle size={16} className="text-red-500"/>Blacklist Automation</h3><div className="p-3 bg-red-50 rounded-xl text-sm text-red-700 mb-3">Auto-blacklist customers exceeding cancellation threshold.</div><T label="Enable Auto Blacklist" desc="Automatic blacklisting on repeated cancellations." checked={s.auto_blacklist} onChange={e=>setV('auto_blacklist',e.target.checked)}/>{s.auto_blacklist&&<div className="pl-4 border-l-2 border-red-200"><label className="input-label text-xs">Threshold</label><input type="number" className="input-field !w-24" value={s.blacklist_threshold||3} onChange={set('blacklist_threshold')} min={1}/><p className="text-[10px] text-gray-400 mt-1">Cancellations before auto-blacklist</p></div>}</div></>}

{sec==='inventory'&&<><SH icon={Package} title="Inventory Management" subtitle="Stock tracking and visibility policies." accent="orange"/>
<div className="glass-card-solid p-6 space-y-4 mt-4"><T label="Manage Stock" desc="Track product stock levels automatically." checked={s.manage_stock!==false} onChange={e=>setV('manage_stock',e.target.checked)}/><div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Low Stock Threshold</label><input type="number" className="input-field font-mono" value={s.low_stock_threshold||5} onChange={set('low_stock_threshold')} min={0}/><p className="text-[10px] text-gray-400 mt-1">Flag items below this count</p></div><div className="flex items-center"><T label="Show Stock on Storefront" desc="Display 'Only X left' message." checked={s.show_stock_storefront} onChange={e=>setV('show_stock_storefront',e.target.checked)}/></div></div></div><div className="flex gap-3"><SP label="Total SKUs" value={currentStore?.product_count||0} color="brand"/><SP label="Health" value="85% in stock" color="emerald"/></div></>}

{sec==='marketing'&&<><SH icon={TrendingUp} title="Tracking & Analytics" subtitle="Conversion pixels and telemetry." accent="purple"/>
<div className="glass-card-solid p-6 space-y-4 mt-4"><h3 className="font-bold text-sm">Pixel Configuration</h3><div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Facebook Pixel ID</label><input className="input-field font-mono" value={s.fb_pixel||''} onChange={set('fb_pixel')} placeholder="1234567890..."/></div><div><label className="input-label text-xs">TikTok Pixel ID</label><input className="input-field font-mono" value={s.tiktok_pixel||''} onChange={set('tiktok_pixel')} placeholder="C12345..."/></div><div><label className="input-label text-xs">Google Analytics ID</label><input className="input-field font-mono" value={s.ga_id||''} onChange={set('ga_id')} placeholder="G-XXXXXXX"/></div><div><label className="input-label text-xs">Snapchat Pixel ID</label><input className="input-field font-mono" value={s.snap_pixel||''} onChange={set('snap_pixel')} placeholder="xxxx-xxxx..."/></div></div></div>
<div className="p-4 bg-blue-50 rounded-xl text-sm text-blue-700">Deploy Facebook Pixel first for retargeting. Ensure GA4 is active for session analytics.</div></>}

{sec==='domains'&&<><SH icon={Globe} title="Domain Management" subtitle="Connect custom domains." accent="blue"/>
<div className="glass-card-solid p-6 mt-4"><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">Current Domain</p><div className="flex items-center gap-3"><p className="font-mono font-bold text-gray-900">{storeDomain}</p><span className="badge badge-success text-[10px]">PRIMARY</span><button onClick={()=>{navigator.clipboard.writeText(storeDomain);toast.success('Copied!');}} className="p-1.5 hover:bg-gray-100 rounded"><Copy size={14} className="text-gray-400"/></button></div></div>
<div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold text-sm">Custom Domain</h3><div className="flex gap-3"><input className="input-field flex-1 font-mono" placeholder="www.yourstore.com" value={s.custom_domain||''} onChange={set('custom_domain')}/><button onClick={()=>{if(s.custom_domain){save();toast.success('Saved!');}else toast.error('Enter a domain');}} className="btn-primary text-sm">Connect</button></div></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold text-sm mb-3">Security</h3><T label="Force HTTPS" desc="Secure connections." checked={s.force_https!==false} onChange={e=>setV('force_https',e.target.checked)}/><T label="Redirect www" desc="www to root." checked={s.redirect_www!==false} onChange={e=>setV('redirect_www',e.target.checked)}/><T label="Clean URLs" desc="Remove .html extensions." checked={s.clean_urls!==false} onChange={e=>setV('clean_urls',e.target.checked)}/><T label="Bot Mitigation" desc="Challenge suspicious traffic." checked={s.bot_mitigation} onChange={e=>setV('bot_mitigation',e.target.checked)}/></div></>}

{sec==='ai'&&<><SH icon={Bot} title="AI Messaging Agent" subtitle="Automated engagement, confirmations, and follow-ups." accent="brand"/>
<div className="glass-card-solid p-6 mt-4"><div className="flex items-center justify-between"><div><h3 className="font-bold text-gray-900">Agent Protocol</h3><p className="text-xs text-gray-400">Enable or disable the AI engine.</p></div><div className={`w-14 h-7 rounded-full cursor-pointer ${s.ai_agent_enabled?'bg-brand-500':'bg-gray-300'} relative`} onClick={()=>setV('ai_agent_enabled',!s.ai_agent_enabled)}><div className={`absolute top-0.5 w-6 h-6 bg-white rounded-full shadow-md transition-transform ${s.ai_agent_enabled?'translate-x-7':'translate-x-0.5'}`}/></div></div></div>
{s.ai_agent_enabled&&<><div className="glass-card-solid p-6 space-y-4"><div className="grid grid-cols-2 gap-6"><div><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">Channel</p><div className="flex gap-2">{['WHATSAPP','SMS','EMAIL'].map(ch=>(<button key={ch} onClick={()=>setV('ai_channel',ch)} className={`px-4 py-2 rounded-xl text-xs font-bold ${(s.ai_channel||'WHATSAPP')===ch?'bg-emerald-500 text-white':'bg-gray-100 text-gray-500'}`}>{ch}</button>))}</div></div><div><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">Reminder Delay</p><div className="flex items-center gap-3"><input type="range" min="5" max="120" step="5" value={s.ai_reminder_delay||30} onChange={e=>setV('ai_reminder_delay',parseInt(e.target.value))} className="flex-1 accent-brand-500"/><span className="font-black text-lg">{s.ai_reminder_delay||30}<span className="text-xs font-normal text-gray-400 ml-1">min</span></span></div></div></div></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold text-sm">WhatsApp Connection</h3><div><label className="input-label text-xs">Business Number</label><input className="input-field font-mono" placeholder="0XX XX XX XX" value={s.wa_business_number||''} onChange={set('wa_business_number')}/></div><button onClick={()=>{if(!s.wa_business_number)return toast.error('Enter number first');setQrGenerated(true);toast.success('QR Generated!');}} className="btn-primary text-sm w-full flex items-center justify-center gap-2 bg-emerald-500 hover:bg-emerald-600"><QrCode size={16}/>Generate QR</button>{qrGenerated&&<div className="p-6 bg-gray-50 rounded-xl text-center"><QrCode size={64} className="mx-auto text-gray-700"/><p className="text-xs text-gray-400 mt-2">Scan with WhatsApp Business</p></div>}</div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold text-sm">AI Features</h3><T label="AI Chatbot" desc="Smart support bot." checked={s.ai_chatbot_enabled} onChange={e=>setV('ai_chatbot_enabled',e.target.checked)}/>{s.ai_chatbot_enabled&&<div className="pl-4 border-l-2 border-brand-200 space-y-2"><div><label className="input-label text-xs">Bot Name</label><input className="input-field" value={s.ai_chatbot_name||''} onChange={set('ai_chatbot_name')}/></div><div><label className="input-label text-xs">Greeting</label><textarea className="input-field" rows={2} value={s.ai_chatbot_greeting||''} onChange={set('ai_chatbot_greeting')}/></div></div>}<T label="Fake Order Detection" desc="Score orders for fraud." checked={s.ai_fake_detection} onChange={e=>setV('ai_fake_detection',e.target.checked)}/><T label="Cart Recovery" desc="Automated recovery sequences." checked={s.ai_cart_recovery} onChange={e=>setV('ai_cart_recovery',e.target.checked)}/></div></>}</>}

{sec==='account'&&<><div className="glass-card-solid p-6"><h3 className="font-bold text-lg text-gray-900 mb-4">Profile</h3><div className="flex items-start gap-8"><div className="flex-1 space-y-4"><div><label className="input-label text-xs">Full Name</label><input className="input-field" value={profile.full_name||''} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Username</label>{usernameEdit?<div className="flex gap-2"><input className="input-field flex-1" value={newUsername} onChange={e=>setNewUsername(e.target.value)}/><button onClick={saveUsername} className="btn-primary text-xs">Save</button><button onClick={()=>setUsernameEdit(false)} className="btn-ghost text-xs">×</button></div>:<div className="flex gap-2"><input className="input-field flex-1" value={profile.username||''} readOnly/><button onClick={()=>setUsernameEdit(true)} className="px-3 py-2 border border-brand-500 text-brand-600 rounded-xl text-xs font-bold">Change</button></div>}</div></div><div><label className="input-label text-xs">Email</label>{emailEdit?<div className="space-y-2"><input className="input-field" placeholder="New email" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><input type="password" className="input-field" placeholder="Password to confirm" value={emailPw} onChange={e=>setEmailPw(e.target.value)}/><div className="flex gap-2"><button onClick={saveEmail} className="btn-primary text-xs">Save</button><button onClick={()=>{setEmailEdit(false);setEmailPw('');}} className="btn-ghost text-xs">×</button></div></div>:<div className="flex gap-2"><input className="input-field flex-1" value={profile.email||''} readOnly/><button onClick={()=>setEmailEdit(true)} className="px-3 py-2 border border-brand-500 text-brand-600 rounded-xl text-xs font-bold">Change</button></div>}</div></div><div className="w-20 h-20 rounded-full bg-gray-100 flex items-center justify-center"><User size={32} className="text-gray-400"/></div></div><button onClick={saveProfile} disabled={profileLoading} className="btn-primary text-sm mt-4">{profileLoading?'Saving...':'Save Profile'}</button></div>
<div className="glass-card-solid p-6"><h3 className="font-bold text-sm mb-3">Password</h3><div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div className="flex items-center gap-3"><Key size={18} className="text-amber-500"/><div><p className="font-medium text-sm">Security Credentials</p><p className="text-[10px] text-gray-400">Change your account password</p></div></div><button onClick={()=>setShowPwSection(!showPwSection)} className="text-sm text-brand-600 font-medium">Update</button></div>{showPwSection&&<div className="mt-4 space-y-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">Current Password</label><input type="password" className="input-field" value={pwForm.current_password} onChange={e=>setPwForm({...pwForm,current_password:e.target.value})}/></div><div><label className="input-label text-xs">New Password</label><input type="password" className="input-field" value={pwForm.new_password} onChange={e=>setPwForm({...pwForm,new_password:e.target.value})}/></div><div><label className="input-label text-xs">Confirm</label><input type="password" className="input-field" value={pwForm.confirm_password} onChange={e=>setPwForm({...pwForm,confirm_password:e.target.value})}/></div><button onClick={changePassword} className="btn-primary text-sm">Update Password</button></div>}</div>
<div className="glass-card-solid p-6"><h3 className="font-bold text-sm mb-3">Interface Language</h3><div className="grid grid-cols-3 gap-3">{[{c:'en',l:'EN'},{c:'fr',l:'FR'},{c:'ar',l:'العربية'}].map(x=>(<button key={x.c} onClick={()=>setV('interface_language',x.c)} className={`p-3 rounded-xl border-2 text-center font-bold ${(s.interface_language||'en')===x.c?'border-brand-500 bg-brand-50':'border-gray-200'}`}>{x.l}</button>))}</div></div>
<div className="grid lg:grid-cols-2 gap-6"><div className="glass-card-solid p-6"><h3 className="font-bold text-sm mb-3 flex items-center gap-2"><Shield size={14} className="text-emerald-500"/>Security</h3><div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div className="flex items-center gap-3"><Lock size={16} className="text-gray-600"/><div><p className="font-medium text-sm">2FA Authentication</p><p className="text-[10px] text-amber-600 font-bold">Recommended</p></div></div><button onClick={toggleTwoFa} className={`px-4 py-2 rounded-xl text-xs font-bold ${profile.two_fa_enabled?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-600'}`}>{profile.two_fa_enabled?'Enabled ✓':'Setup'}</button></div></div>
<div className="glass-card-solid p-6 border-2 border-red-100"><h3 className="font-bold text-sm text-red-600 mb-3 flex items-center gap-2"><AlertTriangle size={14}/>Danger Zone</h3><p className="text-xs text-gray-400 mb-4">Permanently delete your account. This is irreversible.</p>{deleteConfirm?<div className="space-y-3"><input type="password" className="input-field" placeholder="Password to confirm" value={deletePw} onChange={e=>setDeletePw(e.target.value)}/><div className="flex gap-2"><button onClick={deleteAccount} className="px-4 py-2 bg-red-600 text-white rounded-xl text-sm font-bold">Confirm Delete</button><button onClick={()=>{setDeleteConfirm(false);setDeletePw('');}} className="btn-ghost text-sm">Cancel</button></div></div>:<button onClick={()=>setDeleteConfirm(true)} className="w-full py-3 bg-red-600 text-white rounded-xl font-bold text-sm hover:bg-red-700">DELETE MY ACCOUNT</button>}</div></div></>}

{sec==='taxes'&&<div className="glass-card-solid p-12 text-center"><SI size={48} className="mx-auto text-gray-300 mb-4"/><h3 className="font-bold text-gray-900 mb-2">Taxes</h3><p className="text-gray-400 text-sm">Coming soon!</p></div>}

{sec==='subscription'&&<SubscriptionSection/>}

      </div>
    </div>
    {showRole&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowRole(null)}><div className="bg-white rounded-3xl p-8 w-full max-w-2xl max-h-[80vh] overflow-y-auto shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">Role: {roles[showRole]?.label}</h2><button onClick={()=>setShowRole(null)} className="text-gray-400 hover:text-gray-600">✕</button></div><div className="grid grid-cols-2 gap-4">{[['Orders',['View Dashboard','View Orders','Manage Orders','Delete Orders','Confirm Orders','Prepare Orders']],['Products',['View Products','Manage Products','Delete Products']],['Customers',['View Customers','Manage Customers']]].map(([cat,perms])=>(<div key={cat}><h4 className="font-bold text-xs text-gray-500 uppercase mb-2">{cat}</h4>{perms.map(p=>{const has=roles[showRole]?.perms.includes(p);return(<label key={p} className="flex items-center gap-2 mb-1.5"><div className={`w-5 h-5 rounded flex items-center justify-center text-white text-xs ${has?'bg-brand-500':'bg-gray-200'}`}>{has&&<Check size={12}/>}</div><span className="text-sm text-gray-700">{p}</span></label>);})}</div>))}</div><button onClick={()=>setShowRole(null)} className="btn-primary w-full mt-6">Close</button></div></div>}
    {showStaff&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowStaff(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-bold mb-6">Create User</h2><div className="space-y-3"><div><label className="input-label">Name</label><input className="input-field" value={sf.name} onChange={e=>setSf({...sf,name:e.target.value})}/></div><div><label className="input-label">Email</label><input className="input-field" value={sf.email} onChange={e=>setSf({...sf,email:e.target.value})}/></div><div><label className="input-label">Phone</label><input className="input-field" value={sf.phone} onChange={e=>setSf({...sf,phone:e.target.value})}/></div><div><label className="input-label">Password</label><input type="password" className="input-field" value={sf.password} onChange={e=>setSf({...sf,password:e.target.value})}/></div><div><label className="input-label">Role</label><select className="input-field" value={sf.role} onChange={e=>setSf({...sf,role:e.target.value})}><option value="admin">Admin</option><option value="preparer">Preparer</option><option value="confirmer">Confirmer</option><option value="viewer">Viewer</option></select></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowStaff(false)} className="btn-ghost flex-1">Cancel</button><button onClick={addStaff} className="btn-primary flex-1">Create</button></div></div></div>}
  </DashboardLayout>);
}
