import React, { useState, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { ownerApi } from '../../utils/api';
import { useStoreManagement } from '../../hooks/useStore';
import DashboardLayout from '../../components/shared/DashboardLayout';
import toast from 'react-hot-toast';
import api from '../../utils/api';
import { Save,Store,Palette,CreditCard,Truck,Bot,Upload,Globe,Users,ShoppingCart,Settings as SI,Bell,BarChart3,Shield,Tag,Code,Type,MessageSquare,Eye,Trash2,Plus,Check,Layout,Sliders,Zap,Lock,Package,Percent } from 'lucide-react';

const themes=[{id:'classic',name:'Classic Store',desc:'PROFESSIONAL & CLEAN',c:'#7C3AED'},{id:'nova-dark',name:'Nova Dark',desc:'FUTURISTIC & SLEEK',c:'#8B5CF6'},{id:'enterprise',name:'Enterprise',desc:'DENSE & FUNCTIONAL',c:'#3B82F6'},{id:'ocean-bloom',name:'Ocean Bloom',desc:'SOFT & FRIENDLY',c:'#06B6D4'},{id:'nzxt-pro',name:'NZXT Pro',desc:'HIGH CONTRAST',c:'#A855F7'},{id:'moonlight',name:'Moonlight',desc:'ETHEREAL & CALM',c:'#818CF8'}];
const brandColors=['#10B981','#06B6D4','#3B82F6','#6366F1','#8B5CF6','#A855F7','#D946EF','#EC4899','#F43F5E','#EF4444','#F97316','#EAB308','#84CC16','#22C55E','#14B8A6','#0EA5E9'];
const roles={admin:{label:'Admin',desc:'Full access',color:'bg-brand-500',perms:['View Dashboard','View Orders','Manage Orders','Delete Orders','Confirm Orders','Prepare Orders','View Products','Manage Products','View Customers','Manage Customers']},manager:{label:'Manager',desc:'Orders + Customers',color:'bg-blue-500',perms:['View Dashboard','View Orders','Manage Orders','Confirm Orders','View Products','View Customers']},staff:{label:'Staff',desc:'Orders only',color:'bg-emerald-500',perms:['View Orders','Manage Orders','View Products','View Customers']},viewer:{label:'Viewer',desc:'Read-only',color:'bg-gray-500',perms:['View Dashboard','View Orders','View Products']},confirmer:{label:'Confirmer',desc:'Validate orders',color:'bg-green-500',perms:['View Orders','Confirm Orders','View Customers']}};

export default function StoreSettings(){
  const{t}=useTranslation();const{currentStore,setCurrentStore}=useStoreManagement();
  const[s,setS]=useState({});const[sec,setSec]=useState('store-details');const[loading,setLoading]=useState(false);
  const[staff,setStaff]=useState([]);const[wilayas,setWilayas]=useState([]);const[showRole,setShowRole]=useState(null);
  const[showStaff,setShowStaff]=useState(false);const[sf,setSf]=useState({name:'',email:'',phone:'',password:'',role:'viewer'});
  const logoR=useRef(null);const coverR=useRef(null);

  useEffect(()=>{if(currentStore){setS({...currentStore,theme:currentStore.theme||'classic'});loadData();}},[currentStore?.id]);
  const loadData=()=>{if(!currentStore?.id)return;api.get(`/owner/stores/${currentStore.id}/staff`).then(r=>setStaff(r.data)).catch(()=>{});api.get(`/manage/stores/${currentStore.id}/shipping-wilayas`).then(r=>setWilayas(r.data)).catch(()=>{});};
  const save=async()=>{setLoading(true);try{const{data}=await ownerApi.updateStore(currentStore.id,s);setCurrentStore(data);toast.success('Saved ✓');}catch{toast.error('Failed');}setLoading(false);};
  const set=(k)=>(e)=>setS({...s,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value});
  const setV=(k,v)=>setS({...s,[k]:v});
  const imgUp=(field,sz=400)=>(e)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const i=new window.Image();i.onload=()=>{const c=document.createElement('canvas');c.width=sz;c.height=sz;c.getContext('2d').drawImage(i,0,0,sz,sz);setS({...s,[field]:c.toDataURL('image/jpeg',0.7)});toast.success('Uploaded!');};i.src=r.result;};r.readAsDataURL(f);};
  const seedW=async()=>{try{await api.post(`/manage/stores/${currentStore.id}/shipping-wilayas/seed`);toast.success('58 wilayas loaded!');loadData();}catch{toast.error('Failed');}};
  const addStaff=async()=>{try{await api.post(`/owner/stores/${currentStore.id}/staff`,sf);toast.success('Added!');setShowStaff(false);setSf({name:'',email:'',phone:'',password:'',role:'viewer'});loadData();}catch{toast.error('Failed');}};
  const T=({label,desc,checked,onChange})=>(<label className="flex items-center justify-between p-4 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors"><div><p className="font-medium text-sm text-gray-800">{label}</p>{desc&&<p className="text-xs text-gray-400 mt-0.5">{desc}</p>}</div><div className={`w-11 h-6 rounded-full transition-colors ${checked?'bg-brand-500':'bg-gray-300'} relative`}><div className={`absolute top-0.5 w-5 h-5 bg-white rounded-full shadow-md transition-transform ${checked?'translate-x-5':'translate-x-0.5'}`}/></div><input type="checkbox" className="sr-only" checked={checked||false} onChange={onChange}/></label>);
  const secs=[{id:'store-details',icon:Store,l:'Store Details'},{id:'customization',icon:Palette,l:'Customization'},{id:'dashboard-config',icon:Layout,l:'Dashboard'},{id:'users',icon:Users,l:'Users & Permissions'},{id:'checkout',icon:ShoppingCart,l:'Checkout'},{id:'shipping',icon:Truck,l:'Shipping'},{id:'payments',icon:CreditCard,l:'Payments'},{id:'taxes',icon:Percent,l:'Taxes'},{id:'notifications',icon:Bell,l:'Notifications'},{id:'orders-config',icon:Package,l:'Orders'},{id:'customers-config',icon:Users,l:'Customers'},{id:'inventory',icon:BarChart3,l:'Inventory'},{id:'marketing',icon:Tag,l:'Marketing & Pixels'},{id:'domains',icon:Globe,l:'Domains'},{id:'ai',icon:Bot,l:'AI Messaging'},{id:'subscription',icon:Zap,l:'Subscription'},{id:'account',icon:SI,l:'Account'}];

  return(<DashboardLayout>
    <div className="flex items-center justify-between mb-6"><h1 className="page-header">{t('sidebar.settings')}</h1><button onClick={save} disabled={loading} className="btn-primary flex items-center gap-2 text-sm">{loading?<div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>:<Save size={16}/>}Save Changes</button></div>
    <div className="flex gap-6">
      <div className="w-56 shrink-0 space-y-0.5">{secs.map(x=>{const I=x.icon;return(<button key={x.id} onClick={()=>setSec(x.id)} className={`w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-sm font-medium transition-all text-left ${sec===x.id?'bg-brand-50 text-brand-600':'text-gray-500 hover:text-gray-700 hover:bg-gray-50'}`}><I size={16}/>{x.l}</button>);})}</div>
      <div className="flex-1 space-y-6 animate-fade-in">

{sec==='store-details'&&<><div className="grid lg:grid-cols-2 gap-6">
<div className="glass-card-solid p-6 space-y-4"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center"><Store size={20} className="text-brand-500"/></div><div><h3 className="font-bold text-gray-900">Store Identity</h3><p className="text-xs text-gray-400">Manage how your business appears to the world.</p></div></div><div><label className="input-label">Store Name</label><input className="input-field" value={s.name||s.store_name||''} onChange={e=>setS({...s,name:e.target.value})}/></div><div className="grid grid-cols-2 gap-4"><div><label className="input-label">Store Phone</label><input className="input-field" value={s.contact_phone||''} onChange={set('contact_phone')}/></div><div><label className="input-label">Support Phone</label><input className="input-field" value={s.support_phone||''} onChange={set('support_phone')}/></div></div>
<p className="text-xs font-bold text-gray-400 uppercase tracking-wider pt-2">Brand Assets</p><div className="flex gap-4"><div><p className="text-xs font-semibold text-gray-600 mb-1">Store Logo</p><div className="w-24 h-24 rounded-xl bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden cursor-pointer hover:border-brand-400" onClick={()=>logoR.current?.click()}>{s.logo?<img src={s.logo} className="w-full h-full object-cover"/>:<Upload size={20} className="text-gray-400"/>}</div><input ref={logoR} type="file" accept="image/*" className="hidden" onChange={imgUp('logo')}/>{s.logo&&<p className="text-[10px] text-emerald-500 font-bold mt-1"><Check size={10} className="inline"/>READY</p>}</div><div><p className="text-xs font-semibold text-gray-600 mb-1">Cover Image</p><div className="w-36 h-24 rounded-xl bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center overflow-hidden cursor-pointer hover:border-brand-400" onClick={()=>coverR.current?.click()}>{s.cover_image?<img src={s.cover_image} className="w-full h-full object-cover"/>:<div className="text-center"><Upload size={16} className="text-gray-400 mx-auto"/><p className="text-[10px] text-gray-400 mt-1">Click to upload</p></div>}</div><input ref={coverR} type="file" accept="image/*" className="hidden" onChange={imgUp('cover_image',800)}/></div></div></div>
<div className="glass-card-solid p-6 space-y-4"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center"><Globe size={20} className="text-cyan-500"/></div><div><h3 className="font-bold text-gray-900">Regional Settings</h3><p className="text-xs text-gray-400">CURRENCY & LANGUAGE</p></div></div><div><label className="input-label text-xs uppercase tracking-wider">Store Currency</label><select className="input-field" value={s.currency||'DZD'} onChange={set('currency')}><option value="DZD">DZD - Algerian Dinar</option><option value="EUR">EUR - Euro</option><option value="USD">USD - Dollar</option></select></div><div><label className="input-label text-xs uppercase tracking-wider">Default Language</label><div className="grid grid-cols-3 gap-3 mt-2">{[{c:'ar',l:'العربية',f:'🇩🇿'},{c:'fr',l:'Français',f:'🇫🇷'},{c:'en',l:'English',f:'🇬🇧'}].map(x=>(<button key={x.c} onClick={()=>setV('default_language',x.c)} className={`p-3 rounded-xl border-2 text-center transition-all ${(s.default_language||'en')===x.c?'border-brand-500 bg-brand-50':'border-gray-200 hover:border-gray-300'}`}><span className="text-2xl block mb-1">{x.f}</span><span className="text-xs font-semibold">{x.l}</span>{(s.default_language||'en')===x.c&&<Check size={14} className="text-brand-500 mx-auto mt-1"/>}</button>))}</div></div></div>
</div>
<div className="grid lg:grid-cols-2 gap-6"><div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center"><Globe size={20} className="text-blue-500"/></div><div><h3 className="font-bold text-gray-900">Social Media</h3><p className="text-xs text-gray-400">CONNECT YOUR PLATFORMS</p></div></div><input className="input-field" placeholder="Facebook Page URL" value={s.social_facebook||''} onChange={set('social_facebook')}/><input className="input-field" placeholder="Instagram Profile URL" value={s.social_instagram||''} onChange={set('social_instagram')}/><input className="input-field" placeholder="TikTok Profile URL" value={s.social_tiktok||''} onChange={set('social_tiktok')}/><input className="input-field" placeholder="YouTube Channel URL" value={s.youtube||''} onChange={set('youtube')}/></div>
<div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center"><BarChart3 size={20} className="text-purple-500"/></div><div><h3 className="font-bold text-gray-900">SEO</h3><p className="text-xs text-gray-400">IMPROVE VISIBILITY ON GOOGLE</p></div></div><div><label className="input-label text-xs">Homepage Title</label><input className="input-field" value={s.meta_title||''} onChange={set('meta_title')}/><p className="text-[10px] text-gray-400 mt-1">70 chars max</p></div><div><label className="input-label text-xs">Meta Description</label><textarea className="input-field" rows={3} value={s.meta_description||''} onChange={set('meta_description')}/><p className="text-[10px] text-gray-400 mt-1">160 chars max</p></div></div></div></>}

{sec==='customization'&&<><div className="glass-card-solid p-6"><div className="flex items-center gap-3 mb-4"><Palette size={20} className="text-brand-500"/><div><h3 className="font-bold text-gray-900">Design Studio</h3><p className="text-xs text-gray-400">Choose a starting point or craft your unique style.</p></div></div><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{themes.map(th=>(<button key={th.id} onClick={()=>setS({...s,theme:th.id,primary_color:th.c})} className={`p-4 rounded-xl border-2 text-left transition-all ${s.theme===th.id?'border-brand-500 bg-brand-50 ring-2 ring-brand-200':'border-gray-200 hover:border-gray-300'}`}><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg" style={{backgroundColor:th.c}}/><div><p className="font-bold text-sm">{th.name}</p><p className="text-[10px] text-gray-400 uppercase">{th.desc}</p></div></div>{s.theme===th.id&&<Check size={14} className="text-brand-500 mt-2"/>}</button>))}</div></div>
<div className="glass-card-solid p-6"><p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">Brand Essence</p><div className="grid lg:grid-cols-2 gap-6"><div><p className="text-sm font-bold text-gray-800 mb-2"><span className="text-red-500">*</span> Primary Brand Color</p><div className="flex flex-wrap gap-2 mb-3">{brandColors.map(c=>(<button key={c} onClick={()=>setV('primary_color',c)} className={`w-8 h-8 rounded-full transition-transform hover:scale-110 ${s.primary_color===c?'ring-2 ring-offset-2 ring-brand-500 scale-110':''}`} style={{backgroundColor:c}}/>))}</div><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg" style={{backgroundColor:s.primary_color||'#7C3AED'}}/><input className="input-field !w-32 text-sm" value={s.primary_color||'#7C3AED'} onChange={set('primary_color')}/></div></div><div><p className="text-sm font-bold text-gray-800 mb-2"><span className="text-red-500">*</span> Text Colors</p><div className="space-y-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gray-900"/><div><p className="text-[10px] text-gray-400 uppercase">Primary Text</p><input className="input-field !w-32 text-sm" value={s.text_color||'#202223'} onChange={set('text_color')}/></div></div><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-gray-400"/><div><p className="text-[10px] text-gray-400 uppercase">Secondary Text</p><input className="input-field !w-32 text-sm" value={s.secondary_text||'#6d7175'} onChange={set('secondary_text')}/></div></div></div></div></div></div>
<div className="glass-card-solid p-6 space-y-3"><p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Advanced Config</p><div className="grid grid-cols-2 gap-3"><T label="Sticky Header" checked={s.sticky_header!==false} onChange={e=>setV('sticky_header',e.target.checked)}/><T label="Page Transitions" checked={s.page_transitions!==false} onChange={e=>setV('page_transitions',e.target.checked)}/></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><Type size={16}/><h4 className="font-bold text-sm">Button Text</h4></div><div className="grid grid-cols-2 gap-4"><div><label className="input-label text-xs">Add to Cart</label><input className="input-field" value={s.btn_add_cart||'Add to Cart'} onChange={set('btn_add_cart')}/></div><div><label className="input-label text-xs">Order Now</label><input className="input-field" value={s.btn_order_now||'Order Now'} onChange={set('btn_order_now')}/></div></div></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><MessageSquare size={16}/><h4 className="font-bold text-sm">Store Messages</h4></div><div><label className="input-label text-xs">Welcome Message</label><textarea className="input-field" rows={2} value={s.welcome_message||''} onChange={set('welcome_message')}/></div><div><label className="input-label text-xs">Success Message</label><textarea className="input-field" rows={2} value={s.success_message||''} onChange={set('success_message')}/></div></div>
<div className="p-5 bg-gray-50 rounded-xl space-y-3"><div className="flex items-center gap-2"><Tag size={16} className="text-red-500"/><h4 className="font-bold text-sm">Offer & Sale Branding</h4></div><T label="Enable Offer Banner" desc="Show promotional banner with countdown" checked={s.offer_enabled} onChange={set('offer_enabled')}/>{s.offer_enabled&&<><div className="grid grid-cols-2 gap-3"><div><label className="input-label text-xs">Offer Title</label><input className="input-field" value={s.offer_title||'Limited Offer'} onChange={set('offer_title')}/></div><div><label className="input-label text-xs">Discount Text</label><input className="input-field" value={s.offer_discount||'40% OFF'} onChange={set('offer_discount')}/></div></div><div className="grid grid-cols-3 gap-3"><div><label className="input-label text-xs">Timer Label</label><input className="input-field" value={s.offer_label||'Ends in:'} onChange={set('offer_label')}/></div><div><label className="input-label text-xs">Hours</label><input type="number" className="input-field" value={s.offer_hours||15} onChange={set('offer_hours')}/></div><div><label className="input-label text-xs">Minutes</label><input type="number" className="input-field" value={s.offer_minutes||33} onChange={set('offer_minutes')}/></div></div><div className="grid grid-cols-2 gap-3"><div><label className="input-label text-xs">BG Color</label><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded" value={s.offer_bg||'#ef4444'} onChange={set('offer_bg')}/><input className="input-field !w-28" value={s.offer_bg||'#ef4444'} onChange={set('offer_bg')}/></div></div><div><label className="input-label text-xs">Text Color</label><div className="flex gap-2"><input type="color" className="w-8 h-8 rounded" value={s.offer_tc||'#ffffff'} onChange={set('offer_tc')}/><input className="input-field !w-28" value={s.offer_tc||'#ffffff'} onChange={set('offer_tc')}/></div></div></div></>}</div></div></>}

{sec==='dashboard-config'&&<div className="glass-card-solid p-6"><div className="bg-gradient-to-r from-gray-900 to-gray-800 rounded-xl p-5 mb-6"><div className="flex items-center gap-3"><Zap size={20} className="text-white"/><div><h3 className="font-bold text-white">Command Center</h3><p className="text-xs text-white/50">Configure your primary workflow hub.</p></div><span className="ml-auto badge bg-brand-500 text-white text-[10px]">LIVE ENGINE V2.4</span></div></div><div className="space-y-4"><div className="flex items-center gap-2"><Sliders size={16} className="text-brand-500"/><h4 className="font-bold text-sm">Module Visibility</h4></div><div className="grid grid-cols-2 gap-3"><T label="Action Bar" desc="Quick-entry tools" checked={s.dash_action!==false} onChange={e=>setV('dash_action',e.target.checked)}/><T label="Telemetry" desc="Core financial metrics" checked={s.dash_telemetry!==false} onChange={e=>setV('dash_telemetry',e.target.checked)}/><T label="Pulse Charts" desc="Visual trend analysis" checked={s.dash_pulse!==false} onChange={e=>setV('dash_pulse',e.target.checked)}/><T label="Log Stream" desc="Real-time order data" checked={s.dash_log!==false} onChange={e=>setV('dash_log',e.target.checked)}/></div></div><div className="grid grid-cols-2 gap-4 mt-4"><div className="p-5 bg-gray-50 rounded-xl"><h4 className="font-bold text-sm mb-2">Greeting Intel</h4><input className="input-field" value={s.dash_greeting||'Welcome back! 👋'} onChange={set('dash_greeting')}/><T label="Chronicle Label" desc="Display system date" checked={s.dash_date!==false} onChange={e=>setV('dash_date',e.target.checked)}/></div><div className="p-5 bg-gray-50 rounded-xl"><h4 className="font-bold text-sm mb-2">Chart Spec</h4><div className="flex gap-2 mb-2">{['AREA','LINE','BAR'].map(t=>(<button key={t} onClick={()=>setV('chart_type',t)} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${(s.chart_type||'AREA')===t?'bg-brand-500 text-white':'bg-gray-200 text-gray-500'}`}>{t}</button>))}</div><p className="text-xs text-gray-400">Timeline: 1 Week</p></div></div></div>}

{sec==='users'&&<><div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><div className="flex gap-4"><span className="text-sm font-bold text-brand-600 border-b-2 border-brand-500 pb-2">Team Members</span><span className="text-sm text-gray-400 pb-2">Roles & Permissions</span></div><button onClick={()=>setShowStaff(true)} className="btn-primary text-xs flex items-center gap-1"><Plus size={14}/>Create New User</button></div>
<table className="w-full text-sm"><thead><tr className="text-left text-xs text-gray-400 uppercase"><th className="pb-2">User</th><th className="pb-2">Role</th><th className="pb-2">Actions</th></tr></thead><tbody>{staff.map(x=>(<tr key={x.id} className="border-t border-gray-100"><td className="py-3"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-brand-100 flex items-center justify-center text-brand-600 font-bold text-sm">{x.name?.[0]?.toUpperCase()}</div><div><p className="font-semibold text-gray-800">{x.name}</p><p className="text-xs text-gray-400">{x.email}</p></div></div></td><td><select className="input-field !py-1.5 !w-36 text-sm" defaultValue={x.role}><option value="admin">Admin</option><option value="preparer">Preparer</option><option value="confirmer">Confirmer</option><option value="accountant">Accountant</option><option value="viewer">Viewer</option></select></td><td><div className="flex gap-1"><button className="p-1.5 hover:bg-gray-100 rounded text-gray-400"><Eye size={14}/></button><button className="p-1.5 hover:bg-red-50 rounded text-red-400"><Trash2 size={14}/></button></div></td></tr>))}</tbody></table>{staff.length===0&&<p className="text-center py-8 text-gray-400 text-sm">No team members yet</p>}</div>
<div className="glass-card-solid p-6"><h3 className="font-bold text-gray-900 mb-4">Roles & Permissions</h3><div className="space-y-3">{Object.entries(roles).map(([k,r])=>(<div key={k} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-xl ${r.color} flex items-center justify-center text-white font-bold text-sm`}>{r.label[0]}</div><div><p className="font-bold text-gray-800">{r.label} <span className="badge badge-neutral text-[9px] ml-1">SYSTEM</span></p><p className="text-xs text-gray-400">{r.desc}</p><div className="flex flex-wrap gap-1 mt-1">{r.perms.slice(0,5).map(p=><span key={p} className="px-2 py-0.5 bg-blue-50 text-blue-600 text-[9px] rounded-full">{p}</span>)}{r.perms.length>5&&<span className="text-[9px] text-gray-400">+{r.perms.length-5} more</span>}</div></div></div><button onClick={()=>setShowRole(k)} className="text-sm text-brand-600 font-medium hover:underline">Edit Permissions</button></div>))}</div></div></>}

{sec==='checkout'&&<><div className="glass-card-solid p-6 bg-gradient-to-r from-brand-500 to-purple-600 text-white rounded-2xl"><div className="flex items-center gap-3"><ShoppingCart size={24}/><div><h3 className="font-bold text-lg">Purchase Flow</h3><p className="text-white/70 text-sm">Optimize visitor to customer conversion.</p></div></div></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold flex items-center gap-2"><Lock size={16}/>Data Collection</h3><div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl"><div><p className="font-semibold text-sm">Full Name</p><p className="text-[10px] text-gray-400">Primary identifier for shipping.</p></div><span className="badge badge-danger text-[10px]">REQUIRED</span></div><div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl"><div><p className="font-semibold text-sm">Phone Number</p><p className="text-[10px] text-gray-400">Vital for delivery coordination.</p></div><span className="badge badge-danger text-[10px]">REQUIRED</span></div><T label="Email Collection" desc="Used for automated invoice flow." checked={s.checkout_email} onChange={e=>setV('checkout_email',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold flex items-center gap-2"><Zap size={16}/>Experience Logic</h3><T label="Instant Cart Drawer" desc="Flash open side-cart on click." checked={s.cart_drawer} onChange={e=>setV('cart_drawer',e.target.checked)}/><T label="Order Remarques" desc="Special instructions from buyer." checked={s.order_notes} onChange={e=>setV('order_notes',e.target.checked)}/><T label="Trust Signals" desc="Security badges in footer." checked={s.trust_signals!==false} onChange={e=>setV('trust_signals',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><h3 className="font-bold flex items-center gap-2"><ShoppingCart size={16}/>Cart Experience</h3><T label="Cart Drawer" desc="Show cart as side drawer." checked={s.cart_drawer_mode} onChange={e=>setV('cart_drawer_mode',e.target.checked)}/><T label="Sticky Checkout Button" desc="Always visible Buy Now on mobile." checked={s.sticky_checkout} onChange={e=>setV('sticky_checkout',e.target.checked)}/><T label="Show Savings" desc="Highlight discount amounts." checked={s.show_savings} onChange={e=>setV('show_savings',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-2"><Shield size={16} className="text-emerald-500"/><h3 className="font-bold">Safety & Trust</h3></div><div className="grid grid-cols-2 gap-3"><T label="Secure Payment" desc="SSL encrypted badge." checked={s.badge_secure!==false} onChange={e=>setV('badge_secure',e.target.checked)}/><T label="Guaranteed Safe" desc="Safe checkout badge." checked={s.badge_safe!==false} onChange={e=>setV('badge_safe',e.target.checked)}/></div><T label="Free Shipping" desc="Free shipping visual." checked={s.badge_free_ship} onChange={e=>setV('badge_free_ship',e.target.checked)}/></div>
<div className="glass-card-solid p-6 space-y-3"><div className="flex items-center gap-2"><Code size={16}/><h3 className="font-bold">Developer Protocol</h3></div><textarea className="input-field font-mono text-xs" rows={3} value={s.post_script||''} onChange={set('post_script')} placeholder="<script>console.log('Order received!')</script>"/><p className="text-[10px] text-gray-400">Runs on checkout page only.</p></div></>}

{sec==='shipping'&&<><div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-4"><h3 className="font-bold text-gray-900">Shipping Wilayas ({wilayas.length}/58)</h3><button onClick={seedW} className="btn-primary text-xs">Load All 58 Wilayas</button></div>{wilayas.length===0?<p className="text-center py-8 text-gray-400">Click "Load All 58 Wilayas" to set up rates.</p>:<div className="max-h-96 overflow-y-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-white"><tr className="text-left text-xs text-gray-400 uppercase"><th className="pb-2">Code</th><th className="pb-2">Wilaya</th><th className="pb-2">Desk</th><th className="pb-2">Home</th><th className="pb-2">Days</th></tr></thead><tbody>{wilayas.map(w=>(<tr key={w.id} className="border-t border-gray-50"><td className="py-2 font-mono text-xs text-gray-400">{w.wilaya_code}</td><td className="font-medium">{w.wilaya_name}</td><td>{w.desk_delivery_price} DZD</td><td>{w.home_delivery_price} DZD</td><td>{w.delivery_days}d</td></tr>))}</tbody></table></div>}</div></>}

{sec==='payments'&&<div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold mb-2">Payment Methods</h3><T label="Cash on Delivery (COD)" desc="Pay in cash upon delivery." checked={s.enable_cod} onChange={set('enable_cod')}/><T label="CCP Direct Transfer" checked={s.enable_ccp} onChange={set('enable_ccp')}/>{s.enable_ccp&&<div className="grid grid-cols-2 gap-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">CCP Account</label><input className="input-field" value={s.ccp_account||''} onChange={set('ccp_account')}/></div><div><label className="input-label text-xs">CCP Name</label><input className="input-field" value={s.ccp_name||''} onChange={set('ccp_name')}/></div></div>}<T label="BaridiMob QR" checked={s.enable_baridimob} onChange={set('enable_baridimob')}/>{s.enable_baridimob&&<div className="pl-4 border-l-2 border-brand-200"><label className="input-label text-xs">RIP</label><input className="input-field" value={s.baridimob_rip||''} onChange={set('baridimob_rip')}/></div>}<T label="Bank Transfer" checked={s.enable_bank_transfer} onChange={set('enable_bank_transfer')}/>{s.enable_bank_transfer&&<div className="grid grid-cols-3 gap-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">Bank</label><input className="input-field" value={s.bank_name||''} onChange={set('bank_name')}/></div><div><label className="input-label text-xs">Account</label><input className="input-field" value={s.bank_account||''} onChange={set('bank_account')}/></div><div><label className="input-label text-xs">RIB</label><input className="input-field" value={s.bank_rib||''} onChange={set('bank_rib')}/></div></div>}<T label="Terms & Conditions" desc="Require agreement before checkout." checked={s.require_terms} onChange={e=>setV('require_terms',e.target.checked)}/><T label="Marketing Opt-in" desc="Newsletter subscription." checked={s.marketing_optin} onChange={e=>setV('marketing_optin',e.target.checked)}/></div>}

{sec==='ai'&&<div className="glass-card-solid p-6 space-y-4"><h3 className="font-bold">AI Features</h3><T label="AI Chatbot" desc="Smart customer support bot." checked={s.ai_chatbot_enabled} onChange={set('ai_chatbot_enabled')}/>{s.ai_chatbot_enabled&&<div className="space-y-3 pl-4 border-l-2 border-brand-200"><div><label className="input-label text-xs">Bot Name</label><input className="input-field" value={s.ai_chatbot_name||''} onChange={set('ai_chatbot_name')}/></div><div><label className="input-label text-xs">Greeting</label><textarea className="input-field" rows={2} value={s.ai_chatbot_greeting||''} onChange={set('ai_chatbot_greeting')}/></div></div>}<T label="Fake Order Detection" desc="Score orders for fraud risk." checked={s.ai_fake_detection} onChange={set('ai_fake_detection')}/><T label="Cart Recovery" desc="Automated WhatsApp sequences." checked={s.ai_cart_recovery} onChange={set('ai_cart_recovery')}/></div>}

{['taxes','notifications','orders-config','customers-config','inventory','marketing','domains','subscription','account'].includes(sec)&&<div className="glass-card-solid p-12 text-center"><SI size={48} className="mx-auto text-gray-300 mb-4"/><h3 className="font-bold text-gray-900 mb-2">{secs.find(x=>x.id===sec)?.l}</h3><p className="text-gray-400 text-sm">This section is being built. Coming soon!</p></div>}

      </div>
    </div>
    {showRole&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowRole(null)}><div className="bg-white rounded-3xl p-8 w-full max-w-2xl max-h-[80vh] overflow-y-auto shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">Edit Role</h2><button onClick={()=>setShowRole(null)} className="text-gray-400 hover:text-gray-600">✕</button></div><div className="grid grid-cols-2 gap-4 mb-4"><div><label className="input-label text-xs">Role Name</label><input className="input-field" value={roles[showRole]?.label} readOnly/></div><div><label className="input-label text-xs">Description</label><input className="input-field" value={roles[showRole]?.desc} readOnly/></div></div><h3 className="font-bold text-sm mb-3">Permissions</h3><div className="grid grid-cols-2 gap-4">{[['Orders',['View Dashboard','View Orders','Manage Orders','Delete Orders','Confirm Orders','Prepare Orders','Transfer Orders','Manage Shipping']],['Products',['View Products','Manage Products','Delete Products']],['Inventory',['Manage Inventory']],['Customers',['View Customers','Manage Customers']]].map(([cat,perms])=>(<div key={cat}><h4 className="font-bold text-xs text-gray-500 uppercase mb-2">{cat}</h4>{perms.map(p=>{const has=roles[showRole]?.perms.includes(p);return(<label key={p} className="flex items-center gap-2 mb-1.5 cursor-pointer"><div className={`w-5 h-5 rounded flex items-center justify-center text-white text-xs ${has?'bg-brand-500':'bg-gray-200'}`}>{has&&<Check size={12}/>}</div><div><p className="text-sm text-gray-700">{p}</p></div></label>);})}</div>))}</div><div className="flex gap-3 mt-6"><button onClick={()=>setShowRole(null)} className="btn-ghost flex-1">Cancel</button><button onClick={()=>{setShowRole(null);toast.success('Updated!');}} className="btn-primary flex-1">Update Role</button></div></div></div>}
    {showStaff&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm" onClick={()=>setShowStaff(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-bold mb-6">Create New User</h2><div className="space-y-3"><div><label className="input-label">Name</label><input className="input-field" value={sf.name} onChange={e=>setSf({...sf,name:e.target.value})}/></div><div><label className="input-label">Email</label><input className="input-field" value={sf.email} onChange={e=>setSf({...sf,email:e.target.value})}/></div><div><label className="input-label">Phone</label><input className="input-field" value={sf.phone} onChange={e=>setSf({...sf,phone:e.target.value})}/></div><div><label className="input-label">Password</label><input type="password" className="input-field" value={sf.password} onChange={e=>setSf({...sf,password:e.target.value})}/></div><div><label className="input-label">Role</label><select className="input-field" value={sf.role} onChange={e=>setSf({...sf,role:e.target.value})}><option value="admin">Admin</option><option value="preparer">Preparer</option><option value="confirmer">Confirmer</option><option value="accountant">Accountant</option><option value="viewer">Viewer</option></select></div></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowStaff(false)} className="btn-ghost flex-1">Cancel</button><button onClick={addStaff} className="btn-primary flex-1">Create</button></div></div></div>}
  </DashboardLayout>);
}
