import React,{useState} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import toast from'react-hot-toast';import{Zap,Check,X,ChevronDown,Shield,Clock,ArrowRight,CreditCard,Star}from'lucide-react';
export default function StoreBilling(){const[selected,setSelected]=useState(null);const[showPay,setShowPay]=useState(false);const[faqOpen,setFaqOpen]=useState(null);
const plans=[{id:'basic',name:'Basic Plan',price:'2 900',desc:'Perfect for new entrepreneurs starting their online journey.',features:[{t:'Up to 50 Products',ok:true},{t:'Up to 300 Orders / month',ok:true},{t:'1 Admin User',ok:true},{t:'Basic Analytics Dashboard',ok:true},{t:'Standard Email Support',ok:true},{t:'WhatsApp Automation',ok:false},{t:'Abandoned Cart Recovery',ok:false},{t:'Custom Domain',ok:false},{t:'API Access',ok:false}]},
{id:'advanced',name:'Advanced Plan',price:'7 900',popular:true,desc:'All-in-one platform for scaling stores with AI-powered tools.',features:[{t:'Unlimited Products',ok:true},{t:'Unlimited Orders',ok:true},{t:'Multiple Admin Users',ok:true},{t:'Advanced Analytics & Reports',ok:true},{t:'Priority 24/7 Support',ok:true},{t:'WhatsApp Automation',ok:true},{t:'Abandoned Cart Recovery',ok:true},{t:'Custom Domain Support',ok:true},{t:'Full API Access',ok:true},{t:'AI Product Assistant',ok:true}]}];
const faqs=[{q:'How does payment verification work?',a:'After subscribing, upload your payment receipt. We verify it manually within 24 hours.'},{q:'Can I upgrade or downgrade my plan?',a:'Yes, you can change your plan at any time. The difference is prorated.'},{q:'What happens when my subscription expires?',a:'Your store remains live but you cannot add new products or process orders until renewed.'},{q:'Is there a refund policy?',a:'Yes, we offer a 7-day money back guarantee on all plans.'},{q:'What payment methods do you accept?',a:'We accept Edahabia, BaridiMob, CCP Transfer, and Bank Transfer.'}];
return(<DashboardLayout>
<h1 className="text-2xl font-bold mb-6">Billing & Plans</h1>
{/* Plans */}
<div className="grid lg:grid-cols-2 gap-6 mb-8">
{plans.map(p=>(<div key={p.id} className={`glass-card-solid p-8 relative ${p.popular?'ring-2 ring-brand-500':''}`}>
{p.popular&&<span className="absolute top-4 right-4 badge bg-brand-500 text-white text-[10px]">MOST POPULAR</span>}
<div className={`w-12 h-12 rounded-2xl ${p.popular?'bg-gradient-to-br from-brand-500 to-purple-600':'bg-gradient-to-br from-cyan-500 to-blue-600'} flex items-center justify-center mb-4`}><Zap size={22} className="text-white"/></div>
<h3 className="text-xl font-bold mb-1">{p.name}</h3><p className="text-sm text-gray-500 mb-4">{p.desc}</p>
<div className="mb-6"><span className="text-4xl font-black">{p.price} DZD</span><span className="text-gray-400 text-sm"> /month</span><p className="text-xs text-brand-500 mt-1">⏱ 7-day free trial included</p></div>
<div className="space-y-2 mb-6">{p.features.map((f,i)=>(<div key={i} className="flex items-center gap-2"><div className={`w-5 h-5 rounded-full flex items-center justify-center ${f.ok?'bg-emerald-100 text-emerald-600':'bg-gray-100 text-gray-400'}`}>{f.ok?<Check size={12}/>:<X size={12}/>}</div><span className={`text-sm ${f.ok?'text-gray-800':'text-gray-400 line-through'}`}>{f.t}</span></div>))}</div>
<button onClick={()=>{setSelected(p.id);setShowPay(true);toast.success(`${p.name} selected!`);}} className={`w-full py-3.5 rounded-xl font-bold flex items-center justify-center gap-2 ${p.popular?'bg-gradient-to-r from-brand-500 to-purple-600 text-white':'bg-gradient-to-r from-cyan-500 to-blue-600 text-white'}`}>SUBSCRIBE NOW <ArrowRight size={16}/></button>
</div>))}
</div>
{/* Payment methods */}
<div className="text-center mb-8"><h2 className="text-2xl font-bold mb-2">Accepted Payment Methods</h2><p className="text-gray-500">100% local Algerian payments — no foreign cards needed.</p>
<div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{[{icon:'🏦',name:'Edahabia',desc:'Algeria Post Dahabia card'},{icon:'📱',name:'BaridiMob',desc:'Mobile payment via BaridiPay'},{icon:'💳',name:'CCP Transfer',desc:'Algeria Post CCP account'},{icon:'🏛️',name:'Bank Transfer',desc:'BEA / BNA / CNEP bank wire'}].map(m=>(<div key={m.name} className="glass-card-solid p-6 text-center"><span className="text-3xl block mb-2">{m.icon}</span><h3 className="font-bold">{m.name}</h3><p className="text-xs text-gray-400">{m.desc}</p></div>))}</div></div>
{/* How it works */}
<div className="glass-card-solid p-8 mb-8 text-center"><h2 className="text-2xl font-bold mb-6">How Subscription Works</h2><div className="grid grid-cols-4 gap-4">{[{n:'01',t:'Choose Plan',d:'Select Basic or Advanced, pick monthly or yearly.'},{n:'02',t:'Pay Locally',d:'Use Edahabia, BaridiMob, CCP or bank wire.'},{n:'03',t:'Upload Receipt',d:'Take a screenshot and upload it here.'},{n:'04',t:'Activate (24h)',d:'We verify and activate within 24 hours.'}].map(s=>(<div key={s.n}><div className="w-12 h-12 rounded-full bg-brand-50 flex items-center justify-center mx-auto mb-2"><span className="text-brand-500 font-bold">{s.n}</span></div><h4 className="font-bold text-sm">{s.t}</h4><p className="text-xs text-gray-400 mt-1">{s.d}</p></div>))}</div></div>
{/* FAQ */}
<div className="max-w-2xl mx-auto"><h2 className="text-2xl font-bold text-center mb-6">Frequently Asked Questions</h2>{faqs.map((f,i)=>(<div key={i} className="glass-card-solid mb-3 overflow-hidden"><button onClick={()=>setFaqOpen(faqOpen===i?null:i)} className="w-full flex items-center justify-between p-5 text-left"><span className="font-medium text-gray-800">{f.q}</span><ChevronDown size={16} className={`text-gray-400 transition-transform ${faqOpen===i?'rotate-180':''}`}/></button>{faqOpen===i&&<div className="px-5 pb-5 text-sm text-gray-600">{f.a}</div>}</div>))}</div>
{/* Trust */}
<div className="grid grid-cols-3 gap-4 mt-8">{[{icon:Shield,t:'Secure Payments',d:'All transfers are verified manually.'},{icon:Clock,t:'Fast Activation',d:'Store activated within 24 hours.'},{icon:Star,t:'7-Day Money Back',d:'Not satisfied? Full refund within 7 days.'}].map((s,i)=>{const I=s.icon;return(<div key={i} className="glass-card-solid p-6 text-center"><I size={32} className="mx-auto text-brand-500 mb-3"/><h3 className="font-bold">{s.t}</h3><p className="text-xs text-gray-400">{s.d}</p></div>);})}</div>
{showPay&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={()=>setShowPay(false)}><div className="bg-white rounded-3xl p-8 w-full max-w-md" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-bold mb-4">Upload Payment Receipt</h2><p className="text-sm text-gray-500 mb-4">Pay via any method above, then upload a screenshot of your receipt.</p><div className="border-2 border-dashed border-gray-300 rounded-2xl p-8 text-center cursor-pointer hover:border-brand-400"><p className="text-sm text-gray-500">Click to upload receipt image</p></div><div className="flex gap-3 mt-6"><button onClick={()=>setShowPay(false)} className="btn-ghost flex-1">Cancel</button><button onClick={()=>{setShowPay(false);toast.success('Receipt uploaded! We will verify within 24 hours.');}} className="btn-primary flex-1">Submit</button></div></div></div>}
</DashboardLayout>);}
