import React,{useState,useEffect} from'react';import{useStoreManagement}from'../../hooks/useStore';import DashboardLayout from'../../components/shared/DashboardLayout';import api from'../../utils/api';import{Search,Users,Download,Upload,Plus,Phone}from'lucide-react';
export default function StoreCustomers(){const{currentStore}=useStoreManagement();const[customers,setCustomers]=useState([]);const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[loading,setLoading]=useState(true);
useEffect(()=>{if(!currentStore?.id)return;api.get(`/manage/stores/${currentStore.id}/customers`,{params:{search}}).then(r=>setCustomers(Array.isArray(r.data)?r.data:[])).catch(()=>setCustomers([])).finally(()=>setLoading(false));},[currentStore?.id,search]);
const filtered=customers.filter(c=>{if(filter==='vip')return c.total_spent>5000;if(filter==='repeat')return c.total_orders>1;if(filter==='new')return c.total_orders<=1;if(filter==='inactive')return!c.is_active;return true;});
return(<DashboardLayout>
<div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold">Customers</h1><div className="flex gap-2"><button className="btn-ghost text-xs flex items-center gap-1"><Download size={14}/>Export</button><button className="btn-ghost text-xs flex items-center gap-1"><Upload size={14}/>Import</button><button className="btn-primary text-xs flex items-center gap-1"><Plus size={14}/>Add customer</button></div></div>
<div className="flex items-center gap-4 mb-4"><div className="relative flex-1 max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input-field !pl-9" placeholder="Search customers..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
<div className="flex gap-1">{['all','VIP','Repeat','New','Inactive'].map(f=>(<button key={f} onClick={()=>setFilter(f.toLowerCase())} className={`px-3 py-1.5 rounded-full text-xs font-bold transition-colors ${filter===f.toLowerCase()?'bg-brand-500 text-white':'text-gray-500 hover:bg-gray-100'}`}>{f}</button>))}</div></div>
<div className="glass-card-solid overflow-hidden">
{loading?<div className="p-12 text-center"><div className="w-8 h-8 border-3 border-brand-200 border-t-brand-500 rounded-full animate-spin mx-auto"/></div>:filtered.length===0?<div className="p-12 text-center"><Users size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500">No customers found</p></div>:(
<table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs text-gray-500 uppercase"><th className="px-4 py-3">Customer Name</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Location</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">Total Spent</th></tr></thead>
<tbody>{filtered.map(c=>(<tr key={c.id} className="border-t border-gray-100 hover:bg-gray-50"><td className="px-4 py-3"><div><p className="font-semibold text-gray-800">{c.name||c.full_name}</p><p className="text-xs text-gray-400">{c.email||'—'}</p></div></td><td className="px-4 py-3"><span className={`badge text-[10px] ${c.total_orders>3?'badge-warning':c.total_orders>1?'badge-info':'badge-success'}`}>{c.total_orders>3?'VIP':c.total_orders>1?'Repeat':'New'}</span></td><td className="px-4 py-3 text-gray-600"><span className="flex items-center gap-1">{c.phone} <Phone size={12} className="text-green-500"/></span></td><td className="px-4 py-3 text-gray-500">{c.city||c.wilaya||'Unknown'}</td><td className="px-4 py-3">{c.total_orders||0} orders</td><td className="px-4 py-3 font-bold">{parseFloat(c.total_spent||0).toLocaleString()}DZD</td></tr>))}</tbody></table>)}
</div></DashboardLayout>);}
