import React,{useState} from'react';import DashboardLayout from'../../components/shared/DashboardLayout';import{useTranslation}from'react-i18next';import toast from'react-hot-toast';import{Plus,DollarSign,TrendingUp,TrendingDown,Edit,Trash2,X}from'lucide-react';
const cats=['Operations','Marketing','Utilities','Inventory','Salaries','Rent','Other'];
export default function StoreCosts(){const{t}=useTranslation();
const[expenses,setExpenses]=useState([]);
const[showModal,setShowModal]=useState(false);
const[editing,setEditing]=useState(null);
const[form,setForm]=useState({description:'',category:'Other',date:new Date().toISOString().split('T')[0],amount:'',status:'Paid'});
const total=expenses.reduce((s,e)=>s+parseFloat(e.amount||0),0);
const fixed=expenses.filter(e=>['Rent','Salaries'].includes(e.category)).reduce((s,e)=>s+parseFloat(e.amount||0),0);
const variable=total-fixed;
const save=()=>{if(!form.description||!form.amount){toast.error('Fill all fields');return;}
if(editing!==null){setExpenses(expenses.map((e,i)=>i===editing?{...form}:e));setEditing(null);}
else{setExpenses([...expenses,{...form,id:Date.now()}]);}
setShowModal(false);setForm({description:'',category:'Other',date:new Date().toISOString().split('T')[0],amount:'',status:'Paid'});toast.success('Saved!');};
const edit=(i)=>{setEditing(i);setForm(expenses[i]);setShowModal(true);};
const del=(i)=>{setExpenses(expenses.filter((_,idx)=>idx!==i));toast.success('Deleted');};
return(<DashboardLayout>
<div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold">Costs</h1><p className="text-sm text-gray-500">Showing activity for {new Date().toLocaleDateString('en',{month:'long',year:'numeric'})}</p></div><button onClick={()=>{setEditing(null);setForm({description:'',category:'Other',date:new Date().toISOString().split('T')[0],amount:'',status:'Paid'});setShowModal(true);}} className="btn-primary flex items-center gap-2"><Plus size={16}/>Add Expense</button></div>
<div className="grid grid-cols-3 gap-6 mb-6">
<div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-2"><div className="w-10 h-10 rounded-xl bg-red-50 flex items-center justify-center"><DollarSign size={20} className="text-red-500"/></div>{total>0&&<span className="text-xs text-red-500 font-bold flex items-center gap-0.5"><TrendingUp size={12}/>+12.5%</span>}</div><p className="text-xs text-gray-400 uppercase font-bold">Total Expenses</p><p className="text-2xl font-bold">DZD {total.toLocaleString()}</p></div>
<div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-2"><div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center"><DollarSign size={20} className="text-blue-500"/></div></div><p className="text-xs text-gray-400 uppercase font-bold">Fixed Costs</p><p className="text-2xl font-bold">DZD {fixed.toLocaleString()}</p></div>
<div className="glass-card-solid p-6"><div className="flex items-center justify-between mb-2"><div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center"><DollarSign size={20} className="text-emerald-500"/></div></div><p className="text-xs text-gray-400 uppercase font-bold">Variable Costs</p><p className="text-2xl font-bold">DZD {variable.toLocaleString()}</p></div>
</div>
{expenses.length===0?<div className="glass-card-solid p-12 text-center"><DollarSign size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500 mb-2">No expenses recorded yet</p><p className="text-sm text-gray-400">Click "Add Expense" to start tracking your costs.</p></div>:(
<div className="glass-card-solid overflow-hidden"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs text-gray-500 uppercase"><th className="px-4 py-3">Expense</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead>
<tbody>{expenses.map((e,i)=>(<tr key={i} className="border-t border-gray-100 hover:bg-gray-50"><td className="px-4 py-3 font-medium">{e.description}</td><td className="px-4 py-3"><span className="badge badge-info text-[10px]">{e.category}</span></td><td className="px-4 py-3 text-gray-500">{e.date}</td><td className="px-4 py-3 font-bold">DZD {parseFloat(e.amount).toLocaleString()}</td><td className="px-4 py-3"><span className={`badge ${e.status==='Paid'?'badge-success':'badge-warning'} text-[10px]`}>{e.status}</span></td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={()=>edit(i)} className="p-1.5 hover:bg-gray-100 rounded text-gray-400 hover:text-brand-500"><Edit size={14}/></button><button onClick={()=>del(i)} className="p-1.5 hover:bg-red-50 rounded text-gray-400 hover:text-red-500"><Trash2 size={14}/></button></div></td></tr>))}</tbody></table></div>)}
{showModal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm" onClick={()=>setShowModal(false)}><div className="bg-gray-900 text-white rounded-3xl p-8 w-full max-w-md shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-6"><h2 className="text-xl font-bold">{editing!==null?'Edit Expense':'Add Expense'}</h2><button onClick={()=>setShowModal(false)} className="text-white/50 hover:text-white"><X size={20}/></button></div>
<div className="space-y-4"><div><label className="text-xs text-white/50 uppercase font-bold">Description</label><input className="w-full bg-white/10 border border-white/10 rounded-xl px-4 py-3 text-white mt-1" placeholder="e.g. Monthly Internet Bill" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
<div className="grid grid-cols-2 gap-4"><div><label className="text-xs text-white/50 uppercase font-bold">Category</label><select className="w-full bg-white/10 border border-white/10 rounded-xl px-4 py-3 text-white mt-1" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{cats.map(c=>(<option key={c} value={c}>{c}</option>))}</select></div><div><label className="text-xs text-white/50 uppercase font-bold">Date</label><input type="date" className="w-full bg-white/10 border border-white/10 rounded-xl px-4 py-3 text-white mt-1" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div></div>
<div className="grid grid-cols-2 gap-4"><div><label className="text-xs text-white/50 uppercase font-bold">Amount</label><input type="number" className="w-full bg-white/10 border border-white/10 rounded-xl px-4 py-3 text-white mt-1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div><label className="text-xs text-white/50 uppercase font-bold">Status</label><select className="w-full bg-white/10 border border-white/10 rounded-xl px-4 py-3 text-white mt-1" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Paid</option><option>Pending</option></select></div></div></div>
<div className="flex gap-3 mt-6"><button onClick={()=>setShowModal(false)} className="flex-1 py-3 bg-white/10 rounded-xl font-medium">Cancel</button><button onClick={save} className="flex-1 py-3 bg-brand-500 rounded-xl font-bold">Add Expense</button></div></div></div>}
</DashboardLayout>);}
