import React,{useState,useRef,useEffect} from 'react';
import {aiApi} from '../../utils/api';
import {MessageCircle,Phone,Send,X,Save,Clock,ShoppingCart,QrCode,RefreshCw,Wifi,WifiOff} from 'lucide-react';

const WA_STATUSES=['new_order','confirmed','under_preparation','shipped','delivered','cancelled','awaiting','failed_call_1','failed_call_2','failed_call_3','returned'];
const WA_STATUS_LABELS={new_order:{en:'New Order',fr:'Nouvelle commande',ar:'طلب جديد'},confirmed:{en:'Confirmed',fr:'Confirmé',ar:'تم التأكيد'},under_preparation:{en:'Under Preparation',fr:'En préparation',ar:'قيد التحضير'},shipped:{en:'Shipped',fr:'Expédié',ar:'تم الشحن'},delivered:{en:'Delivered',fr:'Livré',ar:'تم التسليم'},cancelled:{en:'Cancelled',fr:'Annulé',ar:'ملغي'},awaiting:{en:'Awaiting',fr:'En attente',ar:'في الانتظار'},failed_call_1:{en:'Failed Call 1',fr:'Appel échoué 1',ar:'اتصال فاشل 1'},failed_call_2:{en:'Failed Call 2',fr:'Appel échoué 2',ar:'اتصال فاشل 2'},failed_call_3:{en:'Failed Call 3',fr:'Appel échoué 3',ar:'اتصال فاشل 3'},returned:{en:'Returned',fr:'Retourné',ar:'مرتجع'}};
const WA_TIMING_OPTIONS=[{v:'immediately',en:'Immediately',fr:'Immédiatement',ar:'فورا'},{v:'5min',en:'After 5 min',fr:'Après 5 min',ar:'بعد 5 دقائق'},{v:'15min',en:'After 15 min',fr:'Après 15 min',ar:'بعد 15 دقيقة'},{v:'30min',en:'After 30 min',fr:'Après 30 min',ar:'بعد 30 دقيقة'},{v:'1hour',en:'After 1 hour',fr:'Après 1 heure',ar:'بعد ساعة'},{v:'2hours',en:'After 2 hours',fr:'Après 2 heures',ar:'بعد ساعتين'}];
const WA_CART_TIMING=[{v:'1hour',en:'After 1 hour',fr:'Après 1 heure',ar:'بعد ساعة'},{v:'3hours',en:'After 3 hours',fr:'Après 3 heures',ar:'بعد 3 ساعات'},{v:'6hours',en:'After 6 hours',fr:'Après 6 heures',ar:'بعد 6 ساعات'},{v:'12hours',en:'After 12 hours',fr:'Après 12 heures',ar:'بعد 12 ساعة'},{v:'24hours',en:'After 24 hours',fr:'Après 24 heures',ar:'بعد 24 ساعة'}];
const WA_VARS=['{store_name}','{order_number}','{customer_name}','{total}','{currency}','{shipping_address}','{shipping_city}','{shipping_wilaya}','{payment_method}','{tracking_number}','{delivery_company}'];
const WA_CART_VARS=['{store_name}','{cart_url}','{item_count}','{customer_name}'];
const WA_DEFAULT_TEMPLATES={
  en:{new_order:'Hi {customer_name}! We received your order #{order_number} at {store_name}. Total: {total} {currency}. We will process it shortly!',confirmed:'Hi {customer_name}! Your order #{order_number} from {store_name} has been confirmed. Total: {total} {currency}. We\'ll keep you updated!',under_preparation:'Hello {customer_name}! Your order #{order_number} is now being prepared at {store_name}. We\'ll notify you once it ships!',shipped:'Great news {customer_name}! Your order #{order_number} has been shipped. Track: {tracking_number}. Delivery by {delivery_company}.',delivered:'Your order #{order_number} has been delivered! Thank you for shopping at {store_name}!',cancelled:'Hi {customer_name}, your order #{order_number} from {store_name} has been cancelled. If this was a mistake, please contact us.',awaiting:'Hi {customer_name}, your order #{order_number} is awaiting confirmation. We will get back to you soon!',failed_call_1:'Hi {customer_name}, we tried to reach you about order #{order_number}. Please call us back at your convenience.',failed_call_2:'Hello {customer_name}, this is our second attempt to reach you about order #{order_number}. Please respond as soon as possible.',failed_call_3:'Dear {customer_name}, we have been unable to reach you about order #{order_number}. Your order may be cancelled if we don\'t hear from you.',returned:'Hi {customer_name}, your order #{order_number} has been returned. Please contact {store_name} for more details.',abandoned_cart:'Hi {customer_name}! You left {item_count} item(s) in your cart at {store_name}. Complete your order here: {cart_url}'},
  fr:{new_order:'Bonjour {customer_name}! Nous avons reçu votre commande #{order_number} chez {store_name}. Total: {total} {currency}.',confirmed:'Bonjour {customer_name}! Votre commande #{order_number} de {store_name} est confirmée. Total: {total} {currency}.',under_preparation:'Bonjour {customer_name}! Votre commande #{order_number} est en cours de préparation chez {store_name}.',shipped:'Bonne nouvelle {customer_name}! Votre commande #{order_number} a été expédiée. Suivi: {tracking_number}. Livraison par {delivery_company}.',delivered:'Votre commande #{order_number} a été livrée! Merci d\'avoir choisi {store_name}!',cancelled:'Bonjour {customer_name}, votre commande #{order_number} de {store_name} a été annulée. Si c\'est une erreur, contactez-nous.',awaiting:'Bonjour {customer_name}, votre commande #{order_number} est en attente de confirmation.',failed_call_1:'Bonjour {customer_name}, nous avons essayé de vous joindre concernant la commande #{order_number}. Veuillez nous rappeler.',failed_call_2:'Bonjour {customer_name}, ceci est notre deuxième tentative pour la commande #{order_number}. Merci de nous répondre.',failed_call_3:'Cher {customer_name}, nous n\'arrivons pas à vous joindre pour la commande #{order_number}. Elle risque d\'être annulée.',returned:'Bonjour {customer_name}, votre commande #{order_number} a été retournée. Contactez {store_name} pour plus de détails.',abandoned_cart:'Bonjour {customer_name}! Vous avez laissé {item_count} article(s) dans votre panier chez {store_name}. Complétez ici: {cart_url}'},
  ar:{new_order:'مرحبا {customer_name}! استلمنا طلبك #{order_number} من {store_name}. المبلغ: {total} {currency}.',confirmed:'مرحبا {customer_name}! تم تأكيد طلبك #{order_number} من {store_name}. المبلغ: {total} {currency}.',under_preparation:'مرحبا {customer_name}! طلبك #{order_number} قيد التحضير في {store_name}.',shipped:'أخبار سارة {customer_name}! تم شحن طلبك #{order_number}. رقم التتبع: {tracking_number}. التوصيل عبر {delivery_company}.',delivered:'تم تسليم طلبك #{order_number}! شكرا لتسوقك من {store_name}!',cancelled:'مرحبا {customer_name}، تم إلغاء طلبك #{order_number} من {store_name}. إذا كان هذا خطأ، تواصل معنا.',awaiting:'مرحبا {customer_name}، طلبك #{order_number} في انتظار التأكيد.',failed_call_1:'مرحبا {customer_name}، حاولنا الاتصال بك بخصوص الطلب #{order_number}. يرجى معاودة الاتصال.',failed_call_2:'مرحبا {customer_name}، هذه المحاولة الثانية للاتصال بك بخصوص الطلب #{order_number}. يرجى الرد.',failed_call_3:'عزيزي {customer_name}، لم نتمكن من الوصول إليك بخصوص الطلب #{order_number}. قد يتم إلغاء طلبك.',returned:'مرحبا {customer_name}، تم إرجاع طلبك #{order_number}. تواصل مع {store_name} لمزيد من التفاصيل.',abandoned_cart:'مرحبا {customer_name}! تركت {item_count} منتج(ات) في سلتك في {store_name}. أكمل طلبك هنا: {cart_url}'}
};

export {WA_STATUSES,WA_STATUS_LABELS,WA_TIMING_OPTIONS,WA_CART_TIMING,WA_VARS,WA_CART_VARS,WA_DEFAULT_TEMPLATES};

export default function WhatsAppConfigModal({show,onClose,storeId,initialConfig,onSave}){
  const[cfg,setCfg]=useState({});
  const[lang,setLang]=useState('fr');
  const[activeStatus,setActiveStatus]=useState('confirmed');
  const[waStatus,setWaStatus]=useState(null);
  const[waLoading,setWaLoading]=useState(false);
  const[waError,setWaError]=useState(null);
  const msgRef=useRef(null);

  useEffect(()=>{if(show&&initialConfig)setCfg({...initialConfig});},[show,initialConfig]);
  useEffect(()=>{if(show&&storeId&&!waStatus)checkStatus();},[show,storeId]);

  const setV=(k,v)=>setCfg(p=>({...p,[k]:v}));

  // Template helpers
  const getTemplates=()=>{try{return cfg.wa_templates?JSON.parse(typeof cfg.wa_templates==='string'?cfg.wa_templates:JSON.stringify(cfg.wa_templates)):{};}catch{return{};}};
  const getTpl=(st)=>{const t=getTemplates();return t?.[lang]?.[st]||WA_DEFAULT_TEMPLATES[lang]?.[st]||'';};
  const setTpl=(st,val)=>{const t=getTemplates();if(!t[lang])t[lang]={};t[lang][st]=val;setV('wa_templates',JSON.stringify(t));};
  const getEnabled=(st)=>{try{const e=cfg.wa_enabled_statuses?JSON.parse(typeof cfg.wa_enabled_statuses==='string'?cfg.wa_enabled_statuses:JSON.stringify(cfg.wa_enabled_statuses)):{}; return e[st]!==false;}catch{return true;}};
  const setEnabled=(st,val)=>{try{const e=cfg.wa_enabled_statuses?JSON.parse(typeof cfg.wa_enabled_statuses==='string'?cfg.wa_enabled_statuses:JSON.stringify(cfg.wa_enabled_statuses)):{}; e[st]=val;setV('wa_enabled_statuses',JSON.stringify(e));}catch{}};
  const getTiming=(st)=>{try{const tm=cfg.wa_timing?JSON.parse(typeof cfg.wa_timing==='string'?cfg.wa_timing:JSON.stringify(cfg.wa_timing)):{}; return tm[st]||'immediately';}catch{return 'immediately';}};
  const setTiming=(st,val)=>{try{const tm=cfg.wa_timing?JSON.parse(typeof cfg.wa_timing==='string'?cfg.wa_timing:JSON.stringify(cfg.wa_timing)):{}; tm[st]=val;setV('wa_timing',JSON.stringify(tm));}catch{}};

  const insertVar=(v)=>{const ta=msgRef.current;if(!ta)return;const start=ta.selectionStart;const end=ta.selectionEnd;const cur=getTpl(activeStatus);const nv=cur.substring(0,start)+v+cur.substring(end);setTpl(activeStatus,nv);setTimeout(()=>{ta.focus();ta.selectionStart=ta.selectionEnd=start+v.length;},50);};

  const preview=(tpl)=>{let m=tpl||'';m=m.replace(/\{store_name\}/g,cfg.name||cfg.store_name||'My Store');m=m.replace(/\{order_number\}/g,'100254');m=m.replace(/\{customer_name\}/g,'Ahmed');m=m.replace(/\{total\}/g,'3,500');m=m.replace(/\{currency\}/g,cfg.currency||'DZD');m=m.replace(/\{shipping_address\}/g,'12 Rue Didouche');m=m.replace(/\{shipping_city\}/g,'Alger');m=m.replace(/\{shipping_wilaya\}/g,'Alger');m=m.replace(/\{payment_method\}/g,'COD');m=m.replace(/\{tracking_number\}/g,'TR-98421');m=m.replace(/\{delivery_company\}/g,'Yalidine');m=m.replace(/\{cart_url\}/g,'https://store.com/cart/abc');m=m.replace(/\{item_count\}/g,'3');return m;};

  const startConnection=async()=>{if(!storeId)return;setWaLoading(true);setWaError(null);try{const{data}=await aiApi.waQrStart(storeId);if(data.qr||data.connected){setWaStatus(data);setWaLoading(false);return;}for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,2000));try{const{data:st}=await aiApi.waQrStatus(storeId);setWaStatus(st);if(st.qr||st.connected){setWaLoading(false);return;}}catch{}}setWaError('QR is taking a while. Try again.');}catch(e){setWaError(e.response?.data?.error||e.message);}setWaLoading(false);};
  const disconnect=async()=>{if(!storeId)return;try{await aiApi.waQrDisconnect(storeId);setWaStatus({status:'disconnected',connected:false});}catch{}};
  const checkStatus=async()=>{if(!storeId)return;try{const{data}=await aiApi.waQrStatus(storeId);setWaStatus(data);}catch{setWaStatus({status:'not_started',connected:false});}};

  const isRtl=lang==='ar';

  const handleSave=()=>{if(onSave)onSave(cfg);onClose();};

  if(!show)return null;

  return(<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 backdrop-blur-sm p-2 sm:p-4" onClick={onClose}>
    <div className="bg-white rounded-3xl w-full max-w-6xl max-h-[95vh] overflow-hidden shadow-2xl flex flex-col" onClick={e=>e.stopPropagation()}>
      {/* Header */}
      <div className="px-4 sm:px-6 py-4 border-b border-gray-100 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-emerald-500 flex items-center justify-center"><MessageCircle size={20} className="text-white"/></div><div><h2 className="font-black text-lg text-gray-900">WhatsApp Configuration</h2><p className="text-xs text-gray-400">Configure automated messages for every order status</p></div></div>
        <div className="flex items-center gap-2">
          <div className="flex bg-gray-100 rounded-xl p-1 gap-0.5">{[{c:'fr',l:'FR',f:'🇫🇷'},{c:'ar',l:'AR',f:'🇩🇿'},{c:'en',l:'EN',f:'🇬🇧'}].map(lg=>(<button key={lg.c} onClick={()=>{setLang(lg.c);setV('wa_language',lg.c);}} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1 ${lang===lg.c?'bg-white shadow text-gray-900':'text-gray-500 hover:text-gray-700'}`}><span>{lg.f}</span>{lg.l}</button>))}</div>
          <button onClick={onClose} className="w-8 h-8 rounded-lg hover:bg-gray-100 flex items-center justify-center"><X size={18}/></button>
        </div>
      </div>
      {/* Body */}
      <div className="flex-1 overflow-y-auto"><div className="flex flex-col lg:flex-row">
        {/* LEFT: WhatsApp Preview */}
        <div className="lg:w-[340px] shrink-0 p-4 sm:p-5 bg-gray-50 border-b lg:border-b-0 lg:border-r border-gray-100">
          <p className="text-[10px] font-bold text-gray-400 uppercase mb-3">Message Preview</p>
          <div className="bg-[#0b141a] rounded-2xl overflow-hidden shadow-xl max-w-[300px] mx-auto">
            <div className="bg-[#1f2c34] px-3 py-2 flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-emerald-600 flex items-center justify-center text-white text-xs font-bold">{(cfg.name||cfg.store_name||'S')[0]?.toUpperCase()}</div><div className="flex-1 min-w-0"><p className="text-white text-sm font-semibold truncate">{cfg.name||cfg.store_name||'My Store'}</p><p className="text-[10px] text-emerald-400">online</p></div><Phone size={16} className="text-gray-400"/></div>
            <div className="p-3 min-h-[280px] max-h-[350px] overflow-y-auto" style={{backgroundImage:'url("data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'none\' fill-rule=\'evenodd\'%3E%3Cg fill=\'%23ffffff\' fill-opacity=\'0.03\'%3E%3Cpath d=\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")'}}>
              <div className={`flex ${isRtl?'flex-row-reverse':''} mb-2`}><div className="max-w-[85%]"><div className="bg-[#005c4b] rounded-xl rounded-tl-sm px-3 py-2 shadow-sm" style={{direction:isRtl?'rtl':'ltr'}}><p className="text-white text-[13px] leading-relaxed whitespace-pre-wrap break-words">{preview(getTpl(activeStatus))||'Configure a message template...'}</p><div className={`flex items-center gap-1 mt-1 ${isRtl?'justify-start':'justify-end'}`}><span className="text-[10px] text-emerald-200">{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span className="text-emerald-300 text-[10px]">✓✓</span></div></div></div></div>
            </div>
            <div className="bg-[#1f2c34] px-3 py-2 flex items-center gap-2"><div className="flex-1 bg-[#2a3942] rounded-full px-3 py-1.5"><span className="text-gray-500 text-xs">Type a message</span></div><div className="w-8 h-8 rounded-full bg-emerald-600 flex items-center justify-center"><Send size={14} className="text-white"/></div></div>
          </div>
          <p className="text-[10px] text-gray-400 text-center mt-2">Preview updates in real-time as you type</p>
          {/* Connection Status */}
          <div className="mt-4 p-3 bg-white rounded-xl border border-gray-200">
            <div className="flex items-center justify-between mb-2"><p className="text-xs font-bold text-gray-700">Connection</p>{waStatus?.connected?<span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><Wifi size={12}/>Connected</span>:<span className="flex items-center gap-1 text-xs font-bold text-gray-400"><WifiOff size={12}/>Disconnected</span>}</div>
            {waStatus?.connected?(<button onClick={disconnect} className="w-full py-2 bg-red-50 text-red-600 rounded-lg text-xs font-bold hover:bg-red-100 transition-colors">Disconnect</button>):waStatus?.qr?(<div className="text-center"><img src={waStatus.qr.startsWith('data:')?waStatus.qr:`data:image/png;base64,${waStatus.qr}`} alt="QR" className="w-40 h-40 mx-auto rounded-lg border"/><p className="text-[10px] text-gray-400 mt-1">Scan with WhatsApp</p><button onClick={startConnection} className="mt-2 text-xs text-emerald-600 font-bold hover:underline flex items-center gap-1 mx-auto"><RefreshCw size={12}/>Refresh QR</button></div>):(<div><button onClick={startConnection} disabled={waLoading} className="w-full py-2.5 bg-emerald-500 text-white rounded-lg text-xs font-bold hover:bg-emerald-600 transition-colors flex items-center justify-center gap-2 disabled:opacity-50">{waLoading?<div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>:<QrCode size={14}/>}{waLoading?'Connecting...':'Connect WhatsApp'}</button>{waError&&<p className="text-xs text-red-500 mt-2 text-center">{waError}</p>}</div>)}
          </div>
        </div>
        {/* RIGHT: Configuration */}
        <div className="flex-1 min-w-0 p-4 sm:p-5 space-y-4">
          <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">Order Status Templates</p><div className="flex flex-wrap gap-1.5">{WA_STATUSES.map(st=>(<button key={st} onClick={()=>setActiveStatus(st)} className={`px-2.5 py-1.5 rounded-lg text-[11px] font-bold transition-all whitespace-nowrap ${activeStatus===st?'bg-emerald-500 text-white shadow-sm':'bg-gray-100 text-gray-600 hover:bg-gray-200'} ${!getEnabled(st)?'opacity-50':''}`}>{WA_STATUS_LABELS[st]?.[lang]||st}</button>))}</div></div>
          {/* Active Status Config */}
          <div className="bg-gray-50 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="font-bold text-sm text-gray-900 flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${getEnabled(activeStatus)?'bg-emerald-500':'bg-gray-300'}`}/>{WA_STATUS_LABELS[activeStatus]?.[lang]||activeStatus}</h4>
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-1.5"><Clock size={14} className="text-gray-400"/><select className="text-xs bg-white border border-gray-200 rounded-lg px-2 py-1.5 font-medium" value={getTiming(activeStatus)} onChange={e=>setTiming(activeStatus,e.target.value)}>{WA_TIMING_OPTIONS.map(o=><option key={o.v} value={o.v}>{o[lang]||o.en}</option>)}</select></div>
                <div className={`w-10 rounded-full cursor-pointer ${getEnabled(activeStatus)?'bg-emerald-500':'bg-gray-300'} relative transition-colors`} style={{height:22}} onClick={()=>setEnabled(activeStatus,!getEnabled(activeStatus))}><div className={`absolute bg-white rounded-full shadow transition-transform ${getEnabled(activeStatus)?'translate-x-5':'translate-x-0.5'}`} style={{width:18,height:18,top:2}}/></div>
              </div>
            </div>
            <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-1.5">Insert Variable</p><div className="flex flex-wrap gap-1">{WA_VARS.map(v=>(<button key={v} onClick={()=>insertVar(v)} className="px-2 py-1 bg-white border border-gray-200 rounded-md text-[10px] font-mono text-emerald-700 hover:bg-emerald-50 hover:border-emerald-300 transition-colors">{v}</button>))}</div></div>
            <div><textarea ref={msgRef} className="w-full bg-white border border-gray-200 rounded-xl px-3 py-2.5 text-sm resize-none focus:ring-2 focus:ring-emerald-300 focus:border-emerald-400 outline-none transition-all" rows={4} value={getTpl(activeStatus)} onChange={e=>setTpl(activeStatus,e.target.value)} placeholder="Type your message template..." style={{direction:isRtl?'rtl':'ltr'}} disabled={!getEnabled(activeStatus)}/><div className="flex items-center justify-between mt-1"><p className="text-[10px] text-gray-400">{getTpl(activeStatus).length} characters</p><button onClick={()=>setTpl(activeStatus,WA_DEFAULT_TEMPLATES[lang]?.[activeStatus]||'')} className="text-[10px] text-emerald-600 font-bold hover:underline">Reset to default</button></div></div>
          </div>
          {/* All Statuses Overview */}
          <div><p className="text-[10px] font-bold text-gray-400 uppercase mb-2">All Status Overview</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-[200px] overflow-y-auto pr-1">{WA_STATUSES.map(st=>(<div key={st} onClick={()=>setActiveStatus(st)} className={`flex items-center justify-between p-2.5 rounded-lg border cursor-pointer transition-all ${activeStatus===st?'border-emerald-400 bg-emerald-50':'border-gray-100 bg-white hover:border-gray-200'}`}><div className="flex items-center gap-2 min-w-0"><div className={`w-2 h-2 rounded-full shrink-0 ${getEnabled(st)?'bg-emerald-500':'bg-gray-300'}`}/><span className="text-xs font-medium text-gray-700 truncate">{WA_STATUS_LABELS[st]?.[lang]||st}</span></div><div className="flex items-center gap-1.5 shrink-0"><span className="text-[9px] text-gray-400 font-medium">{WA_TIMING_OPTIONS.find(o=>o.v===getTiming(st))?.[lang]||'Immediately'}</span><div className={`w-7 h-4 rounded-full ${getEnabled(st)?'bg-emerald-500':'bg-gray-300'} relative`} onClick={e=>{e.stopPropagation();setEnabled(st,!getEnabled(st));}}><div className={`absolute w-3 h-3 bg-white rounded-full shadow transition-transform ${getEnabled(st)?'translate-x-3.5':'translate-x-0.5'}`} style={{top:2}}/></div></div></div>))}</div></div>
          {/* Abandoned Cart */}
          <div className="bg-purple-50 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between"><div className="flex items-center gap-2"><ShoppingCart size={16} className="text-purple-600"/><h4 className="font-bold text-sm text-gray-900">Abandoned Cart Recovery</h4></div><div className="flex items-center gap-3"><div className="flex items-center gap-1.5"><Clock size={14} className="text-gray-400"/><select className="text-xs bg-white border border-gray-200 rounded-lg px-2 py-1.5 font-medium" value={cfg.wa_abandoned_cart_timing||'3hours'} onChange={e=>setV('wa_abandoned_cart_timing',e.target.value)}>{WA_CART_TIMING.map(o=><option key={o.v} value={o.v}>{o[lang]||o.en}</option>)}</select></div><div className={`w-10 rounded-full cursor-pointer ${cfg.wa_abandoned_cart_enabled?'bg-purple-500':'bg-gray-300'} relative transition-colors`} style={{height:22}} onClick={()=>setV('wa_abandoned_cart_enabled',!cfg.wa_abandoned_cart_enabled)}><div className={`absolute bg-white rounded-full shadow transition-transform ${cfg.wa_abandoned_cart_enabled?'translate-x-5':'translate-x-0.5'}`} style={{width:18,height:18,top:2}}/></div></div></div>
            <div className="flex flex-wrap gap-1">{WA_CART_VARS.map(v=>(<button key={v} onClick={()=>{const cur=cfg.wa_abandoned_cart_msg||WA_DEFAULT_TEMPLATES[lang]?.abandoned_cart||'';setV('wa_abandoned_cart_msg',cur+v);}} className="px-2 py-1 bg-white border border-purple-200 rounded-md text-[10px] font-mono text-purple-700 hover:bg-purple-50 transition-colors">{v}</button>))}</div>
            <textarea className="w-full bg-white border border-purple-200 rounded-xl px-3 py-2.5 text-sm resize-none focus:ring-2 focus:ring-purple-300 focus:border-purple-400 outline-none transition-all" rows={3} value={cfg.wa_abandoned_cart_msg||WA_DEFAULT_TEMPLATES[lang]?.abandoned_cart||''} onChange={e=>setV('wa_abandoned_cart_msg',e.target.value)} placeholder="Abandoned cart message..." style={{direction:isRtl?'rtl':'ltr'}} disabled={!cfg.wa_abandoned_cart_enabled}/>
          </div>
        </div>
      </div></div>
      {/* Footer */}
      <div className="px-4 sm:px-6 py-3 border-t border-gray-100 flex items-center justify-between shrink-0 bg-gray-50">
        <p className="text-[10px] text-gray-400">Changes are saved when you click Save & Close</p>
        <div className="flex items-center gap-2"><button onClick={onClose} className="px-4 py-2 text-xs font-bold text-gray-500 hover:text-gray-700">Close</button><button onClick={handleSave} className="px-4 py-2 bg-emerald-500 text-white rounded-xl text-xs font-bold hover:bg-emerald-600 flex items-center gap-1.5"><Save size={14}/>Save & Close</button></div>
      </div>
    </div>
  </div>);
}
