// Flat EN -> { fr, ar } dictionary used by the global DOM auto-translator.
// Add or extend entries here — every page in the app will pick them up
// automatically without needing per-component t() wrapping.
// Keys are matched against the trimmed text content of any text node, as well
// as placeholder / title / aria-label / value attributes on inputs & buttons.

const D = {
  // ==== Generic ====
  'Save': { fr: 'Enregistrer', ar: 'حفظ' },
  'Save Changes': { fr: 'Enregistrer les modifications', ar: 'حفظ التغييرات' },
  'Cancel': { fr: 'Annuler', ar: 'إلغاء' },
  'Delete': { fr: 'Supprimer', ar: 'حذف' },
  'Edit': { fr: 'Modifier', ar: 'تعديل' },
  'Add': { fr: 'Ajouter', ar: 'إضافة' },
  'Create': { fr: 'Créer', ar: 'إنشاء' },
  'Update': { fr: 'Mettre à jour', ar: 'تحديث' },
  'Search': { fr: 'Rechercher', ar: 'بحث' },
  'Loading...': { fr: 'Chargement...', ar: 'جار التحميل...' },
  'Loading': { fr: 'Chargement', ar: 'جار التحميل' },
  'No data found': { fr: 'Aucune donnée trouvée', ar: 'لا توجد بيانات' },
  'Confirm': { fr: 'Confirmer', ar: 'تأكيد' },
  'Back': { fr: 'Retour', ar: 'رجوع' },
  'Next': { fr: 'Suivant', ar: 'التالي' },
  'Previous': { fr: 'Précédent', ar: 'السابق' },
  'Submit': { fr: 'Envoyer', ar: 'إرسال' },
  'View All': { fr: 'Voir tout', ar: 'عرض الكل' },
  'View Details': { fr: 'Voir les détails', ar: 'عرض التفاصيل' },
  'View': { fr: 'Voir', ar: 'عرض' },
  'Close': { fr: 'Fermer', ar: 'إغلاق' },
  'Open': { fr: 'Ouvrir', ar: 'فتح' },
  'Yes': { fr: 'Oui', ar: 'نعم' },
  'No': { fr: 'Non', ar: 'لا' },
  'Active': { fr: 'Actif', ar: 'نشط' },
  'Inactive': { fr: 'Inactif', ar: 'غير نشط' },
  'Enabled': { fr: 'Activé', ar: 'مفعل' },
  'Disabled': { fr: 'Désactivé', ar: 'معطل' },
  'Status': { fr: 'Statut', ar: 'الحالة' },
  'Actions': { fr: 'Actions', ar: 'إجراءات' },
  'Refresh': { fr: 'Actualiser', ar: 'تحديث' },
  'Export': { fr: 'Exporter', ar: 'تصدير' },
  'Import': { fr: 'Importer', ar: 'استيراد' },
  'Download': { fr: 'Télécharger', ar: 'تنزيل' },
  'Upload': { fr: 'Téléverser', ar: 'تحميل' },
  'Filter': { fr: 'Filtrer', ar: 'تصفية' },
  'Filters': { fr: 'Filtres', ar: 'الفلاتر' },
  'All': { fr: 'Tous', ar: 'الكل' },
  'all': { fr: 'tous', ar: 'الكل' },
  'Total': { fr: 'Total', ar: 'الإجمالي' },
  'Subtotal': { fr: 'Sous-total', ar: 'المجموع الفرعي' },
  'Date': { fr: 'Date', ar: 'التاريخ' },
  'Name': { fr: 'Nom', ar: 'الاسم' },
  'Email': { fr: 'E-mail', ar: 'البريد الإلكتروني' },
  'Phone': { fr: 'Téléphone', ar: 'الهاتف' },
  'Phone Number': { fr: 'Numéro de téléphone', ar: 'رقم الهاتف' },
  'Address': { fr: 'Adresse', ar: 'العنوان' },
  'City': { fr: 'Ville', ar: 'المدينة' },
  'Wilaya': { fr: 'Wilaya', ar: 'الولاية' },
  'Country': { fr: 'Pays', ar: 'البلد' },
  'Password': { fr: 'Mot de passe', ar: 'كلمة المرور' },
  'Full Name': { fr: 'Nom complet', ar: 'الاسم الكامل' },
  'Description': { fr: 'Description', ar: 'الوصف' },
  'Category': { fr: 'Catégorie', ar: 'الفئة' },
  'Categories': { fr: 'Catégories', ar: 'الفئات' },
  'Price': { fr: 'Prix', ar: 'السعر' },
  'Stock': { fr: 'Stock', ar: 'المخزون' },
  'Quantity': { fr: 'Quantité', ar: 'الكمية' },
  'Image': { fr: 'Image', ar: 'صورة' },
  'Images': { fr: 'Images', ar: 'صور' },
  'Logo': { fr: 'Logo', ar: 'الشعار' },
  'Settings': { fr: 'Paramètres', ar: 'الإعدادات' },
  'Profile': { fr: 'Profil', ar: 'الملف الشخصي' },
  'Logout': { fr: 'Déconnexion', ar: 'تسجيل الخروج' },
  'Login': { fr: 'Connexion', ar: 'تسجيل الدخول' },
  'Sign in': { fr: 'Se connecter', ar: 'تسجيل الدخول' },
  'Sign up': { fr: 'S\'inscrire', ar: 'إنشاء حساب' },
  'Register': { fr: 'S\'inscrire', ar: 'تسجيل' },
  'Create Account': { fr: 'Créer un compte', ar: 'إنشاء حساب' },
  'Forgot password?': { fr: 'Mot de passe oublié ?', ar: 'هل نسيت كلمة المرور؟' },
  'Disconnect': { fr: 'Se déconnecter', ar: 'قطع الاتصال' },
  'Collapse': { fr: 'Réduire', ar: 'طي' },
  'Expand': { fr: 'Développer', ar: 'توسيع' },
  'Live': { fr: 'En direct', ar: 'مباشر' },
  'Offline': { fr: 'Hors ligne', ar: 'غير متصل' },
  'Online': { fr: 'En ligne', ar: 'متصل' },
  'Home': { fr: 'Accueil', ar: 'الرئيسية' },
  'Dashboard': { fr: 'Tableau de bord', ar: 'لوحة التحكم' },
  'Overview': { fr: 'Aperçu', ar: 'نظرة عامة' },
  'Welcome': { fr: 'Bienvenue', ar: 'مرحباً' },
  'Welcome back': { fr: 'Bon retour', ar: 'مرحباً بعودتك' },
  'Help': { fr: 'Aide', ar: 'المساعدة' },
  'Support': { fr: 'Support', ar: 'الدعم' },
  'Contact': { fr: 'Contact', ar: 'اتصل بنا' },
  'About': { fr: 'À propos', ar: 'حول' },
  'About Us': { fr: 'À propos de nous', ar: 'من نحن' },
  'Features': { fr: 'Fonctionnalités', ar: 'الميزات' },
  'Pricing': { fr: 'Tarifs', ar: 'الأسعار' },
  'FAQs': { fr: 'FAQ', ar: 'الأسئلة الشائعة' },
  'Search everything...': { fr: 'Rechercher partout...', ar: 'ابحث في كل شيء...' },
  'Search products...': { fr: 'Rechercher des produits...', ar: 'ابحث عن المنتجات...' },
  'Search orders...': { fr: 'Rechercher des commandes...', ar: 'ابحث عن الطلبات...' },
  'Search customers...': { fr: 'Rechercher des clients...', ar: 'ابحث عن العملاء...' },

  // ==== Sidebar / Menu ====
  'Main Menu': { fr: 'Menu principal', ar: 'القائمة الرئيسية' },
  'STORE DASHBOARD': { fr: 'TABLEAU DE BORD DU MAGASIN', ar: 'لوحة تحكم المتجر' },
  'Orders': { fr: 'Commandes', ar: 'الطلبات' },
  'Products': { fr: 'Produits', ar: 'المنتجات' },
  'Customers': { fr: 'Clients', ar: 'العملاء' },
  'Analytics': { fr: 'Analyses', ar: 'التحليلات' },
  'Apps': { fr: 'Applications', ar: 'التطبيقات' },
  'Apps & Integrations': { fr: 'Applications et intégrations', ar: 'التطبيقات والتكاملات' },
  'Staff': { fr: 'Personnel', ar: 'الموظفون' },
  'Staff Management': { fr: 'Gestion du personnel', ar: 'إدارة الموظفين' },
  'Stock Manager': { fr: 'Gestion des stocks', ar: 'إدارة المخزون' },
  'Smart Reviews': { fr: 'Avis intelligents', ar: 'المراجعات الذكية' },
  'AI Intelligence': { fr: 'Intelligence IA', ar: 'الذكاء الاصطناعي' },
  'Costs': { fr: 'Coûts', ar: 'التكاليف' },
  'Costs & Expenses': { fr: 'Coûts et dépenses', ar: 'التكاليف والمصاريف' },
  'Billing': { fr: 'Facturation', ar: 'الفوترة' },
  'Billing & Plans': { fr: 'Facturation et forfaits', ar: 'الفوترة والخطط' },
  'Billing & Subscription': { fr: 'Facturation et abonnement', ar: 'الفوترة والاشتراك' },
  'Domains': { fr: 'Domaines', ar: 'النطاقات' },
  'Domains & URLs': { fr: 'Domaines et URLs', ar: 'النطاقات والروابط' },
  'Taxes': { fr: 'Taxes', ar: 'الضرائب' },
  'Delivery': { fr: 'Livraison', ar: 'التوصيل' },
  'Store & Settings': { fr: 'Magasin et paramètres', ar: 'المتجر والإعدادات' },
  'All Settings': { fr: 'Tous les paramètres', ar: 'جميع الإعدادات' },
  'Page Builder': { fr: 'Constructeur de page', ar: 'منشئ الصفحات' },
  'Home Page': { fr: 'Page d\'accueil', ar: 'الصفحة الرئيسية' },
  'Contact Info': { fr: 'Coordonnées', ar: 'معلومات الاتصال' },
  'Shipping': { fr: 'Livraison', ar: 'الشحن' },
  'Shipping Partners': { fr: 'Partenaires de livraison', ar: 'شركاء الشحن' },
  'Shipping Wilayas': { fr: 'Wilayas de livraison', ar: 'ولايات الشحن' },
  'How to Connect': { fr: 'Comment se connecter', ar: 'كيفية الاتصال' },
  'Automatic Blacklist': { fr: 'Liste noire automatique', ar: 'القائمة السوداء التلقائية' },
  'Blacklist': { fr: 'Liste noire', ar: 'القائمة السوداء' },
  'Tracking Orders': { fr: 'Suivi des commandes', ar: 'تتبع الطلبات' },
  'Abandoned Orders': { fr: 'Commandes abandonnées', ar: 'الطلبات المتروكة' },
  'Cart Recovery': { fr: 'Récupération de panier', ar: 'استرداد السلة' },
  'Preparing': { fr: 'En préparation', ar: 'قيد التحضير' },

  // ==== Orders ====
  'Order': { fr: 'Commande', ar: 'الطلب' },
  'Pending': { fr: 'En attente', ar: 'قيد الانتظار' },
  'Confirmed': { fr: 'Confirmée', ar: 'مؤكدة' },
  'Shipped': { fr: 'Expédiée', ar: 'تم الشحن' },
  'Delivered': { fr: 'Livrée', ar: 'تم التسليم' },
  'Cancelled': { fr: 'Annulée', ar: 'ملغاة' },
  'Returned': { fr: 'Retournée', ar: 'مرتجعة' },
  'Customer': { fr: 'Client', ar: 'العميل' },
  'Customer Name': { fr: 'Nom du client', ar: 'اسم العميل' },
  'Total Spent': { fr: 'Total dépensé', ar: 'الإجمالي المنفق' },
  'Location': { fr: 'Emplacement', ar: 'الموقع' },
  'Unknown': { fr: 'Inconnu', ar: 'غير معروف' },
  'orders': { fr: 'commandes', ar: 'طلبات' },
  'No orders yet': { fr: 'Aucune commande pour le moment', ar: 'لا توجد طلبات بعد' },
  'Order Items': { fr: 'Articles de la commande', ar: 'عناصر الطلب' },
  'Payment Method': { fr: 'Mode de paiement', ar: 'طريقة الدفع' },
  'Shipping Address': { fr: 'Adresse de livraison', ar: 'عنوان الشحن' },
  'Tracking Number': { fr: 'Numéro de suivi', ar: 'رقم التتبع' },
  'Notes': { fr: 'Notes', ar: 'ملاحظات' },

  // ==== Products ====
  'Add Product': { fr: 'Ajouter un produit', ar: 'إضافة منتج' },
  'Edit Product': { fr: 'Modifier le produit', ar: 'تعديل المنتج' },
  'Product Name': { fr: 'Nom du produit', ar: 'اسم المنتج' },
  'No products yet': { fr: 'Aucun produit pour le moment', ar: 'لا توجد منتجات بعد' },
  'in stock': { fr: 'en stock', ar: 'متوفر' },
  'Out of stock': { fr: 'Rupture de stock', ar: 'نفد المخزون' },
  'Featured Product': { fr: 'Produit vedette', ar: 'منتج مميز' },

  // ==== Customers ====
  'Add customer': { fr: 'Ajouter un client', ar: 'إضافة عميل' },
  'No customers found': { fr: 'Aucun client trouvé', ar: 'لم يتم العثور على عملاء' },
  'VIP': { fr: 'VIP', ar: 'كبار الشخصيات' },
  'Repeat': { fr: 'Récurrent', ar: 'متكرر' },
  'New': { fr: 'Nouveau', ar: 'جديد' },

  // ==== Staff ====
  'Add Staff': { fr: 'Ajouter un membre', ar: 'إضافة موظف' },
  'Add Staff Member': { fr: 'Ajouter un membre du personnel', ar: 'إضافة موظف' },
  'Update Staff': { fr: 'Mettre à jour', ar: 'تحديث الموظف' },
  'Edit Staff Member': { fr: 'Modifier le membre', ar: 'تعديل الموظف' },
  'Add First Member': { fr: 'Ajouter le premier membre', ar: 'إضافة أول موظف' },
  'Role': { fr: 'Rôle', ar: 'الدور' },
  'Role Name': { fr: 'Nom du rôle', ar: 'اسم الدور' },
  'Permissions': { fr: 'Permissions', ar: 'الصلاحيات' },
  'permissions selected': { fr: 'permissions sélectionnées', ar: 'صلاحيات مختارة' },
  'Custom Roles': { fr: 'Rôles personnalisés', ar: 'الأدوار المخصصة' },
  'New Role': { fr: 'Nouveau rôle', ar: 'دور جديد' },
  'Create Role': { fr: 'Créer le rôle', ar: 'إنشاء الدور' },
  'Create Custom Role': { fr: 'Créer un rôle personnalisé', ar: 'إنشاء دور مخصص' },
  'Activate': { fr: 'Activer', ar: 'تفعيل' },
  'Deactivate': { fr: 'Désactiver', ar: 'إلغاء التفعيل' },
  'Check all': { fr: 'Tout cocher', ar: 'تحديد الكل' },
  'Uncheck all': { fr: 'Tout décocher', ar: 'إلغاء تحديد الكل' },

  // ==== Settings / Plans ====
  'General': { fr: 'Général', ar: 'عام' },
  'Design & Appearance': { fr: 'Design et apparence', ar: 'التصميم والمظهر' },
  'Payment Methods': { fr: 'Modes de paiement', ar: 'طرق الدفع' },
  'AI Features': { fr: 'Fonctionnalités IA', ar: 'ميزات الذكاء الاصطناعي' },
  'Store Name': { fr: 'Nom du magasin', ar: 'اسم المتجر' },
  'Store URL': { fr: 'URL du magasin', ar: 'رابط المتجر' },
  'Store Logo': { fr: 'Logo du magasin', ar: 'شعار المتجر' },
  'Currency': { fr: 'Devise', ar: 'العملة' },
  'Primary Color': { fr: 'Couleur principale', ar: 'اللون الأساسي' },
  'Secondary Color': { fr: 'Couleur secondaire', ar: 'اللون الثانوي' },
  'Free': { fr: 'Gratuit', ar: 'مجاني' },
  'Monthly': { fr: 'Mensuel', ar: 'شهري' },
  'Yearly': { fr: 'Annuel', ar: 'سنوي' },
  'Subscribe': { fr: 'S\'abonner', ar: 'اشترك' },
  'Most Popular': { fr: 'Le plus populaire', ar: 'الأكثر شعبية' },
  'Get Started': { fr: 'Commencer', ar: 'ابدأ الآن' },
  'Get Started Free': { fr: 'Commencer gratuitement', ar: 'ابدأ مجاناً' },

  // ==== Landing ====
  'Build Your Online Platform': { fr: 'Créez votre plateforme en ligne', ar: 'أنشئ منصتك الإلكترونية' },
  'No credit card required': { fr: 'Aucune carte requise', ar: 'لا حاجة لبطاقة ائتمان' },
  '14-day free trial': { fr: 'Essai gratuit 14 jours', ar: 'تجربة مجانية 14 يوم' },
  'Cancel anytime': { fr: 'Annulez à tout moment', ar: 'ألغِ في أي وقت' },
  'Ready to Start Selling?': { fr: 'Prêt à commencer à vendre ?', ar: 'هل أنت مستعد للبيع؟' },

  // ==== Misc ====
  'Today': { fr: 'Aujourd\'hui', ar: 'اليوم' },
  'This Week': { fr: 'Cette semaine', ar: 'هذا الأسبوع' },
  'This Month': { fr: 'Ce mois-ci', ar: 'هذا الشهر' },
  'Last 30 Days': { fr: '30 derniers jours', ar: 'آخر 30 يوم' },
  'Revenue': { fr: 'Revenu', ar: 'الإيرادات' },
  'Total Revenue': { fr: 'Revenu total', ar: 'إجمالي الإيرادات' },
  'Total Orders': { fr: 'Total des commandes', ar: 'إجمالي الطلبات' },
  'Total Sales': { fr: 'Ventes totales', ar: 'إجمالي المبيعات' },
  'Avg Order': { fr: 'Commande moy.', ar: 'متوسط الطلب' },
  'Avg Order Value': { fr: 'Valeur moy. de commande', ar: 'متوسط قيمة الطلب' },
  'Conversion Rate': { fr: 'Taux de conversion', ar: 'معدل التحويل' },
  'Store Visits': { fr: 'Visites du magasin', ar: 'زيارات المتجر' },
  'Recent Orders': { fr: 'Commandes récentes', ar: 'الطلبات الأخيرة' },
  'Top Products': { fr: 'Meilleurs produits', ar: 'أفضل المنتجات' },
  'Order Status': { fr: 'Statut de la commande', ar: 'حالة الطلب' },
  'Performance': { fr: 'Performance', ar: 'الأداء' },
  'performance': { fr: 'performance', ar: 'الأداء' },
};

export default D;
