// Flat EN -> { fr, ar } dictionary used by the global DOM auto-translator.
// Add or extend entries here — every page in the app will pick them up
// automatically without needing per-component t() wrapping.
// Keys are matched against the trimmed text content of any text node, as well
// as placeholder / title / aria-label / value attributes on inputs & buttons.

const D = {
  // ==== Generic ====
  'Save': { fr: 'Enregistrer', ar: 'حفظ' },
  'Save Changes': { fr: 'Enregistrer les modifications', ar: 'حفظ التغييرات' },
  'Cancel': { fr: 'Annuler', ar: 'إلغاء' },
  'Delete': { fr: 'Supprimer', ar: 'حذف' },
  'Edit': { fr: 'Modifier', ar: 'تعديل' },
  'Add': { fr: 'Ajouter', ar: 'إضافة' },
  'Create': { fr: 'Créer', ar: 'إنشاء' },
  'Update': { fr: 'Mettre à jour', ar: 'تحديث' },
  'Search': { fr: 'Rechercher', ar: 'بحث' },
  'Loading...': { fr: 'Chargement...', ar: 'جار التحميل...' },
  'Loading': { fr: 'Chargement', ar: 'جار التحميل' },
  'No data found': { fr: 'Aucune donnée trouvée', ar: 'لا توجد بيانات' },
  'Confirm': { fr: 'Confirmer', ar: 'تأكيد' },
  'Back': { fr: 'Retour', ar: 'رجوع' },
  'Next': { fr: 'Suivant', ar: 'التالي' },
  'Previous': { fr: 'Précédent', ar: 'السابق' },
  'Submit': { fr: 'Envoyer', ar: 'إرسال' },
  'View All': { fr: 'Voir tout', ar: 'عرض الكل' },
  'View Details': { fr: 'Voir les détails', ar: 'عرض التفاصيل' },
  'View': { fr: 'Voir', ar: 'عرض' },
  'Close': { fr: 'Fermer', ar: 'إغلاق' },
  'Open': { fr: 'Ouvrir', ar: 'فتح' },
  'Yes': { fr: 'Oui', ar: 'نعم' },
  'No': { fr: 'Non', ar: 'لا' },
  'Active': { fr: 'Actif', ar: 'نشط' },
  'Inactive': { fr: 'Inactif', ar: 'غير نشط' },
  'Enabled': { fr: 'Activé', ar: 'مفعل' },
  'Disabled': { fr: 'Désactivé', ar: 'معطل' },
  'Status': { fr: 'Statut', ar: 'الحالة' },
  'Actions': { fr: 'Actions', ar: 'إجراءات' },
  'Refresh': { fr: 'Actualiser', ar: 'تحديث' },
  'Export': { fr: 'Exporter', ar: 'تصدير' },
  'Import': { fr: 'Importer', ar: 'استيراد' },
  'Download': { fr: 'Télécharger', ar: 'تنزيل' },
  'Upload': { fr: 'Téléverser', ar: 'تحميل' },
  'Filter': { fr: 'Filtrer', ar: 'تصفية' },
  'Filters': { fr: 'Filtres', ar: 'الفلاتر' },
  'All': { fr: 'Tous', ar: 'الكل' },
  'all': { fr: 'tous', ar: 'الكل' },
  'Total': { fr: 'Total', ar: 'الإجمالي' },
  'Subtotal': { fr: 'Sous-total', ar: 'المجموع الفرعي' },
  'Date': { fr: 'Date', ar: 'التاريخ' },
  'Name': { fr: 'Nom', ar: 'الاسم' },
  'Email': { fr: 'E-mail', ar: 'البريد الإلكتروني' },
  'Phone': { fr: 'Téléphone', ar: 'الهاتف' },
  'Phone Number': { fr: 'Numéro de téléphone', ar: 'رقم الهاتف' },
  'Address': { fr: 'Adresse', ar: 'العنوان' },
  'City': { fr: 'Ville', ar: 'المدينة' },
  'Wilaya': { fr: 'Wilaya', ar: 'الولاية' },
  'Country': { fr: 'Pays', ar: 'البلد' },
  'Password': { fr: 'Mot de passe', ar: 'كلمة المرور' },
  'Full Name': { fr: 'Nom complet', ar: 'الاسم الكامل' },
  'Description': { fr: 'Description', ar: 'الوصف' },
  'Category': { fr: 'Catégorie', ar: 'الفئة' },
  'Categories': { fr: 'Catégories', ar: 'الفئات' },
  'Price': { fr: 'Prix', ar: 'السعر' },
  'Stock': { fr: 'Stock', ar: 'المخزون' },
  'Quantity': { fr: 'Quantité', ar: 'الكمية' },
  'Image': { fr: 'Image', ar: 'صورة' },
  'Images': { fr: 'Images', ar: 'صور' },
  'Logo': { fr: 'Logo', ar: 'الشعار' },
  'Settings': { fr: 'Paramètres', ar: 'الإعدادات' },
  'Profile': { fr: 'Profil', ar: 'الملف الشخصي' },
  'Logout': { fr: 'Déconnexion', ar: 'تسجيل الخروج' },
  'Login': { fr: 'Connexion', ar: 'تسجيل الدخول' },
  'Sign in': { fr: 'Se connecter', ar: 'تسجيل الدخول' },
  'Sign up': { fr: 'S\'inscrire', ar: 'إنشاء حساب' },
  'Register': { fr: 'S\'inscrire', ar: 'تسجيل' },
  'Create Account': { fr: 'Créer un compte', ar: 'إنشاء حساب' },
  'Forgot password?': { fr: 'Mot de passe oublié ?', ar: 'هل نسيت كلمة المرور؟' },
  'Disconnect': { fr: 'Se déconnecter', ar: 'قطع الاتصال' },
  'Collapse': { fr: 'Réduire', ar: 'طي' },
  'Expand': { fr: 'Développer', ar: 'توسيع' },
  'Live': { fr: 'En direct', ar: 'مباشر' },
  'Offline': { fr: 'Hors ligne', ar: 'غير متصل' },
  'Online': { fr: 'En ligne', ar: 'متصل' },
  'Home': { fr: 'Accueil', ar: 'الرئيسية' },
  'Dashboard': { fr: 'Tableau de bord', ar: 'لوحة التحكم' },
  'Overview': { fr: 'Aperçu', ar: 'نظرة عامة' },
  'Welcome': { fr: 'Bienvenue', ar: 'مرحباً' },
  'Welcome back': { fr: 'Bon retour', ar: 'مرحباً بعودتك' },
  'Help': { fr: 'Aide', ar: 'المساعدة' },
  'Support': { fr: 'Support', ar: 'الدعم' },
  'Contact': { fr: 'Contact', ar: 'اتصل بنا' },
  'About': { fr: 'À propos', ar: 'حول' },
  'About Us': { fr: 'À propos de nous', ar: 'من نحن' },
  'Features': { fr: 'Fonctionnalités', ar: 'الميزات' },
  'Pricing': { fr: 'Tarifs', ar: 'الأسعار' },
  'FAQs': { fr: 'FAQ', ar: 'الأسئلة الشائعة' },
  'Search everything...': { fr: 'Rechercher partout...', ar: 'ابحث في كل شيء...' },
  'Search products...': { fr: 'Rechercher des produits...', ar: 'ابحث عن المنتجات...' },
  'Search orders...': { fr: 'Rechercher des commandes...', ar: 'ابحث عن الطلبات...' },
  'Search customers...': { fr: 'Rechercher des clients...', ar: 'ابحث عن العملاء...' },

  // ==== Sidebar / Menu ====
  'Main Menu': { fr: 'Menu principal', ar: 'القائمة الرئيسية' },
  'STORE DASHBOARD': { fr: 'TABLEAU DE BORD DU MAGASIN', ar: 'لوحة تحكم المتجر' },
  'Orders': { fr: 'Commandes', ar: 'الطلبات' },
  'Products': { fr: 'Produits', ar: 'المنتجات' },
  'Customers': { fr: 'Clients', ar: 'العملاء' },
  'Analytics': { fr: 'Analyses', ar: 'التحليلات' },
  'Apps': { fr: 'Applications', ar: 'التطبيقات' },
  'Apps & Integrations': { fr: 'Applications et intégrations', ar: 'التطبيقات والتكاملات' },
  'Staff': { fr: 'Personnel', ar: 'الموظفون' },
  'Staff Management': { fr: 'Gestion du personnel', ar: 'إدارة الموظفين' },
  'Stock Manager': { fr: 'Gestion des stocks', ar: 'إدارة المخزون' },
  'Smart Reviews': { fr: 'Avis intelligents', ar: 'المراجعات الذكية' },
  'AI Intelligence': { fr: 'Intelligence IA', ar: 'الذكاء الاصطناعي' },
  'Costs': { fr: 'Coûts', ar: 'التكاليف' },
  'Costs & Expenses': { fr: 'Coûts et dépenses', ar: 'التكاليف والمصاريف' },
  'Billing': { fr: 'Facturation', ar: 'الفوترة' },
  'Billing & Plans': { fr: 'Facturation et forfaits', ar: 'الفوترة والخطط' },
  'Billing & Subscription': { fr: 'Facturation et abonnement', ar: 'الفوترة والاشتراك' },
  'Domains': { fr: 'Domaines', ar: 'النطاقات' },
  'Domains & URLs': { fr: 'Domaines et URLs', ar: 'النطاقات والروابط' },
  'Taxes': { fr: 'Taxes', ar: 'الضرائب' },
  'Delivery': { fr: 'Livraison', ar: 'التوصيل' },
  'Store & Settings': { fr: 'Magasin et paramètres', ar: 'المتجر والإعدادات' },
  'All Settings': { fr: 'Tous les paramètres', ar: 'جميع الإعدادات' },
  'Page Builder': { fr: 'Constructeur de page', ar: 'منشئ الصفحات' },
  'Home Page': { fr: 'Page d\'accueil', ar: 'الصفحة الرئيسية' },
  'Contact Info': { fr: 'Coordonnées', ar: 'معلومات الاتصال' },
  'Shipping': { fr: 'Livraison', ar: 'الشحن' },
  'Shipping Partners': { fr: 'Partenaires de livraison', ar: 'شركاء الشحن' },
  'Shipping Wilayas': { fr: 'Wilayas de livraison', ar: 'ولايات الشحن' },
  'How to Connect': { fr: 'Comment se connecter', ar: 'كيفية الاتصال' },
  'Automatic Blacklist': { fr: 'Liste noire automatique', ar: 'القائمة السوداء التلقائية' },
  'Blacklist': { fr: 'Liste noire', ar: 'القائمة السوداء' },
  'Tracking Orders': { fr: 'Suivi des commandes', ar: 'تتبع الطلبات' },
  'Abandoned Orders': { fr: 'Commandes abandonnées', ar: 'الطلبات المتروكة' },
  'Cart Recovery': { fr: 'Récupération de panier', ar: 'استرداد السلة' },
  'Preparing': { fr: 'En préparation', ar: 'قيد التحضير' },

  // ==== Orders ====
  'Order': { fr: 'Commande', ar: 'الطلب' },
  'Pending': { fr: 'En attente', ar: 'قيد الانتظار' },
  'Confirmed': { fr: 'Confirmée', ar: 'مؤكدة' },
  'Shipped': { fr: 'Expédiée', ar: 'تم الشحن' },
  'Delivered': { fr: 'Livrée', ar: 'تم التسليم' },
  'Cancelled': { fr: 'Annulée', ar: 'ملغاة' },
  'Returned': { fr: 'Retournée', ar: 'مرتجعة' },
  'Customer': { fr: 'Client', ar: 'العميل' },
  'Customer Name': { fr: 'Nom du client', ar: 'اسم العميل' },
  'Total Spent': { fr: 'Total dépensé', ar: 'الإجمالي المنفق' },
  'Location': { fr: 'Emplacement', ar: 'الموقع' },
  'Unknown': { fr: 'Inconnu', ar: 'غير معروف' },
  'orders': { fr: 'commandes', ar: 'طلبات' },
  'No orders yet': { fr: 'Aucune commande pour le moment', ar: 'لا توجد طلبات بعد' },
  'Order Items': { fr: 'Articles de la commande', ar: 'عناصر الطلب' },
  'Payment Method': { fr: 'Mode de paiement', ar: 'طريقة الدفع' },
  'Shipping Address': { fr: 'Adresse de livraison', ar: 'عنوان الشحن' },
  'Tracking Number': { fr: 'Numéro de suivi', ar: 'رقم التتبع' },
  'Notes': { fr: 'Notes', ar: 'ملاحظات' },

  // ==== Products ====
  'Add Product': { fr: 'Ajouter un produit', ar: 'إضافة منتج' },
  'Edit Product': { fr: 'Modifier le produit', ar: 'تعديل المنتج' },
  'Product Name': { fr: 'Nom du produit', ar: 'اسم المنتج' },
  'No products yet': { fr: 'Aucun produit pour le moment', ar: 'لا توجد منتجات بعد' },
  'in stock': { fr: 'en stock', ar: 'متوفر' },
  'Out of stock': { fr: 'Rupture de stock', ar: 'نفد المخزون' },
  'Featured Product': { fr: 'Produit vedette', ar: 'منتج مميز' },

  // ==== Customers ====
  'Add customer': { fr: 'Ajouter un client', ar: 'إضافة عميل' },
  'No customers found': { fr: 'Aucun client trouvé', ar: 'لم يتم العثور على عملاء' },
  'VIP': { fr: 'VIP', ar: 'كبار الشخصيات' },
  'Repeat': { fr: 'Récurrent', ar: 'متكرر' },
  'New': { fr: 'Nouveau', ar: 'جديد' },

  // ==== Staff ====
  'Add Staff': { fr: 'Ajouter un membre', ar: 'إضافة موظف' },
  'Add Staff Member': { fr: 'Ajouter un membre du personnel', ar: 'إضافة موظف' },
  'Update Staff': { fr: 'Mettre à jour', ar: 'تحديث الموظف' },
  'Edit Staff Member': { fr: 'Modifier le membre', ar: 'تعديل الموظف' },
  'Add First Member': { fr: 'Ajouter le premier membre', ar: 'إضافة أول موظف' },
  'Role': { fr: 'Rôle', ar: 'الدور' },
  'Role Name': { fr: 'Nom du rôle', ar: 'اسم الدور' },
  'Permissions': { fr: 'Permissions', ar: 'الصلاحيات' },
  'permissions selected': { fr: 'permissions sélectionnées', ar: 'صلاحيات مختارة' },
  'Custom Roles': { fr: 'Rôles personnalisés', ar: 'الأدوار المخصصة' },
  'New Role': { fr: 'Nouveau rôle', ar: 'دور جديد' },
  'Create Role': { fr: 'Créer le rôle', ar: 'إنشاء الدور' },
  'Create Custom Role': { fr: 'Créer un rôle personnalisé', ar: 'إنشاء دور مخصص' },
  'Activate': { fr: 'Activer', ar: 'تفعيل' },
  'Deactivate': { fr: 'Désactiver', ar: 'إلغاء التفعيل' },
  'Check all': { fr: 'Tout cocher', ar: 'تحديد الكل' },
  'Uncheck all': { fr: 'Tout décocher', ar: 'إلغاء تحديد الكل' },

  // ==== Settings / Plans ====
  'General': { fr: 'Général', ar: 'عام' },
  'Design & Appearance': { fr: 'Design et apparence', ar: 'التصميم والمظهر' },
  'Payment Methods': { fr: 'Modes de paiement', ar: 'طرق الدفع' },
  'AI Features': { fr: 'Fonctionnalités IA', ar: 'ميزات الذكاء الاصطناعي' },
  'Store Name': { fr: 'Nom du magasin', ar: 'اسم المتجر' },
  'Store URL': { fr: 'URL du magasin', ar: 'رابط المتجر' },
  'Store Logo': { fr: 'Logo du magasin', ar: 'شعار المتجر' },
  'Currency': { fr: 'Devise', ar: 'العملة' },
  'Primary Color': { fr: 'Couleur principale', ar: 'اللون الأساسي' },
  'Secondary Color': { fr: 'Couleur secondaire', ar: 'اللون الثانوي' },
  'Free': { fr: 'Gratuit', ar: 'مجاني' },
  'Monthly': { fr: 'Mensuel', ar: 'شهري' },
  'Yearly': { fr: 'Annuel', ar: 'سنوي' },
  'Subscribe': { fr: 'S\'abonner', ar: 'اشترك' },
  'Most Popular': { fr: 'Le plus populaire', ar: 'الأكثر شعبية' },
  'Get Started': { fr: 'Commencer', ar: 'ابدأ الآن' },
  'Get Started Free': { fr: 'Commencer gratuitement', ar: 'ابدأ مجاناً' },

  // ==== Landing ====
  'Build Your Online Platform': { fr: 'Créez votre plateforme en ligne', ar: 'أنشئ منصتك الإلكترونية' },
  'No credit card required': { fr: 'Aucune carte requise', ar: 'لا حاجة لبطاقة ائتمان' },
  '14-day free trial': { fr: 'Essai gratuit 14 jours', ar: 'تجربة مجانية 14 يوم' },
  'Cancel anytime': { fr: 'Annulez à tout moment', ar: 'ألغِ في أي وقت' },
  'Ready to Start Selling?': { fr: 'Prêt à commencer à vendre ?', ar: 'هل أنت مستعد للبيع؟' },

  // ==== Misc ====
  'Today': { fr: 'Aujourd\'hui', ar: 'اليوم' },
  'This Week': { fr: 'Cette semaine', ar: 'هذا الأسبوع' },
  'This Month': { fr: 'Ce mois-ci', ar: 'هذا الشهر' },
  'Last 30 Days': { fr: '30 derniers jours', ar: 'آخر 30 يوم' },
  'Revenue': { fr: 'Revenu', ar: 'الإيرادات' },
  'Total Revenue': { fr: 'Revenu total', ar: 'إجمالي الإيرادات' },
  'Total Orders': { fr: 'Total des commandes', ar: 'إجمالي الطلبات' },
  'Total Sales': { fr: 'Ventes totales', ar: 'إجمالي المبيعات' },
  'Avg Order': { fr: 'Commande moy.', ar: 'متوسط الطلب' },
  'Avg Order Value': { fr: 'Valeur moy. de commande', ar: 'متوسط قيمة الطلب' },
  'Conversion Rate': { fr: 'Taux de conversion', ar: 'معدل التحويل' },
  'Store Visits': { fr: 'Visites du magasin', ar: 'زيارات المتجر' },
  'Recent Orders': { fr: 'Commandes récentes', ar: 'الطلبات الأخيرة' },
  'Top Products': { fr: 'Meilleurs produits', ar: 'أفضل المنتجات' },
  'Order Status': { fr: 'Statut de la commande', ar: 'حالة الطلب' },
  'Performance': { fr: 'Performance', ar: 'الأداء' },
  'performance': { fr: 'performance', ar: 'الأداء' },

  // ==== Extended ====
  'Manage': { fr: 'Gérer', ar: 'إدارة' },
  'Manage your store': { fr: 'Gérez votre magasin', ar: 'إدارة متجرك' },
  'Manage your plan and payment history': { fr: 'Gérez votre forfait et l\'historique des paiements', ar: 'إدارة خطتك وسجل المدفوعات' },
  'Track your business expenses': { fr: 'Suivez vos dépenses', ar: 'تتبع نفقات عملك' },
  'Connect your own domain or use the platform URL': { fr: 'Connectez votre domaine ou utilisez l\'URL de la plateforme', ar: 'اربط نطاقك الخاص أو استخدم رابط المنصة' },
  'Track shipments with delivery partners': { fr: 'Suivez les expéditions avec les partenaires', ar: 'تتبع الشحنات مع شركاء التوصيل' },
  'Set your tax rate and see how much tax you owe on your revenue': { fr: 'Définissez votre taux de TVA et voyez la taxe due', ar: 'حدد معدل الضريبة واطلع على المستحقات' },
  'Add Expense': { fr: 'Ajouter une dépense', ar: 'إضافة مصروف' },
  'Edit Expense': { fr: 'Modifier la dépense', ar: 'تعديل المصروف' },
  'Total Expenses': { fr: 'Total des dépenses', ar: 'إجمالي المصاريف' },
  'Entries': { fr: 'Entrées', ar: 'الإدخالات' },
  'By Category': { fr: 'Par catégorie', ar: 'حسب الفئة' },
  'No expenses recorded': { fr: 'Aucune dépense enregistrée', ar: 'لا توجد مصاريف مسجلة' },
  'Amount': { fr: 'Montant', ar: 'المبلغ' },
  'Paid': { fr: 'Payé', ar: 'مدفوع' },
  'Overdue': { fr: 'En retard', ar: 'متأخر' },
  'Operations': { fr: 'Opérations', ar: 'العمليات' },
  'Marketing': { fr: 'Marketing', ar: 'التسويق' },
  'Utilities': { fr: 'Services publics', ar: 'المرافق' },
  'Inventory': { fr: 'Inventaire', ar: 'المخزون' },
  'Salaries': { fr: 'Salaires', ar: 'الرواتب' },
  'Rent': { fr: 'Loyer', ar: 'الإيجار' },
  'Other': { fr: 'Autre', ar: 'أخرى' },

  // Tax page
  'Tax Configuration': { fr: 'Configuration de la taxe', ar: 'إعدادات الضريبة' },
  'Applied storewide on checkout & invoices': { fr: 'Appliqué sur tout le magasin', ar: 'يطبق على المتجر بأكمله' },
  'Enable tax': { fr: 'Activer la taxe', ar: 'تفعيل الضريبة' },
  'Tax Rate (%)': { fr: 'Taux de taxe (%)', ar: 'نسبة الضريبة (%)' },
  'Label': { fr: 'Libellé', ar: 'التسمية' },
  'Price mode': { fr: 'Mode de prix', ar: 'وضع السعر' },
  'Presets:': { fr: 'Préréglages :', ar: 'الإعدادات المسبقة:' },
  'Tax on Revenue': { fr: 'Taxe sur les revenus', ar: 'الضريبة على الإيرادات' },
  'Quarter': { fr: 'Trimestre', ar: 'الربع' },
  'Year': { fr: 'Année', ar: 'السنة' },
  'All Time': { fr: 'Tout le temps', ar: 'كل الوقت' },
  'Taxable Base': { fr: 'Base imposable', ar: 'الأساس الخاضع للضريبة' },
  'owed': { fr: 'dû', ar: 'مستحق' },
  'Grand Total': { fr: 'Total général', ar: 'المجموع الكلي' },
  'Reset': { fr: 'Réinitialiser', ar: 'إعادة تعيين' },
  'Save Settings': { fr: 'Enregistrer les paramètres', ar: 'حفظ الإعدادات' },
  'Saving...': { fr: 'Enregistrement...', ar: 'جار الحفظ...' },

  // Billing page
  'Current Plan': { fr: 'Forfait actuel', ar: 'الخطة الحالية' },
  'SUSPENDED': { fr: 'SUSPENDU', ar: 'موقوف' },
  'ACTIVE': { fr: 'ACTIF', ar: 'نشط' },
  'FREE': { fr: 'GRATUIT', ar: 'مجاني' },
  'Expires:': { fr: 'Expire :', ar: 'تنتهي:' },
  'Save 20%': { fr: 'Économisez 20 %', ar: 'وفر 20%' },
  'Payment History': { fr: 'Historique des paiements', ar: 'سجل المدفوعات' },
  'No payments yet': { fr: 'Aucun paiement', ar: 'لا توجد مدفوعات بعد' },
  'Subscribe to': { fr: 'S\'abonner à', ar: 'الاشتراك في' },
  'Amount to pay': { fr: 'Montant à payer', ar: 'المبلغ المستحق' },
  'CCP Transfer': { fr: 'Virement CCP', ar: 'تحويل CCP' },
  'BaridiMob': { fr: 'BaridiMob', ar: 'بريدي موب' },
  'Upload Payment Receipt': { fr: 'Téléverser le reçu', ar: 'تحميل إيصال الدفع' },
  'Click to upload receipt screenshot': { fr: 'Cliquez pour téléverser', ar: 'انقر لتحميل لقطة الإيصال' },
  'Submit Payment': { fr: 'Envoyer le paiement', ar: 'إرسال الدفع' },
  'Select a plan': { fr: 'Choisir un forfait', ar: 'اختر خطة' },
  'Copied!': { fr: 'Copié !', ar: 'تم النسخ!' },

  // Domains page
  'Connect Domain': { fr: 'Connecter un domaine', ar: 'ربط نطاق' },
  'Active Store URL': { fr: 'URL active du magasin', ar: 'رابط المتجر النشط' },
  'Choose which URL your customers will use': { fr: 'Choisissez l\'URL que vos clients utiliseront', ar: 'اختر الرابط الذي سيستخدمه عملاؤك' },
  'Platform URL': { fr: 'URL de la plateforme', ar: 'رابط المنصة' },
  'CUSTOM': { fr: 'PERSONNALISÉ', ar: 'مخصص' },
  'Connected Domains': { fr: 'Domaines connectés', ar: 'النطاقات المتصلة' },
  'DNS not verified': { fr: 'DNS non vérifié', ar: 'DNS غير محقق' },
  'How to connect your domain': { fr: 'Comment connecter votre domaine', ar: 'كيفية ربط نطاقك' },
  'Type': { fr: 'Type', ar: 'النوع' },
  'Value': { fr: 'Valeur', ar: 'القيمة' },
  'Your Domain': { fr: 'Votre domaine', ar: 'نطاقك' },
  'Adding...': { fr: 'Ajout...', ar: 'جار الإضافة...' },

  // Tracking
  'Total Shipped': { fr: 'Total expédié', ar: 'إجمالي المشحون' },
  'With Tracking': { fr: 'Avec suivi', ar: 'مع تتبع' },
  'No Tracking': { fr: 'Sans suivi', ar: 'بدون تتبع' },
  'Destination': { fr: 'Destination', ar: 'الوجهة' },
  'Partner': { fr: 'Partenaire', ar: 'الشريك' },
  'LIVE': { fr: 'EN DIRECT', ar: 'مباشر' },
  'No tracking number': { fr: 'Aucun numéro de suivi', ar: 'لا يوجد رقم تتبع' },
  'Delivery Progress': { fr: 'Progression de la livraison', ar: 'تقدم التسليم' },
  'Awaiting Pickup': { fr: 'En attente de collecte', ar: 'في انتظار الاستلام' },
  'Picked Up': { fr: 'Collecté', ar: 'تم الاستلام' },
  'At Center': { fr: 'Au centre', ar: 'في المركز' },
  'In Transit': { fr: 'En transit', ar: 'في الطريق' },
  'Out for Delivery': { fr: 'En cours de livraison', ar: 'قارب على التسليم' },
  'Timeline': { fr: 'Chronologie', ar: 'الجدول الزمني' },
  'Track on': { fr: 'Suivre sur', ar: 'تتبع على' },

  // Analytics
  'Order Status Breakdown': { fr: 'Répartition des statuts', ar: 'توزيع حالات الطلبات' },
  'Revenue & Orders (Last 30 Days)': { fr: 'Revenus et commandes (30 derniers jours)', ar: 'الإيرادات والطلبات (آخر 30 يوم)' },
  'No order data yet': { fr: 'Aucune donnée de commande', ar: 'لا توجد بيانات طلبات' },
  'No product data yet': { fr: 'Aucune donnée produit', ar: 'لا توجد بيانات منتجات' },
  'Quantity sold': { fr: 'Quantité vendue', ar: 'الكمية المباعة' },

  // Apps
  'Supercharge your store with powerful apps and integrations.': { fr: 'Boostez votre magasin avec des applications puissantes.', ar: 'عزز متجرك بتطبيقات قوية.' },
  'Install': { fr: 'Installer', ar: 'تثبيت' },
  'Uninstall': { fr: 'Désinstaller', ar: 'إلغاء التثبيت' },
  'Coming soon': { fr: 'Bientôt disponible', ar: 'قريباً' },
  'Installed': { fr: 'Installé', ar: 'مثبت' },

  // Recovery
  'Manage and automate abandoned order conversion.': { fr: 'Gérez et automatisez la conversion des paniers abandonnés.', ar: 'إدارة وأتمتة تحويل الطلبات المتروكة.' },
  'Total Carts': { fr: 'Total des paniers', ar: 'إجمالي السلال' },
  'Recovered': { fr: 'Récupérés', ar: 'المسترد' },
  'Recovered Revenue': { fr: 'Revenu récupéré', ar: 'الإيرادات المستردة' },
  'Lost Revenue': { fr: 'Revenu perdu', ar: 'الإيرادات المفقودة' },
  'Sync Data': { fr: 'Synchroniser', ar: 'مزامنة البيانات' },
  'Automation Settings': { fr: 'Paramètres d\'automatisation', ar: 'إعدادات الأتمتة' },

  // Settings tabs
  'Store Details': { fr: 'Détails du magasin', ar: 'تفاصيل المتجر' },
  'Customization': { fr: 'Personnalisation', ar: 'التخصيص' },
  'Users & Permissions': { fr: 'Utilisateurs et permissions', ar: 'المستخدمون والصلاحيات' },
  'Checkout': { fr: 'Paiement', ar: 'الدفع' },
  'Payments': { fr: 'Paiements', ar: 'المدفوعات' },
  'Notifications': { fr: 'Notifications', ar: 'الإشعارات' },
  'Marketing & Pixels': { fr: 'Marketing et pixels', ar: 'التسويق والبكسلات' },
  'AI Messaging': { fr: 'Messagerie IA', ar: 'رسائل الذكاء الاصطناعي' },
  'Subscription': { fr: 'Abonnement', ar: 'الاشتراك' },
  'Account': { fr: 'Compte', ar: 'الحساب' },
  'Hero Title': { fr: 'Titre du héros', ar: 'العنوان الرئيسي' },
  'Hero Subtitle': { fr: 'Sous-titre du héros', ar: 'العنوان الفرعي' },
  'Meta Title (SEO)': { fr: 'Titre Meta (SEO)', ar: 'عنوان ميتا (SEO)' },
  'Meta Description (SEO)': { fr: 'Description Meta (SEO)', ar: 'وصف ميتا (SEO)' },
  'Background Color': { fr: 'Couleur de fond', ar: 'لون الخلفية' },
  'Accent Color': { fr: 'Couleur d\'accent', ar: 'لون التمييز' },
  'AI Chatbot': { fr: 'Chatbot IA', ar: 'روبوت الدردشة' },
  'Bot Name': { fr: 'Nom du bot', ar: 'اسم الروبوت' },
  'Greeting Message': { fr: 'Message d\'accueil', ar: 'رسالة الترحيب' },
  'AI Fake Order Detection': { fr: 'Détection de fausses commandes', ar: 'كشف الطلبات الوهمية' },
  'AI Cart Recovery': { fr: 'Récupération de panier IA', ar: 'استرداد السلة بالذكاء الاصطناعي' },
  'Store is Live (Published)': { fr: 'Le magasin est en ligne', ar: 'المتجر منشور' },
  'Contact Phone / WhatsApp': { fr: 'Téléphone / WhatsApp', ar: 'الهاتف / واتساب' },
  'Contact Email': { fr: 'E-mail de contact', ar: 'بريد التواصل' },
  'Upload logo from device': { fr: 'Téléverser le logo', ar: 'تحميل الشعار من الجهاز' },

  // Storefront / buyer
  'Add to Cart': { fr: 'Ajouter au panier', ar: 'أضف إلى السلة' },
  'Buy Now': { fr: 'Acheter maintenant', ar: 'اشترِ الآن' },
  'Cart': { fr: 'Panier', ar: 'السلة' },
  'Continue Shopping': { fr: 'Continuer les achats', ar: 'متابعة التسوق' },
  'Order Summary': { fr: 'Résumé de la commande', ar: 'ملخص الطلب' },
  'Place Order': { fr: 'Passer la commande', ar: 'إرسال الطلب' },
  'Order Placed Successfully!': { fr: 'Commande passée avec succès !', ar: 'تم إرسال الطلب بنجاح!' },
  'Cash on Delivery': { fr: 'Paiement à la livraison', ar: 'الدفع عند الاستلام' },
  'Bank Transfer': { fr: 'Virement bancaire', ar: 'تحويل بنكي' },
  'Shipping Information': { fr: 'Informations de livraison', ar: 'معلومات الشحن' },
  'Favorites': { fr: 'Favoris', ar: 'المفضلة' },
  'My Orders': { fr: 'Mes commandes', ar: 'طلباتي' },
  'My Profile': { fr: 'Mon profil', ar: 'ملفي الشخصي' },

  // Admin
  'Store Owners': { fr: 'Propriétaires de magasin', ar: 'أصحاب المتاجر' },
  'All Stores': { fr: 'Tous les magasins', ar: 'جميع المتاجر' },
  'All Orders': { fr: 'Toutes les commandes', ar: 'جميع الطلبات' },
  'Site Branding': { fr: 'Image du site', ar: 'هوية الموقع' },
  'System Health': { fr: 'État du système', ar: 'صحة النظام' },
  'Super Admins': { fr: 'Super administrateurs', ar: 'المشرفون الكبار' },
  'Super Admin': { fr: 'Super administrateur', ar: 'مشرف كبير' },
  'Control Panel': { fr: 'Panneau de contrôle', ar: 'لوحة التحكم' },
  'Platform Overview': { fr: 'Aperçu de la plateforme', ar: 'نظرة عامة على المنصة' },
  'Platform Administration': { fr: 'Administration de la plateforme', ar: 'إدارة المنصة' },
  'Update Login Info': { fr: 'Mettre à jour les identifiants', ar: 'تحديث معلومات الدخول' },
  'Across Stores': { fr: 'Dans tous les magasins', ar: 'عبر المتاجر' },
  'Registered Buyers': { fr: 'Acheteurs inscrits', ar: 'المشترون المسجلون' },
  'Admin': { fr: 'Administrateur', ar: 'المسؤول' },
};

export default D;
