// Flat EN -> { fr, ar } dictionary used by the global DOM auto-translator.
// Add or extend entries here — every page in the app will pick them up
// automatically without needing per-component t() wrapping.
// Keys are matched against the trimmed text content of any text node, as well
// as placeholder / title / aria-label / value attributes on inputs & buttons.

const D = {
  // ==== Generic ====
  'Save': { fr: 'Enregistrer', ar: 'حفظ' },
  'Save Changes': { fr: 'Enregistrer les modifications', ar: 'حفظ التغييرات' },
  'Cancel': { fr: 'Annuler', ar: 'إلغاء' },
  'Delete': { fr: 'Supprimer', ar: 'حذف' },
  'Edit': { fr: 'Modifier', ar: 'تعديل' },
  'Add': { fr: 'Ajouter', ar: 'إضافة' },
  'Create': { fr: 'Créer', ar: 'إنشاء' },
  'Update': { fr: 'Mettre à jour', ar: 'تحديث' },
  'Search': { fr: 'Rechercher', ar: 'بحث' },
  'Loading...': { fr: 'Chargement...', ar: 'جار التحميل...' },
  'Loading': { fr: 'Chargement', ar: 'جار التحميل' },
  'No data found': { fr: 'Aucune donnée trouvée', ar: 'لا توجد بيانات' },
  'Confirm': { fr: 'Confirmer', ar: 'تأكيد' },
  'Back': { fr: 'Retour', ar: 'رجوع' },
  'Next': { fr: 'Suivant', ar: 'التالي' },
  'Previous': { fr: 'Précédent', ar: 'السابق' },
  'Submit': { fr: 'Envoyer', ar: 'إرسال' },
  'View All': { fr: 'Voir tout', ar: 'عرض الكل' },
  'View Details': { fr: 'Voir les détails', ar: 'عرض التفاصيل' },
  'View': { fr: 'Voir', ar: 'عرض' },
  'Close': { fr: 'Fermer', ar: 'إغلاق' },
  'Open': { fr: 'Ouvrir', ar: 'فتح' },
  'Yes': { fr: 'Oui', ar: 'نعم' },
  'No': { fr: 'Non', ar: 'لا' },
  'Active': { fr: 'Actif', ar: 'نشط' },
  'Inactive': { fr: 'Inactif', ar: 'غير نشط' },
  'Enabled': { fr: 'Activé', ar: 'مفعل' },
  'Disabled': { fr: 'Désactivé', ar: 'معطل' },
  'Status': { fr: 'Statut', ar: 'الحالة' },
  'Actions': { fr: 'Actions', ar: 'إجراءات' },
  'Refresh': { fr: 'Actualiser', ar: 'تحديث' },
  'Export': { fr: 'Exporter', ar: 'تصدير' },
  'Import': { fr: 'Importer', ar: 'استيراد' },
  'Download': { fr: 'Télécharger', ar: 'تنزيل' },
  'Upload': { fr: 'Téléverser', ar: 'تحميل' },
  'Filter': { fr: 'Filtrer', ar: 'تصفية' },
  'Filters': { fr: 'Filtres', ar: 'الفلاتر' },
  'All': { fr: 'Tous', ar: 'الكل' },
  'all': { fr: 'tous', ar: 'الكل' },
  'Total': { fr: 'Total', ar: 'الإجمالي' },
  'Subtotal': { fr: 'Sous-total', ar: 'المجموع الفرعي' },
  'Date': { fr: 'Date', ar: 'التاريخ' },
  'Name': { fr: 'Nom', ar: 'الاسم' },
  'Email': { fr: 'E-mail', ar: 'البريد الإلكتروني' },
  'Phone': { fr: 'Téléphone', ar: 'الهاتف' },
  'Phone Number': { fr: 'Numéro de téléphone', ar: 'رقم الهاتف' },
  'Address': { fr: 'Adresse', ar: 'العنوان' },
  'City': { fr: 'Ville', ar: 'المدينة' },
  'Wilaya': { fr: 'Wilaya', ar: 'الولاية' },
  'Country': { fr: 'Pays', ar: 'البلد' },
  'Password': { fr: 'Mot de passe', ar: 'كلمة المرور' },
  'Full Name': { fr: 'Nom complet', ar: 'الاسم الكامل' },
  'Description': { fr: 'Description', ar: 'الوصف' },
  'Category': { fr: 'Catégorie', ar: 'الفئة' },
  'Categories': { fr: 'Catégories', ar: 'الفئات' },
  'Price': { fr: 'Prix', ar: 'السعر' },
  'Stock': { fr: 'Stock', ar: 'المخزون' },
  'Quantity': { fr: 'Quantité', ar: 'الكمية' },
  'Image': { fr: 'Image', ar: 'صورة' },
  'Images': { fr: 'Images', ar: 'صور' },
  'Logo': { fr: 'Logo', ar: 'الشعار' },
  'Settings': { fr: 'Paramètres', ar: 'الإعدادات' },
  'Profile': { fr: 'Profil', ar: 'الملف الشخصي' },
  'Logout': { fr: 'Déconnexion', ar: 'تسجيل الخروج' },
  'Login': { fr: 'Connexion', ar: 'تسجيل الدخول' },
  'Sign in': { fr: 'Se connecter', ar: 'تسجيل الدخول' },
  'Sign up': { fr: 'S\'inscrire', ar: 'إنشاء حساب' },
  'Register': { fr: 'S\'inscrire', ar: 'تسجيل' },
  'Create Account': { fr: 'Créer un compte', ar: 'إنشاء حساب' },
  'Forgot password?': { fr: 'Mot de passe oublié ?', ar: 'هل نسيت كلمة المرور؟' },
  'Disconnect': { fr: 'Se déconnecter', ar: 'قطع الاتصال' },
  'Collapse': { fr: 'Réduire', ar: 'طي' },
  'Expand': { fr: 'Développer', ar: 'توسيع' },
  'Live': { fr: 'En direct', ar: 'مباشر' },
  'Offline': { fr: 'Hors ligne', ar: 'غير متصل' },
  'Online': { fr: 'En ligne', ar: 'متصل' },
  'Home': { fr: 'Accueil', ar: 'الرئيسية' },
  'Dashboard': { fr: 'Tableau de bord', ar: 'لوحة التحكم' },
  'Overview': { fr: 'Aperçu', ar: 'نظرة عامة' },
  'Welcome': { fr: 'Bienvenue', ar: 'مرحباً' },
  'Welcome back': { fr: 'Bon retour', ar: 'مرحباً بعودتك' },
  'Help': { fr: 'Aide', ar: 'المساعدة' },
  'Support': { fr: 'Support', ar: 'الدعم' },
  'Contact': { fr: 'Contact', ar: 'اتصل بنا' },
  'About': { fr: 'À propos', ar: 'حول' },
  'About Us': { fr: 'À propos de nous', ar: 'من نحن' },
  'Features': { fr: 'Fonctionnalités', ar: 'الميزات' },
  'Pricing': { fr: 'Tarifs', ar: 'الأسعار' },
  'FAQs': { fr: 'FAQ', ar: 'الأسئلة الشائعة' },
  'Search everything...': { fr: 'Rechercher partout...', ar: 'ابحث في كل شيء...' },
  'Search products...': { fr: 'Rechercher des produits...', ar: 'ابحث عن المنتجات...' },
  'Search orders...': { fr: 'Rechercher des commandes...', ar: 'ابحث عن الطلبات...' },
  'Search customers...': { fr: 'Rechercher des clients...', ar: 'ابحث عن العملاء...' },

  // ==== Sidebar / Menu ====
  'Main Menu': { fr: 'Menu principal', ar: 'القائمة الرئيسية' },
  'STORE DASHBOARD': { fr: 'TABLEAU DE BORD DU MAGASIN', ar: 'لوحة تحكم المتجر' },
  'Orders': { fr: 'Commandes', ar: 'الطلبات' },
  'Products': { fr: 'Produits', ar: 'المنتجات' },
  'Customers': { fr: 'Clients', ar: 'العملاء' },
  'Analytics': { fr: 'Analyses', ar: 'التحليلات' },
  'Apps': { fr: 'Applications', ar: 'التطبيقات' },
  'Apps & Integrations': { fr: 'Applications et intégrations', ar: 'التطبيقات والتكاملات' },
  'Staff': { fr: 'Personnel', ar: 'الموظفون' },
  'Staff Management': { fr: 'Gestion du personnel', ar: 'إدارة الموظفين' },
  'Stock Manager': { fr: 'Gestion des stocks', ar: 'إدارة المخزون' },
  'Smart Reviews': { fr: 'Avis intelligents', ar: 'المراجعات الذكية' },
  'AI Intelligence': { fr: 'Intelligence IA', ar: 'الذكاء الاصطناعي' },
  'Costs': { fr: 'Coûts', ar: 'التكاليف' },
  'Costs & Expenses': { fr: 'Coûts et dépenses', ar: 'التكاليف والمصاريف' },
  'Billing': { fr: 'Facturation', ar: 'الفوترة' },
  'Billing & Plans': { fr: 'Facturation et forfaits', ar: 'الفوترة والخطط' },
  'Billing & Subscription': { fr: 'Facturation et abonnement', ar: 'الفوترة والاشتراك' },
  'Domains': { fr: 'Domaines', ar: 'النطاقات' },
  'Domains & URLs': { fr: 'Domaines et URLs', ar: 'النطاقات والروابط' },
  'Taxes': { fr: 'Taxes', ar: 'الضرائب' },
  'Delivery': { fr: 'Livraison', ar: 'التوصيل' },
  'Store & Settings': { fr: 'Magasin et paramètres', ar: 'المتجر والإعدادات' },
  'All Settings': { fr: 'Tous les paramètres', ar: 'جميع الإعدادات' },
  'Page Builder': { fr: 'Constructeur de page', ar: 'منشئ الصفحات' },
  'Home Page': { fr: 'Page d\'accueil', ar: 'الصفحة الرئيسية' },
  'Contact Info': { fr: 'Coordonnées', ar: 'معلومات الاتصال' },
  'Shipping': { fr: 'Livraison', ar: 'الشحن' },
  'Shipping Partners': { fr: 'Partenaires de livraison', ar: 'شركاء الشحن' },
  'Shipping Wilayas': { fr: 'Wilayas de livraison', ar: 'ولايات الشحن' },
  'How to Connect': { fr: 'Comment se connecter', ar: 'كيفية الاتصال' },
  'Automatic Blacklist': { fr: 'Liste noire automatique', ar: 'القائمة السوداء التلقائية' },
  'Blacklist': { fr: 'Liste noire', ar: 'القائمة السوداء' },
  'Tracking Orders': { fr: 'Suivi des commandes', ar: 'تتبع الطلبات' },
  'Abandoned Orders': { fr: 'Commandes abandonnées', ar: 'الطلبات المتروكة' },
  'Cart Recovery': { fr: 'Récupération de panier', ar: 'استرداد السلة' },
  'Preparing': { fr: 'En préparation', ar: 'قيد التحضير' },

  // ==== Orders ====
  'Order': { fr: 'Commande', ar: 'الطلب' },
  'Pending': { fr: 'En attente', ar: 'قيد الانتظار' },
  'Confirmed': { fr: 'Confirmée', ar: 'مؤكدة' },
  'Shipped': { fr: 'Expédiée', ar: 'تم الشحن' },
  'Delivered': { fr: 'Livrée', ar: 'تم التسليم' },
  'Cancelled': { fr: 'Annulée', ar: 'ملغاة' },
  'Returned': { fr: 'Retournée', ar: 'مرتجعة' },
  'Customer': { fr: 'Client', ar: 'العميل' },
  'Customer Name': { fr: 'Nom du client', ar: 'اسم العميل' },
  'Total Spent': { fr: 'Total dépensé', ar: 'الإجمالي المنفق' },
  'Location': { fr: 'Emplacement', ar: 'الموقع' },
  'Unknown': { fr: 'Inconnu', ar: 'غير معروف' },
  'orders': { fr: 'commandes', ar: 'طلبات' },
  'No orders yet': { fr: 'Aucune commande pour le moment', ar: 'لا توجد طلبات بعد' },
  'Order Items': { fr: 'Articles de la commande', ar: 'عناصر الطلب' },
  'Payment Method': { fr: 'Mode de paiement', ar: 'طريقة الدفع' },
  'Shipping Address': { fr: 'Adresse de livraison', ar: 'عنوان الشحن' },
  'Tracking Number': { fr: 'Numéro de suivi', ar: 'رقم التتبع' },
  'Notes': { fr: 'Notes', ar: 'ملاحظات' },

  // ==== Products ====
  'Add Product': { fr: 'Ajouter un produit', ar: 'إضافة منتج' },
  'Edit Product': { fr: 'Modifier le produit', ar: 'تعديل المنتج' },
  'Product Name': { fr: 'Nom du produit', ar: 'اسم المنتج' },
  'No products yet': { fr: 'Aucun produit pour le moment', ar: 'لا توجد منتجات بعد' },
  'in stock': { fr: 'en stock', ar: 'متوفر' },
  'Out of stock': { fr: 'Rupture de stock', ar: 'نفد المخزون' },
  'Featured Product': { fr: 'Produit vedette', ar: 'منتج مميز' },

  // ==== Customers ====
  'Add customer': { fr: 'Ajouter un client', ar: 'إضافة عميل' },
  'No customers found': { fr: 'Aucun client trouvé', ar: 'لم يتم العثور على عملاء' },
  'VIP': { fr: 'VIP', ar: 'كبار الشخصيات' },
  'Repeat': { fr: 'Récurrent', ar: 'متكرر' },
  'New': { fr: 'Nouveau', ar: 'جديد' },

  // ==== Staff ====
  'Add Staff': { fr: 'Ajouter un membre', ar: 'إضافة موظف' },
  'Add Staff Member': { fr: 'Ajouter un membre du personnel', ar: 'إضافة موظف' },
  'Update Staff': { fr: 'Mettre à jour', ar: 'تحديث الموظف' },
  'Edit Staff Member': { fr: 'Modifier le membre', ar: 'تعديل الموظف' },
  'Add First Member': { fr: 'Ajouter le premier membre', ar: 'إضافة أول موظف' },
  'Role': { fr: 'Rôle', ar: 'الدور' },
  'Role Name': { fr: 'Nom du rôle', ar: 'اسم الدور' },
  'Permissions': { fr: 'Permissions', ar: 'الصلاحيات' },
  'permissions selected': { fr: 'permissions sélectionnées', ar: 'صلاحيات مختارة' },
  'Custom Roles': { fr: 'Rôles personnalisés', ar: 'الأدوار المخصصة' },
  'New Role': { fr: 'Nouveau rôle', ar: 'دور جديد' },
  'Create Role': { fr: 'Créer le rôle', ar: 'إنشاء الدور' },
  'Create Custom Role': { fr: 'Créer un rôle personnalisé', ar: 'إنشاء دور مخصص' },
  'Activate': { fr: 'Activer', ar: 'تفعيل' },
  'Deactivate': { fr: 'Désactiver', ar: 'إلغاء التفعيل' },
  'Check all': { fr: 'Tout cocher', ar: 'تحديد الكل' },
  'Uncheck all': { fr: 'Tout décocher', ar: 'إلغاء تحديد الكل' },

  // ==== Settings / Plans ====
  'General': { fr: 'Général', ar: 'عام' },
  'Design & Appearance': { fr: 'Design et apparence', ar: 'التصميم والمظهر' },
  'Payment Methods': { fr: 'Modes de paiement', ar: 'طرق الدفع' },
  'AI Features': { fr: 'Fonctionnalités IA', ar: 'ميزات الذكاء الاصطناعي' },
  'Store Name': { fr: 'Nom du magasin', ar: 'اسم المتجر' },
  'Store URL': { fr: 'URL du magasin', ar: 'رابط المتجر' },
  'Store Logo': { fr: 'Logo du magasin', ar: 'شعار المتجر' },
  'Currency': { fr: 'Devise', ar: 'العملة' },
  'Primary Color': { fr: 'Couleur principale', ar: 'اللون الأساسي' },
  'Secondary Color': { fr: 'Couleur secondaire', ar: 'اللون الثانوي' },
  'Free': { fr: 'Gratuit', ar: 'مجاني' },
  'Monthly': { fr: 'Mensuel', ar: 'شهري' },
  'Yearly': { fr: 'Annuel', ar: 'سنوي' },
  'Subscribe': { fr: 'S\'abonner', ar: 'اشترك' },
  'Most Popular': { fr: 'Le plus populaire', ar: 'الأكثر شعبية' },
  'Get Started': { fr: 'Commencer', ar: 'ابدأ الآن' },
  'Get Started Free': { fr: 'Commencer gratuitement', ar: 'ابدأ مجاناً' },

  // ==== Landing ====
  'Build Your Online Platform': { fr: 'Créez votre plateforme en ligne', ar: 'أنشئ منصتك الإلكترونية' },
  'No credit card required': { fr: 'Aucune carte requise', ar: 'لا حاجة لبطاقة ائتمان' },
  '14-day free trial': { fr: 'Essai gratuit 14 jours', ar: 'تجربة مجانية 14 يوم' },
  'Cancel anytime': { fr: 'Annulez à tout moment', ar: 'ألغِ في أي وقت' },
  'Ready to Start Selling?': { fr: 'Prêt à commencer à vendre ?', ar: 'هل أنت مستعد للبيع؟' },

  // ==== Misc ====
  'Today': { fr: 'Aujourd\'hui', ar: 'اليوم' },
  'This Week': { fr: 'Cette semaine', ar: 'هذا الأسبوع' },
  'This Month': { fr: 'Ce mois-ci', ar: 'هذا الشهر' },
  'Last 30 Days': { fr: '30 derniers jours', ar: 'آخر 30 يوم' },
  'Revenue': { fr: 'Revenu', ar: 'الإيرادات' },
  'Total Revenue': { fr: 'Revenu total', ar: 'إجمالي الإيرادات' },
  'Total Orders': { fr: 'Total des commandes', ar: 'إجمالي الطلبات' },
  'Total Sales': { fr: 'Ventes totales', ar: 'إجمالي المبيعات' },
  'Avg Order': { fr: 'Commande moy.', ar: 'متوسط الطلب' },
  'Avg Order Value': { fr: 'Valeur moy. de commande', ar: 'متوسط قيمة الطلب' },
  'Conversion Rate': { fr: 'Taux de conversion', ar: 'معدل التحويل' },
  'Store Visits': { fr: 'Visites du magasin', ar: 'زيارات المتجر' },
  'Recent Orders': { fr: 'Commandes récentes', ar: 'الطلبات الأخيرة' },
  'Top Products': { fr: 'Meilleurs produits', ar: 'أفضل المنتجات' },
  'Order Status': { fr: 'Statut de la commande', ar: 'حالة الطلب' },
  'Performance': { fr: 'Performance', ar: 'الأداء' },
  'performance': { fr: 'performance', ar: 'الأداء' },

  // ==== Extended ====
  'Manage': { fr: 'Gérer', ar: 'إدارة' },
  'Manage your store': { fr: 'Gérez votre magasin', ar: 'إدارة متجرك' },
  'Manage your plan and payment history': { fr: 'Gérez votre forfait et l\'historique des paiements', ar: 'إدارة خطتك وسجل المدفوعات' },
  'Track your business expenses': { fr: 'Suivez vos dépenses', ar: 'تتبع نفقات عملك' },
  'Connect your own domain or use the platform URL': { fr: 'Connectez votre domaine ou utilisez l\'URL de la plateforme', ar: 'اربط نطاقك الخاص أو استخدم رابط المنصة' },
  'Track shipments with delivery partners': { fr: 'Suivez les expéditions avec les partenaires', ar: 'تتبع الشحنات مع شركاء التوصيل' },
  'Set your tax rate and see how much tax you owe on your revenue': { fr: 'Définissez votre taux de TVA et voyez la taxe due', ar: 'حدد معدل الضريبة واطلع على المستحقات' },
  'Add Expense': { fr: 'Ajouter une dépense', ar: 'إضافة مصروف' },
  'Edit Expense': { fr: 'Modifier la dépense', ar: 'تعديل المصروف' },
  'Total Expenses': { fr: 'Total des dépenses', ar: 'إجمالي المصاريف' },
  'Entries': { fr: 'Entrées', ar: 'الإدخالات' },
  'By Category': { fr: 'Par catégorie', ar: 'حسب الفئة' },
  'No expenses recorded': { fr: 'Aucune dépense enregistrée', ar: 'لا توجد مصاريف مسجلة' },
  'Amount': { fr: 'Montant', ar: 'المبلغ' },
  'Paid': { fr: 'Payé', ar: 'مدفوع' },
  'Overdue': { fr: 'En retard', ar: 'متأخر' },
  'Operations': { fr: 'Opérations', ar: 'العمليات' },
  'Marketing': { fr: 'Marketing', ar: 'التسويق' },
  'Utilities': { fr: 'Services publics', ar: 'المرافق' },
  'Inventory': { fr: 'Inventaire', ar: 'المخزون' },
  'Salaries': { fr: 'Salaires', ar: 'الرواتب' },
  'Rent': { fr: 'Loyer', ar: 'الإيجار' },
  'Other': { fr: 'Autre', ar: 'أخرى' },

  // Tax page
  'Tax Configuration': { fr: 'Configuration de la taxe', ar: 'إعدادات الضريبة' },
  'Applied storewide on checkout & invoices': { fr: 'Appliqué sur tout le magasin', ar: 'يطبق على المتجر بأكمله' },
  'Enable tax': { fr: 'Activer la taxe', ar: 'تفعيل الضريبة' },
  'Tax Rate (%)': { fr: 'Taux de taxe (%)', ar: 'نسبة الضريبة (%)' },
  'Label': { fr: 'Libellé', ar: 'التسمية' },
  'Price mode': { fr: 'Mode de prix', ar: 'وضع السعر' },
  'Presets:': { fr: 'Préréglages :', ar: 'الإعدادات المسبقة:' },
  'Tax on Revenue': { fr: 'Taxe sur les revenus', ar: 'الضريبة على الإيرادات' },
  'Quarter': { fr: 'Trimestre', ar: 'الربع' },
  'Year': { fr: 'Année', ar: 'السنة' },
  'All Time': { fr: 'Tout le temps', ar: 'كل الوقت' },
  'Taxable Base': { fr: 'Base imposable', ar: 'الأساس الخاضع للضريبة' },
  'owed': { fr: 'dû', ar: 'مستحق' },
  'Grand Total': { fr: 'Total général', ar: 'المجموع الكلي' },
  'Reset': { fr: 'Réinitialiser', ar: 'إعادة تعيين' },
  'Save Settings': { fr: 'Enregistrer les paramètres', ar: 'حفظ الإعدادات' },
  'Saving...': { fr: 'Enregistrement...', ar: 'جار الحفظ...' },

  // Billing page
  'Current Plan': { fr: 'Forfait actuel', ar: 'الخطة الحالية' },
  'SUSPENDED': { fr: 'SUSPENDU', ar: 'موقوف' },
  'ACTIVE': { fr: 'ACTIF', ar: 'نشط' },
  'FREE': { fr: 'GRATUIT', ar: 'مجاني' },
  'Expires:': { fr: 'Expire :', ar: 'تنتهي:' },
  'Save 20%': { fr: 'Économisez 20 %', ar: 'وفر 20%' },
  'Payment History': { fr: 'Historique des paiements', ar: 'سجل المدفوعات' },
  'No payments yet': { fr: 'Aucun paiement', ar: 'لا توجد مدفوعات بعد' },
  'Subscribe to': { fr: 'S\'abonner à', ar: 'الاشتراك في' },
  'Amount to pay': { fr: 'Montant à payer', ar: 'المبلغ المستحق' },
  'CCP Transfer': { fr: 'Virement CCP', ar: 'تحويل CCP' },
  'BaridiMob': { fr: 'BaridiMob', ar: 'بريدي موب' },
  'Upload Payment Receipt': { fr: 'Téléverser le reçu', ar: 'تحميل إيصال الدفع' },
  'Click to upload receipt screenshot': { fr: 'Cliquez pour téléverser', ar: 'انقر لتحميل لقطة الإيصال' },
  'Submit Payment': { fr: 'Envoyer le paiement', ar: 'إرسال الدفع' },
  'Select a plan': { fr: 'Choisir un forfait', ar: 'اختر خطة' },
  'Copied!': { fr: 'Copié !', ar: 'تم النسخ!' },

  // Domains page
  'Connect Domain': { fr: 'Connecter un domaine', ar: 'ربط نطاق' },
  'Active Store URL': { fr: 'URL active du magasin', ar: 'رابط المتجر النشط' },
  'Choose which URL your customers will use': { fr: 'Choisissez l\'URL que vos clients utiliseront', ar: 'اختر الرابط الذي سيستخدمه عملاؤك' },
  'Platform URL': { fr: 'URL de la plateforme', ar: 'رابط المنصة' },
  'CUSTOM': { fr: 'PERSONNALISÉ', ar: 'مخصص' },
  'Connected Domains': { fr: 'Domaines connectés', ar: 'النطاقات المتصلة' },
  'DNS not verified': { fr: 'DNS non vérifié', ar: 'DNS غير محقق' },
  'How to connect your domain': { fr: 'Comment connecter votre domaine', ar: 'كيفية ربط نطاقك' },
  'Type': { fr: 'Type', ar: 'النوع' },
  'Value': { fr: 'Valeur', ar: 'القيمة' },
  'Your Domain': { fr: 'Votre domaine', ar: 'نطاقك' },
  'Adding...': { fr: 'Ajout...', ar: 'جار الإضافة...' },

  // Tracking
  'Total Shipped': { fr: 'Total expédié', ar: 'إجمالي المشحون' },
  'With Tracking': { fr: 'Avec suivi', ar: 'مع تتبع' },
  'No Tracking': { fr: 'Sans suivi', ar: 'بدون تتبع' },
  'Destination': { fr: 'Destination', ar: 'الوجهة' },
  'Partner': { fr: 'Partenaire', ar: 'الشريك' },
  'LIVE': { fr: 'EN DIRECT', ar: 'مباشر' },
  'No tracking number': { fr: 'Aucun numéro de suivi', ar: 'لا يوجد رقم تتبع' },
  'Delivery Progress': { fr: 'Progression de la livraison', ar: 'تقدم التسليم' },
  'Awaiting Pickup': { fr: 'En attente de collecte', ar: 'في انتظار الاستلام' },
  'Picked Up': { fr: 'Collecté', ar: 'تم الاستلام' },
  'At Center': { fr: 'Au centre', ar: 'في المركز' },
  'In Transit': { fr: 'En transit', ar: 'في الطريق' },
  'Out for Delivery': { fr: 'En cours de livraison', ar: 'قارب على التسليم' },
  'Timeline': { fr: 'Chronologie', ar: 'الجدول الزمني' },
  'Track on': { fr: 'Suivre sur', ar: 'تتبع على' },

  // Analytics
  'Order Status Breakdown': { fr: 'Répartition des statuts', ar: 'توزيع حالات الطلبات' },
  'Revenue & Orders (Last 30 Days)': { fr: 'Revenus et commandes (30 derniers jours)', ar: 'الإيرادات والطلبات (آخر 30 يوم)' },
  'No order data yet': { fr: 'Aucune donnée de commande', ar: 'لا توجد بيانات طلبات' },
  'No product data yet': { fr: 'Aucune donnée produit', ar: 'لا توجد بيانات منتجات' },
  'Quantity sold': { fr: 'Quantité vendue', ar: 'الكمية المباعة' },

  // Apps
  'Supercharge your store with powerful apps and integrations.': { fr: 'Boostez votre magasin avec des applications puissantes.', ar: 'عزز متجرك بتطبيقات قوية.' },
  'Install': { fr: 'Installer', ar: 'تثبيت' },
  'Uninstall': { fr: 'Désinstaller', ar: 'إلغاء التثبيت' },
  'Coming soon': { fr: 'Bientôt disponible', ar: 'قريباً' },
  'Installed': { fr: 'Installé', ar: 'مثبت' },

  // Recovery
  'Manage and automate abandoned order conversion.': { fr: 'Gérez et automatisez la conversion des paniers abandonnés.', ar: 'إدارة وأتمتة تحويل الطلبات المتروكة.' },
  'Total Carts': { fr: 'Total des paniers', ar: 'إجمالي السلال' },
  'Recovered': { fr: 'Récupérés', ar: 'المسترد' },
  'Recovered Revenue': { fr: 'Revenu récupéré', ar: 'الإيرادات المستردة' },
  'Lost Revenue': { fr: 'Revenu perdu', ar: 'الإيرادات المفقودة' },
  'Sync Data': { fr: 'Synchroniser', ar: 'مزامنة البيانات' },
  'Automation Settings': { fr: 'Paramètres d\'automatisation', ar: 'إعدادات الأتمتة' },

  // Settings tabs
  'Store Details': { fr: 'Détails du magasin', ar: 'تفاصيل المتجر' },
  'Customization': { fr: 'Personnalisation', ar: 'التخصيص' },
  'Users & Permissions': { fr: 'Utilisateurs et permissions', ar: 'المستخدمون والصلاحيات' },
  'Checkout': { fr: 'Paiement', ar: 'الدفع' },
  'Payments': { fr: 'Paiements', ar: 'المدفوعات' },
  'Notifications': { fr: 'Notifications', ar: 'الإشعارات' },
  'Marketing & Pixels': { fr: 'Marketing et pixels', ar: 'التسويق والبكسلات' },
  'AI Messaging': { fr: 'Messagerie IA', ar: 'رسائل الذكاء الاصطناعي' },
  'Subscription': { fr: 'Abonnement', ar: 'الاشتراك' },
  'Account': { fr: 'Compte', ar: 'الحساب' },
  'Hero Title': { fr: 'Titre du héros', ar: 'العنوان الرئيسي' },
  'Hero Subtitle': { fr: 'Sous-titre du héros', ar: 'العنوان الفرعي' },
  'Meta Title (SEO)': { fr: 'Titre Meta (SEO)', ar: 'عنوان ميتا (SEO)' },
  'Meta Description (SEO)': { fr: 'Description Meta (SEO)', ar: 'وصف ميتا (SEO)' },
  'Background Color': { fr: 'Couleur de fond', ar: 'لون الخلفية' },
  'Accent Color': { fr: 'Couleur d\'accent', ar: 'لون التمييز' },
  'AI Chatbot': { fr: 'Chatbot IA', ar: 'روبوت الدردشة' },
  'Bot Name': { fr: 'Nom du bot', ar: 'اسم الروبوت' },
  'Greeting Message': { fr: 'Message d\'accueil', ar: 'رسالة الترحيب' },
  'AI Fake Order Detection': { fr: 'Détection de fausses commandes', ar: 'كشف الطلبات الوهمية' },
  'AI Cart Recovery': { fr: 'Récupération de panier IA', ar: 'استرداد السلة بالذكاء الاصطناعي' },
  'Store is Live (Published)': { fr: 'Le magasin est en ligne', ar: 'المتجر منشور' },
  'Contact Phone / WhatsApp': { fr: 'Téléphone / WhatsApp', ar: 'الهاتف / واتساب' },
  'Contact Email': { fr: 'E-mail de contact', ar: 'بريد التواصل' },
  'Upload logo from device': { fr: 'Téléverser le logo', ar: 'تحميل الشعار من الجهاز' },

  // Storefront / buyer
  'Add to Cart': { fr: 'Ajouter au panier', ar: 'أضف إلى السلة' },
  'Buy Now': { fr: 'Acheter maintenant', ar: 'اشترِ الآن' },
  'Cart': { fr: 'Panier', ar: 'السلة' },
  'Continue Shopping': { fr: 'Continuer les achats', ar: 'متابعة التسوق' },
  'Order Summary': { fr: 'Résumé de la commande', ar: 'ملخص الطلب' },
  'Place Order': { fr: 'Passer la commande', ar: 'إرسال الطلب' },
  'Order Placed Successfully!': { fr: 'Commande passée avec succès !', ar: 'تم إرسال الطلب بنجاح!' },
  'Cash on Delivery': { fr: 'Paiement à la livraison', ar: 'الدفع عند الاستلام' },
  'Bank Transfer': { fr: 'Virement bancaire', ar: 'تحويل بنكي' },
  'Shipping Information': { fr: 'Informations de livraison', ar: 'معلومات الشحن' },
  'Favorites': { fr: 'Favoris', ar: 'المفضلة' },
  'My Orders': { fr: 'Mes commandes', ar: 'طلباتي' },
  'My Profile': { fr: 'Mon profil', ar: 'ملفي الشخصي' },

  // Admin
  'Store Owners': { fr: 'Propriétaires de magasin', ar: 'أصحاب المتاجر' },
  'All Stores': { fr: 'Tous les magasins', ar: 'جميع المتاجر' },
  'All Orders': { fr: 'Toutes les commandes', ar: 'جميع الطلبات' },
  'Site Branding': { fr: 'Image du site', ar: 'هوية الموقع' },
  'System Health': { fr: 'État du système', ar: 'صحة النظام' },
  'Super Admins': { fr: 'Super administrateurs', ar: 'المشرفون الكبار' },
  'Super Admin': { fr: 'Super administrateur', ar: 'مشرف كبير' },
  'Control Panel': { fr: 'Panneau de contrôle', ar: 'لوحة التحكم' },
  'Platform Overview': { fr: 'Aperçu de la plateforme', ar: 'نظرة عامة على المنصة' },
  'Platform Administration': { fr: 'Administration de la plateforme', ar: 'إدارة المنصة' },
  'Update Login Info': { fr: 'Mettre à jour les identifiants', ar: 'تحديث معلومات الدخول' },
  'Across Stores': { fr: 'Dans tous les magasins', ar: 'عبر المتاجر' },
  'Registered Buyers': { fr: 'Acheteurs inscrits', ar: 'المشترون المسجلون' },
  'Admin': { fr: 'Administrateur', ar: 'المسؤول' },

  // ==== Apps page ====
  'AI Customer Chatbot': { fr: 'Chatbot client IA', ar: 'روبوت دردشة العملاء' },
  'AI Product Descriptions': { fr: 'Descriptions IA des produits', ar: 'أوصاف المنتجات بالذكاء الاصطناعي' },
  'AI Messaging Agent': { fr: 'Agent de messagerie IA', ar: 'وكيل الرسائل الذكي' },
  'Fake Order Detection': { fr: 'Détection des fausses commandes', ar: 'كشف الطلبات الوهمية' },
  'Smart Reviews': { fr: 'Avis intelligents', ar: 'المراجعات الذكية' },
  'Abandoned Cart Recovery': { fr: 'Récupération de panier abandonné', ar: 'استرداد السلة المتروكة' },
  'Inventory Management': { fr: 'Gestion des stocks', ar: 'إدارة المخزون' },
  'Blacklist Automation': { fr: 'Liste noire automatique', ar: 'القائمة السوداء التلقائية' },
  'Google Sheets Sync': { fr: 'Synchronisation Google Sheets', ar: 'مزامنة جداول جوجل' },
  'WhatsApp Recovery Messages': { fr: 'Messages de récupération WhatsApp', ar: 'رسائل الاسترداد عبر واتساب' },
  'Domain Management': { fr: 'Gestion des domaines', ar: 'إدارة النطاقات' },
  'Activate AI features and integrations': { fr: 'Activez les fonctionnalités IA et les intégrations', ar: 'فعّل ميزات الذكاء الاصطناعي والتكاملات' },
  'AI-moderated product reviews.': { fr: 'Avis de produits modérés par IA.', ar: 'مراجعات المنتجات بإشراف الذكاء الاصطناعي.' },
  'AI-powered fraud scoring.': { fr: 'Notation de fraude par IA.', ar: 'تقييم الاحتيال بالذكاء الاصطناعي.' },
  'AI-generated recovery messages': { fr: 'Messages de récupération générés par IA', ar: 'رسائل استرداد بالذكاء الاصطناعي' },
  'Track and recover abandoned carts with AI messages.': { fr: 'Suivez et récupérez les paniers abandonnés.', ar: 'تتبع واسترد السلال المتروكة برسائل ذكية.' },
  'Track product stock levels automatically.': { fr: 'Suivez automatiquement les niveaux de stock.', ar: 'تتبع مستويات المخزون تلقائياً.' },
  'Automatic blacklisting on repeated cancellations.': { fr: 'Liste noire auto sur annulations répétées.', ar: 'قائمة سوداء تلقائية عند الإلغاءات المتكررة.' },
  'Send recovery messages via WhatsApp.': { fr: 'Envoyez des messages de récupération via WhatsApp.', ar: 'أرسل رسائل الاسترداد عبر واتساب.' },
  'Connect custom domains.': { fr: 'Connectez des domaines personnalisés.', ar: 'اربط نطاقات مخصصة.' },
  'Export orders to Google Sheets.': { fr: 'Exportez les commandes vers Google Sheets.', ar: 'تصدير الطلبات إلى جداول جوجل.' },
  'Smart support bot.': { fr: 'Bot d\'assistance intelligent.', ar: 'روبوت دعم ذكي.' },
  'Generate descriptions instantly': { fr: 'Générez des descriptions instantanément', ar: 'أنشئ الأوصاف فوراً' },
  'Automated engagement, confirmations, and follow-ups.': { fr: 'Engagement, confirmations et suivis automatisés.', ar: 'تفاعل وتأكيدات ومتابعات مؤتمتة.' },
  'Score orders for fraud.': { fr: 'Notez les commandes pour la fraude.', ar: 'قيّم الطلبات للكشف عن الاحتيال.' },
  'Connected': { fr: 'Connecté', ar: 'متصل' },
  'Not Connected': { fr: 'Non connecté', ar: 'غير متصل' },
  'Disconnect': { fr: 'Déconnecter', ar: 'قطع الاتصال' },
  'Connect': { fr: 'Connecter', ar: 'اتصال' },
  'Test Chatbot': { fr: 'Tester le chatbot', ar: 'اختبر الروبوت' },
  'Test AI Descriptions': { fr: 'Tester les descriptions IA', ar: 'اختبر أوصاف الذكاء الاصطناعي' },
  'Test Fraud Detection': { fr: 'Tester la détection de fraude', ar: 'اختبر كشف الاحتيال' },
  'Test Cart Recovery': { fr: 'Tester la récupération de panier', ar: 'اختبر استرداد السلة' },
  'Test Connection': { fr: 'Tester la connexion', ar: 'اختبر الاتصال' },
  'Test Email': { fr: 'E-mail de test', ar: 'بريد اختبار' },
  'Test API': { fr: 'Tester l\'API', ar: 'اختبر API' },
  'Test WhatsApp': { fr: 'Tester WhatsApp', ar: 'اختبر واتساب' },
  'Test Store': { fr: 'Magasin de test', ar: 'متجر تجريبي' },
  'Test Customer': { fr: 'Client test', ar: 'عميل تجريبي' },
  'Test order fraud scoring': { fr: 'Test de notation de fraude', ar: 'اختبار تقييم الاحتيال' },
  'Test the connection': { fr: 'Tester la connexion', ar: 'اختبر الاتصال' },
  'Test from your store': { fr: 'Test depuis votre magasin', ar: 'اختبار من متجرك' },
  'Test your store\'s chatbot': { fr: 'Testez le chatbot de votre magasin', ar: 'اختبر روبوت متجرك' },
  'Send Test': { fr: 'Envoyer le test', ar: 'إرسال اختبار' },
  'Send Test Email': { fr: 'Envoyer un e-mail test', ar: 'إرسال بريد اختبار' },
  'Send Test Message': { fr: 'Envoyer un message test', ar: 'إرسال رسالة اختبار' },
  'Send a test email': { fr: 'Envoyer un e-mail de test', ar: 'إرسال بريد إلكتروني تجريبي' },
  'Connect your WhatsApp': { fr: 'Connectez votre WhatsApp', ar: 'اربط واتساب الخاص بك' },
  'Connect your WhatsApp to send order updates': { fr: 'Connectez votre WhatsApp pour envoyer les mises à jour', ar: 'اربط واتساب لإرسال تحديثات الطلبات' },
  'Scan with WhatsApp': { fr: 'Scanner avec WhatsApp', ar: 'امسح بواتساب' },
  'Scan with WhatsApp Business': { fr: 'Scanner avec WhatsApp Business', ar: 'امسح بواتساب الأعمال' },
  'Waiting for scan...': { fr: 'En attente du scan...', ar: 'في انتظار المسح...' },
  'Generate QR': { fr: 'Générer un QR', ar: 'إنشاء QR' },
  'Generate QR Code': { fr: 'Générer le code QR', ar: 'إنشاء رمز QR' },
  'Refresh QR': { fr: 'Actualiser le QR', ar: 'تحديث QR' },
  'Replace QR': { fr: 'Remplacer le QR', ar: 'استبدال QR' },
  'Upload QR image': { fr: 'Téléverser l\'image QR', ar: 'تحميل صورة QR' },
  'WhatsApp Connection': { fr: 'Connexion WhatsApp', ar: 'اتصال واتساب' },
  'Coming soon!': { fr: 'Bientôt disponible !', ar: 'قريباً!' },

  // ==== Add / Edit Product modal ====
  'Create Product': { fr: 'Créer un produit', ar: 'إنشاء منتج' },
  'Update Product': { fr: 'Mettre à jour le produit', ar: 'تحديث المنتج' },
  'Product description...': { fr: 'Description du produit...', ar: 'وصف المنتج...' },
  'Compare Price': { fr: 'Prix comparé', ar: 'سعر المقارنة' },
  'SKU': { fr: 'SKU', ar: 'SKU' },
  'Main Images': { fr: 'Images principales', ar: 'الصور الرئيسية' },
  'Cover Image': { fr: 'Image de couverture', ar: 'صورة الغلاف' },
  'Variant': { fr: 'Variante', ar: 'متغير' },
  'Add Variant': { fr: 'Ajouter une variante', ar: 'إضافة متغير' },
  'Variant Images': { fr: 'Images de variante', ar: 'صور المتغير' },
  'Variant details...': { fr: 'Détails de la variante...', ar: 'تفاصيل المتغير...' },
  'Color': { fr: 'Couleur', ar: 'اللون' },
  'Size': { fr: 'Taille', ar: 'المقاس' },
  'Material': { fr: 'Matière', ar: 'المادة' },
  'Style': { fr: 'Style', ar: 'النمط' },
  'Manage Stock': { fr: 'Gérer le stock', ar: 'إدارة المخزون' },
  'Low Stock Threshold': { fr: 'Seuil de stock faible', ar: 'حد المخزون المنخفض' },
  'Show Stock on Storefront': { fr: 'Afficher le stock', ar: 'عرض المخزون في المتجر' },
  'AI Generate': { fr: 'Générer avec IA', ar: 'إنشاء بالذكاء الاصطناعي' },
  'Generate Description': { fr: 'Générer la description', ar: 'إنشاء الوصف' },
  'AI description generated!': { fr: 'Description IA générée !', ar: 'تم إنشاء الوصف!' },
  'AI descriptions generated in 3 languages!': { fr: 'Descriptions IA dans 3 langues !', ar: 'تم إنشاء الأوصاف بثلاث لغات!' },
  'AI generation failed': { fr: 'Échec de la génération IA', ar: 'فشل توليد الذكاء الاصطناعي' },
  'All 3 Languages': { fr: 'Les 3 langues', ar: 'كل اللغات الثلاث' },
  'Enter product name': { fr: 'Entrez le nom du produit', ar: 'أدخل اسم المنتج' },
  'Enter product name first': { fr: 'Entrez d\'abord le nom du produit', ar: 'أدخل اسم المنتج أولاً' },
  'Name and price required': { fr: 'Nom et prix requis', ar: 'الاسم والسعر مطلوبان' },
  'Click to upload': { fr: 'Cliquez pour téléverser', ar: 'انقر للتحميل' },
  'Upload images': { fr: 'Téléverser des images', ar: 'تحميل الصور' },
  'Uploaded!': { fr: 'Téléversé !', ar: 'تم التحميل!' },
  'Threshold': { fr: 'Seuil', ar: 'العتبة' },
  'Total SKUs': { fr: 'Total des SKU', ar: 'إجمالي SKU' },

  // ==== Shipping Partners ====
  'Add Delivery Company': { fr: 'Ajouter une société de livraison', ar: 'إضافة شركة توصيل' },
  'Add Company': { fr: 'Ajouter une société', ar: 'إضافة شركة' },
  'Add your delivery companies': { fr: 'Ajoutez vos sociétés de livraison', ar: 'أضف شركات التوصيل الخاصة بك' },
  'No delivery companies yet': { fr: 'Aucune société de livraison', ar: 'لا توجد شركات توصيل بعد' },
  'Choose Partner': { fr: 'Choisir un partenaire', ar: 'اختر الشريك' },
  'Quick setup or add any company you want.': { fr: 'Configuration rapide ou ajoutez la société de votre choix.', ar: 'إعداد سريع أو أضف أي شركة تريدها.' },
  'Connect multiple partners and choose the best rate.': { fr: 'Connectez plusieurs partenaires et choisissez le meilleur tarif.', ar: 'اربط عدة شركاء واختر أفضل سعر.' },
  'Any Other Company': { fr: 'Toute autre société', ar: 'أي شركة أخرى' },
  'Any company name': { fr: 'Nom de la société', ar: 'أي اسم شركة' },
  'Company': { fr: 'Société', ar: 'الشركة' },
  'Company name required': { fr: 'Nom de la société requis', ar: 'اسم الشركة مطلوب' },
  'API Configuration': { fr: 'Configuration API', ar: 'إعدادات API' },
  'API Connected': { fr: 'API connectée', ar: 'API متصل' },
  'Authentication': { fr: 'Authentification', ar: 'المصادقة' },
  'Authentication Type': { fr: 'Type d\'authentification', ar: 'نوع المصادقة' },
  'No Authentication': { fr: 'Aucune authentification', ar: 'بدون مصادقة' },
  'Bearer Token': { fr: 'Jeton Bearer', ar: 'رمز Bearer' },
  'Custom Headers': { fr: 'En-têtes personnalisés', ar: 'رؤوس مخصصة' },
  'Headers': { fr: 'En-têtes', ar: 'الرؤوس' },
  'Header-Name': { fr: 'Nom de l\'en-tête', ar: 'اسم الرأس' },
  'Status Field Path': { fr: 'Chemin du champ statut', ar: 'مسار حقل الحالة' },
  'Path to check parcel status. Use': { fr: 'Chemin pour vérifier le statut du colis. Utilisez', ar: 'مسار لفحص حالة الطرد. استخدم' },
  'Get API keys from your delivery partner': { fr: 'Obtenez les clés API auprès de votre partenaire', ar: 'احصل على مفاتيح API من شريك التوصيل' },
  'Get these from your delivery company\'s API documentation.': { fr: 'Obtenez-les depuis la documentation API de votre transporteur.', ar: 'احصل عليها من وثائق API لشركة التوصيل.' },
  'Contact NOEST for API credentials': { fr: 'Contactez NOEST pour les identifiants API', ar: 'تواصل مع NOEST للحصول على بيانات API' },
  'Contact Maystro support for API access': { fr: 'Contactez le support Maystro pour l\'accès API', ar: 'تواصل مع دعم Maystro للوصول' },
  'Enable API Tracking': { fr: 'Activer le suivi API', ar: 'تفعيل تتبع API' },
  'Enter API Base URL first': { fr: 'Entrez d\'abord l\'URL de base API', ar: 'أدخل عنوان API الأساسي أولاً' },
  'Enter your API ID and Token': { fr: 'Entrez votre ID API et jeton', ar: 'أدخل معرف API والرمز' },
  'Instant Tracking': { fr: 'Suivi instantané', ar: 'تتبع فوري' },
  'Tracking numbers are returned instantly and saved back.': { fr: 'Les numéros de suivi sont retournés instantanément.', ar: 'تُرجع أرقام التتبع فوراً وتُحفظ.' },
  'Ready to automate? Connection takes less than 2 minutes.': { fr: 'Prêt à automatiser ? La connexion prend moins de 2 minutes.', ar: 'جاهز للأتمتة؟ الاتصال يستغرق أقل من دقيقتين.' },
  'Obtain Credentials': { fr: 'Obtenir les identifiants', ar: 'الحصول على بيانات الاعتماد' },
  'Step-by-step connection guide': { fr: 'Guide de connexion étape par étape', ar: 'دليل اتصال خطوة بخطوة' },
  'Verify Link': { fr: 'Vérifier le lien', ar: 'التحقق من الرابط' },
  'Avg Rate': { fr: 'Taux moyen', ar: 'متوسط السعر' },
  'Partners': { fr: 'Partenaires', ar: 'الشركاء' },
  'Yalidine': { fr: 'Yalidine', ar: 'ياليدين' },
  'NOEST': { fr: 'NOEST', ar: 'NOEST' },
  'Maystro Delivery': { fr: 'Maystro Delivery', ar: 'مايسترو' },
  'ZR Express': { fr: 'ZR Express', ar: 'ZR إكسبرس' },

  // ==== Shipping Wilayas ====
  'Active Wilayas': { fr: 'Wilayas actives', ar: 'الولايات النشطة' },
  'Inactive Wilayas': { fr: 'Wilayas inactives', ar: 'الولايات غير النشطة' },
  'Total Wilayas': { fr: 'Total des wilayas', ar: 'إجمالي الولايات' },
  'Delivery Wilayas': { fr: 'Wilayas de livraison', ar: 'ولايات التوصيل' },
  'Desk': { fr: 'Bureau', ar: 'المكتب' },
  'Desk Price': { fr: 'Prix bureau', ar: 'سعر المكتب' },
  'Home Price': { fr: 'Prix domicile', ar: 'سعر المنزل' },
  'Days': { fr: 'Jours', ar: 'أيام' },
  'Load All 58 Wilayas': { fr: 'Charger les 58 wilayas', ar: 'تحميل جميع الولايات' },
  'Manage in Detail': { fr: 'Gérer en détail', ar: 'إدارة مفصلة' },
  'No shipping wilayas configured yet.': { fr: 'Aucune wilaya configurée.', ar: 'لم يتم تكوين أي ولاية بعد.' },
  'Search by name or code...': { fr: 'Rechercher par nom ou code...', ar: 'ابحث بالاسم أو الرمز...' },
  'MANAGE DELIVERY DESKS': { fr: 'GÉRER LES BUREAUX DE LIVRAISON', ar: 'إدارة مكاتب التوصيل' },

  // ==== How to Connect ====
  'CONNECT YOUR PLATFORMS': { fr: 'CONNECTEZ VOS PLATEFORMES', ar: 'اربط منصاتك' },
  'LOGISTICS CONFIGURATION': { fr: 'CONFIGURATION LOGISTIQUE', ar: 'إعدادات الخدمات اللوجستية' },
  'Technical Integration': { fr: 'Intégration technique', ar: 'التكامل التقني' },
  'Developer Documentation': { fr: 'Documentation développeur', ar: 'وثائق المطور' },
  'Security Credentials': { fr: 'Identifiants de sécurité', ar: 'بيانات الأمان' },

  // ==== Settings - Customization / Dashboard / etc ====
  'Customization': { fr: 'Personnalisation', ar: 'التخصيص' },
  'Dashboard': { fr: 'Tableau de bord', ar: 'لوحة التحكم' },
  'Store Identity': { fr: 'Identité du magasin', ar: 'هوية المتجر' },
  'Brand Assets': { fr: 'Ressources de marque', ar: 'أصول العلامة' },
  'Brand Essence': { fr: 'Essence de la marque', ar: 'جوهر العلامة' },
  'Choose a starting point or craft your unique style.': { fr: 'Choisissez un point de départ ou créez votre style.', ar: 'اختر نقطة بداية أو ابتكر أسلوبك.' },
  'Manage how your business appears to the world.': { fr: 'Gérez comment votre entreprise apparaît au monde.', ar: 'إدارة طريقة ظهور عملك للعالم.' },
  'Design Studio': { fr: 'Studio de design', ar: 'استوديو التصميم' },
  'Primary Brand Color': { fr: 'Couleur principale de la marque', ar: 'لون العلامة الأساسي' },
  'Primary Text': { fr: 'Texte principal', ar: 'النص الأساسي' },
  'Secondary Text': { fr: 'Texte secondaire', ar: 'النص الثانوي' },
  'Text Colors': { fr: 'Couleurs du texte', ar: 'ألوان النص' },
  'Trust Signals': { fr: 'Signaux de confiance', ar: 'إشارات الثقة' },
  'Security badges.': { fr: 'Badges de sécurité.', ar: 'شارات الأمان.' },
  'Always visible Buy Now.': { fr: 'Bouton Acheter toujours visible.', ar: 'زر اشترِ الآن دائم الظهور.' },
  'Side-cart on click.': { fr: 'Panier latéral au clic.', ar: 'سلة جانبية عند النقر.' },
  'Display \'Only X left\' message.': { fr: 'Afficher \'Plus que X disponibles\'.', ar: 'إظهار رسالة \'تبقى X فقط\'.' },
  'Highlight discounts.': { fr: 'Mettre en avant les remises.', ar: 'إبراز الخصومات.' },
  'Sticky Header': { fr: 'En-tête fixe', ar: 'رأس ثابت' },
  'Sticky Checkout': { fr: 'Paiement fixe', ar: 'دفع ثابت' },
  'Cart Drawer': { fr: 'Tiroir du panier', ar: 'درج السلة' },
  'Page Transitions': { fr: 'Transitions de page', ar: 'انتقالات الصفحات' },
  'Show Savings': { fr: 'Afficher les économies', ar: 'إظهار التوفير' },
  'Show Date': { fr: 'Afficher la date', ar: 'إظهار التاريخ' },
  'Display system date': { fr: 'Afficher la date système', ar: 'عرض تاريخ النظام' },
  'Module Visibility': { fr: 'Visibilité des modules', ar: 'رؤية الوحدات' },
  'Quick-entry tools': { fr: 'Outils de saisie rapide', ar: 'أدوات الإدخال السريع' },
  'Action Bar': { fr: 'Barre d\'action', ar: 'شريط الإجراءات' },
  'Bulk Actions': { fr: 'Actions groupées', ar: 'إجراءات جماعية' },
  'Pulse Charts': { fr: 'Graphiques Pulse', ar: 'مخططات النبض' },
  'Visual trend analysis': { fr: 'Analyse visuelle des tendances', ar: 'تحليل بصري للاتجاهات' },
  'Chart Type': { fr: 'Type de graphique', ar: 'نوع المخطط' },
  'Command Center': { fr: 'Centre de commande', ar: 'مركز التحكم' },
  'Configure your primary workflow hub.': { fr: 'Configurez votre hub de flux de travail.', ar: 'قم بإعداد مركز سير العمل الأساسي.' },
  'Core financial metrics': { fr: 'Indicateurs financiers clés', ar: 'مؤشرات مالية أساسية' },
  'Customer activity': { fr: 'Activité des clients', ar: 'نشاط العملاء' },
  'Real-time order data': { fr: 'Données de commandes en temps réel', ar: 'بيانات الطلبات الفورية' },
  'Delivery coordination': { fr: 'Coordination des livraisons', ar: 'تنسيق التوصيل' },
  'Health': { fr: 'Santé', ar: 'الصحة' },
  'Log Stream': { fr: 'Flux de journal', ar: 'تدفق السجلات' },
  'Notification Center': { fr: 'Centre de notifications', ar: 'مركز الإشعارات' },
  'Email Digests': { fr: 'Résumés e-mail', ar: 'ملخصات البريد' },
  'Push Alerts': { fr: 'Alertes push', ar: 'تنبيهات فورية' },
  'Email alerts': { fr: 'Alertes e-mail', ar: 'تنبيهات بريدية' },
  'Stock alerts': { fr: 'Alertes de stock', ar: 'تنبيهات المخزون' },
  'Daily summary and critical alerts': { fr: 'Résumé quotidien et alertes critiques', ar: 'ملخص يومي وتنبيهات هامة' },
  'Recipient Email': { fr: 'E-mail du destinataire', ar: 'بريد المستلم' },
  'Admin recipient for all system emails': { fr: 'Destinataire admin pour les e-mails système', ar: 'مستلم المسؤول لجميع رسائل النظام' },
  'New orders and status changes': { fr: 'Nouvelles commandes et changements de statut', ar: 'الطلبات الجديدة وتغييرات الحالة' },
  'Low stock notifications': { fr: 'Notifications de stock faible', ar: 'إشعارات المخزون المنخفض' },
  'New registrations': { fr: 'Nouvelles inscriptions', ar: 'التسجيلات الجديدة' },
  'Order updates': { fr: 'Mises à jour des commandes', ar: 'تحديثات الطلبات' },
  'Order Status Notifications': { fr: 'Notifications de statut', ar: 'إشعارات حالة الطلب' },
  'Auto-notify customers on status changes.': { fr: 'Notifier les clients automatiquement.', ar: 'إخطار العملاء تلقائياً عند تغيير الحالة.' },
  'Order Configuration': { fr: 'Configuration des commandes', ar: 'إعدادات الطلبات' },
  'Order ID Format': { fr: 'Format de l\'ID de commande', ar: 'تنسيق معرف الطلب' },
  'Sequencing logic and archiving rules.': { fr: 'Logique de séquençage et règles d\'archivage.', ar: 'منطق الترقيم وقواعد الأرشفة.' },
  'Auto-Archive': { fr: 'Archivage automatique', ar: 'أرشفة تلقائية' },
  'Move completed orders to archive after 30 days.': { fr: 'Archiver les commandes terminées après 30 jours.', ar: 'نقل الطلبات المكتملة للأرشيف بعد 30 يوم.' },
  'Prefix': { fr: 'Préfixe', ar: 'البادئة' },
  'Suffix': { fr: 'Suffixe', ar: 'اللاحقة' },
  'Start Number': { fr: 'Numéro de départ', ar: 'رقم البداية' },
  'Stock tracking and visibility policies.': { fr: 'Suivi du stock et politiques de visibilité.', ar: 'تتبع المخزون وسياسات الظهور.' },
  'Flag items below this count': { fr: 'Marquer les articles sous ce seuil', ar: 'وضع علامة على العناصر أقل من هذا العدد' },
  'Roles & Permissions': { fr: 'Rôles et permissions', ar: 'الأدوار والصلاحيات' },
  'Team Members': { fr: 'Membres de l\'équipe', ar: 'أعضاء الفريق' },
  'No team members yet': { fr: 'Aucun membre pour le moment', ar: 'لا يوجد أعضاء بعد' },
  'Create New User': { fr: 'Créer un utilisateur', ar: 'إنشاء مستخدم' },
  'Create User': { fr: 'Créer l\'utilisateur', ar: 'إنشاء المستخدم' },
  'Manager': { fr: 'Manager', ar: 'مدير' },
  'Preparer': { fr: 'Préparateur', ar: 'محضّر' },
  'Confirmer': { fr: 'Confirmateur', ar: 'مؤكِّد' },
  'Accountant': { fr: 'Comptable', ar: 'محاسب' },
  'Viewer': { fr: 'Observateur', ar: 'مشاهد' },
  'Full access': { fr: 'Accès complet', ar: 'وصول كامل' },
  'Read-only': { fr: 'Lecture seule', ar: 'للقراءة فقط' },

  // Currency / regional
  'DZD - Algerian Dinar': { fr: 'DZD - Dinar algérien', ar: 'دينار جزائري' },
  'EUR - Euro': { fr: 'EUR - Euro', ar: 'يورو' },
  'USD - Dollar': { fr: 'USD - Dollar', ar: 'دولار' },
  'Store Currency': { fr: 'Devise du magasin', ar: 'عملة المتجر' },
  'Default Language': { fr: 'Langue par défaut', ar: 'اللغة الافتراضية' },
  'Interface Language': { fr: 'Langue de l\'interface', ar: 'لغة الواجهة' },
  'Regional Settings': { fr: 'Paramètres régionaux', ar: 'الإعدادات الإقليمية' },
  'CURRENCY & LANGUAGE': { fr: 'DEVISE ET LANGUE', ar: 'العملة واللغة' },
  'English': { fr: 'Anglais', ar: 'الإنجليزية' },
  'French': { fr: 'Français', ar: 'الفرنسية' },
  'Arabic': { fr: 'Arabe', ar: 'العربية' },

  // Tax / pricing
  'Apply tax to all orders': { fr: 'Appliquer la taxe à toutes les commandes', ar: 'تطبيق الضريبة على جميع الطلبات' },
  'Enable Tax': { fr: 'Activer la taxe', ar: 'تفعيل الضريبة' },
  'Price Mode': { fr: 'Mode de prix', ar: 'وضع السعر' },
  'TAP 2%': { fr: 'TAP 2 %', ar: 'TAP 2%' },
  'TVA 9%': { fr: 'TVA 9 %', ar: 'TVA 9%' },
  'TVA 19%': { fr: 'TVA 19 %', ar: 'TVA 19%' },
  'For detailed revenue-based tax calculations, visit the': { fr: 'Pour des calculs détaillés, visitez la', ar: 'لحسابات الضريبة المفصلة، تفضل بزيارة' },
  'Taxes page': { fr: 'page des taxes', ar: 'صفحة الضرائب' },

  // Domains / SEO
  'Custom Domain': { fr: 'Domaine personnalisé', ar: 'نطاق مخصص' },
  'Current Domain': { fr: 'Domaine actuel', ar: 'النطاق الحالي' },
  'Force HTTPS': { fr: 'Forcer HTTPS', ar: 'فرض HTTPS' },
  'Redirect www': { fr: 'Rediriger www', ar: 'إعادة توجيه www' },
  'Clean URLs': { fr: 'URLs propres', ar: 'روابط نظيفة' },
  'Remove .html extensions.': { fr: 'Supprimer les extensions .html.', ar: 'إزالة امتدادات .html.' },
  'IMPROVE VISIBILITY ON GOOGLE': { fr: 'AMÉLIORER LA VISIBILITÉ SUR GOOGLE', ar: 'تحسين الظهور في جوجل' },

  // Marketing & Pixels
  'Pixel Configuration': { fr: 'Configuration des pixels', ar: 'إعداد البكسلات' },
  'Conversion pixels and telemetry.': { fr: 'Pixels de conversion et télémétrie.', ar: 'بكسلات التحويل والقياس عن بعد.' },
  'Facebook Pixel ID': { fr: 'ID Pixel Facebook', ar: 'معرف بكسل فيسبوك' },
  'TikTok Pixel ID': { fr: 'ID Pixel TikTok', ar: 'معرف بكسل تيك توك' },
  'Snapchat Pixel ID': { fr: 'ID Pixel Snapchat', ar: 'معرف بكسل سناب شات' },
  'Google Analytics ID': { fr: 'ID Google Analytics', ar: 'معرف جوجل أناليتكس' },
  'Telemetry': { fr: 'Télémétrie', ar: 'القياس عن بعد' },
  'Tracking & Analytics': { fr: 'Suivi et analyses', ar: 'التتبع والتحليلات' },
  'Data Collection': { fr: 'Collecte de données', ar: 'جمع البيانات' },
  'Email Collection': { fr: 'Collecte d\'e-mails', ar: 'جمع البريد الإلكتروني' },
  'Custom Scripts': { fr: 'Scripts personnalisés', ar: 'سكريبتات مخصصة' },
  'Runs on checkout page only.': { fr: 'S\'exécute uniquement sur la page de paiement.', ar: 'يعمل فقط في صفحة الدفع.' },
  'Safe Data Relay': { fr: 'Relais de données sécurisé', ar: 'ترحيل البيانات الآمن' },
  'All customer data are pushed through encrypted endpoints.': { fr: 'Toutes les données client passent par des points chiffrés.', ar: 'جميع بيانات العملاء تمر عبر نقاط مشفرة.' },

  // Security
  'Security': { fr: 'Sécurité', ar: 'الأمان' },
  'Security & Filtering': { fr: 'Sécurité et filtrage', ar: 'الأمان والتصفية' },
  'Bot Mitigation': { fr: 'Atténuation des bots', ar: 'منع الروبوتات' },
  'Challenge suspicious traffic.': { fr: 'Défier le trafic suspect.', ar: 'فحص حركة المرور المشبوهة.' },
  'Secure connections.': { fr: 'Connexions sécurisées.', ar: 'اتصالات آمنة.' },
  'Cancellations before auto-blacklist': { fr: 'Annulations avant blacklist auto', ar: 'الإلغاءات قبل الإدراج التلقائي' },
  'Enable Auto Blacklist': { fr: 'Activer la liste noire auto', ar: 'تفعيل القائمة السوداء التلقائية' },
  'Validate orders': { fr: 'Valider les commandes', ar: 'التحقق من الطلبات' },
  'Fraud Detection Test': { fr: 'Test de détection de fraude', ar: 'اختبار كشف الاحتيال' },

  // Account / Danger
  'Danger Zone': { fr: 'Zone dangereuse', ar: 'منطقة خطر' },
  'Permanently delete your account. This is irreversible.': { fr: 'Supprimez votre compte définitivement.', ar: 'حذف حسابك نهائياً. لا رجعة فيه.' },
  'Password to confirm': { fr: 'Mot de passe pour confirmer', ar: 'كلمة المرور للتأكيد' },
  'DELETE MY ACCOUNT': { fr: 'SUPPRIMER MON COMPTE', ar: 'حذف حسابي' },
  'Account deleted': { fr: 'Compte supprimé', ar: 'تم حذف الحساب' },
  'Confirm Delete': { fr: 'Confirmer la suppression', ar: 'تأكيد الحذف' },
  'Change your account password': { fr: 'Modifier le mot de passe de votre compte', ar: 'تغيير كلمة مرور حسابك' },
  'Current Password': { fr: 'Mot de passe actuel', ar: 'كلمة المرور الحالية' },
  'New Password': { fr: 'Nouveau mot de passe', ar: 'كلمة المرور الجديدة' },
  'Update Password': { fr: 'Mettre à jour le mot de passe', ar: 'تحديث كلمة المرور' },
  'Password updated!': { fr: 'Mot de passe mis à jour !', ar: 'تم تحديث كلمة المرور!' },
  'Passwords do not match': { fr: 'Les mots de passe ne correspondent pas', ar: 'كلمات المرور غير متطابقة' },
  'Save Profile': { fr: 'Enregistrer le profil', ar: 'حفظ الملف الشخصي' },
  'Profile updated!': { fr: 'Profil mis à jour !', ar: 'تم تحديث الملف الشخصي!' },
  'Username': { fr: 'Nom d\'utilisateur', ar: 'اسم المستخدم' },
  'Username updated!': { fr: 'Nom d\'utilisateur mis à jour !', ar: 'تم تحديث اسم المستخدم!' },
  'Email updated!': { fr: 'E-mail mis à jour !', ar: 'تم تحديث البريد!' },
  'New email': { fr: 'Nouvel e-mail', ar: 'بريد جديد' },
  'Sign in with Google': { fr: 'Se connecter avec Google', ar: 'تسجيل الدخول بجوجل' },
  'Disconnect Google': { fr: 'Déconnecter Google', ar: 'فصل جوجل' },
  'Google account connected': { fr: 'Compte Google connecté', ar: 'تم ربط حساب جوجل' },
  'Google connected!': { fr: 'Google connecté !', ar: 'تم الاتصال بجوجل!' },
  'Google auth failed': { fr: 'Échec de la connexion Google', ar: 'فشل المصادقة عبر جوجل' },
  'Google Client ID not set. Ask platform admin.': { fr: 'ID client Google non défini. Demandez à l\'admin.', ar: 'لم يتم تعيين معرف عميل جوجل.' },
  'Session expired. Sign in again.': { fr: 'Session expirée. Reconnectez-vous.', ar: 'انتهت الجلسة. سجل الدخول مجدداً.' },

  // Templates / messaging
  'Templates': { fr: 'Modèles', ar: 'القوالب' },
  'Save Templates': { fr: 'Enregistrer les modèles', ar: 'حفظ القوالب' },
  'Templates saved!': { fr: 'Modèles enregistrés !', ar: 'تم حفظ القوالب!' },
  'Welcome Message': { fr: 'Message de bienvenue', ar: 'رسالة الترحيب' },
  'Greeting': { fr: 'Salutation', ar: 'تحية' },
  'Cart Recovery Messages': { fr: 'Messages de récupération de panier', ar: 'رسائل استرداد السلة' },
  'Store Messages': { fr: 'Messages du magasin', ar: 'رسائل المتجر' },
  'Customize the messages sent to customers. Use': { fr: 'Personnalisez les messages envoyés aux clients. Utilisez', ar: 'خصص الرسائل المرسلة للعملاء. استخدم' },
  'Reminder Delay': { fr: 'Délai du rappel', ar: 'تأخير التذكير' },
  'Hours': { fr: 'Heures', ar: 'ساعات' },
  'Minutes': { fr: 'Minutes', ar: 'دقائق' },
  'Channel': { fr: 'Canal', ar: 'القناة' },
  'Subject': { fr: 'Sujet', ar: 'الموضوع' },
  'Message': { fr: 'Message', ar: 'الرسالة' },
  'Type a message...': { fr: 'Tapez un message...', ar: 'اكتب رسالة...' },
  'Message Log': { fr: 'Journal des messages', ar: 'سجل الرسائل' },
  'No messages sent yet': { fr: 'Aucun message envoyé', ar: 'لم تُرسل رسائل بعد' },
  'Sent to': { fr: 'Envoyé à', ar: 'مرسل إلى' },
  'Email sent!': { fr: 'E-mail envoyé !', ar: 'تم إرسال البريد!' },
  'Message sent!': { fr: 'Message envoyé !', ar: 'تم إرسال الرسالة!' },

  // Misc / hero
  'Offer Title': { fr: 'Titre de l\'offre', ar: 'عنوان العرض' },
  'Offer & Sale Branding': { fr: 'Image de marque offre et solde', ar: 'هوية العروض والتخفيضات' },
  'Enable Offer Banner': { fr: 'Activer la bannière d\'offre', ar: 'تفعيل لافتة العرض' },
  'Show promotional banner with countdown': { fr: 'Afficher une bannière promo avec compte à rebours', ar: 'إظهار لافتة ترويجية مع عد تنازلي' },
  'Discount Text': { fr: 'Texte de remise', ar: 'نص الخصم' },
  'Button Text': { fr: 'Texte du bouton', ar: 'نص الزر' },
  'Timer Label': { fr: 'Libellé du minuteur', ar: 'تسمية المؤقت' },
  'Limited Offer': { fr: 'Offre limitée', ar: 'عرض محدود' },
  'Order Now': { fr: 'Commander', ar: 'اطلب الآن' },
  'Homepage Title': { fr: 'Titre de la page d\'accueil', ar: 'عنوان الصفحة الرئيسية' },
  'Meta Description': { fr: 'Description Meta', ar: 'وصف ميتا' },
  'Store Phone': { fr: 'Téléphone du magasin', ar: 'هاتف المتجر' },
  'Support Phone': { fr: 'Téléphone de support', ar: 'هاتف الدعم' },
  'Business Number': { fr: 'Numéro professionnel', ar: 'رقم العمل' },
  'Facebook Page URL': { fr: 'URL de la page Facebook', ar: 'رابط صفحة فيسبوك' },
  'Instagram Profile URL': { fr: 'URL du profil Instagram', ar: 'رابط حساب إنستغرام' },
  'TikTok Profile URL': { fr: 'URL du profil TikTok', ar: 'رابط حساب تيك توك' },
  'YouTube Channel URL': { fr: 'URL de la chaîne YouTube', ar: 'رابط قناة يوتيوب' },
  'Social Media': { fr: 'Réseaux sociaux', ar: 'وسائل التواصل' },

  // Status badges
  'POPULAR': { fr: 'POPULAIRE', ar: 'الأكثر طلباً' },
  'FEATURED': { fr: 'EN VEDETTE', ar: 'مميز' },
  'SOON': { fr: 'BIENTÔT', ar: 'قريباً' },
  'READY': { fr: 'PRÊT', ar: 'جاهز' },
  'SENT': { fr: 'ENVOYÉ', ar: 'مرسل' },
  'FAILED': { fr: 'ÉCHEC', ar: 'فشل' },
  'INACTIVE': { fr: 'INACTIF', ar: 'غير نشط' },
  'POST': { fr: 'POST', ar: 'POST' },
  'PRIMARY': { fr: 'PRINCIPAL', ar: 'أساسي' },
  'REQUIRED': { fr: 'REQUIS', ar: 'مطلوب' },
  'RISK': { fr: 'RISQUE', ar: 'مخاطرة' },
  'SYSTEM': { fr: 'SYSTÈME', ar: 'النظام' },
  'TOTAL': { fr: 'TOTAL', ar: 'الإجمالي' },
  'EMAIL': { fr: 'E-MAIL', ar: 'البريد' },
  'WHATSAPP': { fr: 'WHATSAPP', ar: 'واتساب' },
  'LIVE TRACKING': { fr: 'SUIVI EN DIRECT', ar: 'تتبع مباشر' },
  'MAIN': { fr: 'PRINCIPAL', ar: 'الرئيسي' },
  'MANUAL': { fr: 'MANUEL', ar: 'يدوي' },
  'COMMUNITY STEP': { fr: 'ÉTAPE COMMUNAUTAIRE', ar: 'خطوة المجتمع' },

  // ═══════════════════════════════════════════════════
  // FULL SCAN — Every remaining hardcoded string found
  // across the entire codebase (toast messages, inline
  // JSX, modal text, error/success messages, labels,
  // badges, headings, placeholders, etc.)
  // ═══════════════════════════════════════════════════

  // ── Toast / feedback messages ──
  'Added to favorites': { fr: 'Ajouté aux favoris', ar: 'تمت الإضافة للمفضلة' },
  'Removed from favorites': { fr: 'Retiré des favoris', ar: 'تمت الإزالة من المفضلة' },
  'Added to cart': { fr: 'Ajouté au panier', ar: 'تمت الإضافة للسلة' },
  'Please choose:': { fr: 'Veuillez choisir :', ar: 'يرجى اختيار:' },
  'Pick a quantity': { fr: 'Choisissez une quantité', ar: 'اختر الكمية' },
  'Please pick a quantity': { fr: 'Veuillez choisir une quantité', ar: 'يرجى اختيار الكمية' },
  'Welcome, Super Admin!': { fr: 'Bienvenue, Super Admin !', ar: 'مرحباً، المسؤول الأعلى!' },
  'Welcome, Admin!': { fr: 'Bienvenue, Admin !', ar: 'مرحباً، المسؤول!' },
  'Welcome back!': { fr: 'Bon retour !', ar: 'مرحباً بعودتك!' },
  'Account created!': { fr: 'Compte créé !', ar: 'تم إنشاء الحساب!' },
  'Account created! Welcome aboard!': { fr: 'Compte créé ! Bienvenue !', ar: 'تم إنشاء الحساب! أهلاً بك!' },
  'Verification code sent to your WhatsApp': { fr: 'Code de vérification envoyé par WhatsApp', ar: 'تم إرسال رمز التحقق عبر واتساب' },
  'Enter the 6-digit code': { fr: 'Entrez le code à 6 chiffres', ar: 'أدخل الرمز المكون من 6 أرقام' },
  'Code resent': { fr: 'Code renvoyé', ar: 'تم إعادة إرسال الرمز' },
  'Receipt uploaded!': { fr: 'Reçu téléversé !', ar: 'تم رفع الإيصال!' },
  'Receipt submitted! Will be verified within 24 hours.': { fr: 'Reçu soumis ! Vérification sous 24 heures.', ar: 'تم إرسال الإيصال! سيتم التحقق خلال 24 ساعة.' },
  'Invalid coupon': { fr: 'Coupon invalide', ar: 'قسيمة غير صالحة' },
  'Upload failed': { fr: 'Échec du téléversement', ar: 'فشل التحميل' },
  'Please upload your receipt': { fr: 'Veuillez téléverser votre reçu', ar: 'يرجى رفع الإيصال' },
  'Payment gateway unavailable': { fr: 'Passerelle de paiement indisponible', ar: 'بوابة الدفع غير متاحة' },
  'AI message generated!': { fr: 'Message IA généré !', ar: 'تم إنشاء رسالة الذكاء الاصطناعي!' },
  'AI generation failed': { fr: 'Échec de la génération IA', ar: 'فشل توليد الذكاء الاصطناعي' },
  'Review submitted! It will appear after approval.': { fr: 'Avis soumis ! Il apparaîtra après approbation.', ar: 'تم إرسال التقييم! سيظهر بعد الموافقة.' },
  'Category added': { fr: 'Catégorie ajoutée', ar: 'تمت إضافة الفئة' },
  'Deleted selected products': { fr: 'Produits sélectionnés supprimés', ar: 'تم حذف المنتجات المحددة' },
  'Copy failed': { fr: 'Échec de la copie', ar: 'فشل النسخ' },
  'Saved': { fr: 'Enregistré', ar: 'تم الحفظ' },
  'Saved!': { fr: 'Enregistré !', ar: 'تم الحفظ!' },
  'Failed': { fr: 'Échec', ar: 'فشل' },
  'Exported': { fr: 'Exporté', ar: 'تم التصدير' },
  'Allow pop-ups to print orders': { fr: 'Autorisez les pop-ups pour imprimer', ar: 'اسمح بالنوافذ المنبثقة للطباعة' },
  'Order created': { fr: 'Commande créée', ar: 'تم إنشاء الطلب' },
  'Team member updated': { fr: 'Membre mis à jour', ar: 'تم تحديث العضو' },
  'Role name required': { fr: 'Nom du rôle requis', ar: 'اسم الدور مطلوب' },
  'Role saved': { fr: 'Rôle enregistré', ar: 'تم حفظ الدور' },
  'Delete this role?': { fr: 'Supprimer ce rôle ?', ar: 'حذف هذا الدور؟' },
  'Updated': { fr: 'Mis à jour', ar: 'تم التحديث' },
  'Removed': { fr: 'Supprimé', ar: 'تمت الإزالة' },
  'Remove this user?': { fr: 'Supprimer cet utilisateur ?', ar: 'إزالة هذا المستخدم؟' },
  'Bad image': { fr: 'Image incorrecte', ar: 'صورة غير صالحة' },
  'Read failed': { fr: 'Échec de la lecture', ar: 'فشل القراءة' },
  'Name and password required': { fr: 'Nom et mot de passe requis', ar: 'الاسم وكلمة المرور مطلوبان' },
  'Page saved!': { fr: 'Page enregistrée !', ar: 'تم حفظ الصفحة!' },
  'Billing config saved!': { fr: 'Configuration facturation enregistrée !', ar: 'تم حفظ إعدادات الفوترة!' },
  'Profile updated': { fr: 'Profil mis à jour', ar: 'تم تحديث الملف الشخصي' },
  'Password changed': { fr: 'Mot de passe changé', ar: 'تم تغيير كلمة المرور' },
  'Super admin added!': { fr: 'Super admin ajouté !', ar: 'تمت إضافة المسؤول الأعلى!' },
  'Remove this admin? They will lose all super admin access.': { fr: 'Supprimer cet admin ? Il perdra tout accès.', ar: 'إزالة هذا المسؤول؟ سيفقد كل الصلاحيات.' },
  'Webhook URL copied': { fr: 'URL Webhook copiée', ar: 'تم نسخ رابط Webhook' },
  'Name, email and password are required': { fr: 'Nom, e-mail et mot de passe requis', ar: 'الاسم والبريد وكلمة المرور مطلوبة' },
  'Password must be at least 6 characters': { fr: 'Le mot de passe doit faire au moins 6 caractères', ar: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل' },
  'Name, phone, and password required': { fr: 'Nom, téléphone et mot de passe requis', ar: 'الاسم والهاتف وكلمة المرور مطلوبة' },
  'All password fields required': { fr: 'Tous les champs de mot de passe requis', ar: 'جميع حقول كلمة المرور مطلوبة' },
  'Plan created': { fr: 'Plan créé', ar: 'تم إنشاء الخطة' },
  'Plan updated': { fr: 'Plan mis à jour', ar: 'تم تحديث الخطة' },
  'Toggled': { fr: 'Basculé', ar: 'تم التبديل' },
  'Enter days': { fr: 'Entrez les jours', ar: 'أدخل الأيام' },
  'Owner deleted': { fr: 'Propriétaire supprimé', ar: 'تم حذف المالك' },
  'Owner activated!': { fr: 'Propriétaire activé !', ar: 'تم تفعيل المالك!' },
  'Payment approved! Subscription activated.': { fr: 'Paiement approuvé ! Abonnement activé.', ar: 'تمت الموافقة على الدفع! تم تفعيل الاشتراك.' },
  'Starting — scan the QR code with WhatsApp': { fr: 'Démarrage — scannez le QR avec WhatsApp', ar: 'جارٍ البدء — امسح رمز QR بواتساب' },
  'Enter a phone number': { fr: 'Entrez un numéro de téléphone', ar: 'أدخل رقم الهاتف' },
  'Test message sent': { fr: 'Message de test envoyé', ar: 'تم إرسال الرسالة التجريبية' },
  'Send failed': { fr: 'Échec de l\'envoi', ar: 'فشل الإرسال' },
  'English name is required': { fr: 'Le nom en anglais est requis', ar: 'الاسم بالإنجليزية مطلوب' },
  'Role created': { fr: 'Rôle créé', ar: 'تم إنشاء الدور' },
  'Role updated': { fr: 'Rôle mis à jour', ar: 'تم تحديث الدور' },
  'Max 5MB': { fr: 'Max 5 Mo', ar: 'الحد الأقصى 5 ميغابايت' },
  'Suspend? Their stores go offline.': { fr: 'Suspendre ? Leurs boutiques seront hors ligne.', ar: 'تعليق؟ ستصبح متاجرهم غير متصلة.' },
  'Delete this store and ALL its data? This cannot be undone.': { fr: 'Supprimer cette boutique et TOUTES ses données ? Irréversible.', ar: 'حذف هذا المتجر وجميع بياناته؟ لا يمكن التراجع.' },

  // ── Storefront / buyer-facing inline text ──
  'Store not found': { fr: 'Boutique introuvable', ar: 'المتجر غير موجود' },
  'Store Temporarily Unavailable': { fr: 'Boutique temporairement indisponible', ar: 'المتجر غير متاح مؤقتاً' },
  'This store is currently suspended. Please check back later or contact the store owner.': { fr: 'Cette boutique est actuellement suspendue. Revenez plus tard ou contactez le propriétaire.', ar: 'هذا المتجر معلّق حالياً. يرجى المحاولة لاحقاً أو الاتصال بالمالك.' },
  'Go to homepage': { fr: 'Aller à l\'accueil', ar: 'الذهاب للصفحة الرئيسية' },
  'Checkout Preview': { fr: 'Aperçu de la commande', ar: 'معاينة الطلب' },
  'Confirm your order': { fr: 'Confirmez votre commande', ar: 'أكد طلبك' },
  'Continue to Checkout': { fr: 'Continuer vers le paiement', ar: 'متابعة إلى الدفع' },
  'Qty:': { fr: 'Qté :', ar: 'الكمية:' },
  'In Stock': { fr: 'En stock', ar: 'متوفر' },
  'In stock': { fr: 'En stock', ar: 'متوفر' },
  'Out of Stock': { fr: 'Rupture de stock', ar: 'نفد المخزون' },
  'Available for order': { fr: 'Disponible à la commande', ar: 'متاح للطلب' },
  'Available': { fr: 'Disponible', ar: 'متاح' },
  'SALE': { fr: 'SOLDE', ar: 'تخفيض' },
  'ORDER NOW': { fr: 'COMMANDER', ar: 'اطلب الآن' },
  'Selected:': { fr: 'Sélectionné :', ar: 'المحدد:' },
  'Fast Delivery': { fr: 'Livraison rapide', ar: 'توصيل سريع' },
  'Secure': { fr: 'Sécurisé', ar: 'آمن' },
  'Returns': { fr: 'Retours', ar: 'المرتجعات' },
  'Limited Offer': { fr: 'Offre limitée', ar: 'عرض محدود' },
  '40% OFF': { fr: '-40 %', ar: 'خصم 40%' },
  'Ends in:': { fr: 'Finit dans :', ar: 'ينتهي في:' },
  'Operational': { fr: 'Opérationnel', ar: 'يعمل' },
  'SUGGESTED ACTIONS': { fr: 'ACTIONS SUGGÉRÉES', ar: 'إجراءات مقترحة' },
  'Shipping rates': { fr: 'Tarifs de livraison', ar: 'أسعار الشحن' },
  'Best sellers': { fr: 'Meilleures ventes', ar: 'الأكثر مبيعاً' },
  'Contact info': { fr: 'Coordonnées', ar: 'معلومات الاتصال' },
  'Enter command...': { fr: 'Entrez une commande...', ar: 'أدخل أمراً...' },
  'Now with AI-Powered Features': { fr: 'Avec des fonctionnalités IA', ar: 'الآن مع ميزات الذكاء الاصطناعي' },
  'All rights reserved.': { fr: 'Tous droits réservés.', ar: 'جميع الحقوق محفوظة.' },
  'Set a YouTube URL in the page builder': { fr: 'Définissez une URL YouTube dans le constructeur', ar: 'حدد رابط يوتيوب في منشئ الصفحات' },
  'MOST POPULAR': { fr: 'LE PLUS POPULAIRE', ar: 'الأكثر شعبية' },

  // ── Landing page fallback plans (replaced by real API data when available) ──
  '1 Store': { fr: '1 boutique', ar: 'متجر واحد' },
  '50 Products': { fr: '50 produits', ar: '50 منتج' },
  'Basic Analytics': { fr: 'Analyses basiques', ar: 'تحليلات أساسية' },
  'COD Payment': { fr: 'Paiement à la livraison', ar: 'الدفع عند الاستلام' },
  '3 Stores': { fr: '3 boutiques', ar: '3 متاجر' },
  'Unlimited Products': { fr: 'Produits illimités', ar: 'منتجات غير محدودة' },
  'AI Chatbot': { fr: 'Chatbot IA', ar: 'روبوت الدردشة' },
  'All Payments': { fr: 'Tous les paiements', ar: 'جميع طرق الدفع' },
  'Custom Domain': { fr: 'Domaine personnalisé', ar: 'نطاق مخصص' },

  // ── Buyer pages ──
  'No favorites yet': { fr: 'Aucun favori', ar: 'لا توجد مفضلات بعد' },
  'Browse products and tap the heart icon to save items you love.': { fr: 'Parcourez les produits et appuyez sur le cœur pour sauvegarder.', ar: 'تصفح المنتجات واضغط على القلب لحفظ ما يعجبك.' },
  'Browse Store': { fr: 'Parcourir la boutique', ar: 'تصفح المتجر' },
  'My Favorites': { fr: 'Mes favoris', ar: 'المفضلة' },
  'items saved': { fr: 'articles sauvegardés', ar: 'عناصر محفوظة' },
  'Clear All': { fr: 'Tout effacer', ar: 'مسح الكل' },
  'Move to Cart': { fr: 'Ajouter au panier', ar: 'نقل إلى السلة' },
  'Remove': { fr: 'Supprimer', ar: 'إزالة' },
  'Sign In': { fr: 'Se connecter', ar: 'تسجيل الدخول' },
  'Sign Up': { fr: 'S\'inscrire', ar: 'إنشاء حساب' },
  'Don\'t have an account?': { fr: 'Pas de compte ?', ar: 'ليس لديك حساب؟' },
  'Already have an account?': { fr: 'Déjà un compte ?', ar: 'لديك حساب بالفعل؟' },
  'Your name': { fr: 'Votre nom', ar: 'اسمك' },
  'Your phone number': { fr: 'Votre numéro de téléphone', ar: 'رقم هاتفك' },
  'Your password': { fr: 'Votre mot de passe', ar: 'كلمة مرورك' },
  'Confirm Password': { fr: 'Confirmer le mot de passe', ar: 'تأكيد كلمة المرور' },
  'or continue with': { fr: 'ou continuer avec', ar: 'أو المتابعة مع' },
  'Track your order': { fr: 'Suivez votre commande', ar: 'تتبع طلبك' },
  'Enter your details to see live status': { fr: 'Entrez vos détails pour voir le statut', ar: 'أدخل بياناتك لمعرفة الحالة' },
  'By phone number': { fr: 'Par numéro de téléphone', ar: 'بواسطة رقم الهاتف' },
  'By order ID': { fr: 'Par numéro de commande', ar: 'بواسطة رقم الطلب' },
  'Find my order': { fr: 'Trouver ma commande', ar: 'البحث عن طلبي' },
  'No orders found': { fr: 'Aucune commande trouvée', ar: 'لم يتم العثور على طلبات' },
  'Order found': { fr: 'Commande trouvée', ar: 'تم العثور على الطلب' },
  'orders found': { fr: 'commandes trouvées', ar: 'طلبات' },

  // ── Product detail page ──
  'Write a review': { fr: 'Écrire un avis', ar: 'كتابة تقييم' },
  'Submit Review': { fr: 'Soumettre l\'avis', ar: 'إرسال التقييم' },
  'Reviews': { fr: 'Avis', ar: 'التقييمات' },
  'No reviews yet': { fr: 'Aucun avis', ar: 'لا توجد تقييمات بعد' },
  'Be the first to review this product': { fr: 'Soyez le premier à évaluer ce produit', ar: 'كن أول من يقيّم هذا المنتج' },
  'Related Products': { fr: 'Produits similaires', ar: 'منتجات مشابهة' },
  'Your Review': { fr: 'Votre avis', ar: 'تقييمك' },
  'Share your experience...': { fr: 'Partagez votre expérience...', ar: 'شارك تجربتك...' },
  'Submitting...': { fr: 'Envoi...', ar: 'جار الإرسال...' },
  'Product not found': { fr: 'Produit introuvable', ar: 'المنتج غير موجود' },
  'Back to store': { fr: 'Retour à la boutique', ar: 'العودة إلى المتجر' },
  'Tap to rate': { fr: 'Appuyez pour noter', ar: 'اضغط للتقييم' },
  'rating': { fr: 'note', ar: 'تقييم' },
  'ratings': { fr: 'notes', ar: 'تقييمات' },

  // ── Customer profile ──
  'Personal Information': { fr: 'Informations personnelles', ar: 'المعلومات الشخصية' },
  'Order History': { fr: 'Historique des commandes', ar: 'سجل الطلبات' },
  'No orders yet': { fr: 'Aucune commande', ar: 'لا توجد طلبات بعد' },
  'View Order': { fr: 'Voir la commande', ar: 'عرض الطلب' },
  'Reorder': { fr: 'Commander à nouveau', ar: 'إعادة الطلب' },
  'Profile saved!': { fr: 'Profil enregistré !', ar: 'تم حفظ الملف الشخصي!' },
  'Save Changes': { fr: 'Enregistrer les modifications', ar: 'حفظ التغييرات' },

  // ── Store admin ──
  'Activate Owner': { fr: 'Activer le propriétaire', ar: 'تفعيل المالك' },
  'Delete this product?': { fr: 'Supprimer ce produit ?', ar: 'حذف هذا المنتج؟' },
  'Copied': { fr: 'Copié', ar: 'تم النسخ' },
  'No shipped orders found': { fr: 'Aucune commande expédiée', ar: 'لا توجد طلبات مشحونة' },
  'Orders appear here once marked as shipped': { fr: 'Les commandes apparaissent ici une fois expédiées', ar: 'تظهر الطلبات هنا بعد شحنها' },
  'Search orders or tracking...': { fr: 'Rechercher commandes ou suivi...', ar: 'ابحث في الطلبات أو رقم التتبع...' },
  'Assign one from the Orders page': { fr: 'Assignez-en un depuis la page Commandes', ar: 'عيّنه من صفحة الطلبات' },

  // ── Settings / config labels ──
  'Scrollbar Studio': { fr: 'Studio de défilement', ar: 'استوديو شريط التمرير' },
  'Section Animations': { fr: 'Animations de section', ar: 'حركات الأقسام' },
  'Sticky Add to Cart': { fr: 'Bouton Ajouter fixe', ar: 'زر إضافة ثابت' },
  'Low Stock Warning': { fr: 'Alerte stock faible', ar: 'تنبيه مخزون منخفض' },
  'Quick View': { fr: 'Aperçu rapide', ar: 'عرض سريع' },
  'Infinite Scroll': { fr: 'Défilement infini', ar: 'تمرير لا نهائي' },
  'Back to Top': { fr: 'Retour en haut', ar: 'العودة للأعلى' },
  'Image Zoom': { fr: 'Zoom image', ar: 'تكبير الصورة' },
  'Social Share': { fr: 'Partage social', ar: 'مشاركة اجتماعية' },
  'Store Announcement': { fr: 'Annonce du magasin', ar: 'إعلان المتجر' },
  'Announcement Banner': { fr: 'Bannière d\'annonce', ar: 'لافتة الإعلان' },
  'Storefront Presets': { fr: 'Préréglages de la vitrine', ar: 'إعدادات واجهة المتجر' },
  'Apply Template': { fr: 'Appliquer le modèle', ar: 'تطبيق القالب' },

  // ── Platform admin ──
  'CONTROL PANEL': { fr: 'PANNEAU DE CONTRÔLE', ar: 'لوحة التحكم' },
  'SUPER ADMIN': { fr: 'SUPER ADMIN', ar: 'مسؤول كبير' },
  'Total Stores': { fr: 'Total des boutiques', ar: 'إجمالي المتاجر' },
  'Total Owners': { fr: 'Total des propriétaires', ar: 'إجمالي المالكين' },
  'Active Stores': { fr: 'Boutiques actives', ar: 'المتاجر النشطة' },
  'Suspended Stores': { fr: 'Boutiques suspendues', ar: 'المتاجر المعلّقة' },
  'Recent Stores': { fr: 'Boutiques récentes', ar: 'المتاجر الأخيرة' },
  'System Status': { fr: 'État du système', ar: 'حالة النظام' },
  'this week': { fr: 'cette semaine', ar: 'هذا الأسبوع' },
  'today': { fr: 'aujourd\'hui', ar: 'اليوم' },
  'Across all stores': { fr: 'Dans toutes les boutiques', ar: 'عبر جميع المتاجر' },
  'Registered buyers': { fr: 'Acheteurs inscrits', ar: 'المشترون المسجلون' },
  'Subscriptions': { fr: 'Abonnements', ar: 'الاشتراكات' },
  'Billing Config': { fr: 'Configuration facturation', ar: 'إعدادات الفوترة' },
  'Approve': { fr: 'Approuver', ar: 'قبول' },
  'Reject': { fr: 'Rejeter', ar: 'رفض' },
  'Grant Free Days': { fr: 'Accorder des jours gratuits', ar: 'منح أيام مجانية' },
  'Extend': { fr: 'Prolonger', ar: 'تمديد' },
  'Pending Payments': { fr: 'Paiements en attente', ar: 'المدفوعات المعلقة' },
  'Rejection Notes': { fr: 'Notes de rejet', ar: 'ملاحظات الرفض' },
  'Enter rejection reason...': { fr: 'Entrez la raison du rejet...', ar: 'أدخل سبب الرفض...' },
  'Confirm Reject': { fr: 'Confirmer le rejet', ar: 'تأكيد الرفض' },

  // ── Checkout page ──
  'Select wilaya...': { fr: 'Sélectionnez la wilaya...', ar: 'اختر الولاية...' },
  'Select city...': { fr: 'Sélectionnez la ville...', ar: 'اختر المدينة...' },
  'Select wilaya first': { fr: 'Sélectionnez d\'abord la wilaya', ar: 'اختر الولاية أولاً' },
  'Delivery Type': { fr: 'Type de livraison', ar: 'نوع التوصيل' },
  'Delivery Company': { fr: 'Société de livraison', ar: 'شركة التوصيل' },
  'Preferred Delivery Company': { fr: 'Société de livraison préférée', ar: 'شركة التوصيل المفضلة' },
  'Desk / Relay Point': { fr: 'Bureau / Point relais', ar: 'مكتب / نقطة استلام' },
  'Home Delivery': { fr: 'Livraison à domicile', ar: 'توصيل إلى المنزل' },
  'Order Updates': { fr: 'Mises à jour de la commande', ar: 'تحديثات الطلب' },
  'How would you like to receive order updates?': { fr: 'Comment souhaitez-vous recevoir les mises à jour ?', ar: 'كيف تريد استلام تحديثات الطلب؟' },
  'Save my information for next time': { fr: 'Enregistrer mes informations', ar: 'حفظ معلوماتي للمرة القادمة' },
  'Apply': { fr: 'Appliquer', ar: 'تطبيق' },
  'Coupon Code': { fr: 'Code promo', ar: 'رمز القسيمة' },
  'Enter coupon code': { fr: 'Entrez le code promo', ar: 'أدخل رمز القسيمة' },
  'TOTAL TO PAY': { fr: 'TOTAL À PAYER', ar: 'المبلغ الإجمالي' },
  'Discount': { fr: 'Remise', ar: 'الخصم' },

  // ── Cart Recovery ──
  'Recovery Rate': { fr: 'Taux de récupération', ar: 'معدل الاسترداد' },
  'Abandoned': { fr: 'Abandonnés', ar: 'متروكة' },
  'Recovery Messages': { fr: 'Messages de récupération', ar: 'رسائل الاسترداد' },
  'Generate AI Message': { fr: 'Générer un message IA', ar: 'إنشاء رسالة بالذكاء الاصطناعي' },
  'Send via WhatsApp': { fr: 'Envoyer par WhatsApp', ar: 'إرسال عبر واتساب' },
  'Send via Email': { fr: 'Envoyer par e-mail', ar: 'إرسال عبر البريد' },

  // ── Smart Reviews ──
  'Approved': { fr: 'Approuvé', ar: 'معتمد' },
  'Flagged': { fr: 'Signalé', ar: 'مُعلَّم' },
  'Spam': { fr: 'Spam', ar: 'بريد مزعج' },
  'AI Score': { fr: 'Score IA', ar: 'تقييم الذكاء الاصطناعي' },
  'Sentiment': { fr: 'Sentiment', ar: 'المشاعر' },
  'Positive': { fr: 'Positif', ar: 'إيجابي' },
  'Negative': { fr: 'Négatif', ar: 'سلبي' },
  'Neutral': { fr: 'Neutre', ar: 'محايد' },

  // ── Stock Manager ──
  'Low Stock': { fr: 'Stock faible', ar: 'مخزون منخفض' },
  'In Stock': { fr: 'En stock', ar: 'متوفر' },
  'Stock Level': { fr: 'Niveau de stock', ar: 'مستوى المخزون' },
  'Restock': { fr: 'Réapprovisionner', ar: 'إعادة التخزين' },
  'Stock History': { fr: 'Historique du stock', ar: 'سجل المخزون' },

  // ── Tracking pixels ──
  'Pixel ID': { fr: 'ID du pixel', ar: 'معرف البكسل' },
  'Conversion Events': { fr: 'Événements de conversion', ar: 'أحداث التحويل' },
  'Page View': { fr: 'Vue de page', ar: 'مشاهدة الصفحة' },
  'Add to Cart': { fr: 'Ajout au panier', ar: 'إضافة للسلة' },
  'Purchase': { fr: 'Achat', ar: 'شراء' },
  'View Content': { fr: 'Voir le contenu', ar: 'مشاهدة المحتوى' },
  'Initiate Checkout': { fr: 'Démarrer le paiement', ar: 'بدء الدفع' },

  // ── Advanced Builder ──
  'Preview': { fr: 'Aperçu', ar: 'معاينة' },
  'Sections': { fr: 'Sections', ar: 'الأقسام' },
  'Add Section': { fr: 'Ajouter une section', ar: 'إضافة قسم' },
  'Move Up': { fr: 'Monter', ar: 'تحريك لأعلى' },
  'Move Down': { fr: 'Descendre', ar: 'تحريك لأسفل' },
  'Duplicate': { fr: 'Dupliquer', ar: 'نسخ' },
  'Background': { fr: 'Arrière-plan', ar: 'الخلفية' },
  'Text Color': { fr: 'Couleur du texte', ar: 'لون النص' },
  'Font Size': { fr: 'Taille de la police', ar: 'حجم الخط' },
  'Padding': { fr: 'Marge interne', ar: 'الحشو' },
  'Alignment': { fr: 'Alignement', ar: 'المحاذاة' },
  'Left': { fr: 'Gauche', ar: 'يسار' },
  'Center': { fr: 'Centre', ar: 'وسط' },
  'Right': { fr: 'Droite', ar: 'يمين' },

  // ── Misc / shared ──
  'Newest First': { fr: 'Plus récent d\'abord', ar: 'الأحدث أولاً' },
  'Oldest First': { fr: 'Plus ancien d\'abord', ar: 'الأقدم أولاً' },
  'Price: Low to High': { fr: 'Prix : croissant', ar: 'السعر: من الأقل للأعلى' },
  'Price: High to Low': { fr: 'Prix : décroissant', ar: 'السعر: من الأعلى للأقل' },
  'Name: A-Z': { fr: 'Nom : A-Z', ar: 'الاسم: أ-ي' },
  'Name: Z-A': { fr: 'Nom : Z-A', ar: 'الاسم: ي-أ' },
  'On Sale': { fr: 'En solde', ar: 'عروض' },
  'Sort by': { fr: 'Trier par', ar: 'ترتيب حسب' },
  'Price Range': { fr: 'Fourchette de prix', ar: 'نطاق السعر' },
  'Min': { fr: 'Min', ar: 'الأدنى' },
  'Max': { fr: 'Max', ar: 'الأقصى' },
  'Reset Filters': { fr: 'Réinitialiser les filtres', ar: 'إعادة تعيين الفلاتر' },
  'No products found': { fr: 'Aucun produit trouvé', ar: 'لم يتم العثور على منتجات' },
  'Try adjusting your filters': { fr: 'Essayez d\'ajuster vos filtres', ar: 'حاول تعديل الفلاتر' },
  'Showing': { fr: 'Affichage', ar: 'عرض' },
  'of': { fr: 'sur', ar: 'من' },
  'products': { fr: 'produits', ar: 'منتجات' },
  'Empty cart': { fr: 'Panier vide', ar: 'السلة فارغة' },
  'Your cart is empty': { fr: 'Votre panier est vide', ar: 'سلتك فارغة' },
  'item': { fr: 'article', ar: 'منتج' },
  'items': { fr: 'articles', ar: 'منتجات' },
  'Proceed to Checkout': { fr: 'Passer au paiement', ar: 'المتابعة إلى الدفع' },
  'Share': { fr: 'Partager', ar: 'مشاركة' },
  'Copy Link': { fr: 'Copier le lien', ar: 'نسخ الرابط' },
  'Link copied!': { fr: 'Lien copié !', ar: 'تم نسخ الرابط!' },
  'Powered by': { fr: 'Propulsé par', ar: 'مدعوم من' },
  'Dark': { fr: 'Sombre', ar: 'داكن' },
  'Light': { fr: 'Clair', ar: 'فاتح' },
  'Theme': { fr: 'Thème', ar: 'المظهر' },
  'Appearance': { fr: 'Apparence', ar: 'المظهر' },

  // ── Email / WhatsApp config modals ──
  'Email Configuration': { fr: 'Configuration e-mail', ar: 'إعدادات البريد الإلكتروني' },
  'SMTP Host': { fr: 'Hôte SMTP', ar: 'مضيف SMTP' },
  'SMTP Port': { fr: 'Port SMTP', ar: 'منفذ SMTP' },
  'SMTP User': { fr: 'Utilisateur SMTP', ar: 'مستخدم SMTP' },
  'SMTP Password': { fr: 'Mot de passe SMTP', ar: 'كلمة مرور SMTP' },
  'From Email': { fr: 'E-mail expéditeur', ar: 'بريد المرسل' },
  'From Name': { fr: 'Nom expéditeur', ar: 'اسم المرسل' },
  'Save Email Config': { fr: 'Enregistrer la config e-mail', ar: 'حفظ إعدادات البريد' },
  'WhatsApp Configuration': { fr: 'Configuration WhatsApp', ar: 'إعدادات واتساب' },
  'Scan QR Code': { fr: 'Scanner le code QR', ar: 'امسح رمز QR' },
  'WhatsApp Status': { fr: 'Statut WhatsApp', ar: 'حالة واتساب' },

  // ── Plans editor ──
  'Add Plan': { fr: 'Ajouter un plan', ar: 'إضافة خطة' },
  'Edit Plan': { fr: 'Modifier le plan', ar: 'تعديل الخطة' },
  'Plan Name': { fr: 'Nom du plan', ar: 'اسم الخطة' },
  'Monthly Price': { fr: 'Prix mensuel', ar: 'السعر الشهري' },
  'Yearly Price': { fr: 'Prix annuel', ar: 'السعر السنوي' },
  'Max Products': { fr: 'Max produits', ar: 'الحد الأقصى للمنتجات' },
  'Max Orders': { fr: 'Max commandes', ar: 'الحد الأقصى للطلبات' },
  'Max Staff': { fr: 'Max personnel', ar: 'الحد الأقصى للموظفين' },
  'Is Popular': { fr: 'Populaire', ar: 'شائع' },
  'Save Plan': { fr: 'Enregistrer le plan', ar: 'حفظ الخطة' },

  // ── Role templates editor ──
  'Add Role Template': { fr: 'Ajouter un modèle de rôle', ar: 'إضافة قالب دور' },
  'Edit Role Template': { fr: 'Modifier le modèle de rôle', ar: 'تعديل قالب الدور' },
  'Template Name': { fr: 'Nom du modèle', ar: 'اسم القالب' },
  'Platform Role Templates': { fr: 'Modèles de rôles plateforme', ar: 'قوالب أدوار المنصة' },

  // ── About / FAQ / Contact pages ──
  'Add Question': { fr: 'Ajouter une question', ar: 'إضافة سؤال' },
  'Question': { fr: 'Question', ar: 'السؤال' },
  'Answer': { fr: 'Réponse', ar: 'الإجابة' },
  'Add FAQ': { fr: 'Ajouter FAQ', ar: 'إضافة سؤال شائع' },
  'No FAQs yet': { fr: 'Aucune FAQ', ar: 'لا توجد أسئلة شائعة بعد' },
  'About Us Page': { fr: 'Page À propos', ar: 'صفحة من نحن' },
  'Store Story': { fr: 'Histoire du magasin', ar: 'قصة المتجر' },
  'Tell your customers about your store...': { fr: 'Parlez de votre boutique à vos clients...', ar: 'أخبر عملاءك عن متجرك...' },
  'Mission': { fr: 'Mission', ar: 'المهمة' },
  'Vision': { fr: 'Vision', ar: 'الرؤية' },
  'Contact Page': { fr: 'Page de contact', ar: 'صفحة الاتصال' },
  'Business Hours': { fr: 'Heures d\'ouverture', ar: 'ساعات العمل' },
  'Monday - Friday': { fr: 'Lundi - Vendredi', ar: 'الاثنين - الجمعة' },
  'Saturday': { fr: 'Samedi', ar: 'السبت' },
  'Sunday': { fr: 'Dimanche', ar: 'الأحد' },
  'Closed': { fr: 'Fermé', ar: 'مغلق' },

  // ── Blacklist ──
  'Blacklisted Customers': { fr: 'Clients sur liste noire', ar: 'العملاء في القائمة السوداء' },
  'Add to Blacklist': { fr: 'Ajouter à la liste noire', ar: 'إضافة إلى القائمة السوداء' },
  'Remove from Blacklist': { fr: 'Retirer de la liste noire', ar: 'إزالة من القائمة السوداء' },
  'Reason': { fr: 'Raison', ar: 'السبب' },
  'Blocked since': { fr: 'Bloqué depuis', ar: 'محظور منذ' },
  'No blacklisted customers': { fr: 'Aucun client sur liste noire', ar: 'لا يوجد عملاء في القائمة السوداء' },

  // ── How to Connect ──
  'Integration Guide': { fr: 'Guide d\'intégration', ar: 'دليل التكامل' },
  'Step': { fr: 'Étape', ar: 'الخطوة' },
  'Documentation': { fr: 'Documentation', ar: 'التوثيق' },

  // ── Order tracking settings ──
  'Enable Order Tracking': { fr: 'Activer le suivi des commandes', ar: 'تفعيل تتبع الطلبات' },
  'Search Logic': { fr: 'Logique de recherche', ar: 'منطق البحث' },
  'Display Options': { fr: 'Options d\'affichage', ar: 'خيارات العرض' },
  'Show Price': { fr: 'Afficher le prix', ar: 'إظهار السعر' },
  'Show Items': { fr: 'Afficher les articles', ar: 'إظهار المنتجات' },
  'Show Timeline': { fr: 'Afficher la chronologie', ar: 'إظهار الجدول الزمني' },
  'Show Address': { fr: 'Afficher l\'adresse', ar: 'إظهار العنوان' },
  'Show Payment': { fr: 'Afficher le paiement', ar: 'إظهار طريقة الدفع' },

  // ── Status management ──
  'Add Custom Status': { fr: 'Ajouter un statut personnalisé', ar: 'إضافة حالة مخصصة' },
  'Notify Customer': { fr: 'Notifier le client', ar: 'إشعار العميل' },
  'BUILT-IN': { fr: 'INTÉGRÉ', ar: 'مدمج' },
  'Status templates saved': { fr: 'Statuts enregistrés', ar: 'تم حفظ الحالات' },
  'Failed to save': { fr: 'Échec de l\'enregistrement', ar: 'فشل الحفظ' },

  // ── Home page editor ──
  'Hero Section': { fr: 'Section héros', ar: 'القسم الرئيسي' },
  'Banner Image': { fr: 'Image de bannière', ar: 'صورة اللافتة' },
  'Featured Products': { fr: 'Produits en vedette', ar: 'منتجات مميزة' },
  'Collections': { fr: 'Collections', ar: 'المجموعات' },
  'Drag to reorder': { fr: 'Glissez pour réorganiser', ar: 'اسحب لإعادة الترتيب' },
  'Visible': { fr: 'Visible', ar: 'مرئي' },
  'Hidden': { fr: 'Masqué', ar: 'مخفي' },

  // ── Misc missing ──
  'Regenerate': { fr: 'Régénérer', ar: 'إعادة توليد' },
  'Choose a style': { fr: 'Choisir un style', ar: 'اختر أسلوباً' },
  'Generating...': { fr: 'Génération...', ar: 'جار التوليد...' },
  'Apply this design': { fr: 'Appliquer ce design', ar: 'تطبيق هذا التصميم' },
  'Try another': { fr: 'Essayer un autre', ar: 'جرب آخر' },
  'No data': { fr: 'Aucune donnée', ar: 'لا توجد بيانات' },
  'per month': { fr: 'par mois', ar: 'شهرياً' },
  'per year': { fr: 'par an', ar: 'سنوياً' },
  'Stores Created': { fr: 'Boutiques créées', ar: 'المتاجر المنشأة' },
  'Orders Processed': { fr: 'Commandes traitées', ar: 'الطلبات المعالجة' },
  'Revenue Generated': { fr: 'Chiffre d\'affaires', ar: 'الإيرادات المحققة' },
  'Happy Merchants': { fr: 'Marchands satisfaits', ar: 'تجار سعداء' },
  'Ready to Start Selling?': { fr: 'Prêt à commencer à vendre ?', ar: 'مستعد لبدء البيع؟' },
  'Get Started Free': { fr: 'Commencer gratuitement', ar: 'ابدأ مجاناً' },
  'Learn More': { fr: 'En savoir plus', ar: 'اعرف المزيد' },
  'Starter': { fr: 'Débutant', ar: 'مبتدئ' },
  'Pro': { fr: 'Pro', ar: 'احترافي' },
  'Enterprise': { fr: 'Entreprise', ar: 'مؤسسات' },
  '/month': { fr: '/mois', ar: '/شهر' },
  'Archive': { fr: 'Archive', ar: 'الأرشيف' },
  'Print': { fr: 'Imprimer', ar: 'طباعة' },
  'CSV Export': { fr: 'Export CSV', ar: 'تصدير CSV' },
  'Bulk Update': { fr: 'Mise à jour groupée', ar: 'تحديث جماعي' },
  'Select All': { fr: 'Tout sélectionner', ar: 'تحديد الكل' },
  'Deselect All': { fr: 'Tout désélectionner', ar: 'إلغاء تحديد الكل' },
  'selected': { fr: 'sélectionné(s)', ar: 'محدد' },
  'Confirm Delete': { fr: 'Confirmer la suppression', ar: 'تأكيد الحذف' },
  'Are you sure?': { fr: 'Êtes-vous sûr ?', ar: 'هل أنت متأكد؟' },
  'This action cannot be undone.': { fr: 'Cette action est irréversible.', ar: 'لا يمكن التراجع عن هذا الإجراء.' },
  'Retry': { fr: 'Réessayer', ar: 'إعادة المحاولة' },
  'Error': { fr: 'Erreur', ar: 'خطأ' },
  'Success': { fr: 'Succès', ar: 'نجاح' },
  'Warning': { fr: 'Avertissement', ar: 'تحذير' },
  'Info': { fr: 'Info', ar: 'معلومة' },
  'Optional': { fr: 'Optionnel', ar: 'اختياري' },
  'Required': { fr: 'Requis', ar: 'مطلوب' },
  'None': { fr: 'Aucun', ar: 'لا شيء' },
  'Default': { fr: 'Par défaut', ar: 'افتراضي' },
  'Custom': { fr: 'Personnalisé', ar: 'مخصص' },
  'More': { fr: 'Plus', ar: 'المزيد' },
  'Less': { fr: 'Moins', ar: 'أقل' },
  'Show More': { fr: 'Voir plus', ar: 'عرض المزيد' },
  'Show Less': { fr: 'Voir moins', ar: 'عرض أقل' },
  'Copy': { fr: 'Copier', ar: 'نسخ' },
  'Paste': { fr: 'Coller', ar: 'لصق' },
  'Undo': { fr: 'Annuler', ar: 'تراجع' },
  'Redo': { fr: 'Rétablir', ar: 'إعادة' },
  'Done': { fr: 'Terminé', ar: 'تم' },
  'Continue': { fr: 'Continuer', ar: 'متابعة' },
  'Skip': { fr: 'Passer', ar: 'تخطي' },
  'OK': { fr: 'OK', ar: 'حسناً' },
  'N/A': { fr: 'N/D', ar: 'غير متاح' },
  'Unlimited': { fr: 'Illimité', ar: 'غير محدود' },
  'ago': { fr: 'il y a', ar: 'منذ' },
  'just now': { fr: 'à l\'instant', ar: 'الآن' },
  'minutes ago': { fr: 'il y a quelques minutes', ar: 'منذ دقائق' },
  'hours ago': { fr: 'il y a quelques heures', ar: 'منذ ساعات' },
  'days ago': { fr: 'il y a quelques jours', ar: 'منذ أيام' },
  'online': { fr: 'en ligne', ar: 'متصل' },
  'offline': { fr: 'hors ligne', ar: 'غير متصل' },
  'OFFLINE': { fr: 'HORS LIGNE', ar: 'غير متصل' },
  'Verified': { fr: 'Vérifié', ar: 'تم التحقق' },
  'Unverified': { fr: 'Non vérifié', ar: 'غير محقق' },
  'Enabled': { fr: 'Activé', ar: 'مفعل' },
  'Enable': { fr: 'Activer', ar: 'تفعيل' },
  'Disable': { fr: 'Désactiver', ar: 'تعطيل' },
  'On': { fr: 'Activé', ar: 'مفعل' },
  'Off': { fr: 'Désactivé', ar: 'معطل' },
  'SAVE - Save': { fr: 'SOLDE - Économisez', ar: 'تخفيض - وفر' },

  // ── Backend API response messages (displayed in toasts/alerts) ──────
  'Already registered': { fr: 'Déjà inscrit', ar: 'مسجل بالفعل' },
  'Invalid credentials': { fr: 'Identifiants invalides', ar: 'بيانات الدخول غير صحيحة' },
  'All fields required': { fr: 'Tous les champs sont obligatoires', ar: 'جميع الحقول مطلوبة' },
  'Password must be at least 6 characters': { fr: 'Le mot de passe doit contenir au moins 6 caractères', ar: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل' },
  'Store name is required': { fr: 'Le nom de la boutique est obligatoire', ar: 'اسم المتجر مطلوب' },
  'Store URL must be at least 3 characters': { fr: "L'URL de la boutique doit contenir au moins 3 caractères", ar: 'يجب أن يكون رابط المتجر 3 أحرف على الأقل' },
  'This URL is reserved, please choose another': { fr: 'Cette URL est réservée, veuillez en choisir une autre', ar: 'هذا الرابط محجوز، يرجى اختيار آخر' },
  'This store URL is already taken. Try a different one.': { fr: 'Cette URL est déjà prise. Essayez-en une autre.', ar: 'رابط المتجر مأخوذ بالفعل. جرب رابطاً آخر.' },
  'Account not found': { fr: 'Compte introuvable', ar: 'الحساب غير موجود' },
  'Account suspended': { fr: 'Compte suspendu', ar: 'الحساب معلق' },
  'Token required': { fr: 'Jeton requis', ar: 'الرمز مطلوب' },
  'Invalid token': { fr: 'Jeton invalide', ar: 'رمز غير صالح' },
  'Staff cannot create stores': { fr: 'Le personnel ne peut pas créer de boutiques', ar: 'لا يمكن للموظفين إنشاء متاجر' },
  'Staff cannot manage other staff': { fr: 'Le personnel ne peut pas gérer d\'autres employés', ar: 'لا يمكن للموظفين إدارة موظفين آخرين' },
  'Staff not found': { fr: 'Employé introuvable', ar: 'الموظف غير موجود' },
  'Domain required': { fr: 'Domaine requis', ar: 'اسم النطاق مطلوب' },
  'This domain is already connected to a store': { fr: 'Ce domaine est déjà connecté à une boutique', ar: 'هذا النطاق متصل بالفعل بمتجر' },
  'Domain not found': { fr: 'Domaine introuvable', ar: 'النطاق غير موجود' },
  'Username must be at least 3 characters': { fr: "Le nom d'utilisateur doit contenir au moins 3 caractères", ar: 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل' },
  'Username already taken': { fr: "Nom d'utilisateur déjà pris", ar: 'اسم المستخدم مأخوذ بالفعل' },
  'Email and password required': { fr: 'Email et mot de passe requis', ar: 'البريد الإلكتروني وكلمة المرور مطلوبان' },
  'Invalid password': { fr: 'Mot de passe invalide', ar: 'كلمة المرور غير صحيحة' },
  'Email already in use': { fr: 'Email déjà utilisé', ar: 'البريد الإلكتروني مستخدم بالفعل' },
  'Both passwords required': { fr: 'Les deux mots de passe sont requis', ar: 'كلتا كلمتي المرور مطلوبتان' },
  'Current password is incorrect': { fr: 'Le mot de passe actuel est incorrect', ar: 'كلمة المرور الحالية غير صحيحة' },
  'Password updated': { fr: 'Mot de passe mis à jour', ar: 'تم تحديث كلمة المرور' },
  'Password required': { fr: 'Mot de passe requis', ar: 'كلمة المرور مطلوبة' },
  'Receipt image required': { fr: 'Image du reçu requise', ar: 'صورة الإيصال مطلوبة' },
  'Invalid subscription': { fr: 'Abonnement invalide', ar: 'اشتراك غير صالح' },
  'Online payment not configured': { fr: 'Paiement en ligne non configuré', ar: 'الدفع الإلكتروني غير مُعدّ' },
  'Receipt uploaded. Will be verified within 24 hours.': { fr: 'Reçu téléversé. Sera vérifié dans les 24 heures.', ar: 'تم رفع الإيصال. ستتم المراجعة خلال 24 ساعة.' },
  'Invalid signature': { fr: 'Signature invalide', ar: 'توقيع غير صالح' },
  'Detection failed': { fr: 'Échec de la détection', ar: 'فشل الكشف' },
  'Email address required': { fr: 'Adresse email requise', ar: 'عنوان البريد الإلكتروني مطلوب' },
  'Phone number required': { fr: 'Numéro de téléphone requis', ar: 'رقم الهاتف مطلوب' },
  'Chatbot error': { fr: 'Erreur du chatbot', ar: 'خطأ في الروبوت' },
  'Customer name and phone required': { fr: 'Nom et téléphone du client requis', ar: 'اسم ورقم هاتف العميل مطلوبان' },
  'At least one item required': { fr: 'Au moins un article requis', ar: 'مطلوب عنصر واحد على الأقل' },
  'No updatable fields': { fr: 'Aucun champ modifiable', ar: 'لا توجد حقول قابلة للتحديث' },
  'Phone required': { fr: 'Téléphone requis', ar: 'رقم الهاتف مطلوب' },
  'Description and amount required': { fr: 'Description et montant requis', ar: 'الوصف والمبلغ مطلوبان' },
  'Tracking not found': { fr: 'Suivi introuvable', ar: 'التتبع غير موجود' },
  'Order not found': { fr: 'Commande introuvable', ar: 'الطلب غير موجود' },
  'No delivery company specified': { fr: 'Aucune société de livraison spécifiée', ar: 'لم يتم تحديد شركة التوصيل' },
  'Delivery company not found': { fr: 'Société de livraison introuvable', ar: 'شركة التوصيل غير موجودة' },
  'Carrier not found': { fr: 'Transporteur introuvable', ar: 'الناقل غير موجود' },
  'No API configured': { fr: 'Aucune API configurée', ar: 'لا يوجد API مُعدّ' },
  'Missing tracking number': { fr: 'Numéro de suivi manquant', ar: 'رقم التتبع مفقود' },
  'Company not found': { fr: 'Entreprise introuvable', ar: 'الشركة غير موجودة' },
  'API Base URL is required': { fr: "L'URL de base de l'API est requise", ar: 'رابط API الأساسي مطلوب' },
  'Nothing to update': { fr: 'Rien à mettre à jour', ar: 'لا يوجد شيء للتحديث' },
  'Name, phone, password required': { fr: 'Nom, téléphone et mot de passe requis', ar: 'الاسم والهاتف وكلمة المرور مطلوبة' },
  'This phone or email belongs to a store admin. Please use a different one.': { fr: 'Ce téléphone ou email appartient à un admin. Veuillez en utiliser un autre.', ar: 'هذا الهاتف أو البريد يخص مسؤول متجر. استخدم آخر.' },
  'This phone or email belongs to a platform admin. Please use a different one.': { fr: 'Ce téléphone ou email appartient à un admin plateforme. Veuillez en utiliser un autre.', ar: 'هذا الهاتف أو البريد يخص مسؤول المنصة. استخدم آخر.' },
  'Phone registered': { fr: 'Téléphone déjà enregistré', ar: 'الهاتف مسجل بالفعل' },
  'Not a customer account': { fr: "Ce n'est pas un compte client", ar: 'ليس حساب عميل' },
  'This phone number belongs to a store admin. Use a different phone.': { fr: 'Ce numéro appartient à un admin. Utilisez un autre.', ar: 'هذا الرقم يخص مسؤول متجر. استخدم رقماً آخر.' },
  'This phone number belongs to a platform admin. Use a different phone.': { fr: 'Ce numéro appartient à un admin plateforme. Utilisez un autre.', ar: 'هذا الرقم يخص مسؤول المنصة. استخدم رقماً آخر.' },
  'This phone number is already in use by another account.': { fr: 'Ce numéro est déjà utilisé par un autre compte.', ar: 'هذا الرقم مستخدم بالفعل بحساب آخر.' },
  'Cart empty': { fr: 'Panier vide', ar: 'السلة فارغة' },
  'Info required': { fr: 'Informations requises', ar: 'المعلومات مطلوبة' },
  'Tracking disabled': { fr: 'Suivi désactivé', ar: 'التتبع معطل' },
  'Name and rating required': { fr: 'Nom et note requis', ar: 'الاسم والتقييم مطلوبان' },
  'Rating must be 1-5': { fr: 'La note doit être entre 1 et 5', ar: 'التقييم يجب أن يكون بين 1 و5' },
  'You already reviewed this product': { fr: 'Vous avez déjà évalué ce produit', ar: 'لقد قيّمت هذا المنتج بالفعل' },
  'Phone and items required': { fr: 'Téléphone et articles requis', ar: 'الهاتف والعناصر مطلوبة' },
  'Phone or order ID required': { fr: 'Téléphone ou numéro de commande requis', ar: 'رقم الهاتف أو رقم الطلب مطلوب' },
  'Auth required': { fr: 'Authentification requise', ar: 'المصادقة مطلوبة' },
  'Forbidden': { fr: 'Interdit', ar: 'محظور' },
  'Your account is suspended. Please renew your subscription or contact support.': { fr: 'Votre compte est suspendu. Veuillez renouveler votre abonnement ou contacter le support.', ar: 'حسابك معلق. يرجى تجديد اشتراكك أو التواصل مع الدعم.' },
  'This staff account is deactivated. Contact your store admin.': { fr: 'Ce compte employé est désactivé. Contactez votre admin.', ar: 'حساب الموظف هذا معطل. تواصل مع مسؤول المتجر.' },
  'Assigned store no longer exists': { fr: "La boutique assignée n'existe plus", ar: 'المتجر المُسند لم يعد موجوداً' },
  'Owner missing': { fr: 'Propriétaire introuvable', ar: 'المالك غير موجود' },
  'Verification token and code required': { fr: 'Jeton de vérification et code requis', ar: 'رمز التحقق والكود مطلوبان' },
  'Verification expired. Request a new code.': { fr: 'Vérification expirée. Demandez un nouveau code.', ar: 'انتهت صلاحية التحقق. اطلب رمزاً جديداً.' },
  'Invalid verification token': { fr: 'Jeton de vérification invalide', ar: 'رمز التحقق غير صالح' },
  'Invalid verification code': { fr: 'Code de vérification invalide', ar: 'رمز التحقق غير صحيح' },
  'Verification session expired. Please restart registration.': { fr: 'Session de vérification expirée. Veuillez recommencer.', ar: 'انتهت جلسة التحقق. يرجى إعادة التسجيل.' },
  'No phone number on file for WhatsApp delivery.': { fr: 'Aucun numéro de téléphone enregistré pour la livraison WhatsApp.', ar: 'لا يوجد رقم هاتف مسجل لتوصيل واتساب.' },
  'Platform WhatsApp is offline. Try email instead.': { fr: 'Le WhatsApp de la plateforme est hors ligne. Essayez par email.', ar: 'واتساب المنصة غير متصل. جرب البريد الإلكتروني.' },
  'No email address on file for email delivery.': { fr: 'Aucune adresse email enregistrée pour la livraison par email.', ar: 'لا يوجد بريد إلكتروني مسجل للتوصيل عبر البريد.' },
  'Failed to send verification code via WhatsApp': { fr: "Échec de l'envoi du code de vérification via WhatsApp", ar: 'فشل إرسال رمز التحقق عبر واتساب' },
  'Token and code required': { fr: 'Jeton et code requis', ar: 'الرمز والكود مطلوبان' },
  'Name required': { fr: 'Nom requis', ar: 'الاسم مطلوب' },
  'No email address. Customer did not provide email at checkout.': { fr: "Pas d'adresse email. Le client n'a pas fourni d'email à la commande.", ar: 'لا يوجد بريد إلكتروني. لم يقدم العميل بريداً عند الطلب.' },
  'days must be 1-3650': { fr: 'Les jours doivent être entre 1 et 3650', ar: 'يجب أن تكون الأيام بين 1 و3650' },
  'Owner not found': { fr: 'Propriétaire introuvable', ar: 'المالك غير موجود' },
  'Plan not found': { fr: 'Plan introuvable', ar: 'الخطة غير موجودة' },
  'Template not found': { fr: 'Modèle introuvable', ar: 'القالب غير موجود' },
  'Current password is required': { fr: 'Le mot de passe actuel est requis', ar: 'كلمة المرور الحالية مطلوبة' },
  'New password must be at least 6 characters': { fr: 'Le nouveau mot de passe doit contenir au moins 6 caractères', ar: 'يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل' },
  'Phone and password are required': { fr: 'Téléphone et mot de passe requis', ar: 'الهاتف وكلمة المرور مطلوبان' },
  'An admin with this phone already exists': { fr: 'Un admin avec ce numéro existe déjà', ar: 'يوجد مسؤول بهذا الرقم بالفعل' },
  'Two-step verification is enabled. Request a code first.': { fr: 'La vérification en deux étapes est activée. Demandez un code d\'abord.', ar: 'التحقق بخطوتين مفعل. اطلب رمزاً أولاً.' },
  'Two-step verification is not enabled.': { fr: "La vérification en deux étapes n'est pas activée.", ar: 'التحقق بخطوتين غير مفعل.' },
  'Token mismatch': { fr: 'Jeton non correspondant', ar: 'عدم تطابق الرمز' },
  'Store suspended': { fr: 'Boutique suspendue', ar: 'المتجر معلق' },
  'Product not found': { fr: 'Produit introuvable', ar: 'المنتج غير موجود' },
  'Required': { fr: 'Obligatoire', ar: 'مطلوب' },
  'ids required': { fr: 'Identifiants requis', ar: 'المعرفات مطلوبة' },
  'Verification is currently unavailable. The administrator has not connected the platform WhatsApp yet.': { fr: "La vérification n'est pas disponible. L'administrateur n'a pas encore connecté WhatsApp.", ar: 'التحقق غير متاح حالياً. لم يقم المسؤول بربط واتساب بعد.' },
  'Missing tracking': { fr: 'Suivi manquant', ar: 'التتبع مفقود' },

  // ── Cart Recovery / Abandoned cart page ──
  'Automated Sequences': { fr: 'Séquences automatisées', ar: 'التسلسلات التلقائية' },
  'Configure Timings': { fr: 'Configurer les délais', ar: 'ضبط التوقيتات' },
  'First Reminder': { fr: 'Premier rappel', ar: 'التذكير الأول' },
  'Gentle nudge via preferred channel': { fr: 'Rappel doux via le canal préféré', ar: 'تنبيه لطيف عبر القناة المفضلة' },
  'Follow Up': { fr: 'Suivi', ar: 'متابعة' },
  'Limited time urgency hook': { fr: 'Offre limitée dans le temps', ar: 'عرض محدود الوقت' },
  'Final Chance': { fr: 'Dernière chance', ar: 'الفرصة الأخيرة' },
  'Discount code incentive': { fr: 'Incitatif avec code de réduction', ar: 'حافز برمز خصم' },

  // ── Store header / notifications ──
  'New store': { fr: 'Nouvelle boutique', ar: 'متجر جديد' },
  'Enable': { fr: 'Activer', ar: 'تفعيل' },
  '🔔 Enable': { fr: '🔔 Activer', ar: '🔔 تفعيل' },
  'Push notifications not supported on this browser': { fr: 'Les notifications push ne sont pas supportées sur ce navigateur', ar: 'إشعارات الدفع غير مدعومة في هذا المتصفح' },
  'Push notifications enabled! You will receive alerts for new orders.': { fr: 'Notifications push activées ! Vous recevrez des alertes pour les nouvelles commandes.', ar: 'تم تفعيل الإشعارات! ستتلقى تنبيهات للطلبات الجديدة.' },
  'No notifications yet': { fr: 'Aucune notification pour le moment', ar: 'لا توجد إشعارات بعد' },
  'Two-step verification is enabled. Request a code first to change these settings.': { fr: 'La vérification en deux étapes est activée. Demandez un code pour modifier ces paramètres.', ar: 'التحقق بخطوتين مفعل. اطلب رمزاً لتغيير هذه الإعدادات.' },
};

export default D;
