import React,{useState} from'react';import{useParams,Link} from'react-router-dom';import{useTranslation}from'react-i18next';import{useCartStore}from'../../hooks/useStore';import toast from'react-hot-toast';import{Heart,ArrowLeft,ShoppingCart,Eye,Trash2,CheckSquare,Square,X,Package}from'lucide-react';
export default function Favorites(){const{storeSlug}=useParams();const{t}=useTranslation();const{addItem}=useCartStore();
const[items,setItems]=useState(()=>{try{return JSON.parse(localStorage.getItem('wishlist_'+storeSlug)||'[]');}catch{return[];}});
const[selected,setSelected]=useState([]);
const save=(newItems)=>{setItems(newItems);localStorage.setItem('wishlist_'+storeSlug,JSON.stringify(newItems));};
const toggle=(id)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
const selectAll=()=>setSelected(selected.length===items.length?[]:items.map(i=>i.id));
const clearAll=()=>{save([]);setSelected([]);};
const removeSelected=()=>{save(items.filter(i=>!selected.includes(i.id)));setSelected([]);toast.success('Removed!');};
const addSelectedToCart=()=>{items.filter(i=>selected.includes(i.id)).forEach(i=>addItem(i));toast.success(`${selected.length} items added to cart!`);setSelected([]);};
const getThumb=(p)=>{if(p.thumbnail)return p.thumbnail;if(Array.isArray(p.images)&&p.images.length)return typeof p.images[0]==='string'?p.images[0]:null;return null;};
return(<div className="min-h-screen bg-[#f5f5f5]"><header className="bg-white sticky top-0 z-30 shadow-sm"><div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between"><Link to={`/s/${storeSlug}`} className="flex items-center gap-2 text-gray-600"><ArrowLeft size={20}/></Link><h1 className="text-lg font-bold">Favorites</h1><div/></div></header>
<div className="max-w-5xl mx-auto px-4 py-8"><div className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><Heart size={28} className="text-red-500" fill="currentColor"/><div><h2 className="text-2xl font-bold">Favorites</h2><p className="text-sm text-gray-400">{items.length} saved products</p></div></div><div className="flex gap-2"><button onClick={selectAll} className="btn-ghost text-sm flex items-center gap-1"><CheckSquare size={14}/>SELECT ALL</button><button onClick={clearAll} className="btn-ghost text-sm flex items-center gap-1 text-red-500"><Trash2 size={14}/>CLEAR ALL</button></div></div>
{selected.length>0&&<div className="bg-brand-50 border border-brand-200 rounded-xl px-4 py-2 mb-4 flex items-center justify-between"><span className="text-sm font-bold text-brand-600">{selected.length} selected</span><button onClick={()=>setSelected([])} className="text-gray-400"><X size={16}/></button></div>}
{items.length===0?<div className="text-center py-20"><Heart size={48} className="mx-auto text-gray-300 mb-4"/><p className="text-gray-500 font-medium">No favorites yet</p><Link to={`/s/${storeSlug}`} className="text-brand-500 text-sm font-semibold mt-2 inline-block">Continue Shopping</Link></div>:
<div className="grid grid-cols-2 md:grid-cols-3 gap-4">{items.map(p=>{const thumb=getThumb(p);const sel=selected.includes(p.id);return(<div key={p.id} className={`bg-white rounded-2xl overflow-hidden shadow-sm transition-all ${sel?'ring-2 ring-brand-400':''}`}><div className="relative"><button onClick={()=>toggle(p.id)} className="absolute top-3 left-3 z-10">{sel?<CheckSquare size={20} className="text-brand-500"/>:<Square size={20} className="text-gray-300"/>}</button>{thumb?<img src={thumb} className="w-full aspect-square object-cover"/>:<div className="w-full aspect-square bg-gray-100 flex items-center justify-center"><Package size={32} className="text-gray-300"/></div>}</div><div className="p-4"><h3 className="font-semibold text-sm truncate">{p.name_en||p.name}</h3>{p.variant&&<span className="badge badge-neutral text-[9px] mt-1">VARIANT</span>}<div className="flex gap-2 mt-3"><button onClick={()=>{addItem(p);toast.success('Added!');}} className="flex-1 flex items-center justify-center gap-1 py-2 bg-brand-50 text-brand-600 rounded-xl text-xs font-bold hover:bg-brand-100"><ShoppingCart size={12}/>CART</button><Link to={`/s/${storeSlug}/product/${p.slug}`} className="flex-1 flex items-center justify-center gap-1 py-2 bg-gray-50 text-gray-600 rounded-xl text-xs font-bold hover:bg-gray-100"><Eye size={12}/>VIEW</Link><button onClick={()=>{save(items.filter(x=>x.id!==p.id));toast.success('Removed');}} className="p-2 bg-gray-50 rounded-xl text-gray-400 hover:text-red-500 hover:bg-red-50"><Trash2 size={12}/></button></div></div></div>);})}</div>}
{selected.length>0&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 bg-white rounded-2xl shadow-2xl border border-gray-200 px-6 py-3 flex items-center gap-4"><span className="badge bg-brand-500 text-white">{selected.length}</span><span className="text-sm font-medium">{selected.length} products selected</span><button onClick={addSelectedToCart} className="btn-primary text-sm flex items-center gap-1"><ShoppingCart size={14}/>ADD TO CART</button><button onClick={removeSelected} className="px-4 py-2 text-red-500 text-sm font-bold flex items-center gap-1 hover:bg-red-50 rounded-xl"><Trash2 size={14}/>DELETE</button><button onClick={()=>setSelected([])} className="text-gray-400"><X size={16}/></button></div>}
<div className="text-center mt-8"><Link to={`/s/${storeSlug}`} className="text-gray-400 text-sm flex items-center justify-center gap-1"><Package size={14}/>CONTINUE SHOPPING</Link></div>
</div></div>);}
